---
title: "R Notebook"
output: html_notebook
---

# Tranforming data

From txt to rda

```{r}
data03 <- read.delim("https://slcladal.github.io/data/data01.txt", header = TRUE)
base::saveRDS(data01, file = here::here("data", "d01.rda"))
data01  <- base::readRDS(url("https://slcladal.github.io/data/d01.rda", "rb"))
```

```{r}
# data03
tdata <- read.delim("https://slcladal.github.io/data/data03.txt", 
                      header = T, sep = "\t")
base::saveRDS(tdata, file = here::here("data", "d03.rda"))
data03  <- base::readRDS(url("https://slcladal.github.io/data/d03.rda", "rb"))
```

```{r}
#data04
degree_adverbs <- read.delim("https://slcladal.github.io/data/data04.txt", sep = "\t", header = T)
base::saveRDS(degree_adverbs, file = here::here("data", "dad.rda"))
degree_adverbs  <- base::readRDS(url("https://slcladal.github.io/data/dad.rda", "rb"))
```

```{r}
# ldat
ldat <- read.delim("https://slcladal.github.io/data/likertdata1.txt", header = TRUE)
base::saveRDS(ldat, file = here::here("data", "lid.rda"))
ldat  <- base::readRDS(url("https://slcladal.github.io/data/lid.rda", "rb"))
```

```{r}
#sud
surveydata <- read.delim("https://slcladal.github.io/data/surveydata1.txt", sep = "\t", header = T)
base::saveRDS(surveydata, file = here::here("data", "sud.rda"))
sud  <- base::readRDS(url("https://slcladal.github.io/data/sud.rda", "rb"))
```

```{r}
#  sud2
sdat <- read.delim("https://slcladal.github.io/data/survey.txt", header = TRUE)
base::saveRDS(sdat, file = here::here("data", "sdd.rda"))
sdd  <- base::readRDS(url("https://slcladal.github.io/data/sdd.rda", "rb"))
```

```{r}
# German
German <- readLines("https://slcladal.github.io/data/phonemictext1.txt")
base::saveRDS(German, file = here::here("data", "ged.rda"))
German  <- base::readRDS(url("https://slcladal.github.io/data/ged.rda", "rb"))
```

```{r}
English <- readLines("https://slcladal.github.io/data/phonemictext2.txt")
Spanish <- readLines("https://slcladal.github.io/data/phonemictext3.txt")
Unknown <- readLines("https://slcladal.github.io/data/phonemictext4.txt")

base::saveRDS(English, file = here::here("data", "end.rda"))
base::saveRDS(Spanish, file = here::here("data", "spd.rda"))
base::saveRDS(Unknown, file = here::here("data", "und.rda"))

German  <- base::readRDS(url("https://slcladal.github.io/data/ged.rda", "rb"))
English  <- base::readRDS(url("https://slcladal.github.io/data/end.rda", "rb"))
Spanish  <- base::readRDS(url("https://slcladal.github.io/data/apd.rda", "rb"))
Unknown  <- base::readRDS(url("https://slcladal.github.io/data/und.rda", "rb"))
```

```{r}
# cfa data
cfadata <- read.delim("https://slcladal.github.io/data/cfadata.txt", header = T, sep = "\t")
base::saveRDS(cfadata, file = here::here("data", "cfd.rda"))
cfadata  <- base::readRDS(url("https://slcladal.github.io/data/cfd.rda", "rb"))
```

```{r}
# vector space data
vsmdata <- read.delim("https://slcladal.github.io/data/vsmdata.txt", sep = "\t", header = T)
base::saveRDS(vsmdata, file = here::here("data", "vsd.rda"))
vsmdata  <- base::readRDS(url("https://slcladal.github.io/data/vsd.rda", "rb"))
```

```{r}
# ampaus
ampaus <- read.table("https://SLCLADAL.github.io/data/ampaus.txt",  sep = "\t", header = T)
base::saveRDS(ampaus, file = here::here("data", "ozd.rda"))
vsmdata  <- base::readRDS(url("https://slcladal.github.io/data/ozd.rda", "rb"))
```

```{r}
#slrdata2 <- read.delim("https://slcladal.github.io/data/slrdata2.txt", sep = "\t", header = T)
#base::saveRDS(slrdata2, file = here::here("data", "sgd.rda"))
slrdata2  <- base::readRDS(url("https://slcladal.github.io/data/sgd.rda", "rb"))
```

```{r}
# load data
#mlrdata <- read.delim("https://slcladal.github.io/data/mlrdata.txt", header = TRUE)
#base::saveRDS(mlrdata, file = here::here("data", "mld.rda"))
mlrdata  <- base::readRDS(url("https://slcladal.github.io/data/mld.rda", "rb"))
```

```{r}
# load data
#blrdata <- read.table("https://slcladal.github.io/data/blrdata.txt",
#                      comment.char = "",  # data does not contain comments
#                      quote = "",         # data does not contain quotes
#                      sep = "\t",         # data is tab separated
#                      header = T)         # variables have headers
#base::saveRDS(blrdata, file = here::here("data", "bld.rda"))
blrdata  <- base::readRDS(url("https://slcladal.github.io/data/bld.rda", "rb"))

```


```{r}
# load data
#ordata <- read.delim("https://slcladal.github.io/data/ordinaldata.txt", 
#                     sep = "\t", header = T)
#base::saveRDS(ordata, file = here::here("data", "ord.rda"))
ordata  <- base::readRDS(url("https://slcladal.github.io/data/ord.rda", "rb")) %>%
  dplyr::rename(Recommend = 1, 
              Internal = 2, 
              Exchange = 3, 
              FinalScore = 4) %>%
  dplyr::mutate(FinalScore = round(FinalScore, 2))
```


```{r}
# load data
#poissondata <- read.delim("https://slcladal.github.io/data/posdata.txt", sep = "\t", header = T, skipNul = T, quote = "")
#base::saveRDS(poissondata, file = here::here("data", "prd.rda"))
poissondata  <- base::readRDS(url("https://slcladal.github.io/data/prd.rda", "rb"))

```


```{r rr1}
# load data
#robustdata <- read.delim("https://slcladal.github.io/data/mlrdata.txt", sep = "\t", header = T)
#base::saveRDS(robustdata, file = here::here("data", "mld.rda"))
robustdata  <- base::readRDS(url("https://slcladal.github.io/data/mld.rda", "rb"))
```

```{r lmm3}
# read in data
#lmmdata <- read.delim("https://slcladal.github.io/data/lmmdata.txt", header = TRUE)
#base::saveRDS(lmmdata, file = here::here("data", "lmd.rda"))
lmmdata  <- base::readRDS(url("https://slcladal.github.io/data/lmd.rda", "rb")) %>%
  # convert date into a numeric variable
  dplyr::mutate(Date = as.numeric(Date))
```

```{r blmm3}
# load data
#mblrdata <- read.table("https://slcladal.github.io/data/mblrdata.txt", 
#                       comment.char = "",# data does not contain comments
#                       quote = "",       # data does not contain quotes
#                       sep = "\t",       # data is tab separated
#                       header = T)       # data has column names
#base::saveRDS(mblrdata, file = here::here("data", "mbd.rda"))
mblrdata  <- base::readRDS(url("https://slcladal.github.io/data/mbd.rda", "rb"))
```

```{r pmm1}
# load data
#countdata <- read.table("https://slcladal.github.io/data/countdata.txt", 
#                       comment.char = "",quote = "", sep = "\t", header = T) 
#base::saveRDS(countdata, file = here::here("data", "cld.rda"))
countdata  <- base::readRDS(url("https://slcladal.github.io/data/cld.rda", "rb"))
```

```{r slr4, message=FALSE, warning=FALSE}
# load data
#slrdata <- read.delim("https://slcladal.github.io/data/lmmdata.txt", header = TRUE)
#base::saveRDS(slrdata, file = here::here("data", "sld.rda"))
slrdata  <- base::readRDS(url("https://slcladal.github.io/data/sld.rda", "rb"))
```

```{r}
# vector space data
cdo <- readLines("https://slcladal.github.io/data/origindarwin.txt")
base::saveRDS(cdo, file = here::here("data", "cdo.rda"))
cdo  <- base::readRDS(url("https://slcladal.github.io/data/cdo.rda", "rb"))
```


```{r}
ordata <- read.delim("https://slcladal.github.io/data/ordinaldata.txt", sep = "\t", header = T)
colnames(ordata) <- c("Recommend", "Internal", "Exchange", "FinalScore")
base::saveRDS(ordata, file = here::here("data", "oda.rda"))
ordata  <- base::readRDS(url("https://slcladal.github.io/data/oda.rda", "rb"))
```


```{r}
airports <- read.delim("https://slcladal.github.io/data/airports.txt", sep = "\t", header = T)
base::saveRDS(airports, file = here::here("data", "apd.rda"))
airports  <- base::readRDS(url("https://slcladal.github.io/data/apd.rda", "rb"))

```

```{r}
routes <- read.delim("https://slcladal.github.io/data/routes.txt", sep = "\t", header = T)
base::saveRDS(routes, file = here::here("data", "ard.rda"))
routes  <- base::readRDS(url("https://slcladal.github.io/data/ard.rda", "rb"))

```

```{r}
visited <- read.delim("https://slcladal.github.io/data/visited.txt", sep = "\t", header = T)
base::saveRDS(visited, file = here::here("data", "vst.rda"))
routes  <- base::readRDS(url("https://slcladal.github.io/data/vst.rda", "rb"))

```

```{r}
# load data
pdat <- base::readRDS(url("https://slcladal.github.io/data/lmm.rda", "rb")) %>%
  dplyr::mutate(GenreRedux = case_when(str_detect(.$Genre, "Letter") ~ "Conversational",
                                Genre == "Diary" ~ "Conversational",
                                Genre == "Bible"|Genre == "Sermon" ~ "Religious",
                                Genre == "Law"|Genre == "TrialProceeding" ~ "Legal",
                                Genre == "Fiction" ~ "Fiction",
                                TRUE ~ "NonFiction")) %>%
  dplyr::mutate(DateRedux = case_when(Date < 1500 ~ "1150-1499",
                               Date < 1600 ~ "1500-1599",
                               Date < 1700 ~ "1600-1699",
                               Date < 1800 ~ "1700-1799",
                               TRUE ~ "1800-1913")) %>%
  dplyr::mutate_if(is.character, factor)
base::saveRDS(pdat, file = here::here("data", "pvd.rda"))
pdat  <- base::readRDS(url("https://slcladal.github.io/data/pvd.rda", "rb"))
```


```{r}
coocdata <- read.delim("https://slcladal.github.io/data/collex_decade.txt", sep = "\t")
base::saveRDS(coocdata, file = here::here("data", "coo.rda"))
#coocdata  <- base::readRDS(url("https://slcladal.github.io/data/coo.rda", "rb"))
```


```{r}
test <- base::readRDS(url("https://slcladal.github.io/data/mdata.rda", "rb"))
str(test)
```

```{r}
melville <- readLines("https://slcladal.github.io/data/melvillemobydick.txt")
base::saveRDS(melville, file = here::here("data", "melville.rda"))
#melville  <- base::readRDS(url("https://slcladal.github.io/data/melville.rda", "rb"))
```

```{r}
darwin <- readLines("https://slcladal.github.io/data/origindarwin.txt")
base::saveRDS(darwin, file = here::here("data", "darwin.rda"))
#darwin  <- base::readRDS(url("https://slcladal.github.io/data/darwin.rda", "rb"))
```




```{r}
cz <- readLines("https://slcladal.github.io/data/L2Corpus/CZPU1002.txt")
base::saveRDS(cz, file = here::here("data/L2Corpus", "cz.rda"))
#cz  <- base::readRDS(url("https://slcladal.github.io/data/L2Corpus/cz.rda", "rb"))
#cz
```

```{r}
fr <- readLines("https://slcladal.github.io/data/L2Corpus/FRUC2045.txt")
base::saveRDS(fr, file = here::here("data/L2Corpus", "fr.rda"))
```

```{r}
de <- readLines("https://slcladal.github.io/data/L2Corpus/GEAU1001.txt")
base::saveRDS(de, file = here::here("data/L2Corpus", "de.rda"))
```

```{r}
it <- readLines("https://slcladal.github.io/data/L2Corpus/ITTO2031.txt")
base::saveRDS(it, file = here::here("data/L2Corpus", "it.rda"))
```

```{r}
pl <- readLines("https://slcladal.github.io/data/L2Corpus/POPZ5032.txt")
base::saveRDS(pl, file = here::here("data/L2Corpus", "pl.rda"))
```

```{r}
ru <- readLines("https://slcladal.github.io/data/L2Corpus/RUMO5042.txt")
base::saveRDS(ru, file = here::here("data/L2Corpus", "ru.rda"))
```

```{r}
sw <- readLines("https://slcladal.github.io/data/L2Corpus/SWUV3007.txt")
base::saveRDS(sw, file = here::here("data/L2Corpus", "sw.rda"))
```

```{r}
ns1 <- readLines("https://slcladal.github.io/data/L1Corpus/alevels1.txt")
base::saveRDS(ns1, file = here::here("data/L1Corpus", "ns1.rda"))
```

```{r}
ns2 <- readLines("https://slcladal.github.io/data/L1Corpus/alevels2.txt")
base::saveRDS(ns2, file = here::here("data/L1Corpus", "ns2.rda"))
```

```{r}
es <- readLines("https://slcladal.github.io/data/LCorpus/SPM07011.txt")
base::saveRDS(es, file = here::here("data/LCorpus", "es.rda"))
```


