{
  "hash": "aa03f5e0eabd127921ba60527fe4099d",
  "result": {
    "markdown": "---\ntitle: \"Cluster and Correspondence Analysis in R\"\nauthor: \"Martin Schweinberger\"\ndate: \"2022-08-31\"\n---\n\n::: {.cell}\n::: {.cell-output-display}\n![](https://slcladal.github.io/images/uq1.jpg){width=100%}\n:::\n:::\n\n\n# Introduction{-}\n\nThis tutorial introduces classification and clustering using R. Cluster analyses fall within the domain of classification methods which are used to find groups or patterns in data or to predict group membership. As such, they are widely used and applied in machine learning. For linguists, classification is not only common when it comes to phylogenetics but also in annotation-based procedures such as part-of-speech tagging and syntactic parsing. \n\n\nThis tutorial is aimed at intermediate users of R with the aim of showcasing how to performing and visualizing the results of cluster and correspondence analyses in R. The aim is not to provide a fully-fledged analysis but rather to show and exemplify selected useful methods associated with cluster and correspondence analyses. \n\n\n<div class=\"warning\" style='padding:0.1em; background-color:#f2f2f2; color:#51247a'>\n<span>\n<p style='margin-top:1em; text-align:center'>\nThe entire R Notebook for the tutorial can be downloaded [**here**](https://slcladal.github.io/content/clust.Rmd).  If you want to render the R Notebook on your machine, i.e. knitting the document to html or a pdf, you need to make sure that you have R and RStudio installed and you also need to download the [**bibliography file**](https://slcladal.github.io/content/bibliography.bib) and store it in the same folder where you store the Rmd file.</p>\n<p style='margin-left:1em;'>\n</p></span>\n</div>\n\n<br>\n\nA more elaborate and highly recommendable introduction to cluster analysis is @kassambara2017practical. Other very useful resources are, e.g.,  @king2015cluster; @kettenring2006practice; @romesburg2004cluster; and @blashfield1988methods.\n\n**Preparation and session set up**\n\nThis tutorial is based on R. If you have not installed R or are new to it, you will find an introduction to and more information how to use R [here](https://slcladal.github.io/intror.html). For this tutorials, we need to install certain *packages* from an R *library* so that the scripts shown below are executed without errors. Before turning to the code below, please install the packages by running the code below this paragraph. If you have already installed the packages mentioned below, then you can skip ahead and ignore this section. To install the necessary packages, simply run the following code - it may take some time (between 1 and 5 minutes to install all of the libraries so you do not need to worry if it takes some time).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set options\noptions(stringsAsFactors = F)         # no automatic data transformation\noptions(\"scipen\" = 100, \"digits\" = 4) # suppress math annotation\n# install packages\ninstall.packages(\"cluster\")\ninstall.packages(\"factoextra\")\ninstall.packages(\"seriation\")\ninstall.packages(\"pvclust\")\ninstall.packages(\"ape\")\ninstall.packages(\"vcd\")\ninstall.packages(\"exact2x2\")\ninstall.packages(\"flextable\")\ninstall.packages(\"tibble\")\ninstall.packages(\"gplots\")\ninstall.packages(\"testthat\")\n# install klippy for copy-to-clipboard button in code chunks\ninstall.packages(\"remotes\")\nremotes::install_github(\"rlesur/klippy\")\n```\n:::\n\n\nIn a next step, we load the packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(cluster)\nlibrary(factoextra)\nlibrary(seriation)\nlibrary(pvclust)\nlibrary(ape)\nlibrary(vcd)\nlibrary(exact2x2)\nlibrary(flextable)\nlibrary(tibble)\nlibrary(gplots)\n# activate klippy for copy-to-clipboard button\nklippy::klippy()\n```\n\n::: {.cell-output-display}\n```{=html}\n<script>\n  addClassKlippyTo(\"pre.r, pre.markdown\");\n  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');\n</script>\n```\n:::\n:::\n\n\nOnce you have installed R and RStudio and initiated the session by executing the code shown above, you are good to go.\n\n# Cluster Analysis\n\nThe most common method in linguistics that is sued to detect groups in data are cluster analyses. Cluster analyses are common in linguistics because they not only detect commonalities based on the frequency or occurrence of features but they also allow to visualize when splits between groups have occurred and are thus the method of choice in historical linguistics to determine and show genealogical relationships. \n\n## Underlying Concepts{-}\n\nThe next section focuses on the basic idea that underlies all cluster analyses. WE will have a look at some very basic examples to highlight and discuss the principles that cluster analyses rely on. \n\nThe underlying idea of cluster analysis is very simple and rather intuitive as we ourselves perform cluster analyses every day in our lives. This is so because we group things together under certain labels and into concepts. The first example used to show this, deals with types of trees and how we group these types of trees based on their outward appearance. \n\nImagine you see six trees representing different types of trees: a pine tree, a fir tree, an oak tree, a beech tree, a phoenix palm tree, and a nikau palm tree. Now, you were asked to group these trees according to similarity. Have a look at the plot below and see whether you would have come up with a similar type of grouping.\n\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl1-1.png){width=672}\n:::\n\n\nAn alternative way to group the trees would be the following.\n\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl2-1.png){width=672}\n:::\n\n\nIn this display, conifers and broad-leaf trees are grouped together because there are more similar to each other compared to palm trees. This poses the question of what is meant by similarity. Consider the display below. \n\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl3-1.png){width=672}\n:::\n\n\nAre the red and the blue line more similar because they have the same shape or are the red and the black line more similar because they are closer together? There is no single correct answer here. Rather the plot intends to raise awareness about the fact that how cluster analyses group data depends on how similarity is defined in the respective algorithm.\n\nLet's consider another example to better understand how cluster analyses determine which data points should be merged when. Imagine you have five students and want to group them together based on their overall performance in school. The data that you rely on are their grades in math, music, and biology (with 1 being the best grade and 6 being the worst).\n\n\n\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-83c1c668{table-layout:auto;width:50%;}.cl-83bd4f84{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83bd4f85{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83bd61e0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-83bd61e1{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-83bd8b0c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b0d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b16{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b17{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b18{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b20{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b21{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b22{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b23{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b2a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b2b{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83bd8b34{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-83c1c668'>\n```\n<caption class=\"Table Caption\">\n\nSample of five students and their grades in math, music, and biology.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b34\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f84\">Student</span></p></td><td class=\"cl-83bd8b2b\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f84\">Math</span></p></td><td class=\"cl-83bd8b2b\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f84\">Music</span></p></td><td class=\"cl-83bd8b2a\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f84\">Biology</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b16\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f85\">StudentA</span></p></td><td class=\"cl-83bd8b0d\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">2</span></p></td><td class=\"cl-83bd8b0d\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">3</span></p></td><td class=\"cl-83bd8b0c\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b20\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f85\">StudentB</span></p></td><td class=\"cl-83bd8b17\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">1</span></p></td><td class=\"cl-83bd8b17\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">3</span></p></td><td class=\"cl-83bd8b18\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b16\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f85\">StudentC</span></p></td><td class=\"cl-83bd8b0d\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">1</span></p></td><td class=\"cl-83bd8b0d\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">2</span></p></td><td class=\"cl-83bd8b0c\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b20\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f85\">StudentD</span></p></td><td class=\"cl-83bd8b17\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">2</span></p></td><td class=\"cl-83bd8b17\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">4</span></p></td><td class=\"cl-83bd8b18\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83bd8b23\"><p class=\"cl-83bd61e0\"><span class=\"cl-83bd4f85\">StudentE</span></p></td><td class=\"cl-83bd8b22\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">3</span></p></td><td class=\"cl-83bd8b22\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">4</span></p></td><td class=\"cl-83bd8b21\"><p class=\"cl-83bd61e1\"><span class=\"cl-83bd4f85\">3</span></p></td></tr></tbody></table></div>\n```\n:::\n\n \n The first step in determining the similarity among students is to create a distance matrix. \n \n\n\n```{.r .cell-code}\ndiststudents <- dist(students, method = \"manhattan\") # create a distance matrix\n```\n\n\nThe distance matrix below shows that Student A and Student B only differ by one grade. Student B and Student C differ by 2 grades. Student A and Student C differ by 3 grades and so on.\n\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-83d26bb2{table-layout:auto;width:50%;}.cl-83cdaba4{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83cdabae{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83cdb6d0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-83cdd2fa{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd2fb{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd304{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd30e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd30f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd310{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd318{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd319{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd31a{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd322{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd323{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83cdd324{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-83d26bb2'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix based of students based on grades in math, music, and biology.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83cdd322\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdaba4\">Student</span></p></td><td class=\"cl-83cdd323\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdaba4\">StudentA</span></p></td><td class=\"cl-83cdd323\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdaba4\">StudentB</span></p></td><td class=\"cl-83cdd323\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdaba4\">StudentC</span></p></td><td class=\"cl-83cdd324\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdaba4\">StudentD</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83cdd2fa\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">StudentB</span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">1</span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td><td class=\"cl-83cdd304\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83cdd30e\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">StudentC</span></p></td><td class=\"cl-83cdd30f\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">3</span></p></td><td class=\"cl-83cdd30f\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">2</span></p></td><td class=\"cl-83cdd30f\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td><td class=\"cl-83cdd310\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83cdd2fa\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">StudentD</span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">3</span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">4</span></p></td><td class=\"cl-83cdd2fb\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">6</span></p></td><td class=\"cl-83cdd304\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83cdd318\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">StudentE</span></p></td><td class=\"cl-83cdd319\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">3</span></p></td><td class=\"cl-83cdd319\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">4</span></p></td><td class=\"cl-83cdd319\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">6</span></p></td><td class=\"cl-83cdd31a\"><p class=\"cl-83cdb6d0\"><span class=\"cl-83cdabae\">2</span></p></td></tr></tbody></table></div>\n```\n:::\n\n\nBased on this distance matrix, we can now implement a cluster analysis in R. \n\n## Cluster Analysis on Numeric Data{-}\n\nTo create a simple cluster object in R, we use the `hclust` function from the `cluster` package. The resulting object is then plotted to create a dendrogram which shows how students have been amalgamated (combined) by the clustering algorithm (which, in the present case, is called `ward.D`).\n\n\n\n```{.r .cell-code}\n# create hierarchical cluster object with ward.D as linkage method\nclusterstudents <- hclust(diststudents, method=\"ward.D\")\n# plot result as dendrogram\nplot(clusterstudents, hang = 0)\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl8-1.png){width=672}\n:::\n\n\nLet us have a look at how the clustering algorithm has amalgamated the students. The amalgamation process takes the distance matrix from above as a starting point and, in a first step, has merged Student A and Student B (because they were the most similar students in the data based on the distance matrix). After collapsing Student A and Student B, the resulting distance matrix looks like the distance matrix below (notice that Student A and Student B now form a cluster that is represented by the means of the grades of the two students).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudents2 <- matrix(c(1.5, 3, 2, 1,  2,  1, 2,  4,  4, 3,  4,  3),\n  nrow = 4, byrow = T)\nstudents2 <- as.data.frame(students2)\nrownames(students2) <- c(\"Cluster1\", \"StudentC\", \"StudentD\", \"StudentE\")\ndiststudents2 <- dist(students2, method = \"manhattan\")\n```\n:::\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-83ed7a06{table-layout:auto;width:50%;}.cl-83ea4822{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83ea4823{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83ea5042{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-83ea6456{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6460{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6461{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea646a{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea646b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea646c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6474{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6475{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6476{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea6477{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea647e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83ea647f{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-83ed7a06'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix of students based on grades in math, music, and biology.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83ea647e\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4822\">Student</span></p></td><td class=\"cl-83ea6477\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4822\">Cluster 1</span></p></td><td class=\"cl-83ea6477\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4822\">Student C</span></p></td><td class=\"cl-83ea647f\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4822\">Student D</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83ea6460\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">Student C</span></p></td><td class=\"cl-83ea6456\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">2.5</span></p></td><td class=\"cl-83ea6456\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\"></span></p></td><td class=\"cl-83ea6461\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83ea646b\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">Student D</span></p></td><td class=\"cl-83ea646a\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">3.5</span></p></td><td class=\"cl-83ea646a\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">6.0</span></p></td><td class=\"cl-83ea646c\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83ea6475\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">Student E</span></p></td><td class=\"cl-83ea6474\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">3.5</span></p></td><td class=\"cl-83ea6474\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">6.0</span></p></td><td class=\"cl-83ea6476\"><p class=\"cl-83ea5042\"><span class=\"cl-83ea4823\">2.0</span></p></td></tr></tbody></table></div>\n```\n:::\n\n\nThe next lowest distance now is 2.0 between Student D and Student E which means that these two students are merged next. The resulting distance matrix is shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudents3 <- matrix(c(1.5,3,2,1,2,1,2.5,4,3.5),\n                    nrow = 3, byrow = T)\nstudents3 <- as.data.frame(students3)\nrownames(students3) <- c(\"Cluster1\", \"StudentC\", \"Cluster2\")\ndiststudents3 <- dist(students3, \n                      method = \"manhattan\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-83f7a274{table-layout:auto;width:50%;}.cl-83f4ae48{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83f4ae52{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-83f4b6e0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-83f4cb76{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb77{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb78{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb80{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb81{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb82{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb8a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb8b{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-83f4cb8c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-83f7a274'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix based of students based on grades in math, music, and biology.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83f4cb8b\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae48\">Student</span></p></td><td class=\"cl-83f4cb8a\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae48\">Cluster 1</span></p></td><td class=\"cl-83f4cb8c\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae48\">Student C</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83f4cb78\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\">Student C</span></p></td><td class=\"cl-83f4cb76\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\">2.5</span></p></td><td class=\"cl-83f4cb77\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-83f4cb80\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\">Cluster 2</span></p></td><td class=\"cl-83f4cb81\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\">3.5</span></p></td><td class=\"cl-83f4cb82\"><p class=\"cl-83f4b6e0\"><span class=\"cl-83f4ae52\">6.0</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nNow, the lowest distance value occurs between Cluster 1 and Student C. Thus, Student C and Cluster 1 are merged. In the final step, the Cluster 2 is merged with the new cluster encompassing Student C and Cluster 1. This amalgamation process can then be displayed visually as a dendrogram (see above). \n\nHow and which elements are merged depends on the what is understood as distance. Since \"distance\" is such an important concept in cluster analyses, we will briefly discuss this notion to understand why there are so many different types of clustering algorithms and this cluster analyses.\n\n## Distance and Similarity Measures{-}\n\nTo understand how a cluster analysis determines to which cluster a given data point belongs, we need to understand what different distance measures represent. Have a look at the Figure below which visually represents three different ways to conceptualize distance.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](clust_files/figure-html/cl13-1.png){width=672}\n:::\n:::\n\n\nThe Figure above depicts three ways to measure distance: the `euclidean` distance represents the distance between points as the hypotenuse of the x- and y-axis distances while the \"maximum distance\" represents distance as the longer distance of either the distance on the x- or the y-axis. The `manhatten` distance (or block distance) is the sum of the distances on the x- and the y-axis. \n\nWe will now turn to another example in order to delve a little deeper into how clustering algorithms work. In this example, we will find cluster of varieties of English based on the relative frequency of selected non-standard features (such as the relative frequencies of cleft constructions and tag questions). As a first step, we generate some fictional data set for this analysis. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate data\nIrishEnglish <- round(sqrt((rnorm(10, 9.5, .5))^2), 3)\nScottishEnglish <- round(sqrt((rnorm(10, 9.3, .4))^2), 3)\nBritishEnglish <- round(sqrt((rnorm(10, 6.4, .7))^2), 3)\nAustralianEnglish <- round(sqrt((rnorm(10, 6.6, .5))^2), 3)\nNewZealandEnglish <- round(sqrt((rnorm(10, 6.5, .4))^2), 3)\nAmericanEnglish <- round(sqrt((rnorm(10, 4.6, .8))^2), 3)\nCanadianEnglish <- round(sqrt((rnorm(10, 4.5, .7))^2), 3)\nJamaicanEnglish <- round(sqrt((rnorm(10, 1.4, .2))^2), 3)\nPhillipineEnglish <- round(sqrt((rnorm(10, 1.5, .4))^2), 3)\nIndianEnglish <- round(sqrt((rnorm(10, 1.3, .5))^2), 3)\nclus <- data.frame(IrishEnglish, ScottishEnglish, BritishEnglish, \n                   AustralianEnglish, NewZealandEnglish, AmericanEnglish, \n                   CanadianEnglish, JamaicanEnglish, PhillipineEnglish, IndianEnglish)\n# add row names\nrownames(clus) <- c(\"nae_neg\", \"like\", \"clefts\", \"tags\", \"youse\", \"soitwas\", \n                    \"dt\", \"nsr\", \"invartag\", \"wh_cleft\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-84174f48{table-layout:auto;width:50%;}.cl-8411ddba{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8411ddc4{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8411e6de{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8411e6df{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84120d6c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d76{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d80{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d81{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d82{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d83{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d8a{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d8b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d94{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d95{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d96{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84120d9e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-84174f48'>\n```\n<caption class=\"Table Caption\">\n\nFrequencies of on-standard features across selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d9e\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddba\">Feature</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">IrishEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">ScottishEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">BritishEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">AustralianEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">NewZealandEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">AmericanEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">CanadianEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">JamaicanEnglish</span></p></td><td class=\"cl-84120d95\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">PhillipineEnglish</span></p></td><td class=\"cl-84120d96\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddba\">IndianEnglish</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d76\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">nae_neg</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.118</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">8.392</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.575</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.170</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.794</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">4.615</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">4.713</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.184</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.292</span></p></td><td class=\"cl-84120d80\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">0.554</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d8b\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">like</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.161</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.741</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.461</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.101</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.372</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">4.236</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.063</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.521</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.983</span></p></td><td class=\"cl-84120d94\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.348</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d76\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">clefts</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.847</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.716</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.337</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.122</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.119</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.203</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">4.697</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.370</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.197</span></p></td><td class=\"cl-84120d80\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">2.112</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d8b\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">tags</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">8.287</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.533</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.155</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.349</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.887</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">3.410</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">3.685</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.367</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.684</span></p></td><td class=\"cl-84120d94\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">0.866</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d76\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">youse</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.771</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.948</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.495</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.187</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.427</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.078</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">3.639</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.393</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.221</span></p></td><td class=\"cl-84120d80\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.906</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d8b\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">soitwas</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.820</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">8.916</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.844</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.618</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.574</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.120</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.848</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.271</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">0.486</span></p></td><td class=\"cl-84120d94\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.162</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d76\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">dt</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">10.081</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.244</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">8.370</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.103</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.562</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.150</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">3.452</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.738</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.832</span></p></td><td class=\"cl-84120d80\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.376</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d8b\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">nsr</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.944</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.555</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.273</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.739</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.400</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.143</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.062</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.008</span></p></td><td class=\"cl-84120d8a\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.580</span></p></td><td class=\"cl-84120d94\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.002</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d76\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">invartag</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.372</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">8.799</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.109</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.878</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">7.362</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.258</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">3.918</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.169</span></p></td><td class=\"cl-84120d6c\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">2.310</span></p></td><td class=\"cl-84120d80\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.406</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84120d83\"><p class=\"cl-8411e6de\"><span class=\"cl-8411ddc4\">wh_cleft</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.902</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">9.320</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.924</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">5.693</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.445</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">6.209</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">4.897</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.368</span></p></td><td class=\"cl-84120d81\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">1.814</span></p></td><td class=\"cl-84120d82\"><p class=\"cl-8411e6df\"><span class=\"cl-8411ddc4\">2.065</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n\nAs a next step, we create a cluster object based on the data we have just generated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# clean data\nclusm <- as.matrix(clus)\nclust <- t(clusm)            # transpose data\nclust <- na.omit(clust)     # remove missing values\nclusts <- scale(clust)      # standardize variables\nclusts <- as.matrix(clusts) # convert into matrix\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-8427512c{table-layout:auto;width:50%;}.cl-84238542{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8423854c{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84238d58{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84238d59{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8423b53a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b544{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b545{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b546{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b547{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b54e{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b54f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b558{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b559{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b55a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b562{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8423b563{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-8427512c'>\n```\n<caption class=\"Table Caption\">\n\nScaled frequencies of on-standard features across selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b563\"><p class=\"cl-84238d58\"><span class=\"cl-84238542\">Variety</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">nae_neg</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">like</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">clefts</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">tags</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">youse</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">soitwas</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">dt</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">nsr</span></p></td><td class=\"cl-8423b55a\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">invartag</span></p></td><td class=\"cl-8423b562\"><p class=\"cl-84238d59\"><span class=\"cl-84238542\">wh_cleft</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b53a\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">IrishEnglish</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.118</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.161</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.847</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">8.287</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.771</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.820</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">10.081</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.944</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.372</span></p></td><td class=\"cl-8423b545\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.902</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b558\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">ScottishEnglish</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">8.392</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.741</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.716</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.533</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.948</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">8.916</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.244</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.555</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">8.799</span></p></td><td class=\"cl-8423b559\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">9.320</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b53a\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">BritishEnglish</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.575</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.461</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.337</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.155</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.495</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.844</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">8.370</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.273</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.109</span></p></td><td class=\"cl-8423b545\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.924</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b558\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">AustralianEnglish</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.170</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.101</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.122</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.349</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.187</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.618</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.103</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.739</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.878</span></p></td><td class=\"cl-8423b559\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.693</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b53a\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">NewZealandEnglish</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.794</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.372</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.119</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.887</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.427</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.574</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.562</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.400</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">7.362</span></p></td><td class=\"cl-8423b545\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.445</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b558\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">AmericanEnglish</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">4.615</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">4.236</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.203</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">3.410</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.078</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.120</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.150</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.143</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.258</span></p></td><td class=\"cl-8423b559\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">6.209</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b53a\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">CanadianEnglish</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">4.713</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.063</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">4.697</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">3.685</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">3.639</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.848</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">3.452</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">5.062</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">3.918</span></p></td><td class=\"cl-8423b545\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">4.897</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b558\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">JamaicanEnglish</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.184</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.521</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.370</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.367</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.393</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.271</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.738</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.008</span></p></td><td class=\"cl-8423b54f\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.169</span></p></td><td class=\"cl-8423b559\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.368</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b53a\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">PhillipineEnglish</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.292</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.983</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.197</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.684</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.221</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">0.486</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.832</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.580</span></p></td><td class=\"cl-8423b544\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">2.310</span></p></td><td class=\"cl-8423b545\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.814</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8423b547\"><p class=\"cl-84238d58\"><span class=\"cl-8423854c\">IndianEnglish</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">0.554</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.348</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">2.112</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">0.866</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.906</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.162</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.376</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.002</span></p></td><td class=\"cl-8423b546\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">1.406</span></p></td><td class=\"cl-8423b54e\"><p class=\"cl-84238d59\"><span class=\"cl-8423854c\">2.065</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n\nWe  assess if data is \"clusterable\" by testing if the data contains non-randomness. To this end, we calculate the *Hopkins statistic* which indicates how similar the data is to a random distribution. \n\n* A Hopkins  value of 0.5 indicates that the data is random and that there are no inherent clusters. \n\n* If the Hopkins statistic is close to 1, then the data is highly clusterable. \n\n* Values of 0 indicate that the data is uniform [@aggarwal2015data, pp. 158]. \n\nThe `n` in the `get_clust_tendency` functions represents the maximum number of clusters to be tested which should be  number of predictors in the data. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# apply get_clust_tendency to cluster object\nclusttendency <- get_clust_tendency(clusts,    \n                                    # define number of points from sample space\n                                    n = 9,      \n                   gradient = list(\n                     # define color for low values\n                     low = \"steelblue\",\n                     # define color for high values\n                     high = \"white\"))    \nclusttendency[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$hopkins_stat\n[1] 0.7430173\n```\n:::\n:::\n\n\nAs the Hopkins value is substantively higher than .5 (randomness) and closer to 1 (highly clusterable) than to .5, thus indicating that there is sufficient structure in the data to warrant a cluster analysis. As such, we can assume that there are actual clusters in the data and continue by generating a distance matrix using  euclidean distances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustd <- dist(clusts,                 # create distance matrix\n               method = \"euclidean\")   # use euclidean (!) distance\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-8446f02c{table-layout:auto;width:50%;}.cl-8443de46{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8443de50{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8443eaf8{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8443eaf9{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84441ac8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ac9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ad2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ad3{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ad4{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441adc{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441add{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ade{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441adf{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ae6{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ae7{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84441ae8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-8446f02c'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix of scaled frequencies of non-standard features across selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ae8\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de46\">Variety</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">IrishEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">ScottishEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">BritishEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">AustralianEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">NewZealandEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">AmericanEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">CanadianEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">JamaicanEnglish</span></p></td><td class=\"cl-84441ae6\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">PhillipineEnglish</span></p></td><td class=\"cl-84441ae7\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de46\">IndianEnglish</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad2\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">IrishEnglish</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.70</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.04</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.08</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.15</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.66</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.17</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.33</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.12</span></p></td><td class=\"cl-84441ac9\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.28</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ade\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">ScottishEnglish</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.70</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.80</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.92</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.92</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.53</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.98</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.11</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">7.90</span></p></td><td class=\"cl-84441add\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.07</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad2\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">BritishEnglish</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.04</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.80</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.19</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.85</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.02</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.55</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.43</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.22</span></p></td><td class=\"cl-84441ac9\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.40</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ade\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">AustralianEnglish</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.08</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.92</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.19</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.76</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.93</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.24</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.37</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.19</span></p></td><td class=\"cl-84441add\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.36</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad2\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">NewZealandEnglish</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.15</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.92</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.85</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.76</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.80</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.26</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.26</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.04</span></p></td><td class=\"cl-84441ac9\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.24</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ade\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">AmericanEnglish</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.66</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.53</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.02</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.93</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.80</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.02</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.74</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.54</span></p></td><td class=\"cl-84441add\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.66</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad2\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">CanadianEnglish</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.17</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">4.98</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.55</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.24</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">2.26</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">1.02</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.31</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.16</span></p></td><td class=\"cl-84441ac9\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.29</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ade\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">JamaicanEnglish</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.33</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.11</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.43</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.37</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.26</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.74</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.31</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441adf\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.55</span></p></td><td class=\"cl-84441add\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.48</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad2\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">PhillipineEnglish</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.12</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">7.90</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.22</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.19</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.04</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.54</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.16</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.55</span></p></td><td class=\"cl-84441ac8\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td><td class=\"cl-84441ac9\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.71</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84441ad4\"><p class=\"cl-8443eaf8\"><span class=\"cl-8443de50\">IndianEnglish</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.28</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">8.07</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.40</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.36</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">5.24</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.66</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">3.29</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.48</span></p></td><td class=\"cl-84441ad3\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.71</span></p></td><td class=\"cl-84441adc\"><p class=\"cl-8443eaf9\"><span class=\"cl-8443de50\">0.00</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nBelow are other methods to create distance matrices with some comments on when using which metric is appropriate. \n\n\n\n```{.r .cell-code}\n# create distance matrix (euclidean method: not good when dealing with many dimensions)\nclustd <- dist(clusts, method = \"euclidean\")\n# create distance matrix (maximum method: here the difference between points dominates)\nclustd_maximum <- round(dist(clusts, method = \"maximum\"), 2)\n# create distance matrix (manhattan method: most popular choice)\nclustd_manhatten <- round(dist(clusts, method = \"manhattan\"), 2) \n# create distance matrix (canberra method: for count data only - focuses on small differences and neglects larger differences)\nclustd_canberra <- round(dist(clusts, method = \"canberra\"), 2)\n# create distance matrix (binary method: for binary data only!)\nclustd_binary <- round(dist(clusts, method = \"binary\"), 2) \n# create distance matrix (minkowski method: is not a true distance measure)\nclustd_minkowski <- round(dist(clusts, method = \"minkowski\"), 2) \n# distance method for words: daisy (other possible distances are \"manhattan\" and \"gower\")\nclustd_daisy <- round(daisy(clusts, metric = \"euclidean\"), 2) \n```\n\n\n\nIf you call the individual distance matrices, you will see that depending on which distance measure is used, the distance matrices differ dramatically! Have a look at the distance matrix created using the `manhatten` metric and compare it to the distance matrix created using the `euclidian` metric (see above).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustd_maximum\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-84589840{table-layout:auto;width:50%;}.cl-84541c98{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84541ca2{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-84542a80{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-84542a81{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-845463d8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-845463e2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-845463e3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-845463ec{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-845463ed{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-845463f6{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84546428{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84546429{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84546432{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84546433{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-84546434{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8454643c{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-84589840'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix of selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8454643c\"><p class=\"cl-84542a80\"><span class=\"cl-84541c98\">Variety</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">IrishEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">ScottishEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">BritishEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">AustralianEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">NewZealandEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">AmericanEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">CanadianEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">JamaicanEnglish</span></p></td><td class=\"cl-84546433\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">PhillipineEnglish</span></p></td><td class=\"cl-84546434\"><p class=\"cl-84542a81\"><span class=\"cl-84541c98\">IndianEnglish</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463e3\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">IrishEnglish</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.40</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.21</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.41</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.17</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.65</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.06</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.86</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.83</span></p></td><td class=\"cl-845463e2\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.83</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84546429\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">ScottishEnglish</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.40</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.10</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.22</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.13</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.97</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.98</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.76</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.74</span></p></td><td class=\"cl-84546428\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.82</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463e3\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">BritishEnglish</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.21</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.10</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.70</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.56</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.21</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.53</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.06</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.03</span></p></td><td class=\"cl-845463e2\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.17</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84546429\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">AustralianEnglish</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.41</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.22</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.70</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.46</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.95</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.00</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.98</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.17</span></p></td><td class=\"cl-84546428\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.19</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463e3\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">NewZealandEnglish</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.17</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.13</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.56</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.46</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.12</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.16</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.09</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.85</span></p></td><td class=\"cl-845463e2\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.01</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84546429\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">AmericanEnglish</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.65</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.97</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.21</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.95</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.12</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.53</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.62</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.47</span></p></td><td class=\"cl-84546428\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.39</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463e3\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">CanadianEnglish</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.06</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.98</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.53</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.00</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.16</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.53</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.39</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.63</span></p></td><td class=\"cl-845463e2\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.42</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-84546429\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">JamaicanEnglish</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.86</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.76</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.06</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.98</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.09</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.62</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.39</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-84546432\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.38</span></p></td><td class=\"cl-84546428\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.23</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463e3\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">PhillipineEnglish</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.83</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.74</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.03</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.17</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.85</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.47</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.63</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.38</span></p></td><td class=\"cl-845463d8\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td><td class=\"cl-845463e2\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.30</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-845463ed\"><p class=\"cl-84542a80\"><span class=\"cl-84541ca2\">IndianEnglish</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.83</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.82</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.17</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.19</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">2.01</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.39</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">1.42</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.23</span></p></td><td class=\"cl-845463ec\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.30</span></p></td><td class=\"cl-845463f6\"><p class=\"cl-84542a81\"><span class=\"cl-84541ca2\">0.00</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nNext, we create a distance plot using the `distplot` function. If the distance plot shows different regions (non-random, non-uniform gray areas) then clustering the data is permittable as the data contains actual structures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create distance plot\ndissplot(clustd) \n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl20-1.png){width=672}\n:::\n:::\n\n\nThe most common method for clustering is called `ward.D` or `ward.D2`. Both of these linkage functions seek to minimize variance. This means that they cluster in a way that the amount of variance is at a minimum (comparable to the regression line in an *ordinary least squares* (OLS) design).\n\n\n\n```{.r .cell-code}\n# create cluster object\ncd <- hclust(clustd, method=\"ward.D2\") \n# display dendrogram              \nplot(cd, hang = -1)              \n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl21-1.png){width=672}\n:::\n\n\nWe will briefly go over some other, alternative linkage methods. Which linkage method is and should be used depends on various factors, for example, the type of variables (nominal versus numeric) or whether the focus should be placed on commonalities or differences.\n \n\n\n```{.r .cell-code}\n# single linkage: cluster with nearest data point\ncd_single <- hclust(clustd, method=\"single\") \n# create cluster object (ward.D linkage)\ncd_wardd <- hclust(clustd, method=\"ward.D\")\n# create cluster object (ward.D2 linkage): \n# cluster in a way to achieve minimum variance\ncd_wardd2 <- hclust(clustd, method=\"ward.D2\")\n# average linkage: cluster with closest mean\ncd_average <- hclust(clustd, method=\"average\") \n# mcquitty linkage\ncd_mcquitty <- hclust(clustd, method=\"mcquitty\") \n# median linkage: cluster with closest median\ncd_median <- hclust(clustd, method=\"median\")\n# centroid linkage: cluster with closest prototypical point of target cluster\ncd_centroid <- hclust(clustd, method=\"centroid\") \n# complete linkage: cluster with nearest/furthest data point of target cluster\ncd_complete <- hclust(clustd, method=\"complete\")  \n```\n\n\nNow, we determine the optimal number of clusters based on silhouette widths which shows the ratio of internal similarity of clusters against the similarity between clusters. If the silhouette widths have values lower than .2 then this indicates that clustering is not appropriate [@levshina2015linguistics 311]. The function below displays the silhouette width values of 2 to 8 clusters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptclus <- sapply(2:8, function(x) summary(silhouette(cutree(cd, k = x), clustd))$avg.width)\noptclus # inspect results\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6087576 0.6614379 0.6749439 0.5494091 0.4463603 0.3984969 0.2467143\n```\n:::\n\n```{.r .cell-code}\noptnclust <- which(optclus == max(optclus)) # determine optimal number of clusters\ngroups <- cutree(cd, k=optnclust) # cut tree into optimal number of clusters\n```\n:::\n\n\nThe optimal number of clusters is the cluster solution with the highest silhouette width. We cut the tree into the optimal number of clusters and plot the result.\n\n\n\n```{.r .cell-code}\ngroups <- cutree(cd, k=optnclust)          # cut tree into optimal clusters\nplot(cd, hang = -1, cex = .75)             # plot result as dendrogram\nrect.hclust(cd, k=optnclust, border=\"red\") # draw red borders around clusters\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl24-1.png){width=672}\n:::\n\n\nIn a next step, we aim to determine which factors are particularly important for the clustering - this step is comparable to measuring the effect size in inferential designs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# which factors are particularly important\nceltic <- clusts[c(1,2),]\nothers <- clusts[-c(1,2),]\n# calculate column means\nceltic.cm <- colMeans(celtic)\nothers.cm <- colMeans(others)\n# calculate difference between celtic and other englishes\ndiff <- celtic.cm - others.cm\nsort(diff, decreasing = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n soitwas     tags invartag  nae_neg       dt   clefts      nsr wh_cleft \n1.556691 1.604529 1.611924 1.619124 1.656250 1.695621 1.725908 1.736202 \n    like    youse \n1.785558 1.826903 \n```\n:::\n:::\n\n\n```{.r .cell-code}\nplot(sort(diff),           # y-values\n  1:length(diff),       # x-values \n  type= \"n\",            # plot type (empty)\n  cex.axis = .75,       # axis font size\n  cex.lab = .75,        # label font size\n  xlab =\"Prototypical for Non-Celtic Varieties (Cluster 2) <-----> Prototypical for Celtic Varieties (Cluster 1)\", # x-axis label\n  yaxt = \"n\",           # no y-axis tick marks\n  ylab = \"\")            # no y-axis label\ntext(sort(diff), 1:length(diff), names(sort(diff)), cex = .75) # plot text into plot\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl26-1.png){width=672}\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nOuter <- clusts[c(6:8),]     # data of outer circle varieties\nInner <- clusts[-c(6:8),]    # data of inner circle varieties\nOuter.cm <- colMeans(Outer)  # column means for outer circle\nInner.cm <- colMeans(Inner)  # column means for inner circle\ndiff <- Outer.cm - Inner.cm  # difference between inner and outer circle\nsort(diff, decreasing = F)   # order difference between inner and outer circle\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      tags   invartag         dt      youse     clefts       like        nsr \n-0.9664380 -0.8710742 -0.8614757 -0.8240724 -0.7713340 -0.7640016 -0.6750898 \n   nae_neg   wh_cleft    soitwas \n-0.6319051 -0.6246979 -0.5144678 \n```\n:::\n:::\n\n\n```{.r .cell-code}\nplot(                   # start plot\n  sort(diff),           # y-values\n  1:length(diff),       # x-values \n  type= \"n\",            # plot type (empty)\n  cex.axis = .75,       # axis font size\n  cex.lab = .75,        # label font size\n  xlab =\"Prototypical for Inner Circle Varieties (Cluster 2) <-----> Prototypical for Outer Circle Varieties (Cluster 1)\", # x-axis label\n  yaxt = \"n\",           # no y-axis tick marks\n  ylab = \"\")            # no y-axis label\ntext(sort(diff), 1:length(diff), names(sort(diff)), cex = .75) # plot text into plot\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl28-1.png){width=672}\n:::\n\n\nWe see that discourse *like* is typical for other varieties and that the use of *youse* as 2^nd^ person plural pronoun and invariant tags are typical for Celtic Englishes.\n\nWe will now test whether the cluster is justified by validating the cluster solution using bootstrapping.\n\n\n::: {.cell paged.print='false'}\n\n```{.r .cell-code}\nres.pv <- pvclust(clus,                     # apply pvclust method to clus data\n                  method.dist=\"euclidean\",  # use eucledian distance\n                  method.hclust=\"ward.D2\",  # use ward.d2 linkage\n                  nboot = 100)              # use 100 bootstrap runs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBootstrap (r = 0.5)... Done.\nBootstrap (r = 0.6)... Done.\nBootstrap (r = 0.7)... Done.\nBootstrap (r = 0.8)... Done.\nBootstrap (r = 0.9)... Done.\nBootstrap (r = 1.0)... Done.\nBootstrap (r = 1.1)... Done.\nBootstrap (r = 1.2)... Done.\nBootstrap (r = 1.3)... Done.\nBootstrap (r = 1.4)... Done.\n```\n:::\n:::\n\n\nThe clustering provides approximately unbiased p-values and bootstrap probability value [see @levshina2015linguistics 316].\n\n\n::: {.cell paged.print='false'}\n\n```{.r .cell-code}\nplot(res.pv, cex = .75)\npvrect(res.pv)\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl30-1.png){width=672}\n:::\n:::\n\n\nWe can also use other packages to customize the dendrograms. \n\n\n\n```{.r .cell-code}\nplot(as.phylo(cd),      # plot cluster object\n     cex = 0.75,        # .75 font size\n     label.offset = .5) # .5 label offset\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl31-1.png){width=672}\n:::\n\n\nOne useful customization is to display an unrooted rather than a rooted tree diagram.\n\n\n\n```{.r .cell-code}\n# plot as unrooted tree\nplot(as.phylo(cd),      # plot cluster object\n     type = \"unrooted\", # plot as unrooted tree\n     cex = .75,         # .75 font size\n     label.offset = 1)  # .5 label offset\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl32-1.png){width=672}\n:::\n\n\n## Cluster Analysis on Nominal Data{-}\n\nSo far, all analyses were based on numeric data. However, especially when working with language data, the data is nominal or categorical rather than numeric. The following will thus show to implement a clustering method for nominal data.\n\nIn a first step, we will create a simple data set representing the presence and absence of features across varieties of English.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate data\nIrishEnglish <- c(1,1,1,1,1,1,1,1,1,1)\nScottishEnglish <- c(1,1,1,1,1,1,1,1,1,1)\nBritishEnglish <- c(0,1,1,1,0,0,1,0,1,1)\nAustralianEnglish <- c(0,1,1,1,0,0,1,0,1,1)\nNewZealandEnglish <- c(0,1,1,1,0,0,1,0,1,1)\nAmericanEnglish <- c(0,1,1,1,0,0,0,0,1,0)\nCanadianEnglish <- c(0,1,1,1,0,0,0,0,1,0)\nJamaicanEnglish <- c(0,0,1,0,0,0,0,0,1,0)\nPhillipineEnglish <- c(0,0,1,0,0,0,0,0,1,0)\nIndianEnglish <- c(0,0,1,0,0,0,0,0,1,0)\nclus <- data.frame(IrishEnglish, ScottishEnglish, BritishEnglish, \n                   AustralianEnglish, NewZealandEnglish, AmericanEnglish, \n                   CanadianEnglish, JamaicanEnglish, PhillipineEnglish, IndianEnglish)\n# add row names\nrownames(clus) <- c(\"nae_neg\", \"like\", \"clefts\", \"tags\", \"youse\", \"soitwas\", \n                    \"dt\", \"nsr\", \"invartag\", \"wh_cleft\")\n# convert into factors\nclus <- apply(clus, 1, function(x){\n  x <- as.factor(x) })\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-852092b4{table-layout:auto;width:50%;}.cl-851cbef0{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-851cbefa{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-851cc76a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-851cf15e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf168{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf172{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf173{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf174{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf175{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf17c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf17d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf186{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf187{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf188{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-851cf190{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-852092b4'>\n```\n<caption class=\"Table Caption\">\n\nOccurrence of non-standard features across selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf190\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">Variety</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">nae_neg</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">like</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">clefts</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">tags</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">youse</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">soitwas</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">dt</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">nsr</span></p></td><td class=\"cl-851cf187\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">invartag</span></p></td><td class=\"cl-851cf188\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbef0\">wh_cleft</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf15e\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">IrishEnglish</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf172\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf17d\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">ScottishEnglish</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf186\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf15e\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">BritishEnglish</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf172\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf17d\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">AustralianEnglish</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf186\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf15e\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">NewZealandEnglish</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf172\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf17d\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">AmericanEnglish</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf186\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf15e\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">CanadianEnglish</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf172\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf17d\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">JamaicanEnglish</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf17c\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf186\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf15e\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">PhillipineEnglish</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf168\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf172\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-851cf174\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">IndianEnglish</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td><td class=\"cl-851cf173\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">1</span></p></td><td class=\"cl-851cf175\"><p class=\"cl-851cc76a\"><span class=\"cl-851cbefa\">0</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nNow that we have our data, we will create a distance matrix but in contrast to previous methods, we will use a different distance measure that takes into account that we are dealing with nominal (or binary) data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# clean data\nclusts <- as.matrix(clus)\n# create distance matrix\nclustd <- dist(clusts, method = \"binary\")   # create a distance object with binary (!) distance\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-85369a1e{table-layout:auto;width:50%;}.cl-853154c8{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-853154c9{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-85315d7e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-85315d7f{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-85318bdc{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318be6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318be7{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318be8{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bf0{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bf1{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bfa{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bfb{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bfc{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318bfd{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318c04{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85318c05{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-85369a1e'>\n```\n<caption class=\"Table Caption\">\n\nDistance matrix of selected varieties of English.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318c05\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c8\">Variety</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">IrishEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">ScottishEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">BritishEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">AustralianEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">NewZealandEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">AmericanEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">CanadianEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">JamaicanEnglish</span></p></td><td class=\"cl-85318bfd\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">PhillipineEnglish</span></p></td><td class=\"cl-85318c04\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c8\">IndianEnglish</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318be7\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">IrishEnglish</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.0</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.0</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.60</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.60</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td><td class=\"cl-85318be6\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318bfb\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">ScottishEnglish</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.0</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.0</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.40</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.60</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.60</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td><td class=\"cl-85318bfa\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.80</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318be7\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">BritishEnglish</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318be6\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318bfb\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">AustralianEnglish</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bfa\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318be7\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">NewZealandEnglish</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.4</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318be6\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318bfb\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">AmericanEnglish</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.6</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.6</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bfa\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318be7\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">CanadianEnglish</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.6</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.6</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.33</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318be6\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318bfb\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">JamaicanEnglish</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bfa\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318be7\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">PhillipineEnglish</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bdc\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318be6\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85318bf0\"><p class=\"cl-85315d7e\"><span class=\"cl-853154c9\">IndianEnglish</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.8</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.67</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.50</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318be8\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td><td class=\"cl-85318bf1\"><p class=\"cl-85315d7f\"><span class=\"cl-853154c9\">0.00</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nAs before, we can now use hierarchical clustering to display the results as a dendrogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create cluster object (ward.D2 linkage)   : cluster in a way to achieve minimum variance\ncd <- hclust(clustd, method=\"ward.D2\")\n# plot result as dendrogram\nplot(cd, hang = -1)              # display dendogram\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/cl35-1.png){width=672}\n:::\n:::\n\n\nIn a next step, we want to determine which features are particularly distinctive for one cluster (the \"Celtic\" cluster containing Irish and Scottish English). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create factor with celtic varieties on one hand and other varieties on other\ncluster <- as.factor(ifelse(as.character(rownames(clusts)) == \"IrishEnglish\", \"1\",\n  ifelse(as.character(rownames(clusts)) == \"ScottishEnglish\", \"1\", \"0\")))\n# convert into data frame\nclsts.df <- as.data.frame(clusts)\n# determine significance\nlibrary(exact2x2)\npfish <- fisher.exact(table(cluster, clsts.df$youse))\npfish[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02222222\n```\n:::\n\n```{.r .cell-code}\n# determine effect size\nassocstats(table(cluster, clsts.df$youse))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    X^2 df  P(> X^2)\nLikelihood Ratio 10.008  1 0.0015586\nPearson          10.000  1 0.0015654\n\nPhi-Coefficient   : 1 \nContingency Coeff.: 0.707 \nCramer's V        : 1 \n```\n:::\n\n```{.r .cell-code}\nassocstats(table(cluster, clsts.df$like))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    X^2 df P(> X^2)\nLikelihood Ratio 1.6323  1  0.20139\nPearson          1.0714  1  0.30062\n\nPhi-Coefficient   : 0.327 \nContingency Coeff.: 0.311 \nCramer's V        : 0.327 \n```\n:::\n:::\n\n\nClustering is a highly complex topic and there many more complexities to it. However, this should have helped to get you started.\n\n\n# Correspondence Analysis\n\nCorrespondence analysis (CA) represents a multivariate statistical technique that provides a graphic method of exploring the relationship between variables in a contingency table. CA is conceptually similar to principal component analysis (PCA), but applies to categorical rather than continuous data.\n\nCA consists out of the following four steps:\n\n1. Computing row and column averages\n2. Computing expected values\n3. Computing the residuals\n4. Plotting residuals\n\nIn this tutorial, we investigate similarities among amplifiers based on their co-occurrences (word embeddings) with adjectives. Adjective amplifiers are elements such as those in 1. to 5.\n\n1. The *very*~amplifier~ *nice*~adjective~ man.\n2. A *truely*~amplifier~ *remarkable*~adjective~ woman. \n2. He was *really*~amplifier~ *hesitant*~adjective~.\n4. The child was *awfully*~amplifier~ *loud*~adjective~.\n5. The festival was *so*~amplifier~ *amazing*~adjective~!\n\nThe similarity among adjective amplifiers can then be used to find clusters or groups of amplifiers that *behave* similarly and are interchangeable. To elaborate, adjective amplifiers are interchangeable with some variants but not with others (consider 6. to 8.; the question mark signifies that the example is unlikely to be used or grammatically not acceptable by L1 speakers of English).\n\n6. The *very*~amplifier~ *nice*~adjective~ man.\n7. The *really*~amplifier~ *nice*~adjective~ man.\n8. ^?^The *completely*~amplifier~ *nice*~adjective~ man.\n\nWe start by loading the data, and then displaying the data which is called `vsmdata` and consist of 5,000 observations of adjectives and contains two columns: one column with the adjectives (Adjectives) and another column which has the amplifiers (0 means that the adjective occurred without an amplifier). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nvsmdata  <- base::readRDS(url(\"https://slcladal.github.io/data/vsd.rda\", \"rb\"))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-85f3799a{table-layout:auto;width:50%;}.cl-85e9ea60{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-85e9ea74{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-85e9fc3a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-85ea2c14{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c1e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c28{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c32{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c33{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c3c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c3d{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-85ea2c46{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-85f3799a'>\n```\n<caption class=\"Table Caption\">\n\nTable showing amplification of English adjectives.\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c46\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea60\">Amplifier</span></p></td><td class=\"cl-85ea2c3d\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea60\">Adjective</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c1e\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c14\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">serious</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c3c\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c33\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">sure</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c1e\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">so</span></p></td><td class=\"cl-85ea2c14\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">many</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c3c\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c33\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">many</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c1e\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c14\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c3c\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c33\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">much</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c1e\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c14\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c3c\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c33\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c1e\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c14\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">last</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-85ea2c32\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">0</span></p></td><td class=\"cl-85ea2c28\"><p class=\"cl-85e9fc3a\"><span class=\"cl-85e9ea74\">nice</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\nFor this tutorial, we will reduce the number of amplifiers and adjectives and thus simplify the data to render it easier to understand what is going on. To simplify the data, we remove \n\n+ all non-amplified adjectives\n+ the adjectives many and much\n+ adjectives that are amplified less than 10 times\n\nIn addition, we collapse all amplifiers that occur less than 20 times into a bin category (*other*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simplify data\nvsmdata_simp <- vsmdata %>%\n  # remove non-amplifier adjectives\n  dplyr::filter(Amplifier != 0,\n         Adjective != \"many\",\n         Adjective != \"much\") %>%\n  # collapse infrequent amplifiers\n  dplyr::group_by(Amplifier) %>%\n  dplyr::mutate(AmpFreq = dplyr::n()) %>%\n  dplyr::ungroup() %>%\n  dplyr::mutate(Amplifier = ifelse(AmpFreq > 20, Amplifier, \"other\")) %>%\n  # collapse infrequent adjectives\n  dplyr::group_by(Adjective) %>%\n  dplyr::mutate(AdjFreq = dplyr::n()) %>%\n  dplyr::ungroup() %>%\n  dplyr::mutate(Adjective = ifelse(AdjFreq > 10, Adjective, \"other\")) %>%\n  dplyr::filter(Adjective != \"other\") %>%\n  dplyr::select(-AmpFreq, -AdjFreq)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div class=\"tabwid\"><style>.cl-86062dc4{table-layout:auto;width:50%;}.cl-86027206{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-86027210{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-86028066{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8602a302{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a30c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a30d{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a316{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a317{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a320{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a321{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8602a322{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-86062dc4'>\n```\n<caption class=\"Table Caption\">\n\nTable showing amplification of English adjectives (simplified).\n\n</caption>\n```{=html}\n<thead><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a322\"><p class=\"cl-86028066\"><span class=\"cl-86027206\">Amplifier</span></p></td><td class=\"cl-8602a321\"><p class=\"cl-86028066\"><span class=\"cl-86027206\">Adjective</span></p></td></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a30c\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">very</span></p></td><td class=\"cl-8602a302\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a320\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a317\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">nice</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a30c\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a302\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a320\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a317\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">bad</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a30c\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">very</span></p></td><td class=\"cl-8602a302\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">nice</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a320\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a317\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">nice</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a30c\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">very</span></p></td><td class=\"cl-8602a302\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">hard</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a320\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">other</span></p></td><td class=\"cl-8602a317\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">good</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a30c\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a302\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">nice</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8602a316\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">really</span></p></td><td class=\"cl-8602a30d\"><p class=\"cl-86028066\"><span class=\"cl-86027210\">good</span></p></td></tr></tbody></table></div>\n```\n:::\n:::\n\n\nWe now use a balloon plot to see if there are any potential correlations between amplifiers and adjectives.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. convert the data as a table\ndt <- as.matrix(table(vsmdata_simp))\n# 2. Graph\nballoonplot(t(dt), main =\"vsmdata_simp\", xlab =\"\", ylab=\"\",\n            label = FALSE, show.margins = FALSE)\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/ca3-1.png){width=672}\n:::\n:::\n\n\nThe balloon plot suggests that there are potential correlations as the dots (balloons) are not distributed evenly according to frequency. To validate if there is significant correlation between the amplifier types and the adjectives using a $\\chi$^2^- test. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq <- chisq.test(dt)\nchisq\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  dt\nX-squared = 124.4, df = 40, p-value = 1.375e-10\n```\n:::\n:::\n\n\nThe $\\chi$^2^- test confirms that there is a significant correlations between amplifier types and the adjectives.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres.ca <- FactoMineR::CA(dt, graph = FALSE)\n# inspect results of the CA\n#print(res.ca)\neig.val <- get_eigenvalue(res.ca)\neig.val\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1 0.24138007        49.868237                    49.86824\nDim.2 0.14687839        30.344536                    80.21277\nDim.3 0.06125177        12.654392                    92.86716\nDim.4 0.03452547         7.132836                   100.00000\n```\n:::\n:::\n\nThe display of the *eigenvalues* provides information on the amount of variance that is explained by each dimension. The first dimension explains 49.87 percent of the variance, the second dimension explains another 30.34 percent of the variance, leaving all other variables with relative moderate explanatory power as they only account for 20 percent variance. We now plot and interpret the results of the CA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# repel= TRUE to avoid text overlapping (slow if many point)\nfviz_ca_biplot(res.ca, \n               repel = TRUE,\n               col.row = \"orange\",\n               col.col = \"darkgray\")\n```\n\n::: {.cell-output-display}\n![](clust_files/figure-html/ca6-1.png){width=672}\n:::\n:::\n\n\nThe results of the CA show that the adjective *different* is collocating with *other* amplifiers while *very* is collocating with *difficult* and *important*, *pretty* is collocating with *big*, *really* is collocating with *nice*, and *so* is collocating with *bad*.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Citation & Session Info {-}\n\nSchweinberger, Martin. 2022. *Cluster and Correspondence Analysis in R*. Brisbane: The University of Queensland. url: https://slcladal.github.io/clust.html (Version 2022.08.31).\n\n```\n@manual{schweinberger2022clust,\n  author = {Schweinberger, Martin},\n  title = {Cluster and Correspondence Analysis in R},\n  note = {https://slcladal.github.io/clust.html},\n  year = {2022},\n  organization = \"The University of Queensland, Australia. School of Languages and Cultures},\n  address = {Brisbane},\n  edition = {2022.08.31}\n}\n```\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.2.1 (2022-06-23)\nPlatform: x86_64-pc-linux-gnu (64-bit)\nRunning under: Ubuntu 22.04.1 LTS\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0\nLAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0\n\nlocale:\n [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    \n [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   \n [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       \n\nattached base packages:\n[1] grid      stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] gplots_3.1.3     tibble_3.1.7     flextable_0.7.3  exact2x2_1.6.6  \n [5] exactci_1.4-2    testthat_3.1.4   ssanv_1.1        vcd_1.4-10      \n [9] ape_5.6-2        pvclust_2.2-0    seriation_1.3.5  factoextra_1.0.7\n[13] ggplot2_3.3.6    cluster_2.1.3   \n\nloaded via a namespace (and not attached):\n [1] nlme_3.1-158         bitops_1.0-7         tools_4.2.1         \n [4] backports_1.4.1      utf8_1.2.2           R6_2.5.1            \n [7] DT_0.24              KernSmooth_2.23-20   DBI_1.1.3           \n[10] colorspace_2.0-3     withr_2.5.0          tidyselect_1.1.2    \n[13] compiler_4.2.1       cli_3.3.0            TSP_1.2-0           \n[16] flashClust_1.01-2    xml2_1.3.3           officer_0.4.3       \n[19] labeling_0.4.2       caTools_1.18.2       scales_1.2.0        \n[22] lmtest_0.9-40        systemfonts_1.0.4    stringr_1.4.0       \n[25] digest_0.6.29        rmarkdown_2.14       base64enc_0.1-3     \n[28] pkgconfig_2.0.3      htmltools_0.5.2      fastmap_1.1.0       \n[31] FactoMineR_2.4       htmlwidgets_1.5.4    rlang_1.0.4         \n[34] rstudioapi_0.13      farver_2.1.1         generics_0.1.3      \n[37] zoo_1.8-10           jsonlite_1.8.0       gtools_3.9.2.2      \n[40] dplyr_1.0.9          zip_2.2.0            car_3.1-0           \n[43] magrittr_2.0.3       leaps_3.1            Rcpp_1.0.8.3        \n[46] munsell_0.5.0        fansi_1.0.3          abind_1.4-5         \n[49] gdtools_0.2.4        lifecycle_1.0.1      scatterplot3d_0.3-41\n[52] stringi_1.7.8        yaml_2.3.5           carData_3.0-5       \n[55] MASS_7.3-58.1        brio_1.1.3           plyr_1.8.7          \n[58] parallel_4.2.1       ggrepel_0.9.1        crayon_1.5.1        \n[61] lattice_0.20-45      knitr_1.39           klippy_0.0.0.9500   \n[64] pillar_1.7.0         ggpubr_0.4.0         uuid_1.1-0          \n[67] ggsignif_0.6.3       reshape2_1.4.4       codetools_0.2-18    \n[70] glue_1.6.2           evaluate_0.15        data.table_1.14.2   \n[73] vctrs_0.4.1          foreach_1.5.2        gtable_0.3.0        \n[76] purrr_0.3.4          tidyr_1.2.0          assertthat_0.2.1    \n[79] xfun_0.31            broom_1.0.0          rstatix_0.7.0       \n[82] iterators_1.0.14     registry_0.5-1       ellipsis_0.3.2      \n```\n:::\n:::\n\n\n\n***\n\n[Back to top](#introduction)\n\n[Back to HOME](https://slcladal.github.io/index.html)\n\n***\n\n# References {-}\n\n",
    "supporting": [
      "clust_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/clipboard-1.7.1/clipboard.min.js\"></script>\n<link href=\"site_libs/primer-tooltips-1.4.0/build.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/klippy-0.0.0.9500/css/klippy.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/klippy-0.0.0.9500/js/klippy.min.js\"></script>\n<link href=\"site_libs/tabwid-1.0.0/tabwid.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/tabwid-1.0.0/scrool.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}