---
title: "Disclaimer and Contact"
---

# Disclaimer

The content of this website is free and comes with ABSOLUTELY NO WARRANTY. You are welcome to redistribute ot under certain conditions. 


The content of this website is distributed under the terms of the GNU General Public License, either Version 2, June 1991 or Version 3, June 2007. The terms of version 2 of the license are in a file called COPYING which you should have received with this software and which can be displayed by typing and executing RShowDoc("COPYING") in the R Console. Version 3 of the license can be displayed by  typing and executing RShowDoc("GPL-3")  in the R Console.

Copies of both versions 2 and 3 of the license can be found at https://www.R-project.org/Licenses/.

**Share and Enjoy***

# Contact
University of Queensland

School of Languages and Cultures

Room 320, Third Floor, Gordon Greenwood Building (32)

The University of Queensland

St Lucia QLD 4072, Australia



Email: <languages-cultures@uq.edu.au>

Phone: (07) 3365 6311

Fax: (07) 3365 6799



