<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="UQ SLC Digital Team" />

<meta name="date" content="2019-02-20" />

<title>The Chi-Square Family of Tests</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="introquant.html">Introduction To Quantitative Reasoning</a>
    </li>
    <li>
      <a href="basicquant.html">Basic Concepts In Quantitative Reasoning</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Research Designs</li>
    <li>
      <a href="researchdesigns.html">Overview</a>
    </li>
    <li>
      <a href="corpling.html">Corpus Linguistics</a>
    </li>
    <li>
      <a href="experiments.html">Experimental Designs</a>
    </li>
    <li>
      <a href="ca.html">Conversation Analysis</a>
    </li>
    <li>
      <a href="acoustic.html">Acoustic Analysis</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Data Collection</li>
    <li>
      <a href="introdatacollection.html">Introduction</a>
    </li>
    <li>
      <a href="fieldwork.html">Field Work</a>
    </li>
    <li>
      <a href="interviews.html">Interviews</a>
    </li>
    <li>
      <a href="questionnaires.html">Questionnaires and Surveys</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics: Getting started with R</a>
    </li>
    <li>
      <a href="introloading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="introtables.html">Tabulating data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic Visualization Techniques</a>
    </li>
    <li>
      <a href="advancedgraphs.html">Advanced Visualization Techniques</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics</li>
    <li>
      <a href="descriptivestatz.html">Descriptive Statistics</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="basicstatz.html">Basic Interential Statistics</a>
    </li>
    <li>
      <a href="basicstatzchi.html">The Chi-Square Family</a>
    </li>
    <li>
      <a href="basicstatzregression.html">Simple Linear Regression</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Advanced Interential Statistics</li>
    <li>
      <a href="advancedstatzregressions.html">Regression Analysis</a>
    </li>
    <li>
      <a href="advancedstatztrees.html">Tree-Based Models</a>
    </li>
    <li>
      <a href="groupingstatz.html">Agglomerative Procedures</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis</li>
    <li>
      <a href="webcrawling.html">Web Crawling</a>
    </li>
    <li>
      <a href="network.html">Network Analysis</a>
    </li>
    <li>
      <a href="topic.html">Topic Modeling</a>
    </li>
    <li>
      <a href="classification.html">Classification</a>
    </li>
    <li>
      <a href="tagging.html">Tagging and Parsing</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Corpus Linguistics</li>
    <li>
      <a href="corplingr.html">Corpus Linguistics in R</a>
    </li>
    <li>
      <a href="corplingantconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="available.html">Available Software</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">The Chi-Square Family of Tests</h1>
<h4 class="author"><em>UQ SLC Digital Team</em></h4>
<h4 class="date"><em>2019-02-20</em></h4>

</div>


<p><img src="images/uq1.jpg" width="100%" /></p>
<div id="pearsonss-chi-square-test" class="section level1">
<h1><span class="header-section-number">1</span> (Pearsons’s) Chi-Square Test</h1>
<p>To explore how chi-square tests (or Pearsons’s chi-square tests, chi-squared tests, or simply <span class="math inline">\(\chi\)</span><sup>2</sup> tests) work, we will focus on a practical example. In this example, we will test whether speakers of American English (AmE) and speakers of British English (BrE) differ in their use of the near-synonyms <em>sort of</em> and <em>kind of</em> as in “<em>He’s sort of stupid</em>” and “<em>He’s kind of stupid</em>”. As a first step, we formulate the hypothesis that we want to test (H<sub>1</sub>) and its Nullhypothesis (H<sub>0</sub>). The Alternative- or Test Hypothesis reads:</p>
<p>H<sub>1</sub>: Speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>while the Null Hypothesis (H<sub>0</sub>) states</p>
<p>H<sub>0</sub>: Speakers of AmE and BrE do not differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>The H<sub>0</sub> claims the non-existence of something (which is the more conservative position) and in our example the non-existence of a correlation between variety of English and the use of <em>sort of</em> und <em>kind of</em>. The question now arises what has to be the case in order to reject the H<sub>0</sub> in favour of the H<sub>1</sub>.</p>
<p>To answer this question, we require information about the probability of error, i.e. the probability that the H<sub>0</sub> does indeed hold for the entire population. Before performing the chi-square test, we follow the convention that the required significance level is 5 percent. In other words, we will reject the H<sub>0</sub> if the likelihood for the H<span class="math inline">\(_{0}\)</span> being true is less than 5 percent given the distribution of the data. In that case, i.e. in case that the likelihood for the H<sub>0</sub> being true is less than 5 percent, we consider the result of the chi-square test as statistically significant. This means that the observed distribution makes it very unlikely that there is no correlation between the variety of English and the use of <em>sort of</em> and <em>kind of</em>.</p>
<p>Let us now assume that we have performed a search for <em>sort of</em> and <em>kind of</em> in two corpora representing American and British English and that we have obtained the following frequencies:</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">655</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">177</td>
<td align="right">67</td>
</tr>
</tbody>
</table>
<p>In a first step, we now have to calculate the row and column sums of our table.</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">655</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">177</td>
<td align="right">67</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358</td>
<td align="right">722</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>Next, we calculate, the values that would have expected if there was no correlation between variety of English and the use of <em>sort of</em> and <em>kind of</em>. In order to get these “expected” frequencies, we apply the equation below to all cells in our table.</p>
<p><span class="math inline">\(\frac{Column total*Row total}{Overall total}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{836*358}{1080} = \frac{299288}{1080} = 277.1185\)</span></p>
<p>For the entire table this means we get the following expected values:</p>
<table>
<caption>Expected frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">277.11850</td>
<td align="right">558.8815</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">80.88148</td>
<td align="right">163.1185</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358.00000</td>
<td align="right">722.0000</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>In a next step, we calculate the contribution of each cell to the overall <span class="math inline">\(\chi\)</span><sup>2</sup> value (<span class="math inline">\(\chi\)</span><sup>2</sup> contribution). To get <span class="math inline">\(\chi\)</span><sup>2</sup> contribution for each cell, we apply the equation below to each cell.</p>
<p><span class="math inline">\(\frac{(observed – expected)^{2}}{expected}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{(181 – 277.1185)^{2}}{277.1185} = \frac{-96.1185^{2}}{277.1185} = \frac{9238.766}{277.1185} = 33.33868\)</span></p>
<p>For the entire table this means we get the following <span class="math inline">\(\chi^{2}\)</span> values:</p>
<table>
<caption>Chi values of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">33.33869</td>
<td align="right">16.53082</td>
<td align="right">49.86951</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">114.22602</td>
<td align="right">56.63839</td>
<td align="right">170.86440</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">147.56470</td>
<td align="right">73.16921</td>
<td align="right">220.73390</td>
</tr>
</tbody>
</table>
<p>The sum of <span class="math inline">\(\chi\)</span><sup>2</sup> contributions in our example is 220.7339. To see if this value is statistically significant, we need to calculate the degrees of freedom because the <span class="math inline">\(\chi\)</span> distribution differs across degrees of freedom. Degrees of freedom are calculated according to the equation below.</p>
<p><span class="math inline">\(DF = (rows -1) * (columns – 1) = (2-1) * (2-1) = 1 * 1 = 1\)</span></p>
<p>In a last step, we check whether the <span class="math inline">\(\chi\)</span><sup>2</sup> value that we have calculated is higher than a critical value (in which case the correlation in our table is significant). Degrees of freedom are relevant here because the critical values are dependent upon the degrees of freedom: the more degrees of freedom, the higher the critical value, i.e. the harder it is to breach the level of significance.</p>
<p>Since there is only 1 degree of freedom in our case, we need to consider only the first column in the table of critical values below.</p>
<table>
<caption>Critical chi values for 1 to 5 degrees of freedom</caption>
<thead>
<tr class="header">
<th align="right">DF</th>
<th align="right">p&lt;.05</th>
<th align="right">p&lt;.01</th>
<th align="right">p&lt;.001</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">3.84</td>
<td align="right">6.64</td>
<td align="right">10.83</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">5.99</td>
<td align="right">9.21</td>
<td align="right">13.82</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">7.82</td>
<td align="right">11.35</td>
<td align="right">16.27</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">9.49</td>
<td align="right">13.28</td>
<td align="right">18.47</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">11.07</td>
<td align="right">15.09</td>
<td align="right">20.52</td>
</tr>
</tbody>
</table>
<p>Since the <span class="math inline">\(\chi\)</span><sup>2</sup> value that we have calculated is much higher than the critical value provided for p&lt;.05, we can reject the H<sub>0</sub> and may now claim that speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>Before we summarize the results, we will calculate the effect size which is a measure for how strong the correlations are.</p>
<div id="effect-sizes-in-chi-square" class="section level3">
<h3><span class="header-section-number">1.0.1</span> Effect Sizes in Chi-Square</h3>
<p>Effect sizes are important because they correlations may be highly significant but the effect between variables can be extremely weak. The effect size is therefore a measure how strong the correlation or the explanatory and predictive power between variables is.</p>
<p>The effect size measure for <span class="math inline">\(\chi\)</span><sup>2</sup> tests can be either the <span class="math inline">\(\phi\)</span>-coefficient (phi-coefficient) or Cramer’s <span class="math inline">\(\phi\)</span> (Cramer’s phi). The <span class="math inline">\(\phi\)</span>-coefficient is used when dealing with 2x2 tables while Cramer’s <span class="math inline">\(\phi\)</span> is used when dealing with tables with more than 4 cells. The <span class="math inline">\(\phi\)</span> coefficient can be calculated by using the equation below (N = overall sample size).</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{\chi^{2}}{N}}\)</span></p>
<p>In our case, this means:</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{220.7339}{1080}} = \sqrt{0.2043832} = 0.4520876\)</span></p>
<p>The <span class="math inline">\(\phi\)</span> coefficient varies between 0 (no effect) and 1 (perfect correlation). For the division into weak, moderate and strong effects one can follow the division for <span class="math inline">\(\omega\)</span> (small omega), so that with values beginning with .1 represent weak, values between 0.3 and .5 represent moderate and values above .5 represent strong effects <span class="citation">(Bühner and Ziegler <a href="#ref-buehner2009statistik">2009</a>, 266)</span>. So, in this example we are dealing with a medium-sized effect/correlation.</p>
</div>
<div id="chi-square-in-r" class="section level3">
<h3><span class="header-section-number">1.0.2</span> Chi-Square in R</h3>
<p>Before we summarize the results, we will see how to perform a chi-square test in <code>R</code>. In addition to what we have done above, we will also visualize the data. To begin with, we will have a look at the data set (which is the same data we have used above).</p>
<pre class="r"><code>chidata              # inspect data</code></pre>
<pre><code>##        BrE AmE
## kindof 181 655
## sortof 177  67</code></pre>
<p>We will now visualize the data with an association. Bars above the dashed line indicate that a feature combination occurs more frequently than expected by chance. The width of the bars indicates the frequency of the feature combination.</p>
<p><img src="basicstatzchi_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The fact that the bars are distributed complimentarily (top left red and below bar; top right black above bar; bottom left black above bar; bottom right red below bar) indicates that the use of “sort of” and “kind of” differs across AmE and BrE. We will check whether the mosaic plot confirms this impression.</p>
<pre class="r"><code>mosaicplot(chidata, shade = TRUE, type = &quot;pearson&quot;, main = &quot;&quot;)  # mosaic plot</code></pre>
<p><img src="basicstatzchi_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The colour contrasts in the mosaic plot substantiate the impression that the two varieties of English differ significantly. To ascertain whether the differences are statistically significant, we can now apply the chi-square test.</p>
<pre class="r"><code>chisq.test(chidata, corr = F)  # perform chi square test</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chidata
## X-squared = 220.73, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>The results reported by <code>R</code> are identical to the results we derived by hand and confirm that BrE and AmE differ significantly in their use of “sort of” and “kind of”. In a next step, we calculate the effect size.</p>
<pre class="r"><code># calculate effect size
sqrt(chisq.test(chidata, corr = F)$statistic / sum(chidata) * (min(dim(chidata))-1))</code></pre>
<pre><code>## X-squared 
## 0.4520877</code></pre>
<p>The phi coefficient of .45 shows that variety of English correlates moderately with the use of “sort of” and “kind of”. We will now summarize the results.</p>
</div>
<div id="summarizing-chi-square-results" class="section level3">
<h3><span class="header-section-number">1.0.3</span> Summarizing Chi-Square Results</h3>
<p>The results of our analysis can be summarised as follows: A <span class="math inline">\(\chi\)</span><sup>2</sup>-test confirms a highly significant correlation of moderate size between the variety of English and the use of the near-synonymous hedges <em>sort of</em> and <em>kind of</em> (<span class="math inline">\(\chi\)</span><sup>2</sup> = 220.73, df = 1, p &lt; .001***, <span class="math inline">\(\phi\)</span> = .452).</p>
</div>
<div id="requirements-of-chi-square" class="section level3">
<h3><span class="header-section-number">1.0.4</span> Requirements of Chi-Square</h3>
<p>Chi-square tests depend on certain requirements that, if violated, negatively affect the reliability of the results of the test. To provide reliable results, 80 percent of cells in a table to which the chi-square test is applied have to have expected values of 5 or higher and at most 20 percent of expected values can be smaller than 5 <span class="citation">(see Bortz, Lienert, and Boehnke <a href="#ref-bortz1990verteilungsfreie">1990</a>, 98)</span>. In addition, none of the expected values can be smaller than 1 <span class="citation">(see Bortz, Lienert, and Boehnke <a href="#ref-bortz1990verteilungsfreie">1990</a>, 136)</span> because then, the estimation, which relies on the <span class="math inline">\(\chi\)</span><sup>2</sup>-distribution, becomes too imprecise to allow meaningful inferences <span class="citation">(Cochran <a href="#ref-cochran1954somemethods">1954</a>)</span>.</p>
<p>If these requirements are violated, then the <em>Fisher’s Exact Test</em> is more reliable and offers the additional advantage that these tests can also be applied to data that represent very small sample sizes. When applying the Fisher’s Exact Test, the probabilities for all possible outcomes are calculated and the summed probability for the observed or more extreme results are determined. If this sum of probabilities exceeds five percent, then the result is deemed statistically significant.</p>
</div>
<div id="extensions-of-chi-square" class="section level2">
<h2><span class="header-section-number">1.1</span> Extensions of Chi-Square</h2>
<p>In the following, we will have a look at tests and methods that can be used if the requirements for ordinary (Pearson’s) chi-square tests are violated and their use would be inappropriate</p>
<div id="the-yates-correction" class="section level3">
<h3><span class="header-section-number">1.1.1</span> The Yates-Correction</h3>
<p>If all requirements for ordinary chi-square tests are acceptable and only the sample size is the issue, then applying a so-called <em>Yates-correction</em> may be appropriate. This type of correction is applied in cases where the overall sample size lies in-between 60 and 15 cases (<span class="citation">(Bortz, Lienert, and Boehnke <a href="#ref-bortz1990verteilungsfreie">1990</a>)</span> 91). The difference between the ordinary chi-square and a Yates-corrected chi-square lies in the fact that the Yates-corrected chi-square is calculated according to the equation below.</p>
<p><span class="math inline">\(\frac{(|observed – expected|-0.5)^{2}}{expected}\)</span></p>
<p>According to this formula, we would get the values shown below rather than the values tabulated above. It is important to note here that this is only a demonstration because a Yates-Correction would actually be inappropriate as our sample size exceeds 60 cases.</p>
<table>
<caption>Corrected chi-square values for sort of and kind of in BrE and AmE</caption>
<thead>
<tr class="header">
<th align="left">Variant</th>
<th align="left">BrE</th>
<th align="left">AmE</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">kind of</td>
<td align="left">32.9927</td>
<td align="left">113.0407</td>
<td align="left">146.0335</td>
</tr>
<tr class="even">
<td align="left">sort of</td>
<td align="left">16.3593</td>
<td align="left">56.0507</td>
<td align="left">72.41</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left">49.352</td>
<td align="left">169.0914</td>
<td align="left">218.4434</td>
</tr>
</tbody>
</table>
<p>If the Yates-correction were applied, then this results in a slightly lower <span class="math inline">\(\chi\)</span><sup>2</sup>-value and thus in more conservative results compared with the traditional test according to Pearson.</p>
</div>
<div id="chi-square-within-2k-tables" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Chi-Square within 2*k Tables</h3>
<p>Although the <span class="math inline">\(\chi\)</span><sup>2</sup>-test is widely used, it is often used inappropriately. This is especially the case when chi-square tests are applied to data representing tables with more than two rows and more than two columns. It is important to note that applying the common Pearson’s’ chi-square test to sub-tables of a larger table is inappropriate because, in such cases, a modified variant of Pearson’s’ chi-square test is warranted. We will go through two examples that represent different scenarios where we are dealing with subsamples of larger tables and a modified version of the <span class="math inline">\(\chi\)</span><sup>2</sup>-test should be used rather than Pearson’s’ chi-square.</p>
<p>In this first example, we are dealing with a table consisting of two columns and multiple rows, a so-called 2*k table (two-by-k table). In order to test if a feature combination, that is represented by a row in the 2*k table, is significantly more common compared with other feature combinations, we need to implement the <span class="math inline">\(\chi\)</span><sup>2</sup>-equation from <span class="citation">(Bortz, Lienert, and Boehnke <a href="#ref-bortz1990verteilungsfreie">1990</a>, 126–27)</span>.</p>
<p>In this example, we want to find out whether soft and hard X-rays differ in their effect on grasshopper larva. The question is whether the larva reach or do not reach a certain life cycle depending on whether they are exposed to soft X-rays, hard X-rays, light, or beta rays. The data for this example is provided below.</p>
<table>
<caption>Data adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">Mitosis not reached</th>
<th align="left">Mitosis reached</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X-ray soft</td>
<td align="left">21</td>
<td align="left">14</td>
<td align="left">35</td>
</tr>
<tr class="even">
<td>X-ray hard</td>
<td align="left">18</td>
<td align="left">13</td>
<td align="left">31</td>
</tr>
<tr class="odd">
<td>Beta-rays</td>
<td align="left">24</td>
<td align="left">12</td>
<td align="left">36</td>
</tr>
<tr class="even">
<td>Light</td>
<td align="left">13</td>
<td align="left">30</td>
<td align="left">43</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">76</td>
<td align="left">69</td>
<td align="left">145</td>
</tr>
</tbody>
</table>
<p>If we would apply an ordinary chi-square test, we would ignore that all data were collected together and using only a subsample would ignore the data set of which the subsample is part of. In other words, the subsample is not independent from the other data (as it represents a subsection of the whole data set). However, for exemplary reasons, we will apply an ordinary chi-square test first and then compare its results to results provided by the correct version of the chi-square test. In a first step, we create a table with all the data.</p>
<pre class="r"><code># create tdata
wholetable &lt;- matrix(c(21, 14, 18, 13, 24, 12, 13, 30), byrow = T, nrow = 4)
colnames(wholetable) &lt;- c(&quot;reached&quot;, &quot;notreached&quot;)           # add column names
rownames(wholetable) &lt;- c(&quot;rsoft&quot;, &quot;rhard&quot;, &quot;beta&quot;, &quot;light&quot;) # add row names
wholetable                                                   # inspect data</code></pre>
<pre><code>##       reached notreached
## rsoft      21         14
## rhard      18         13
## beta       24         12
## light      13         30</code></pre>
<p>Now, we extract the subsample from the data.</p>
<pre class="r"><code>subtable &lt;- wholetable[1:2,] # extract subtable
subtable                     # inspect subtable</code></pre>
<pre><code>##       reached notreached
## rsoft      21         14
## rhard      18         13</code></pre>
<p>Next, we apply the ordinary chi-square test to the subsample.</p>
<pre class="r"><code># simple x2-test
chisq.test(subtable, corr = F)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  subtable
## X-squared = 0.025476, df = 1, p-value = 0.8732</code></pre>
<p>Finally, we perform the correct chi-square test.</p>
<pre class="r"><code># load function for correct chi-square
source(&quot;rscripts/x2.2k.r&quot;) 
x2.2k(wholetable, 1, 2)</code></pre>
<pre><code>## $Description
## [1] &quot;rsoft  against  rhard  by  reached  vs  notreached&quot;
## 
## $`Chi-Squared`
## [1] 0.025
## 
## $df
## [1] 1
## 
## $`p-value`
## [1] 0.8744
## 
## $Phi
## [1] 0.013
## 
## $Report
## [1] &quot;Conclusion: the null hypothesis cannot be rejected! Results are not significant!&quot;</code></pre>
<p>Below is a table comparing the results of the two chi-square tests.</p>
<pre class="r"><code>library(knitr)
critval &lt;- matrix(c(&quot;chi-squared&quot;, 0.0255, 0.025, &quot;p-value&quot;, 0.8732, 0.8744), ncol = 3, byrow = T)
# add column names
colnames(critval) &lt;- c(&quot;&quot;, &quot;chi-square&quot; , &quot;chi-square in 2*k-tables&quot;)
kable(critval, caption = &quot;Table adapted from Bortz (1990: 126)&quot;)</code></pre>
<table>
<caption>Table adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">chi-square</th>
<th align="left">chi-square in 2*k-tables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chi-squared</td>
<td align="left">0.0255</td>
<td align="left">0.025</td>
</tr>
<tr class="even">
<td>p-value</td>
<td align="left">0.8732</td>
<td align="left">0.8744</td>
</tr>
</tbody>
</table>
<p>The comparison shows that, in this example, the results of the two tests are very similar but this may not always be the case.</p>
</div>
<div id="chi-square-within-zk-tables" class="section level3">
<h3><span class="header-section-number">1.1.3</span> Chi-Square within z*k Tables</h3>
<p>Another application in which the <span class="math inline">\(\chi\)</span><sup>2</sup> test is often applied incorrectly is when ordinary Parsons’s <span class="math inline">\(\chi\)</span><sup>2</sup> tests are used to test portions of tables with more than two rows and more than two columns, that is z*k tables (z: row, k: column). An example is discussed by <span class="citation">Gries (<a href="#ref-gries2014frequency">2014</a>)</span> who also wrote the <code>R</code> Script for the correct version of the <span class="math inline">\(\chi\)</span><sup>2</sup> test.</p>
<p>Let’s first load the data discussed in the example of <span class="citation">Gries (<a href="#ref-gries2014frequency">2014</a>)</span> 9. The example deals with metaphors across registers. Based on a larger table, a <span class="math inline">\(\chi\)</span><sup>2</sup> confirmed that registers differ with respect to the frequency of EMOTION metaphors. The more refined question is whether the use of the metaphors EMOTION IS LIGHT and EMOTION IS A FORCE OF NATURE differs between spoken conversation and fiction.</p>
<pre class="r"><code># create table
wholetable &lt;- matrix(c(8, 31, 44, 36, 5, 14, 25, 38, 4, 22, 17, 12, 8, 11, 16, 24), ncol=4)
attr(wholetable, &quot;dimnames&quot;)&lt;-list(Register=c(&quot;acad&quot;, &quot;spoken&quot;, &quot;fiction&quot;, &quot;new&quot;),
Metaphor = c(&quot;Heated fluid&quot;, &quot;Light&quot;, &quot;NatForce&quot;, &quot;Other&quot;))</code></pre>
<p>Based on the table above, we can extract the following subtable.</p>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th align="left">Register</th>
<th align="left">Heated fluid</th>
<th align="left">Light</th>
<th align="left">NatForce</th>
<th align="left">Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">acad</td>
<td align="left">8</td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">spoken</td>
<td align="left">31</td>
<td align="left">14</td>
<td align="left">22</td>
<td align="left">11</td>
</tr>
<tr class="odd">
<td align="left">fiction</td>
<td align="left">44</td>
<td align="left">25</td>
<td align="left">17</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">new</td>
<td align="left">36</td>
<td align="left">38</td>
<td align="left">12</td>
<td align="left">24</td>
</tr>
</tbody>
</table>
<p>If we used an ordinary Pearson’s <span class="math inline">\(\chi\)</span><sup>2</sup> test (the use of which would be inappropriate here), it would reveal that spoken conversations do not differ significantly from fiction in their use of EMOTION IS LIGHT and EMOTION IS A FORCE OF NATURE (<span class="math inline">\(\chi\)</span><sup>2</sup>=3.3016, df=1, p=.069, <span class="math inline">\(\phi\)</span>=.2057).</p>
<pre class="r"><code># create table
subtable &lt;- matrix(c(14, 25, 22, 17), ncol=2)
chisq.results &lt;- chisq.test(subtable, correct=FALSE) # WRONG!
phi.coefficient = sqrt(chisq.results$statistic / sum(subtable) * (min(dim(subtable))-1))
chisq.results</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  subtable
## X-squared = 3.3016, df = 1, p-value = 0.06921</code></pre>
<pre class="r"><code>phi.coefficient</code></pre>
<pre><code>## X-squared 
## 0.2057378</code></pre>
<p>The correct analysis takes into account that it is a subtable that is not independent of the overall table. This means that the correct analysis should take into account the total number of cases, as well as the row and column totals <span class="citation">(vgl. Bortz, Lienert, and Boehnke <a href="#ref-bortz1990verteilungsfreie">1990</a>, 144–48)</span>.</p>
<p>In order to perform the correct analysis, we must either implement the equation proposed in <span class="citation">Bortz, Lienert, and Boehnke (<a href="#ref-bortz1990verteilungsfreie">1990</a>)</span> 144-148 or read in the function written by <span class="citation">Gries (<a href="#ref-gries2014frequency">2014</a>)</span> and apply it to the subtable.</p>
<pre class="r"><code># load function for chi square test for subtables
source(&quot;rscripts/sub.table.r&quot;) 
# apply test
results &lt;- sub.table(wholetable, 2:3, 2:3, out=&quot;short&quot;)
# inspect results
results</code></pre>
<pre><code>## $`Whole table`
##          Metaphor
## Register  Heated fluid Light NatForce Other Sum
##   acad               8     5        4     8  25
##   spoken            31    14       22    11  78
##   fiction           44    25       17    16 102
##   new               36    38       12    24 110
##   Sum              119    82       55    59 315
## 
## $`Sub-table`
##          Metaphor
## Register  Light NatForce Sum
##   spoken     14       22  36
##   fiction    25       17  42
##   Sum        39       39  78
## 
## $`Chi-square tests`
##                                   Chi-square Df    p-value
## Cells of sub-table to whole table  7.2682190  3 0.06382273
## Rows (within sub-table)            0.2526975  1 0.61518204
## Columns (within sub-table)         3.1519956  1 0.07583417
## Contingency (within sub-table)     3.8635259  1 0.04934652</code></pre>
<p>The results show that the difference is, in fact, statistically significant (<span class="math inline">\(\chi^{2}\)</span>=3.864, df=1, p=.049*).</p>
</div>
<div id="chi-square-exercises" class="section level3">
<h3><span class="header-section-number">1.1.4</span> Chi-Square Exercises</h3>
<ol style="list-style-type: decimal">
<li>Imagine you are interested in whether older or younger speakers tend to refer to themselves linguistically. The underlying hypothesis is that - contrary to common belief - older people are more narcissistic compared with younger people. Given this research question, perform a chi-square test and summarize the results on the data below.</li>
</ol>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">1SGPN</th>
<th align="left">PN without 1SG</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Young</td>
<td align="left">61</td>
<td align="left">43</td>
<td align="left">104</td>
</tr>
<tr class="even">
<td>Old</td>
<td align="left">42</td>
<td align="left">36</td>
<td align="left">78</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">103</td>
<td align="left">79</td>
<td align="left">182</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>Imagine you are interested in whether young men or young women exhibit a preference for the word <em>whatever</em> because you have made the unsystematic, anecdotal observation that young men use this word more frequently than young women. Given this research question, perform a chi-square test and summarize the results on the data below.</li>
</ol>
<table class="table table-striped" style>
<caption>
Observed frequency with row- and column totals for the use of <em>whatever</em> by male and female speakers.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
YoungMales
</th>
<th style="text-align:left;">
YoungFemales
</th>
<th style="text-align:left;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
whatever
</td>
<td style="text-align:left;">
17
</td>
<td style="text-align:left;">
55
</td>
<td style="text-align:left;">
71
</td>
</tr>
<tr>
<td style="text-align:left;">
other words
</td>
<td style="text-align:left;">
345128
</td>
<td style="text-align:left;">
916552
</td>
<td style="text-align:left;">
1261680
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
345145
</td>
<td style="text-align:left;">
916607
</td>
<td style="text-align:left;">
1261752
</td>
</tr>
</tbody>
</table>
<ol start="3" style="list-style-type: decimal">
<li>Find a partner and discuss the relationship between significance and effect size. Then, go and find another partner and discuss problems that may arise when testing the frequency of certain words compared with the overall frequency of words in a corpus.</li>
</ol>
</div>
</div>
<div id="hierarchical-configural-frequency-analysis" class="section level2">
<h2><span class="header-section-number">1.2</span> (Hierarchical) Configural Frequency Analysis</h2>
<p>Work in progress</p>
<div id="configural-frequency-analysis-cfa" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Configural Frequency Analysis (CFA)</h3>
<p>Work in progress</p>
</div>
<div id="hierarchical-configural-frequency-analysis-hcfa" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Hierarchical Configural Frequency Analysis (HCFA)</h3>
<p>Work in progress</p>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-bortz1990verteilungsfreie">
<p>Bortz, J, GA Lienert, and K Boehnke. 1990. <em>Verteilungsfreie Methoden in Der Biostatistik</em>. Berlin: Springer Verlag.</p>
</div>
<div id="ref-buehner2009statistik">
<p>Bühner, Markus, and Matthias Ziegler. 2009. <em>Statistik Für Psychologen Und Sozialwissenschaftler</em>. München: Pearson Studium.</p>
</div>
<div id="ref-cochran1954somemethods">
<p>Cochran, W. G. 1954. “Some Methods for Strengthening the Common <span class="math inline">\(\chi\)</span>^2tests.” <em>Biometrics</em> 10: 417–51.</p>
</div>
<div id="ref-gries2014frequency">
<p>Gries, Stefan Thomas. 2014. “Frequency Tables: Tests, Effect Sizes, and Explorations.” In <em>Polysemy and Synonymy: Corpus Methods and Applications in Cognitive Linguistics.</em>, edited by Dylan Glynn and Justyna Robinson, 365–89. Amsterdam: John Benjamins.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
