<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="UQ SLC Digital Team" />

<meta name="date" content="2019-01-23" />

<title>Basic Inferential Statistics</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="introquant.html">Introduction To Quantitative Reasoning</a>
    </li>
    <li>
      <a href="researchdesigns.html">Research Designs</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics: Getting started with R</a>
    </li>
    <li>
      <a href="loading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="introtables.html">Tabulating data</a>
    </li>
    <li>
      <a href="webcrawling.html">Web Crawling</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic Visualization Techniques</a>
    </li>
    <li>
      <a href="advancedgraphs.html">Advanced Visualization Techniques</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics</li>
    <li>
      <a href="descriptives.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="basicstatz.html">Basic Interential Statistics</a>
    </li>
    <li>
      <a href="advancedstatz.html">Advanced Interential Statistics</a>
    </li>
    <li>
      <a href="groupingstatz.html">Clustering</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis and Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Network Analysis</a>
    </li>
    <li>
      <a href="page-c.html">Topic Modeling</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="corplingr.html">Corpus Linguistics in R</a>
    </li>
    <li>
      <a href="corplingantconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="available.html">Available Software</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Basic Inferential Statistics</h1>
<h4 class="author"><em>UQ SLC Digital Team</em></h4>
<h4 class="date"><em>2019-01-23</em></h4>

</div>


<p><img src="images/uq1.jpg" width="100%" /></p>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>This tutorial introduces basic statistical techniques from inferential statistics for hypothesis testing. The first part of this section focuses on basic non-parametric tests such as the chi-square family of tests while the second part introduces simple regression models and discusses their underlying logic.</p>
</div>
<div id="non-parametric-tests" class="section level1">
<h1><span class="header-section-number">2</span> Non-Parametric Tests</h1>
<p>This section focuses on test that do not require the data to be distributed normally. Tests that do not rewuire normal data are referred to as <em>non-parametric tests</em> (test that require the data to be distributed normally are analogously called <em>parametric tests</em>). We focus on non-parametric tests first as this family of test in frequently used in linguistics. In the later part of this section, we will focus on regression modelling where assumptions of about the data become more important.</p>
<div id="pearsonss-chi-square-test" class="section level2">
<h2><span class="header-section-number">2.1</span> Pearsons’s Chi-Square Test</h2>
<p>To explore how chi-square tests (or Pearsons’s chi-square tests, chi-squared tests, or simply <span class="math inline">\(\chi^{2}\)</span> tests) work, we will focus on a practicla example. In this example, we will test whether speakers of American English (AmE) and speakers of British English (BrE) differ in their use of the near-synonyms <em>sort of</em> and <em>kind of</em> as in “<em>He’s sort of stupid</em>” and “<em>He’s kind of stupid</em>”. As a first step, we formulate the hypothesis that we want to test (H<span class="math inline">\(_{1}\)</span>) and its Nullhypothesis (H<span class="math inline">\(_{0}\)</span>). The Alternativ- or Testhypothesis reads:</p>
<p>H<span class="math inline">\(_{1}\)</span>: Speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>while the Nullhypothesis (H<span class="math inline">\(_{0}\)</span>) states</p>
<p>H<span class="math inline">\(_{0}\)</span> Speakers of AmE and BrE do not differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>The H<span class="math inline">\(_{0}\)</span> claims the non-existence of something (which is the more conservative position) and in our example the non-existence of a correlation between variety of English and the use of <em>sort of</em> und <em>kind of</em>. The question now arises what has to be the case in order to reject the H<span class="math inline">\(_{0}\)</span> in favor of the H<span class="math inline">\(_{1}\)</span>.</p>
<p>To answer this question, we require information about the probability of error, i.e. the probability that the H<span class="math inline">\(_{0}\)</span> does indeed hold for the entire population. Before performing the chi-square test, we follow the convetion that the required significance level is 5 percent. In other words, we will reject the H<span class="math inline">\(_{0}\)</span> if the likelyhood for the H<span class="math inline">\(_{0}\)</span> being true is less than 5 percent given the distribution of the data. In that case, i.e. in case that the likelihood for the H<span class="math inline">\(_{0}\)</span> being true is less than 5 percent, we consider the result of the chi-square test as statistically significant. This means that the observed distribution makes it very unlikey that there is no correlation between the variety of English and the use of <em>sort of</em> and <em>kind of</em>.</p>
<p>Let us now assume that we have performed a search for <em>sort of</em> and <em>kind of</em> in two corpora representing American and British English and that we have obtained the following freqeuncies:</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">177</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">655</td>
<td align="right">67</td>
</tr>
</tbody>
</table>
<p>In a first step, we now have to caluculate the row and column sums of our table.</p>
<p>I had the same question. I have tried all solutions provided above and none of them worked… But I have found a solution that works for me, and hopefully for others too.</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">655</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">177</td>
<td align="right">67</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358</td>
<td align="right">722</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>Next, we calculate, the values that would have expected if there was no correlation between variety of English and the use of <em>sort of</em> and <em>kind of</em>. In order to get these “expected” freqeuncies, we apply the equation below to all cells in our table.</p>
<p><span class="math inline">\(\frac{Column total*Row total}{Overall total}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{836*358}{1080} = \frac{299288}{1080} = 277.1185\)</span></p>
<p>For the entire table this means we get the following expected values:</p>
<table>
<caption>Expected frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">277.11850</td>
<td align="right">558.8815</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">80.88148</td>
<td align="right">163.1185</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358.00000</td>
<td align="right">722.0000</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>In a next step, we calculate the contribution of each cell to the overall <span class="math inline">\(\chi^{2}\)</span> value (<span class="math inline">\(\chi^{2}\)</span> contribution). To get <span class="math inline">\(\chi^{2}\)</span> contribution for each cell, we apply the equation below to each cell.</p>
<p><span class="math inline">\(\frac{(observed – expected)^{2}}{expected}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{(181 – 277.1185)^{2}}{277.1185} = \frac{-96.1185^{2}}{277.1185} = \frac{9238.766}{277.1185} = 33.33868\)</span></p>
<p>For the entire table this means we get the following <span class="math inline">\(\chi^{2}\)</span> values:</p>
<table>
<caption>Chi values of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">33.33869</td>
<td align="right">16.53082</td>
<td align="right">49.86951</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">114.22602</td>
<td align="right">56.63839</td>
<td align="right">170.86440</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">147.56470</td>
<td align="right">73.16921</td>
<td align="right">220.73390</td>
</tr>
</tbody>
</table>
<p>The sum of <span class="math inline">\(\chi^{2}\)</span> contributions in our example is 220.7339. To see if this value is staistically significant, we need to calculate the degrees of freedom because the <span class="math inline">\(\chi\)</span> distribution differes across degrees of freedom. Degrees of freedom are calculated accroding to the equation below.</p>
<p><span class="math inline">\(DF = (rows -1) * (columns – 1) = (2-1) * (2-1) = 1 * 1 = 1\)</span></p>
<p>In a last step, we check whether the <span class="math inline">\(\chi^{2}\)</span> value that we have calculated is higher thana critical value (in which case the correlation in our table is significant). Degrees of freedom are relevcvenat here because the critical values is dependent upon the degrees of freedom: the more degrees of freedom, the higher the critical value, i.e. the harder it is to breach ethe level of significance.</p>
<p>Since theer is only 1 degree of freedom in our case, we need to consider only the first column in the table of critical values below.</p>
<table>
<caption>Critical chi values for 1 to 5 degrees of freedom</caption>
<thead>
<tr class="header">
<th align="right">DF</th>
<th align="right">p&lt;.05</th>
<th align="right">p&lt;.01</th>
<th align="right">p&lt;.001</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">3.84</td>
<td align="right">6.64</td>
<td align="right">10.83</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">5.99</td>
<td align="right">9.21</td>
<td align="right">13.82</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">7.82</td>
<td align="right">11.35</td>
<td align="right">16.27</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">9.49</td>
<td align="right">13.28</td>
<td align="right">18.47</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">11.07</td>
<td align="right">15.09</td>
<td align="right">20.52</td>
</tr>
</tbody>
</table>
<p>Since the <span class="math inline">\(\chi^{2}\)</span> value that we have calculated is much higher than the critical value provided for p&lt;.05, we can reject the <span class="math inline">\(H_{0}\)</span> and may now claim that speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>Before we summarize the results, we will calculate the effect size which is a measure for how strong the correleations are.</p>
<div id="effect-sizes-in-chi-square" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Effect Sizes in Chi-Square</h3>
<p>Effect sizes are important because they correlations may be highly significant but the effect between variables can be extremely weak. The effect size is therefore a measure how strong the correlation or the explanatory and predictive power between variables is.</p>
<p>The effect size measure for <span class="math inline">\(\chi^{2}\)</span> tests can be either the <span class="math inline">\(\phi\)</span>-coeffizient (phi-coeffizient) or Cramer’s <span class="math inline">\(\phi\)</span> (Cramer’s phi). The <span class="math inline">\(\phi\)</span>-coeffizient is used when dealing with 2x2 tables while Cramer’s <span class="math inline">\(\phi\)</span> is used when dealing with tables with more than 4 cells. The <span class="math inline">\(\phi\)</span> coeffizient can be calculated by using the equation below (N = overall sample size).</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{\chi^{2}}{N}}\)</span></p>
<p>In our case, this means:</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{220.7339}{1080}} = \sqrt{0.2043832} = 0.4520876\)</span></p>
<p>The <span class="math inline">\(\phi\)</span> coefficient varies between 0 (no effect) and 1 (perfect correlation). Für die Einteilung in schwache, moderate und starke Effekte kann man der Einteilung für <span class="math inline">\(\omega\)</span> (kleines Omega) folgen, sodass man bei Werten von .1 von schwacher, um einen Wert bei 0.3 von moderater und ab .5 von einer starken Effektstärke sprechen kann . Wir haben es in diesem Beispiel also mit einem mittleren Effekt oder Zusammenhang zu tun.</p>
</div>
<div id="chi-square-in-r" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Chi-Square in R</h3>
<p>Befroe we summarize the results, we will see how to perform a chi-square test in <code>R</code>. In addition to what we have done above, we will also visualize the data. To begin with, we will have a look ate the data set (which is the same data we have used above).</p>
<pre class="r"><code>chidata              # inspect data</code></pre>
<pre><code>##        BrE AmE
## kindof 181 177
## sortof 655  67</code></pre>
<p>We will now visualize the data with an association. Bars above the dashed line indicate that a feauture combination occurs more frequently than expected by chance. The width of the bars indicates the frequency of the feature combination.</p>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The fact that the bars are distributed complimentarily (top left red and below bar; top right black above bar; bottom left black above bar; bottom right red below bar) indicates that the use of “sort of” and “kind of” differs across AmE and BrE. We will check whether the mosaicplot confirms this impression.</p>
<pre class="r"><code>mosaicplot(chidata, shade = TRUE, type = &quot;pearson&quot;, main = &quot;&quot;)  # mosaic plot</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The color contarst in the mosaicplot substantiate the impression that the two varieties of English differ significantly. To ascertain whether teh differences are statistically significant, we can now apply the chi-square test.</p>
<pre class="r"><code>chisq.test(chidata, corr = F)  # perform chi square test</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chidata
## X-squared = 220.73, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>The results reported by <code>R</code> are identical to the results we derived by hand and confirm that BrE and AmE differ significantly in their use of “sort of” and “kind of”. In a next setp, we calculate the effect size.</p>
<pre class="r"><code># calculate effect size
sqrt(chisq.test(chidata, corr = F)$statistic / sum(chidata) * (min(dim(chidata))-1))</code></pre>
<pre><code>## X-squared 
## 0.4520877</code></pre>
<p>The phi coefficient of .45 shows that variety of English correlates moderately with the use of “sort of” and “kind of”. We will now summarize the results.</p>
</div>
<div id="summarizing-chi-square-results" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Summarizing Chi-Square Results</h3>
<p>The results of our analysis can be summaried as follows: A <span class="math inline">\(\chi\)</span>^{2}-Test confirms a highly significant correlation of moderate size between the variety of English and the use of the near-synonymous hedges <em>sort of</em> and <em>kind of</em> (<span class="math inline">\(\chi\)</span>^{2} = 220.73, df = 1, p <span class="math inline">\(&lt;\)</span> .001***, <span class="math inline">\(\phi\)</span> = .452).</p>
</div>
<div id="requirements-of-chi-square" class="section level3">
<h3><span class="header-section-number">2.1.4</span> Requirements of Chi-Square</h3>
<p>Chi-square tests depend on certain requirements that, if violated, negativly affect the reliabilty of the results of the test. To provide reliable results, 80 percent of cells in a table to which the chi-square test is applied have to have expected values of 5 or higher and at most 20 percent of expected values can be smaller than 5 (vgl. <span class="citation">[@bortz1990verteilungsfreie]</span> 98). In addition, none of the expected values can be smaller than 1 (vgl. <span class="citation">[@bortz1990verteilungsfreie]</span> 136) because then, the estimation, which relies on the <span class="math inline">\(\chi\)</span>^{2}-distribution, becomes too imprecise to allow meaningful inferences (<span class="citation">[@cochran1954somemethods]</span>).</p>
<p>If these requierments are violated, then the <em>Fisher’s Exact Test</em> is more reliable and offers the additional advantage that these tests can also be applied to data that represent very small sample sizes. When applying the Fisher’s Exact Test, the probabilities for all possibles outcomes are calculated and the summed probability for the observed or more extreme results are determined. If this sum of probabilities exceeds five percent, then the result is deemed statistically significant.</p>
</div>
</div>
<div id="extensions-of-chi-square" class="section level2">
<h2><span class="header-section-number">2.2</span> Extensions of Chi-Square</h2>
<p>In the following, we will have a look at tests and methods that can be used if the requirements for ordinary (Pearson’s) chi-square tests are violated and their use would be inaapropriate</p>
<div id="the-yates-correction" class="section level3">
<h3><span class="header-section-number">2.2.1</span> The Yates-Correction</h3>
<p>If all requirements for ordinary chi-square tests are acceptable and only the sample size is the issue, then applying a so-called <em>Yates-correction</em> may be appropriate. This type of correction is used in cases where the overall sample size lies inbetween 60 and 15 cases (<span class="citation">[@bortz1990verteilungsfreie]</span> 91). The difference between the ordinary chi-square and a Yates-corrected chi-square lies in the fact that the Yates-corrected chi-square is calculated according to the equation below.</p>
<p><span class="math inline">\(\frac{(|observed – expected|-0.5)^{2}}{expected}\)</span></p>
<p>According to this formula, we would get the values shown below rather than the values tabulated above. It is important to note here that this is only a demonstration because a Yates-Correction would actually be inapproprate as our sample size exceeds 60 cases.</p>
<table>
<caption>Corrected chi-square values for sort of and kind of in BrE and AmE</caption>
<thead>
<tr class="header">
<th align="left">Variant</th>
<th align="left">BrE</th>
<th align="left">AmE</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">kind of</td>
<td align="left">32.9927</td>
<td align="left">113.0407</td>
<td align="left">146.0335</td>
</tr>
<tr class="even">
<td align="left">sort of</td>
<td align="left">16.3593</td>
<td align="left">56.0507</td>
<td align="left">72.41</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left">49.352</td>
<td align="left">169.0914</td>
<td align="left">218.4434</td>
</tr>
</tbody>
</table>
<p>If the Yates-correction were applied, then this results in a slightly lower <span class="math inline">\(\chi\)</span>^{2}-value abd thus to more conservative results compared with the traditional test according to Pearsons.</p>
</div>
<div id="chi-square-within-2k-tables" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Chi-Square within 2*k Tables</h3>
<p>Although the chi-sqaure test is widely used, it is often used inappropriately. This is especially the case when chi-square tests are applied to data representing tables with more than two rows and more than two columns. It is important to note that applying the common Pearsons’ chi-square test to subtables of a larger table is inappropriate because, in such cases, a modified variant of Pearsons’ chi-square test is warranted. We will go through two examples that represnt different scenarios where we are dealing with subsamples of larger tables and a modified version of the chi-sqaure test should be used rather than Pearsons’ chi-square.</p>
<p>In this first example, we are dealing with a table consisting of two columns and multiple rows, a so-called 2*k table (two-by-k table). In order to test if a feature combination, that is represented by a row in the 2*k table, is significantly more common compared with other feature combineations, we need to implement the chi-sqaure equation from <span class="citation">[@bortz1990verteilungsfreie]</span>(126-127).</p>
<p>In this example, we want to find out whether soft and hard X-rays differ in their effect on grasshopper larva. The question is whether the larva reach or do not reach a certain life cicle depending on whtehre they are exposed to soft X-rays, hard X-rays, light , or beta rays. The dat for this example is provided below.</p>
<table>
<caption>Data adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">Mitosis not reached</th>
<th align="left">Mitosis reached</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X-ray soft</td>
<td align="left">21</td>
<td align="left">14</td>
<td align="left">35</td>
</tr>
<tr class="even">
<td>X-ray hard</td>
<td align="left">18</td>
<td align="left">13</td>
<td align="left">31</td>
</tr>
<tr class="odd">
<td>Beta-rays</td>
<td align="left">24</td>
<td align="left">12</td>
<td align="left">36</td>
</tr>
<tr class="even">
<td>Light</td>
<td align="left">13</td>
<td align="left">30</td>
<td align="left">43</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">76</td>
<td align="left">69</td>
<td align="left">145</td>
</tr>
</tbody>
</table>
<p>If we would apply an ordinary chi-square test, we would ignore that all data were collected together and using only a subsample would ignore the data set of which the subsample is part of. In other words, te subsampel is not independent from the other data (as it represents a subsetion of the whiole data set). However, for exemplary reasons, we will apply an ordinary chi-square test first and then compare its results to results prvided by the correct version of the chi-square test. Ina first step, we create a table with all the data.</p>
<pre class="r"><code># create tdata
wholetable &lt;- matrix(c(21, 14, 18, 13, 24, 12, 13, 30), byrow = T, nrow = 4)
colnames(wholetable) &lt;- c(&quot;reached&quot;, &quot;notreached&quot;)           # add column names
rownames(wholetable) &lt;- c(&quot;rsoft&quot;, &quot;rhard&quot;, &quot;beta&quot;, &quot;light&quot;) # add row names
wholetable                                                   # inspect data</code></pre>
<pre><code>##       reached notreached
## rsoft      21         14
## rhard      18         13
## beta       24         12
## light      13         30</code></pre>
<p>Now, we extract the subsample from the data.</p>
<pre class="r"><code>subtable &lt;- wholetable[1:2,] # extract subtable
subtable                     # inspect subtable</code></pre>
<pre><code>##       reached notreached
## rsoft      21         14
## rhard      18         13</code></pre>
<p>Next, we apply the ordinary chi-square test to the subsample.</p>
<pre class="r"><code># simple x2-test
chisq.test(subtable, corr = F)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  subtable
## X-squared = 0.025476, df = 1, p-value = 0.8732</code></pre>
<p>Finally, we perform the correct chi-square test.</p>
<pre class="r"><code># load function for correct chi-square
source(&quot;rscripts/x2.2k.r&quot;) 
x2.2k(wholetable, 1, 2)</code></pre>
<pre><code>## $Description
## [1] &quot;rsoft  against  rhard  by  reached  vs  notreached&quot;
## 
## $`Chi-Squared`
## [1] 0.025
## 
## $df
## [1] 1
## 
## $`p-value`
## [1] 0.8744
## 
## $Phi
## [1] 0.013
## 
## $Report
## [1] &quot;Conclusion: the null hypothesis cannot be rejected! Results are not significant!&quot;</code></pre>
<p>Below is a table comparing the results of the two chi-square tests.</p>
<pre class="r"><code>library(knitr)
critval &lt;- matrix(c(&quot;chi-squared&quot;, 0.0255, 0.025, &quot;p-value&quot;, 0.8732, 0.8744), ncol = 3, byrow = T)
# add column names
colnames(critval) &lt;- c(&quot;&quot;, &quot;chi-square&quot; , &quot;chi-square in 2*k-tables&quot;)
kable(critval, caption = &quot;Table adapted from Bortz (1990: 126)&quot;)</code></pre>
<table>
<caption>Table adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">chi-square</th>
<th align="left">chi-square in 2*k-tables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chi-squared</td>
<td align="left">0.0255</td>
<td align="left">0.025</td>
</tr>
<tr class="even">
<td>p-value</td>
<td align="left">0.8732</td>
<td align="left">0.8744</td>
</tr>
</tbody>
</table>
<p>The comparison shows that, in this example, the results of the two tests are very similar but this may not alwyas be the case.</p>
</div>
<div id="chi-square-within-zk-tables" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Chi-Square within z*k Tables</h3>
<p>Eine weitere Anwendung, bei der der <span class="math inline">\(\chi\)</span>^{2}-Test häufig inkorrekter Weise verwendet wird, ist das Testen von Teilen von Tabellen mit mehr als zwei Zeilen und mehr als zwei Spalten, d.h. z*k-Tabellen (z: Zeile, k: Kolumne). Ein Beispiel wird in  besprochen, der auch das -Skript für die korrekte Version des <span class="math inline">\(\chi^{2}\)</span>-Test erstellt hat.</p>
<p>Laden wir zuerst die Daten, die in dem Beispiel von  besprochen werden, in dem es darum geht, ob sich nicht nur Register und EMOTION-Metaphern unterscheiden, sondern auch darum, ob sich gesprochene Konversationen von Fiktion im Gebrach von EMOTION IST LICHT und EMOTION IST EINE NATURKRAFT unterscheiden.</p>
<pre class="r"><code># create table
wholetable &lt;- matrix(c(8, 31, 44, 36, 5, 14, 25, 38, 4, 22, 17, 12, 8, 11, 16, 24), ncol=4)
attr(wholetable, &quot;dimnames&quot;)&lt;-list(Register=c(&quot;acad&quot;, &quot;spoken&quot;, &quot;fiction&quot;, &quot;new&quot;),
Metaphor = c(&quot;Heated fluid&quot;, &quot;Light&quot;, &quot;NatForce&quot;, &quot;Other&quot;))</code></pre>
<p>Es ergibt sich aus diesen Daten Tabelle ().</p>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th align="left">Register</th>
<th align="left">Heated fluid</th>
<th align="left">Light</th>
<th align="left">NatForce</th>
<th align="left">Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">acad</td>
<td align="left">8</td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">spoken</td>
<td align="left">31</td>
<td align="left">14</td>
<td align="left">22</td>
<td align="left">11</td>
</tr>
<tr class="odd">
<td align="left">fiction</td>
<td align="left">44</td>
<td align="left">25</td>
<td align="left">17</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">new</td>
<td align="left">36</td>
<td align="left">38</td>
<td align="left">12</td>
<td align="left">24</td>
</tr>
</tbody>
</table>
<p>Würden wir einen normalen (hier inkorrekten) <span class="math inline">\(\chi\)</span>^{2}-Test verwenden, so würde sich ergeben, dass sich gesprochene Konversationen nicht signifikant von Fiktion im Gebrach von EMOTION IST LICHT und EMOTION IST EINE NATURKRAFT unterscheiden (<span class="math inline">\(\chi^{2}\)</span>=3.3016, df=1, p<span class="math inline">\(=\)</span>.069, <span class="math inline">\(\phi\)</span> = .2057).</p>
<pre class="r"><code># create table
subtable &lt;- matrix(c(14, 25, 22, 17), ncol=2)
chisq.results &lt;- chisq.test(subtable, correct=FALSE) # WRONG!
phi.coefficient = sqrt(chisq.results$statistic / sum(subtable) * (min(dim(subtable))-1))
chisq.results</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  subtable
## X-squared = 3.3016, df = 1, p-value = 0.06921</code></pre>
<pre class="r"><code>phi.coefficient</code></pre>
<pre><code>## X-squared 
## 0.2057378</code></pre>
<p>Die korrekte Analyse berücksichtigt hierbei, dass es sich um eine Untertabelle handelt, die nicht unabhängig von der Gesamttabelle ist. Dies bedeutet, dass die korrekte Analyse die gesamte Anzahl der Fälle, sowie die Gesamtzeilen- und Gesamtspaltensummen zu berücksichtigen sind <span class="citation">[vgl.@bortz1990verteilungsfreie 144-148]</span>.</p>
<p>Um die korrekte Analyse durchführen zu können, muss die Analyse von Funktion von <span class="citation">[@bortz1990verteilungsfreie 144-148]</span> implementiert oder direkt die Funktion von Gries eingelesen und auf die Teiltabelle angewandt werden.</p>
<pre class="r"><code># load function for chi square test for subtables
source(&quot;rscripts/sub.table.r&quot;) 
# apply test
results &lt;- sub.table(wholetable, 2:3, 2:3, out=&quot;short&quot;)
# inspect results
results</code></pre>
<pre><code>## $`Whole table`
##          Metaphor
## Register  Heated fluid Light NatForce Other Sum
##   acad               8     5        4     8  25
##   spoken            31    14       22    11  78
##   fiction           44    25       17    16 102
##   new               36    38       12    24 110
##   Sum              119    82       55    59 315
## 
## $`Sub-table`
##          Metaphor
## Register  Light NatForce Sum
##   spoken     14       22  36
##   fiction    25       17  42
##   Sum        39       39  78
## 
## $`Chi-square tests`
##                                   Chi-square Df    p-value
## Cells of sub-table to whole table  7.2682190  3 0.06382273
## Rows (within sub-table)            0.2526975  1 0.61518204
## Columns (within sub-table)         3.1519956  1 0.07583417
## Contingency (within sub-table)     3.8635259  1 0.04934652</code></pre>
<p>The results show that the difference is, in fact, statistically significant (<span class="math inline">\(\chi^{2}\)</span>=3.864, df=1, p=.049*).</p>
</div>
<div id="chi-square-excercises" class="section level3">
<h3><span class="header-section-number">2.2.4</span> Chi-Square Excercises</h3>
<ol style="list-style-type: decimal">
<li>Imagine you are interested in whether older or younger speakers tend to refer to themselves linguistically. The underlying hypothessi is that - contrary to common belief - older people are more narcicisstic comapred with younger people. Given this research question, perform a chi-square test and summarize the results on the data below.</li>
</ol>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">1SGPN</th>
<th align="left">PN without 1SG</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Young</td>
<td align="left">61</td>
<td align="left">43</td>
<td align="left">104</td>
</tr>
<tr class="even">
<td>Old</td>
<td align="left">42</td>
<td align="left">36</td>
<td align="left">78</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">103</td>
<td align="left">79</td>
<td align="left">182</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>Imagine you are interested in whether young men or young women exhibit a preference for the word <em>whatever</em> because you have made the unsystemtic, anectdotal observation that young men use this word more frequently than young women. Given this research question, perform a chi-square test and summarize the results on the data below.</li>
</ol>
<table>
<caption>Observed frequency with row- and column totals for the use of <em>whatever</em> by male and female speakers.</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">YoungMales</th>
<th align="left">YoungFemales</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>whatever</td>
<td align="left">17</td>
<td align="left">55</td>
<td align="left">71</td>
</tr>
<tr class="even">
<td>other words</td>
<td align="left">345128</td>
<td align="left">916552</td>
<td align="left">1261680</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">345145</td>
<td align="left">916607</td>
<td align="left">1261752</td>
</tr>
</tbody>
</table>
<ol start="3" style="list-style-type: decimal">
<li>Find a partner and discuss the relationship between significance and effect size. Then, go and find another partner and sicuss probelms that may arise when testing the frequency of certain words compared with the overall ferqeuncy of words ina corpus.</li>
</ol>
</div>
</div>
<div id="other-non-parametric-tests" class="section level2">
<h2><span class="header-section-number">2.3</span> Other Non-Parametric Tests</h2>
<p>If the dependend variable is neither nominal nor categorical, but ordinal (that is if the dependent variable represnets an order factor such as ranks), using a chi-square test is not warranted. In such cases it is adviasble to apply tests that are designed to handle ordinal data. In the following, we will therefore briefly touch on bivariate tests that can handle ordinal dependent variables.</p>
<div id="mann-whitney-u-test" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Mann-Whitney U Test</h3>
<p>It is a rather freuent case that numeric depend variables are transformed or converted into ordinal variables because the distribution of residuals do not allow the application of a linear regression. Because we are dealing with ordinal data, the application of a chi-square test is unwarranted and we need to use another test. In such cases, the Mann-Whitney U Test, which may be used even if the groups under investigation represent identical participants that are tested under two conditions, irepresents a viable alternative. If we are dealing with independent groups, i.e. groups that do not consist of the same subjects, and the dependent variable is ordinal, then the Mann-Whitney U Test is implemented as follows.</p>
<pre class="r"><code># y ist aV und numerisch, x ist uV und ein binaerer faktor
#wilcox.test(Ranks ~ Groups)

# y1 ist aV, y2 ist uV und beide sind numerisch
#wilcox.test(y1, y2)</code></pre>
<p>%Hat man es mit abhängigen Gruppen zu tun, muss man das Argument  gleich  setzen (siehe unten).</p>
<pre class="r"><code># dependent 2-group Wilcoxon Signed Rank Test
#wilcox.test(y1,y2,paired=TRUE) # where y1 and y2 are numeric</code></pre>
</div>
<div id="kruskal-wallis-test" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Kruskal Wallis Test</h3>
<p>The Kruskal Wallis Test is a type of Analysis of Variance which can handle ordinal data.</p>
<pre class="r"><code>#y &lt;- c(15, 13, 10, 8, 37, 23, 31, 52, 11, 17)
#x &lt;- c(&quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;)
# Kruskal Wallis Test One Way Anova by Ranks
#kruskal.test(y~x) # where y1 is numeric and x is a factor</code></pre>
<pre class="r"><code># Randomized Block Design - Friedman Test
# friedman.test(y~x|z)
# where y are the data values, x is a grouping factor
# and z is a blocking factor</code></pre>
</div>
<div id="excercises-for-other-non-parametric-tests" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Excercises for Other Non-Parametric Tests</h3>
</div>
</div>
</div>
<div id="simple-linear-regression" class="section level1">
<h1><span class="header-section-number">3</span> Simple Linear Regression</h1>
<p>This chapter focuses on a very widely used statistical method which is called regression. Regressions are used when we try to understand how independent variables correlate with a dependent or outcome variable. So if you want to investigate how certain criteria affect an outcome, then a regression is the way to go. We will have a look at two simple examples to understand what the concepts underlying a regression mean and how a regression works. After that, we will turn to a more compley case and we will implement a multiple linear regression. The <code>R</code>-Code, that we will use, is based on <span class="citation">[@field2012discovering]</span>.</p>
<div id="introduction-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Introduction</h2>
<p>Although the basic logic underlying regressions is identical to the conceptual underpinnings of analysis of variance (ANOVA), a related method, sociolinguistists have traditionally favoured regression analysis in their studes while ANOVAs have been the method of choice in psycholinguistics. The preference for either method is grounded in historical happenstances and the culture of these subdisciplines rather than in methodological reasoning.</p>
<p>A minor difference between regressions and ANOVA lies in the fact that regressions are based on the <span class="math inline">\(t\)</span>-distribution while ANOVAs use the <span class="math inline">\(F\)</span>-distribution (however, the <span class="math inline">\(F\)</span>-value is merely t<sup>2</sup>). Both <span class="math inline">\(t\)</span>- and <span class="math inline">\(F\)</span>-values report on the ratio between explained and unexplained variance.</p>
<p>The idea behind regression analysis is expressed formaly in <a href="#eq:slm">equation</a> and can best be described graphically: Imagine drawing a line through points in a scatterplot (Grafik  left panel).</p>
<p><span class="math inline">\(f_{(x)} = \alpha + \beta_{1}x_{i} + \epsilon\)</span> {#eq:slm}</p>
<p>Regressions aim to find that line which has the minimal summed distance between points and the line (Grafik  center panel). Technically speaking, the aim of a regression is to find the line with the minimal deviance or the line with the minimal sum of residuals (variance) (Grafik  right panel). This means that the sum of the length of the lines between the points and the lines should be minimal. The slope of the line is called <em>coefficient</em> and the point where the line crosses the y-axis is called the <em>intercept</em>.</p>
<pre class="r"><code># Scatterplot with lines from teh regression line to the dots
x &lt;- c(173, 169, 176, 166, 161, 164, 160, 158, 180, 187)
y &lt;- c(80, 68, 72, 75, 70, 65, 62, 60, 85, 92) # plot scatterplot and the regression line
mod1 &lt;- lm(y ~ x)

par(mfrow=c(1, 3)) # two plots in two columns in one window
# ein plot pro fenster
plot(x, y, xlim=c(min(x)-5, max(x)+5), ylim=c(min(y)-10, max(y)+10))
plot(x, y, xlim=c(min(x)-5, max(x)+5), ylim=c(min(y)-10, max(y)+10))
abline(mod1, lwd=2)
plot(x, y, xlim=c(min(x)-5, max(x)+5), ylim=c(min(y)-10, max(y)+10))
abline(mod1, lwd=2)

# calculate residuals and predicted values
res &lt;- signif(residuals(mod1), 5)
pre &lt;- predict(mod1) # plot distances between points and the regression line
segments(x, y, x, pre, col=&quot;red&quot;)
# add labels (res values) to points
library(calibrate)
textxy(x, y, round(res,1), cex=1)</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1, 1)) # restore original graphics parameters</code></pre>
<p>A word about standard errors (SE) is in order here because most commonly used statistics programs will provide SE values when reportigng regression models. The SE is a measure that tells us how much the coefficients were to vary if the same regression were applied to many samples from the same population. A relatively small SE value therefore indicates that the coefficients will ermain very stable if the same regression model is fitted to many different samples with identical parameters. In contrast, a large SE tells you that the model is volatile and not very stable or reliable as the coefficients vary substantially if the model is applied to many samples.</p>
</div>
<div id="example-1-preposition-use-across-real-time" class="section level2">
<h2><span class="header-section-number">3.2</span> Example 1: Preposition Use across Real-Time</h2>
<p>We will now turn to our first example. In this example, we will investiagte whether the frequency of prepositions has changed from Middle English to Late Modern English. The reasoning behind this example is that Old English was highly sythetic compared with Present-Day English which comparatively analytic. In other words, while Old English speakers used case to indicate syntactic relations, speakers of Present-Day English use word order and prepositions to indicate syntactic relationships. This means that the loss of case had to be compensated by different strategies and maybe these strategies continued to develop and incerase in frequency even after the change from synthetic to analytic had been mostly accomplished. And this prolonged change in compensatory strategies is what this example will focus on.</p>
<p>The analysis is based on data extrcted from the <em>Penn Corpora of Historical English</em> (see <a href="http://www.ling.upenn.edu/hist-corpora/" class="uri">http://www.ling.upenn.edu/hist-corpora/</a>), that consistss of 603 texts written between 1125 and 1900. In preparation of this example, all elements that were part-of-speech tagged as prepositions were extracted from the PennCorpora.</p>
<p>Then, the relative frequencies (per 1,000 words) of prepositions per text were calculated. This frequency of prepositions per 1,000 words represents our dependent variable. In a next step, the date when each letter had been written was extracted. The resulting two vectors were combined into a table which thus contained for each text, when it was written (independent variable) and its relative freqeuncy of prepositions (dependent or outcome variable).</p>
<p>A regression analysis will follow the steps described below: Die folgende Ablauf ist typisch für Regressionsanalysen.</p>
<ol style="list-style-type: decimal">
<li>Extraction and processing of the data</li>
<li>Data visualization</li>
<li>Applying the regression analysis to the data</li>
<li>Diagnosing the regression model and checking whether or not basic model assumptions have been violated.</li>
</ol>
<div id="simple-linear-regression-in-r" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Simple Linear Regression in <code>R</code></h3>
<p>In a first step, we prepare our session by cleaning the work space, installing libraries that we need for the analysis, and loading the libraries and fucntions.</p>
<pre class="r"><code># clean workspace
rm(list=ls(all=T))
# installing neccessary or helpful packages/libraries (if you have not sone so previously)
# (remove the # sign to activate the code)
#install.packages(&quot;QuantPsyc&quot;)
#install.packages(&quot;car&quot;)
# initialise packages/libraries
library(QuantPsyc)
library(car)
library(ggplot2)
# function which allows us to plot several plots in one window
source(&quot;rscripts/multiplot_ggplot2.r&quot;)
# function for summarizing simple linear regression models
source(&quot;rscripts/slr.summary.tb.r&quot;) </code></pre>
<p>After perparing our session, we can now load and inspect the data to get a first implression of its properties.</p>
<pre class="r"><code># load data
slrdata &lt;- read.delim(&quot;data/slrdata.txt&quot;, header = TRUE)
# attach data
attach(slrdata)
# unnoetige spalten entfernen
slrdata &lt;- as.data.frame(cbind(datems, pptw))
# spaltennamen hinzufuegen
colnames(slrdata) &lt;- c(&quot;year&quot;, &quot;prep.ptw&quot;)
# entfernen unvollstaendiger datenpunkte
slrdata &lt;- slrdata[!is.na(slrdata$year) == T, ]
# erste zeilen des datensatzes betrachten
head(slrdata)</code></pre>
<pre><code>##   year prep.ptw
## 1 1736   166.01
## 2 1711   139.86
## 3 1808   130.78
## 4 1878   151.29
## 5 1743   145.72
## 6 1807   152.59</code></pre>
<pre class="r"><code># struktur des datensatzes betrachten
str(slrdata)</code></pre>
<pre><code>## &#39;data.frame&#39;:    603 obs. of  2 variables:
##  $ year    : num  1736 1711 1808 1878 1743 ...
##  $ prep.ptw: num  166 140 131 151 146 ...</code></pre>
<pre class="r"><code># eigenschaften des datensatzes betrachten
summary(slrdata)</code></pre>
<pre><code>##       year         prep.ptw     
##  Min.   :1125   Min.   : 63.97  
##  1st Qu.:1545   1st Qu.:115.66  
##  Median :1615   Median :130.78  
##  Mean   :1619   Mean   :129.81  
##  3rd Qu.:1687   3rd Qu.:144.08  
##  Max.   :1913   Max.   :195.86</code></pre>
<p>Inspecting the data is very important because it can happen that a data set may not load completely or that variables which should be numeric have been converted in charater variables. If unchecked, then such hidden data issues could go unnoticed and cause much trouble once you realize that the data you have been working with is different from what you had in mind.</p>
<p>We will now plot the data to get a more thorough impression of the structure of the data.</p>
<pre class="r"><code># visualisieren der daten
ggplot(slrdata, aes(year, prep.ptw)) +
geom_point() +
labs(x = &quot;Year&quot;) +
labs(y = &quot;Prepositions per 1,000 words&quot;) +
geom_smooth()</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code>ggplot(slrdata, aes(year, prep.ptw)) +
geom_point() +
labs(x = &quot;Year&quot;) +
labs(y = &quot;Prepositions per 1,000 words&quot;) +
geom_smooth(method = &quot;lm&quot;) # with linear model smoothing!</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Before beginning with the regression analysis, we will scale the year. We scale by subtracting each values from the mean of year. This can be useful when dealing with numeric variables becasue if we did not scale year, we would get estaimated values for year 0 (a year when English did not even exist yet). If a variable is scaled, the regression provides estimates of the model refer to the mean of that numeric variable. In other words, scaling can eb very helpful, especially with respect to the interpretation of the results that regression models report.</p>
<pre class="r"><code>slrdata$prep.ptw &lt;- slrdata$prep.ptw - mean(slrdata$prep.ptw) # scaling date</code></pre>
<p>Wir beginnen nun mit der Regression, indem wir eine erste Regression rechnen und anschließend deren Ergebnisse und diagnostische Plots betrachten.</p>
<pre class="r"><code># create initial model
prep.lm &lt;- lm(prep.ptw ~ year, data = slrdata)
# inspect results
summary(prep.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prep.ptw ~ year, data = slrdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -66.842 -13.523   1.183  14.086  65.117 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) -27.723706  10.863978  -2.552   0.0110 *
## year          0.017128   0.006691   2.560   0.0107 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.11 on 601 degrees of freedom
## Multiple R-squared:  0.01079,    Adjusted R-squared:  0.00914 
## F-statistic: 6.553 on 1 and 601 DF,  p-value: 0.01071</code></pre>
<pre class="r"><code># plot model: 3 plots per row in one window
par(mfrow = c(1, 3))
plot(resid(prep.lm))
plot(rstandard(prep.lm))
plot(rstudent(prep.lm))</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1)) # restroe default parameters</code></pre>
<p>Die linke Grafik zeigt die Residuen des Modells (d.h. die Unterscheide zwischen den beobachteten und den durch das Modell vorhergesagten Werten). Das Problem bei diesem Plot ist, dass die Residuen nicht standardisiert sind und man sie so nicht mit den Residuen anderer Modelle vergleichen kann. Um diesen Mangel zu beheben standardisiert man die Residuen, indem man die Residuen durch deren Standartabweichung dividiert, und plottet sie gegen die beobachteten Werte (mittlerer Plot). Auf diese Weise erhält man nicht nur standardisierte Residuen, sondern die Werte der Residuen sind nun zu z-Werten geworden und man kann die z-Verteilung nutzen, um problematische Punkte zu finden. Es gibt drei Daumenregeln bezüglich des Findens problematischer Datenpunkte aufgrund von Residuen (<span class="citation">[@field2012discovering]</span> 268-269):</p>
<ol style="list-style-type: decimal">
<li>Punkte mit extremen Werten, d.h. Werten <span class="math inline">\(\ge\)</span> 3 (um genau zu sein, Werten <span class="math inline">\(\ge\)</span> 3.29), sollten aus den Daten entfernt werden.</li>
<li>Falls mehr als 1% der Datenpunkte Werte <span class="math inline">\(\ge\)</span> 2.5 haben (2.58 um genau zu sein), dann sind die Fehler unseres Models zu groß.</li>
<li>Falls mehr als 5% der Datenpunkte Werte <span class="math inline">\(\ge\)</span> 2 haben (1.96 um genau zu sein), dann sind die Fehler unseres Models ebenfalls zu groß.</li>
</ol>
<p>Die rechte Grafik zeigt die <em>studentized Residuen</em>, d.h. die angepassten vorhergesagten Werte jedes Datenpunkts werden durch den Standardfehler der Residuen dividiert. Auf diesem Weg ist es möglich die Student’s t-Verteilung zu nutzen, um unser Model zu diagnostizieren.</p>
<p>Angepasste vorhergesagte Werte sind ebenfalls Residuen, aber einer besonderen Art: Das Model wird ohne einen Datenpunkt gerechnet und dann genutzt um diesen Datenpunkt vorherzusagen. Der Unterschied zwischen dem beobachteten Datenpunkt und dem vorhergesagten Datenpunkt wird dann angepasster vorhergesagter Wert genannt. Zusammenfassend kann gesagt werden, dass studentized Residuen sehr nützlich dahingehend sind, dass Sie einflussreiche Datenpunkte erkennen lassen.</p>
<p>Die Plots zeigen, dass es zwei potentiell problematische Datenpunkte gibt (die Punkte ganz oben und ganz unten). diese zwei Punkte setzten sich deutlich von den anderen Punkten ab und können demnach Ausreißer (outlier) darstellen. Wir werden später testen, ob diese punkte entfernt werden müssen.</p>
<p>Wir werden nun weitere modelldiagnostische Grafiken generieren.</p>
<pre class="r"><code># generiere eine 2x2 matrize diagnostischer grafiken
par(mfrow = c(2, 2))
plot(prep.lm)</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>Die diagnostischen Grafiken sehen sehr gut aus und wir werden im Folgenden erklären warum. Die Grafik im oberen linken Panel ist nützlich, um (a) Oulier zu finden oder (b) die Korrelation zwischen Residuen und vorhergesagten Werten zu bestimmen: Wenn ein Trend in der Linie oder den Punkten sichtbar wird (bspw. ein aufsteigender Trend oder eine Zickzacklinie), dann hätte unser Model ein Problem und wir müssten wahrscheinlich Datenpunkte entfernen.</p>
<p>Die Grafik im oberen rechten Panel zeigt an, ob die Residuen normal verteilt sind (was wünschenswert ist), ober ob die Residuen nicht einer Normalverteilung folgen. Liegen die Punkte auf der Linie, so folgen die Residuen einer Normalverteilung. Wenn die Punkte beispielsweise am oberen und unteren Ende nicht auf der Linie liegen, so zeigt dies, dass das Model kleine und große Werte nicht gut vorhersagt und daher nicht gut auf die Daten angepasst ist.</p>
<p>Die Grafik im unteren linken Panel gibt Aufschluss über Homoskedastizität. Homoskedastizität bedeutet, dass die Varianz der Residuen konstant bleibt und nicht mit dem Wert der unabhängigen Variable korrelieren. In unproblematischen Fällen zeigt die Grafik eine flache Linie. Liegt eine Trend in der Linie vor, so haben wir es mit Heteroskedastizität, also mit einer Korrelation zwischen unabhängigen Variablen und den Residuen, zu tun, die für Regressionen sehr problematisch ist.</p>
<p>Die Grafik im unteren rechten Panel zeigt problematische einflussreiche Datenpunkte, die die Regression überproportional beeinflussen (dies sollte nicht der Fall sein). Falls solche einflussreichen Datenpunkte vorliegen, so sollten diese entweder (a) gewichtet werden (robuste Regression) oder (b) entfernt werden. Die Grafik zeigt die Cookdistanz, welche zeigt, wie sich die Regression verändert, wenn ein Model ohne diesen Datenpunkt gerechnet wird. Die Cookdistanz zeigt also, welchen Einfluss ein Datenpunkt auf die Regression als ganzes hat. Datenpunkte, die eine Cookdistanz <span class="math inline">\(\ge\)</span> 1 haben sind problematisch .</p>
<p>Die sogenannte Leverage ist ebenso ein Maß, das anzeigt, wie stark ein Datenpunkt die Genauigkeit der Regression beeinflusst. Leveragewerte liegen zwischen 0 (kein Einfluss) und 1 (starker Einfluss: suboptimal!). Um zu testen, ob ein spezifischer Datenpunkt einen hohen Leveragewert besitzt, muss man einen Cut-Off-Punkt berechnen, der anzeigt, ob die Leverage zu stark oder noch akzeptabel ist. Folgende zwei Formeln werden hierzu genutzt:</p>
<p><span class="math inline">\(\frac{3(k + 1)}{n}\)</span></p>
<p>oder</p>
<p><span class="math inline">\(\frac{2(k + 1)}{n}\)</span></p>
<p>Wir werden im Kontext der multiplen linearen regression genauer auf Leverage eingehen und nun nur noch eine Überblicktabelle der Ergebnisse der Regression generieren.</p>
<pre class="r"><code># tabulate results
slr.summary(prep.lm)</code></pre>
<pre><code>##                                   Estimate Std. Beta Pearson&#39;s r
## (Intercept)                         -27.72                      
## year                                  0.02    0.1039         0.1
## Model statistics                                                
## Number of cases in model                                        
## Residual standard error on 601 DF                               
## Multiple R-squared                                              
## Adjusted R-squared                                              
## F-statistic (1, 601)                                            
## Model p-value                                                   
##                                   Std. Error t value Pr(&gt;|t|) P-value sig.
## (Intercept)                            10.86   -2.55    0.011     p &lt; .05*
## year                                    0.01    2.56   0.0107     p &lt; .05*
## Model statistics                                                     Value
## Number of cases in model                                               603
## Residual standard error on 601 DF                                    21.11
## Multiple R-squared                                                  0.0108
## Adjusted R-squared                                                  0.0091
## F-statistic (1, 601)                                                  6.55
## Model p-value                                                       0.0107</code></pre>
<p>Typischer weise werden die Ergebnisse von Regressionen in solchen Tabellen wiedergegeben, da diese aller wichtigen Kennzahlen der Modellgüte und die Signifikanz wie auch die Stärke der Effekte beinhalten. Die Tabelle ist hier noch einmal abgebildet.</p>

<p>Zusätzlich sollten die Ergebnisse von einfachen linearen Regressionen schriftlich in etwa wie folgt zusammengefasst werden:\[.2cm]</p>
<p>Eine einfache lineare Regression wurde auf die Daten angepasst. Eine visuelle Begutachtung der modelldiagostischen Grafiken zeigten keine problematischen Datenpunkte (Ausreißer) oder überproportional einflussreiche Datenpunkte an und wiesen auf einen guten Modellfit hin. Das finale lineare Regressionsmodell basiert auf 603 Datenpunkten und korreliert hoch signifikant mit den Daten (<span class="math inline">\(R^{2}\)</span>: 0.0108, F-Statistik (1, 601): 6.553, p-Wert: 0.0107*) und bestätigt eine signifikante positive Korrelation zwischen dem Jahr in dem der Text geschrieben wurde und der relativen Häufigkeit von Präpositionen in den Texten nach (Koeffizient: .02, Std. <span class="math inline">\(\beta\)</span>: 0.1039, SE: 0.01, t-Wert: 2.560, p-Wert: .0107*).</p>
</div>
</div>
<div id="example-2-teaching-styles" class="section level2">
<h2><span class="header-section-number">3.3</span> Example 2: Teaching Styles</h2>
<p>Im vorhergehenden Beispiel haben wir es mit zwei numerischen Variablen zu tun gehabt, während es sich in dem folgenden Beispiel um eine kategoriale und eine numerische abhängige Variable handelt. Die Eigenschaft, dass Regressionen mit sehr verschiedenen Variablenarten umgehen können, macht Regressionen zu einer weit verbreiteten und robusten Analysemethode.</p>
<p>In diesem Beispiel haben wir es mit zwei Gruppen von Schülern zu tun, die zufällig einer Gruppe zugewiesen wurden und unterschiedlichen Lehrmethoden ausgesetzt waren. Beide Gruppen unterziehen sich im Anschluss an die Lehreinheit einem Sprachlerntest mit einer Höchstpunktzahl von 20 Punkten. Die Schüler der ersten Gruppen haben folgende Punktzahlen erreicht:</p>
<ul>
<li>Gruppe A: 15, 12, 11, 18, 15, 15, 9, 19, 14, 13, 11, 12, 18, 15, 16, 14, 16, 17, 15, 17, 13, 14, 13, 15, 17, 19, 17, 18, 16, 14 (mean: 14,93)</li>
</ul>
<p>Die Schüler der zweiten Gruppe haben diese Punktzahlen erreicht.</p>
<ul>
<li>Gruppe B: 11, 16, 14, 18, 6, 8, 9, 14, 12, 12, 10, 15, 12, 9, 13, 16, 17, 12, 8, 7, 15, 5, 14, 13, 13, 12, 11, 13, 11, 7 (mean: 11,77)</li>
</ul>
<p>Unsere Frage ist nun, ob Gruppe A wirklich besser ist oder ob das Ergebnis Zufall ist?</p>
<p>Gehen wir nun dazu über, die Regression in <code>R</code> zu implementieren. Wie im vorherigen Beispiel leeren wir den gegenwärtigen Workspace, installieren und initialisieren/aktivieren notwendige Pakete und laden zusätzliche Funktionen.</p>
<pre class="r"><code># entfernen aller objekte aus dem aktuellen workspace
rm(list=ls(all=T))
# installieren der notwendigen pakete
# (falls nicht schon geschehen)
# (um die befehle zu aktivieren # entfernen)
#install.packages(&quot;QuantPsyc&quot;)
#install.packages(&quot;car&quot;)
# pakete initialisieren
library(QuantPsyc)
library(car)
library(ggplot2)
source(&quot;rscripts/multiplot_ggplot2.r&quot;) # mehrere ggplots in einem fenster
source(&quot;rscripts/slr.summary.tb.r&quot;) # funktion zum erstellen von summary tabellen</code></pre>
<p>Nachdem die notwendigen Spezifikationen durchgeführt wurden, werden wir nun unser Datenset generieren und es anschließend betrachten.</p>
<pre class="r"><code># einladen der daten
g1 &lt;- c(15, 12, 11, 18, 15, 15, 9, 19, 14, 13, 11, 12, 18, 15, 16, 14, 16, 17, 15, 17, 13, 14, 13, 15, 17, 19, 17, 18, 16, 14)
g2 &lt;- c(11, 16, 14, 18, 6, 8, 9, 14, 12, 12, 10, 15, 12, 9, 13, 16, 17, 12, 8, 7, 15, 5, 14, 13, 13, 12, 11, 13, 11, 7)
g &lt;- c(rep(&quot;A&quot;, length(g1)), rep(&quot;B&quot;, length(g2)))
sprtestdata &lt;- data.frame(g, c(g1, g2))
# spaltennamen hinzufuegen
colnames(sprtestdata) &lt;- c(&quot;gruppe&quot;, &quot;punkte&quot;)
# erste zeilen des datensatzes betrachten
head(sprtestdata)</code></pre>
<pre><code>##   gruppe punkte
## 1      A     15
## 2      A     12
## 3      A     11
## 4      A     18
## 5      A     15
## 6      A     15</code></pre>
<pre class="r"><code># struktur des datensatzes betrachten
str(sprtestdata)</code></pre>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  2 variables:
##  $ gruppe: Factor w/ 2 levels &quot;A&quot;,&quot;B&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ punkte: num  15 12 11 18 15 15 9 19 14 13 ...</code></pre>
<pre class="r"><code># eigenschaften des datensatzes betrachten
summary(sprtestdata)</code></pre>
<pre><code>##  gruppe     punkte     
##  A:30   Min.   : 5.00  
##  B:30   1st Qu.:11.75  
##         Median :14.00  
##         Mean   :13.35  
##         3rd Qu.:16.00  
##         Max.   :19.00</code></pre>
<p>Nun stellen wir die Daten grafisch dar. In diesem Fall bietet sich ein Boxplot zur Visualisierung an.</p>
<pre class="r"><code># erstelle boxplot
boxplot(punkte ~ gruppe,
data = sprtestdata, # the data we want to display
main = &quot;&quot;, # you could specify a title here
ylab = &quot;Punkte&quot;, # titel der y-achse
ylim = c(0, 20), # grenzen der y-achse festlegen
xlab = c(&quot;Gruppen&quot;), # titel der x-achse
notch = T, # notches einfuegen
col = c(&quot;lightgreen&quot;, &quot;lightblue&quot;)) # box einfaerben
# text darstellen
text(1:2,
c(4.0, 4.0),
cex = 0.85,
labels = paste(&quot;mean\n&quot;,
c(round(as.vector(by(sprtestdata$punkte, sprtestdata$gruppe, mean))[1], 2),
round(as.vector(by(sprtestdata$punkte, sprtestdata$gruppe, mean))[2], 2),
sep = &quot;&quot;)))
rug(jitter(sprtestdata$punkte),
side=4)
grid()
box()</code></pre>
<div class="figure">
<img src="basicstatz_files/figure-html/boxplot-1.png" alt="Darstellung der Sprachtestdaten" width="672" />
<p class="caption">
Darstellung der Sprachtestdaten
</p>
</div>
<p>Die Daten weisen darauf hin, dass Gruppe A signifikant besser abgeschnitten hat als Gruppe B. Wir werden diesen Eindruck dadurch testen, dass wir im nächsten Schritt das Regressionsmodell und erstellen die modelldiagnostischen Grafiken generieren.</p>
<pre class="r"><code># Simples Lineares Regressionsmodel erstellen
sprtest.lm &lt;- lm(punkte ~ gruppe, data = sprtestdata)
# ergebnisse betrachten
summary(sprtest.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = punkte ~ gruppe, data = sprtestdata)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -6.767 -1.933  0.150  2.067  6.233 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  14.9333     0.5346  27.935  &lt; 2e-16 ***
## gruppeB      -3.1667     0.7560  -4.189 9.67e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.928 on 58 degrees of freedom
## Multiple R-squared:  0.2322, Adjusted R-squared:  0.219 
## F-statistic: 17.55 on 1 and 58 DF,  p-value: 9.669e-05</code></pre>
<pre class="r"><code># graphik parameter setzen: 3 plots in einer reihe
par(mfrow = c(1, 3))
plot(resid(sprtest.lm))
plot(rstandard(sprtest.lm))
plot(rstudent(sprtest.lm))</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1)) # wiederherstellen der originalparameter</code></pre>

<p>Die Grafiken weisen nicht auf Ausreißer oder andere Probleme hin und wir können daher mit weiteren diagnostischen Grafiken fortfahren.</p>
<pre class="r"><code># generiere eine 2x2 matrize diagnostischer grafiken
par(mfrow = c(2, 2))
plot(sprtest.lm)</code></pre>
<p><img src="basicstatz_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>

<p>Auch diese Grafiken weisen auf keine Probleme hin. In diesem Fall können die Daten im nächsten Schritt zusammengefasst werden.</p>
<pre class="r"><code># ergebnisse tabellieren
slr.summary(sprtest.lm)</code></pre>
<pre><code>##                                  Estimate Std. Beta Pearson&#39;s r Std. Error
## (Intercept)                         14.93                             0.53
## gruppeB                             -3.17   -0.4819        0.48       0.76
## Model statistics                                                          
## Number of cases in model                                                  
## Residual standard error on 58 DF                                          
## Multiple R-squared                                                        
## Adjusted R-squared                                                        
## F-statistic (1, 58)                                                       
## Model p-value                                                             
##                                  t value Pr(&gt;|t|) P-value sig.
## (Intercept)                        27.94        0  p &lt; .001***
## gruppeB                            -4.19    1e-04  p &lt; .001***
## Model statistics                                         Value
## Number of cases in model                                    60
## Residual standard error on 58 DF                          2.93
## Multiple R-squared                                      0.2322
## Adjusted R-squared                                       0.219
## F-statistic (1, 58)                                      17.55
## Model p-value                                            1e-04</code></pre>

<p>Die Ergebnisse dieser einfachen linearen Regressionen können wie folgt zusammengefasst werden:\[.2cm]</p>
<p>Eine einfache lineare Regression wurde auf die Daten angepasst. Eine visuelle Begutachtung der modelldiagostischen Grafiken zeigten keine problematischen Datenpunkte (Ausreißer) oder überproportional einflussreiche Datenpunkte an und wiesen auf einen guten Modellfit hin. Das finale lineare Regressionsmodell basiert auf 60 Datenpunkten und korreliert hoch signifikant mit den Daten (<span class="math inline">\(R^{2}\)</span>: 0.2322, <span class="math inline">\(F\)</span>-Statistik (1, 58): 2.93, p-Wert <span class="math inline">\(&lt;\)</span>.001***) und bestätigt, dass Gruppe A signifikant besser bei dem Sprachlerntest abgeschnitten hat als Gruppe B (Koeffizient: -3.17, Std. <span class="math inline">\(\beta\)</span>: -0.4819, SE: 0.48, t-Wert: -4.19, p-Wert <span class="math inline">\(&lt;\)</span>.001***).</p>
</div>
</div>
<div id="references" class="section level1">
<h1><span class="header-section-number">4</span> References</h1>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
