<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Martin Schweinberger" />


<title>The chi square family of tests</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="hypotheses.html">Hypotheses</a>
    </li>
    <li>
      <a href="significance.html">Significance</a>
    </li>
    <li>
      <a href="errors.html">Errors</a>
    </li>
    <li>
      <a href="researchdesigns.html">Research Designs</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics</a>
    </li>
    <li>
      <a href="intror.html">Getting started with R</a>
    </li>
    <li>
      <a href="loading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="page-b.html">Web Crawling</a>
    </li>
    <li>
      <a href="tabulating.html">Tabulating data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic graphs</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (lattice)</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (ggplot2)</a>
    </li>
    <li>
      <a href="page-d.html">Wordclouds</a>
    </li>
    <li>
      <a href="page-d.html">Mapping</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics: Analyzing Data</li>
    <li>
      <a href="descriptives.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="chi.html">Chi-Square test</a>
    </li>
    <li>
      <a href="regression.html">Regression and ANOVA</a>
    </li>
    <li>
      <a href="forests.html">Variable Seclection</a>
    </li>
    <li>
      <a href="cluster.html">Classification</a>
    </li>
    <li>
      <a href="page-c.html">Dimension Reduction</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis/Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Network Analysis</a>
    </li>
    <li>
      <a href="page-c.html">Topic Modeling</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Available Software</a>
    </li>
    <li>
      <a href="antconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="page-c.html">Corpus Linguistics in R</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">The chi square family of tests</h1>
<h4 class="author"><em>Martin Schweinberger</em></h4>
<h4 class="date"><em>2 Dezember 2018</em></h4>

</div>


<p>This tutorial introduces the <span class="math inline">\(\chi^{2}\)</span> family of tests.</p>
<div id="the-chi-square-test-a-simple-example" class="section level1">
<h1><span class="header-section-number">1</span> The chi square test: a simple example</h1>
<p>To explore how <span class="math inline">\(\chi^{2}\)</span> tests work, we will investigate whther speakers of American English (AmE) and speakers of British English (BrE) differ with respect to their preference for the near-synonyms <em>sort of</em> and <em>kind of</em>. As a first step, we formulate the <span class="math inline">\(H_{1}\)</span> and the <span class="math inline">\(H_{0}\)</span>. The Alternativ- or Testhypothesis <span class="math inline">\(H_{1}\)</span> states:</p>
<p><span class="math inline">\(H_{1}\)</span>: Speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>while the Nullhypothesis (<span class="math inline">\(H_{0}\)</span>) states</p>
<p><span class="math inline">\(H_{0}\)</span> Speakers of AmE and BrE do not differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>The <span class="math inline">\(H_{0}\)</span> claims the non-existence of something (which is the more conservative position) and in our example the non-existence of a correlation between variety of English and the use of <em>sort of</em> und <em>kind of</em>.</p>
<p>The question now arises what has to be the case in order to reject the <span class="math inline">\(H_{0}\)</span> in favor of the <span class="math inline">\(H_{1}\)</span>.</p>
<p>To answer this question, we require information about the probability of error, i.e. the probability that the <span class="math inline">\(H_{0}\)</span> does indeed hold for the entire population. Before performing the <span class="math inline">\(\chi^{2}\)</span> test, we follow the convetion that the required significance level is 5 percent. In other words, we will reject the <span class="math inline">\(H_{0}\)</span> if the likelyhood for the <span class="math inline">\(H_{0}\)</span> being true is less than 5 percent given the distribution of the data. In that case, i.e. in case that the likelihood for the <span class="math inline">\(H_{0}\)</span> being true is less than 5 percent, we consider the result of the <span class="math inline">\(\chi^{2}\)</span> test as statistically significant. This means that the observed distribution makes it very unlikey that there is no correlation between the variety of English and the use of <em>sort of</em> and <em>kind of</em>.</p>
<p>Let us now assume that we have performed a search for <em>sort of</em> and <em>kind of</em> in two corpora representing American and British English and that we have obtained the following freqeuncies:</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">177</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">655</td>
<td align="right">67</td>
</tr>
</tbody>
</table>
<p>In a first step, we now have to caluculate the row and column sums of our table.</p>
<p>I had the same question. I have tried all solutions provided above and none of them worked… But I have found a solution that works for me, and hopefully for others too.</p>
<table>
<caption>Observed frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">181</td>
<td align="right">655</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">177</td>
<td align="right">67</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358</td>
<td align="right">722</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>Next, we calculate, the values that would have expected if there was no correlation between variety of English and the use of <em>sort of</em> and <em>kind of</em>. In order to get these “expected” freqeuncies, we apply the equation below to all cells in our table.</p>
<p><span class="math inline">\(\frac{Column total*Row total}{Overall total}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{836*358}{1080} = \frac{299288}{1080} = 277.1185\)</span></p>
<p>For the entire table this means we get the following expected values:</p>
<table>
<caption>Expected frequencies of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">277.11850</td>
<td align="right">558.8815</td>
<td align="right">836</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">80.88148</td>
<td align="right">163.1185</td>
<td align="right">244</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">358.00000</td>
<td align="right">722.0000</td>
<td align="right">1080</td>
</tr>
</tbody>
</table>
<p>In a next step, we calculate the contribution of each cell to the overall <span class="math inline">\(\chi^{2}\)</span> value (<span class="math inline">\(\chi^{2}\)</span> contribution). To get <span class="math inline">\(\chi^{2}\)</span> contribution for each cell, we apply the equation below to each cell.</p>
<p><span class="math inline">\(\frac{(observed – expected)^{2}}{expected}\)</span></p>
<p>In our example this means that for the cell with [+]BrE [+]kindof we get:</p>
<p><span class="math inline">\(\frac{(181 – 277.1185)^{2}}{277.1185} = \frac{-96.1185^{2}}{277.1185} = \frac{9238.766}{277.1185} = 33.33868\)</span></p>
<p>For the entire table this means we get the following <span class="math inline">\(\chi^{2}\)</span> values:</p>
<table>
<caption>Chi values of <em>sort of</em> and <em>kind of</em> in American and British English with row and column totals</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">BrE</th>
<th align="right">AmE</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kindof</td>
<td align="right">33.33869</td>
<td align="right">16.53082</td>
<td align="right">49.86951</td>
</tr>
<tr class="even">
<td>sortof</td>
<td align="right">114.22602</td>
<td align="right">56.63839</td>
<td align="right">170.86440</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="right">147.56470</td>
<td align="right">73.16921</td>
<td align="right">220.73390</td>
</tr>
</tbody>
</table>
<p>The sum of <span class="math inline">\(\chi^{2}\)</span> contributions in our example is 220.7339. To see if this value is staistically significant, we need to calculate the degrees of freedom because the <span class="math inline">\(\chi\)</span> distribution differes across degrees of freedom. Degrees of freedom are calculated accroding to the equation below.</p>
<p><span class="math inline">\(DF = (rows -1) * (columns – 1) = (2-1) * (2-1) = 1 * 1 = 1\)</span></p>
<p>In a last step, we check whether the <span class="math inline">\(\chi^{2}\)</span> value that we have calculated is higher thana critical value (in which case the correlation in our table is significant). Degrees of freedom are relevcvenat here because the critical values is dependent upon the degrees of freedom: the more degrees of freedom, the higher the critical value, i.e. the harder it is to breach ethe level of significance.</p>
<p>Since theer is only 1 degree of freedom in our case, we need to consider only the first column in the table of critical values below.</p>
<table>
<caption>Critical chi values for 1 to 5 degrees of freedom</caption>
<thead>
<tr class="header">
<th align="right">DF</th>
<th align="right">p&lt;.05</th>
<th align="right">p&lt;.01</th>
<th align="right">p&lt;.001</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">3.84</td>
<td align="right">6.64</td>
<td align="right">10.83</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">5.99</td>
<td align="right">9.21</td>
<td align="right">13.82</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">7.82</td>
<td align="right">11.35</td>
<td align="right">16.27</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">9.49</td>
<td align="right">13.28</td>
<td align="right">18.47</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">11.07</td>
<td align="right">15.09</td>
<td align="right">20.52</td>
</tr>
</tbody>
</table>
<p>Since the <span class="math inline">\(\chi^{2}\)</span> value that we have calculated is much higher than the critical value provided for p&lt;.05, we can reject the <span class="math inline">\(H_{0}\)</span> and may now claim that speakers of AmE and BrE differ with respect to their preference for <em>sort of</em> und <em>kind of</em>.</p>
<p>Before we summarize the results, we will calculate the effect size which is a measure for how strong the correleations are.</p>
<div id="effect-size" class="section level2">
<h2><span class="header-section-number">1.1</span> Effect size</h2>
<p>Effect sizes are important because they correlations may be highly significant but the effect between variables can be extremely weak. The effect size is therefore a measure how strong the correlation or the explanatory and predictive power between variables is.</p>
<p>The effect size measure for <span class="math inline">\(\chi^{2}\)</span> tests can be either the <span class="math inline">\(\phi\)</span>-coeffizient (phi-coeffizient) or Cramer’s <span class="math inline">\(\phi\)</span> (Cramer’s phi). The <span class="math inline">\(\phi\)</span>-coeffizient is used when dealing with 2x2 tables while Cramer’s <span class="math inline">\(\phi\)</span> is used when dealing with tables with more than 4 cells. The <span class="math inline">\(\phi\)</span> coeffizient can be calculated by using the equation below (N = overall sample size).</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{\chi^{2}}{N}}\)</span></p>
<p>In our case, this means:</p>
<p><span class="math inline">\(\phi = \sqrt{\frac{220.7339}{1080}} = \sqrt{0.2043832} = 0.4520876\)</span></p>
<p>The <span class="math inline">\(\phi\)</span> coefficient varies between 0 (no effect) and 1 (perfect correlation). Für die Einteilung in schwache, moderate und starke Effekte kann man der Einteilung für <span class="math inline">\(\omega\)</span> (kleines Omega) folgen, sodass man bei Werten von .1 von schwacher, um einen Wert bei 0.3 von moderater und ab .5 von einer starken Effektstärke sprechen kann . Wir haben es in diesem Beispiel also mit einem mittleren Effekt oder Zusammenhang zu tun.</p>
</div>
</div>
<div id="the-chi-square-test-in-r" class="section level1">
<h1><span class="header-section-number">2</span> The chi square test in R</h1>
<p>Bevor wir dazu kommen, wie die Ergebnisse zusammengefasst werden, werden wir im Folgenden den <span class="math inline">\(\chi^{2}\)</span> test in <code>R</code>! rechnen. Zusätzlich zu den Schritten, die wir oben durchlaufen sind, werden wir die Daten graphisch darstellen.</p>
<p>Im ersten Schritt laden wir die Daten ein:</p>
<pre class="r"><code># load data
mydata &lt;- read.table(&quot;http://martinschweinberger.de/docs/data/dt001.txt&quot;, header = F, sep = &quot;\t&quot;, quote = &quot;&quot;, comment.char = &quot;&quot;)
# ad column and row names
colnames(mydata) &lt;- c(&quot;BrE&quot;, &quot;AmE&quot;)
rownames(mydata) &lt;- c(&quot;kindof&quot;, &quot;sortof&quot;)
# inspect data
mydata</code></pre>
<pre><code>##        BrE AmE
## kindof 181 177
## sortof 655  67</code></pre>
<p>We will now visualize the data with an association and a mosaic plot.</p>
<pre class="r"><code># set graphics parameter
par(mfrow=c(1, 2)) # two plots in two columns in one window
assocplot(as.matrix(mydata))
mosaicplot(mydata, shade = TRUE, type = &quot;pearson&quot;, main = &quot;&quot;)</code></pre>
<p><img src="chi_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow=c(1, 1)) # restore default parameter (one plot per window)</code></pre>
<p>Die Farbe des Mosaikplots (rechts) deutet auf einen signifikanten Unterschied hin. Auch der Assoziationsplot (links) deutet dies an indem die Verteilung der Balken in den beiden Panels gespiegelt ist. Im nächsten Schritt werden wir direkt den Test durchführen.</p>
<pre class="r"><code># run chi square test
chisq.results &lt;- chisq.test(mydata, corr = F)
# inspect results
chisq.results</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  mydata
## X-squared = 220.73, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>Wir sehen, dass die Ergebnisse, die <code>R</code> uns berichtet dieselben sind, wie die, die wir vorher ausgerechnet haben. Im nächsten Schritt werden wir die Effektstärke berechnen.</p>
<pre class="r"><code># calculate effect size
phi.coefficient = sqrt(chisq.results$statistic / sum(mydata) * (min(dim(mydata))-1))
# inspect effect size
phi.coefficient</code></pre>
<pre><code>## X-squared 
## 0.4520877</code></pre>
<p>Nach der Visualisierung der Daten, dem Testen und der Berechnung der Effektstärke können wir nun dazu übergehen uns damit zu beschäftigen, wie unsere Ergebnisse zusammengefasst werden sollten.</p>
<div id="summarizing-results" class="section level2">
<h2><span class="header-section-number">2.1</span> Summarizing results</h2>
<p>Man kann das Ergebnis unseres Beispiels wie folgt zusammenfassen: Ein <span class="math inline">\(\chi\)</span>^{2}-Test bestätigt einen hoch signifikanten Zusammenhang mittlerer Stärke zwischen der Varietät des Englischen und der Verwendung der Heckenausdrücke  und  (<span class="math inline">\(\chi\)</span>^{2} = 220.73, df = 1, p <span class="math inline">\(&lt;\)</span> .001***, <span class="math inline">\(\phi\)</span> = .452).</p>
</div>
</div>
<div id="notes-about-the-chi-square-test" class="section level1">
<h1><span class="header-section-number">3</span> Notes about the chi-square test</h1>
<p>Bei <span class="math inline">\(\chi^{2}\)</span>-tests müssen mindestens 80% der Zellen Erwartungswerte <span class="math inline">\(\ge\)</span> 5 sein, höchstens 20% der erwarteten Werte dürfen <span class="math inline">\(&lt;\)</span> 5 sein  und kein Erwartungswert sollte einen Wert <span class="math inline">\(&lt;\)</span> 1 haben , da sonst die Schätzung, die auf der <span class="math inline">\(\chi\)</span>^{2}-Verteilung beruht, zu ungenau wird . Ist diese Bedingung verletzt, so sollte man  rechnen, der zwar sehr viel aufwendiger ist, was die Rechenleistung betrifft, aber dafür auch auf sehr kleine Stichproben angewandt werden kann. Beim Fisher’s Exact Test werden die Wahrscheinlichkeiten für alle möglichen Ausgänge berechnet und dann errechnet, wie hoch die summierte Wahrscheinlichkeit ist, dass das beobachtete oder ein noch extremeres Ergebnis zustande kommen ist. Ist die summierte Wahrscheinlichkeit kleiner als 5%, dann ist Ihr Ergebnis signifikant.</p>
<p>Eine andere Alternative bei kleinen Stichproben bildet die Möglichkeit eine Yates-Korrektur bei dem <span class="math inline">\(\chi\)</span>^{2}-Test durchzuführen, die wir in Sektion  besprechen werden.</p>
</div>
<div id="special-chi-square-tests" class="section level1">
<h1><span class="header-section-number">4</span> Special chi-square tests</h1>
<p>Im Folgenden werden einige Fälle besprochen, bei denen die Anwendung des herkömmlichen (Pearson’s) <span class="math inline">\(\chi\)</span>^{2}-Test inkorrekt oder problematisch wäre.</p>
<div id="the-yates-correction" class="section level2">
<h2><span class="header-section-number">4.1</span> The Yates-Correction</h2>
<p>Die Yates-Korrektur wird in Fällen angewendet, bei denen der Stichprobenumfang relativ gering ist . Der Unterschied zum herkömmlichen Pearson’s) <span class="math inline">\(\chi^{2}\)</span>-Test besteht dabei darin, dass die <span class="math inline">\(\chi\)</span>^{2}-Werte anstatt nach Formel () nach Formel () berechnet werden.</p>
<p><span class="math inline">\(\frac{(|observed – expected|-0.5)^{2}}{expected}\)</span></p>
<p>Damit würde sich für unser Beispiel anstatt Tabelle ({) die folgende Tabelle () führen. Es ist hierbei zu bedenken, dass in unserem Fall keine Yates-Korrektur angebracht wäre, da unsere Stichprobe den Wert von 60 Fällen stark überschreitet.</p>
<table>
<caption>Corrected chi-square values for sort of and kind of in BrE and AmE</caption>
<thead>
<tr class="header">
<th align="left">Variant</th>
<th align="left">BrE</th>
<th align="left">AmE</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">kind of</td>
<td align="left">32.9927</td>
<td align="left">113.0407</td>
<td align="left">146.0335</td>
</tr>
<tr class="even">
<td align="left">sort of</td>
<td align="left">16.3593</td>
<td align="left">56.0507</td>
<td align="left">72.41</td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left">49.352</td>
<td align="left">169.0914</td>
<td align="left">218.4434</td>
</tr>
</tbody>
</table>
<p>Es zeigt sich, dass die Yates-Korrektur zu einem etwas geringerem <span class="math inline">\(\chi\)</span>^{2}-Wert führt und sie somit zu konservativeren Ergebnissen führt, als es nach Pearson der Fall wäre.</p>
</div>
<div id="chi-square-within-2k-tables" class="section level2">
<h2><span class="header-section-number">4.2</span> Chi-square within 2*k tables</h2>
<p>Obwohl der <span class="math inline">\(\chi\)</span>^{2}-Test weit verbreitet ist und insgesamt sehr robust ist, wird er doch häufig falsch verwendet. Dies geschieht insbesondere dann, wenn man den Test auf Tabellen anwendet, die mehr als zwei Spalten oder Zeilen haben. Es ist sehr wichtig festzuhalten, dass man für Untersuchungen, in denen man Teiltabellen auf Signifikanz testen möchte nicht den gewöhnlichen <span class="math inline">\(\chi\)</span>^{2}-Test, sondern abgewandelte Varianten nutzen muss. Im Folgenden sollen zwei Beispiele darstellen, wie man in solchen Fällen vorgehen sollte.</p>
<p>Im ersten Fall handelt es sich um eine Tabelle mit 2 Spalten aber mehreren Zeilen, einer sogenannten 2*k-Tabelle. Um zu testen, ob eine der Ausprägungen in den Zeilen signifikant häufiger ist als eine andere sollte man die Formel, die von  dargelegt wird, implementieren.</p>
<p>In diesem Beispiel geht es darum, ob weiche Röntgenstrahlen sich von harten Röntgenstrahlen im Hinblick auf das Erreichen bzw. Nicht-Erreichen des Mitosestadiums bei Heuschreckenneuroblasten unterscheiden. Die zugrundeliegende Datentabelle sieht wie folgt aus.</p>
<table>
<caption>Data adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">Mitosis not reached</th>
<th align="left">Mitosis reached</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X-ray soft</td>
<td align="left">21</td>
<td align="left">14</td>
<td align="left">35</td>
</tr>
<tr class="even">
<td>X-ray hard</td>
<td align="left">18</td>
<td align="left">13</td>
<td align="left">31</td>
</tr>
<tr class="odd">
<td>Beta-rays</td>
<td align="left">24</td>
<td align="left">12</td>
<td align="left">36</td>
</tr>
<tr class="even">
<td>Light</td>
<td align="left">13</td>
<td align="left">30</td>
<td align="left">43</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">76</td>
<td align="left">69</td>
<td align="left">145</td>
</tr>
</tbody>
</table>
<p>Würde man einen einfachen <span class="math inline">\(\chi\)</span>^{2}-Test rechnen, so würde man unterschlagen, dass die Daten in Zusammenhang mit anderen Daten erhoben wurden und somit nicht unabhängig sind. Wir werden zunächst einen einfachen (falschen) <span class="math inline">\(\chi^{2}\)</span>-Test rechnen, um dann die korrekte Variante zu berechnen, und die Ergebnisse zu vergleichen.</p>
<pre class="r"><code># load function
source(&quot;http://martinschweinberger.de/docs/scripts/x2.2k.r&quot;)
# create table generieren
chitb2 &lt;- matrix(c(21, 14, 18, 13, 24, 12, 13, 30), byrow = T, nrow = 4)
colnames(chitb2) &lt;- c(&quot;erreicht&quot;, &quot;nichterreicht&quot;)
rownames(chitb2) &lt;- c(&quot;rweich&quot;, &quot;rhart&quot;, &quot;beta&quot;, &quot;licht&quot;)
# extract subtable
chitb3 &lt;- matrix(c(21, 14, 18, 13), byrow = T, nrow = 2)
colnames(chitb3) &lt;- c(&quot;erreicht&quot;, &quot;nichterreicht&quot;)
rownames(chitb3) &lt;- c(&quot;rweich&quot;, &quot;rhart&quot;)
# simple x2-test
chisq.test(chitb3, corr = F)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chitb3
## X-squared = 0.025476, df = 1, p-value = 0.8732</code></pre>
<pre class="r"><code>x2.2k(chitb2, 1, 2)</code></pre>
<pre><code>## $Description
## [1] &quot;rweich  against  rhart  by  erreicht  vs  nichterreicht&quot;
## 
## $`Chi-Squared`
## [1] 0.025
## 
## $df
## [1] 1
## 
## $`p-value`
## [1] 0.8744
## 
## $Phi
## [1] 0.013
## 
## $Report
## [1] &quot;Conclusion: the null hypothesis cannot be rejected! Results are not significant!&quot;</code></pre>
<p>Hier die Ergebnisse in tabellarischer Form.</p>
<table>
<caption>Table adapted from Bortz (1990: 126)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">chi-square</th>
<th align="left">chi-square in 2*k-tables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chi-squared</td>
<td align="left">0.0255</td>
<td align="left">0.025</td>
</tr>
<tr class="even">
<td>p-value</td>
<td align="left">0.8732</td>
<td align="left">0.8744</td>
</tr>
</tbody>
</table>
<p>Wie sich zeigt, kommen zwar beide Tests zu den gleichen Ergebnissen, jedoch unterscheiden sich die Resultate minimal. Dies ist nicht immer der Fall, da die Ergebnisse stark variieren können!</p>
</div>
<div id="chi-square-within-zk-tables" class="section level2">
<h2><span class="header-section-number">4.3</span> Chi-square within z*k tables</h2>
<p>Eine weitere Anwendung, bei der der <span class="math inline">\(\chi\)</span>^{2}-Test häufig inkorrekter Weise verwendet wird, ist das Testen von Teilen von Tabellen mit mehr als zwei Zeilen und mehr als zwei Spalten, d.h. z*k-Tabellen (z: Zeile, k: Kolumne). Ein Beispiel wird in  besprochen, der auch das -Skript für die korrekte Version des <span class="math inline">\(\chi^{2}\)</span>-Test erstellt hat.</p>
<p>Laden wir zuerst die Daten, die in dem Beispiel von  besprochen werden, in dem es darum geht, ob sich nicht nur Register und EMOTION-Metaphern unterscheiden, sondern auch darum, ob sich gesprochene Konversationen von Fiktion im Gebrach von EMOTION IST LICHT und EMOTION IST EINE NATURKRAFT unterscheiden.</p>
<pre class="r"><code># create table
x &lt;- matrix(c(8, 31, 44, 36, 5, 14, 25, 38, 4, 22, 17, 12, 8, 11, 16, 24), ncol=4)
attr(x, &quot;dimnames&quot;)&lt;-list(Register=c(&quot;acad&quot;, &quot;spoken&quot;, &quot;fiction&quot;, &quot;new&quot;),
Metaphor = c(&quot;Heated fluid&quot;, &quot;Light&quot;, &quot;NatForce&quot;, &quot;Other&quot;))</code></pre>
<p>Es ergibt sich aus diesen Daten Tabelle ().</p>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th align="left">Register</th>
<th align="left">Heated fluid</th>
<th align="left">Light</th>
<th align="left">NatForce</th>
<th align="left">Other</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">acad</td>
<td align="left">8</td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">spoken</td>
<td align="left">31</td>
<td align="left">14</td>
<td align="left">22</td>
<td align="left">11</td>
</tr>
<tr class="odd">
<td align="left">fiction</td>
<td align="left">44</td>
<td align="left">25</td>
<td align="left">17</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">new</td>
<td align="left">36</td>
<td align="left">38</td>
<td align="left">12</td>
<td align="left">24</td>
</tr>
</tbody>
</table>
<p>Würden wir einen normalen (hier inkorrekten) <span class="math inline">\(\chi\)</span>^{2}-Test verwenden, so würde sich ergeben, dass sich gesprochene Konversationen nicht signifikant von Fiktion im Gebrach von EMOTION IST LICHT und EMOTION IST EINE NATURKRAFT unterscheiden (<span class="math inline">\(\chi^{2}\)</span>=3.3016, df=1, p<span class="math inline">\(=\)</span>.069, <span class="math inline">\(\phi\)</span> = .2057).</p>
<pre class="r"><code># create table
subtable &lt;- matrix(c(14, 25, 22, 17), ncol=2)
chisq.results &lt;- chisq.test(subtable, correct=FALSE) # WRONG!
phi.coefficient = sqrt(chisq.results$statistic / sum(subtable) * (min(dim(subtable))-1))
chisq.results</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  subtable
## X-squared = 3.3016, df = 1, p-value = 0.06921</code></pre>
<pre class="r"><code>phi.coefficient</code></pre>
<pre><code>## X-squared 
## 0.2057378</code></pre>
<p>Die korrekte Analyse berücksichtigt hierbei, dass es sich um eine Untertabelle handelt, die nicht unabhängig von der Gesamttabelle ist. Dies bedeutet, dass die korrekte Analyse die gesamte Anzahl der Fälle, sowie die Gesamtzeilen- und Gesamtspaltensummen zu berücksichtigen sind .</p>
<p>Um die korrekte Analyse durchführen zu können, muss die Analyse von Funktion von  implementiert oder direkt die Funktion von Gries eingelesen und auf die Teiltabelle angewandt werden.</p>
<pre class="r"><code># load function for chi square test for subtables
source(&quot;http://martinschweinberger.de/docs/scripts/sub.table.r&quot;) 
# apply test
results &lt;- sub.table(x, 2:3, 2:3, out=&quot;short&quot;)
# inspect results
results</code></pre>
<pre><code>## $`Whole table`
##          Metaphor
## Register  Heated fluid Light NatForce Other Sum
##   acad               8     5        4     8  25
##   spoken            31    14       22    11  78
##   fiction           44    25       17    16 102
##   new               36    38       12    24 110
##   Sum              119    82       55    59 315
## 
## $`Sub-table`
##          Metaphor
## Register  Light NatForce Sum
##   spoken     14       22  36
##   fiction    25       17  42
##   Sum        39       39  78
## 
## $`Chi-square tests`
##                                   Chi-square Df    p-value
## Cells of sub-table to whole table  7.2682190  3 0.06382273
## Rows (within sub-table)            0.2526975  1 0.61518204
## Columns (within sub-table)         3.1519956  1 0.07583417
## Contingency (within sub-table)     3.8635259  1 0.04934652</code></pre>
<p>The results show that the difference is, in fact, statistically significant (<span class="math inline">\(\chi^{2}\)</span>=3.864, df=1, p=.049*).</p>
</div>
</div>
<div id="excercises" class="section level1">
<h1><span class="header-section-number">5</span> Excercises</h1>
<p>1.Sie sind interessiert daran, ob junge oder alte Sprecher häufiger sprachlich auf sich selbst verweisen, da Sie die Hypothese haben, dass – im Gegensatz zur weitläufig gängigen Ansicht – ältere Menschen eher narzisstisch sind als jüngere Menschen. Sie extrahieren aus einem Korpus folgende Verteilung.</p>
<table>
<caption>Table adapted from Gries (2014: 9)</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">1SGPN</th>
<th align="left">PN without 1SG</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jung</td>
<td align="left">61</td>
<td align="left">43</td>
<td align="left">104</td>
</tr>
<tr class="even">
<td>Alt</td>
<td align="left">42</td>
<td align="left">36</td>
<td align="left">78</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">103</td>
<td align="left">79</td>
<td align="left">182</td>
</tr>
</tbody>
</table>
<p>Rechnen Sie nun einen <span class="math inline">\(\chi^{2}\)</span> test und fassen Sie Ihre Ergebnisse korrekt zusammen.</p>
<ol start="2" style="list-style-type: decimal">
<li>Sie sind nun daran interessiert, ob junge Männer oder junge Frauen häufiger das Wort <em>whatever</em> verwenden, da Sie davon ausgehen, dass entgegen einiger früherer Beobachtungen junge Männer häufiger <em>whatever</em> nutzen als junge Frauen. Sie extrahieren aus einem Korpus folgende Verteilung.</li>
</ol>
<table>
<caption>Observed frequency with row- and column totals for the use of <em>whatever</em> by male and female speakers.</caption>
<thead>
<tr class="header">
<th></th>
<th align="left">YoungMales</th>
<th align="left">YoungFemales</th>
<th align="left">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>whatever</td>
<td align="left">17</td>
<td align="left">55</td>
<td align="left">71</td>
</tr>
<tr class="even">
<td>other words</td>
<td align="left">345128</td>
<td align="left">916552</td>
<td align="left">1261680</td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="left">345145</td>
<td align="left">916607</td>
<td align="left">1261752</td>
</tr>
</tbody>
</table>
<p>Rechnen Sie nun einen <span class="math inline">\(\chi^{2}\)</span> test und fassen Sie Ihre Ergebnisse korrekt zusammen.</p>
<ol start="3" style="list-style-type: decimal">
<li>Suchen Sie sich einen Partner und diskutieren das Verhältnis von Signifikanzwert und Effektstärke. Suchen Sie sich nun einen anderen Partner und sprechen Sie über potentielle Probleme, die entstehen, wenn man die Häufigkeit von Wörtern gegenüber allen anderen Wörtern testet.</li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
