<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Martin Schweinberger" />


<title>Descriptive Statistics</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="hypotheses.html">Hypotheses</a>
    </li>
    <li>
      <a href="significance.html">Significance</a>
    </li>
    <li>
      <a href="errors.html">Errors</a>
    </li>
    <li>
      <a href="researchdesigns.html">Research Designs</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics</a>
    </li>
    <li>
      <a href="intror.html">Getting started with R</a>
    </li>
    <li>
      <a href="loading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="page-b.html">Web Crawling</a>
    </li>
    <li>
      <a href="tabulating.html">Tabulating data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic graphs</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (lattice)</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (ggplot2)</a>
    </li>
    <li>
      <a href="page-d.html">Wordclouds</a>
    </li>
    <li>
      <a href="page-d.html">Mapping</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics: Analyzing Data</li>
    <li>
      <a href="descriptives.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="chi.html">Chi-Square test</a>
    </li>
    <li>
      <a href="regression.html">Regression and ANOVA</a>
    </li>
    <li>
      <a href="forests.html">Variable Seclection</a>
    </li>
    <li>
      <a href="cluster.html">Classification</a>
    </li>
    <li>
      <a href="page-c.html">Dimension Reduction</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis/Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Network Analysis</a>
    </li>
    <li>
      <a href="page-c.html">Topic Modeling</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Available Software</a>
    </li>
    <li>
      <a href="antconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="page-c.html">Corpus Linguistics in R</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Descriptive Statistics</h1>
<h4 class="author"><em>Martin Schweinberger</em></h4>
<h4 class="date"><em>2 Dezember 2018</em></h4>

</div>


<p>Statistics can be divided into two main areas. <em>Descriptive Statistics</em> deals with the description of data and their visualization, while <em>Inference statistics</em> deals with testing assumptions about correlations between variables (&lt;www.slcladal.slcladal.github.io&gt;). The following section focuses on describing data, especially with <em>measures of central tendency</em> and <em>measures of variability</em>.</p>
<div id="measures-of-central-tendency" class="section level1">
<h1><span class="header-section-number">1</span> Measures of central tendency</h1>
<p>In linguistics three measures of central tendency are of particular relevance: the <em>mean</em>, the <em>median</em> and the <em>mode</em>. Which measure is appropriate depends on the type of variables and the data distribution one is dealing with and what is the intended aim of the data summary.</p>
<div id="mean" class="section level2">
<h2><span class="header-section-number">1.1</span> Mean</h2>
<p>The mean is used when the data is numeric and normally distributed. The mean is calculated by applying the formula shown below.</p>
<span class="math display">\[\begin{equation}
\bar{x}=\frac{1}{n} \sum_{i=1}^n x_i = \frac{x_{1}+x_{2}+ \dots + x_{n}}{n}
\label{eq:mittel}
\end{equation}\]</span>
<p>To calculate the mean, sum up all values and divide by the number of valuaes. See the example below for clarification. Consider, we are interested in the mean length of sentences ina short text, then the first thing we could do would be to list the sentences and their length ina table.</p>
<table>
<caption>Sentences of the first paragraph of Herman Melville’s <em>Moby Dick</em> and the number of words in each sentence.</caption>
<thead>
<tr class="header">
<th align="left">Sentences</th>
<th align="right">Words</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Call me Ishmael</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">Some years ago – never mind how long precisely – having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.</td>
<td align="right">40</td>
</tr>
<tr class="odd">
<td align="left">It is a way I have of driving off the spleen, and regulating the circulation.</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people’s hats off–then, I account it high time to get to sea as soon as I can.</td>
<td align="right">87</td>
</tr>
</tbody>
</table>
<p>To calculate the mean, we need to divide the sum of the number of words per sentence (145) by the number of sentences (7) (cf. equation ()).</p>
<span class="math display">\[\begin{equation}
\frac{3+40+15+87}{4} = \frac{145}{4} = 36.25
\label{eq:mittel2}
\end{equation}\]</span>
<p>The mean sentences length in our example is 36.25 words</p>
<p>In <code>R</code>, the mean is calculated as follows.</p>
<pre class="r"><code># create numeric vector
frequencies &lt;- c(3, 40, 15, 87)
# calculate mean
mean(frequencies)</code></pre>
<pre><code>## [1] 36.25</code></pre>
</div>
<div id="median" class="section level2">
<h2><span class="header-section-number">1.2</span> Median</h2>
<p>The median is typically used hwen dealing with ordinal variables, i.e. variables that are ordered but not truely numeric. The median is the central value in a de- or increasing ordering of values in a vector. In other words, 50% of values are above and 50% of values are below the median in a given vector.</p>
<p>If the vector contains an even number of elements, then the two central values are summed up and divided by 2. If the vector contains an uneven number of elements, the median represents the central value.</p>
<span class="math display">\[\begin{equation}
median_{x}=
\begin{cases}
x_{\frac{n+1}{2}} &amp; n\text{ uneven} \\
\frac{1}{2}\bigl(x_{\frac{n}{2}}+x_{\frac{n+1}{2}}\bigr) &amp; n\text{ even}
\end{cases}
\label{eq:median}
\end{equation}\]</span>
<p>Let’s have a look at an example. Consider you are interested in the age stratification of speakers in the private dialogie section of the Irish component of the <em>International Corpus of English</em> (ICE). When tabulating and plotting the age variable you get the following table and graph.</p>
<table>
<caption>Number of speakers across age groups in the private dialogie section of the Irish component of the <em>International Corpus of English</em> (ICE)</caption>
<thead>
<tr class="header">
<th align="left">Age</th>
<th align="right">Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0-10</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">19-25</td>
<td align="right">160</td>
</tr>
<tr class="odd">
<td align="left">26-33</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="left">34-41</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">42-49</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">50+</td>
<td align="right">57</td>
</tr>
</tbody>
</table>
<pre class="r"><code>Age &lt;- c(&quot;0-18&quot;, &quot;19-25&quot;, &quot;26-33&quot;, &quot;34-41&quot;, &quot;42-49&quot;, &quot;50+&quot;)
Counts &lt;- c(9, 160, 70, 15, 9, 57)
df &lt;- data.frame(Age, Counts)
#barplot(df)</code></pre>
<p><img src="descriptives_files/figure-html/unnamed-chunk-5-1.png" width="960" /></p>
<p>The age groups represent an order factor which means that there are catergories with a natural order (here from old to young or vice versa). If we order speakers according to their age from young to old, we geta vector of length 320. If we then take the central value, i.e. the value of the 160<span class="math inline">\(^{th}\)</span> speaker, we get the median age in the private dialogie section of the Irish component of the <em>International Corpus of English</em> (ICE).</p>
<p>In R, the median is calculated like below.</p>
<pre class="r"><code># create a vector consisting out of ranks
ranks &lt;- c(rep(1, 9), rep(2, 160), rep(3, 70), rep(4, 15), rep(5, 9), rep(6, 57))
# calculate  median
median(ranks)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>In our case, the median age is <em>19-25</em> because the 160<span class="math inline">\(^{th}\)</span> speaker belongs to the 2<span class="math inline">\(^{nd}\)</span> age group, i.e. the age group with speakers between 19 and 25 years old.</p>
</div>
<div id="mode" class="section level2">
<h2><span class="header-section-number">1.3</span> Mode</h2>
<p>The mode is typically used when dealing with categorical variables and it reports which level of a factor or a categorical variable is the most frequent. Here is an example to illustrate the mode. Consider you are interested where most speakers in the private dialogie section of the Irish component of the International Corpus of English are currently residing and you get the fowllowing distribution.</p>
<table>
<caption>Number of speakers across couties of current residency in the private dialogie section of the Irish component of the <em>International Corpus of English</em> (ICE)</caption>
<thead>
<tr class="header">
<th align="left">CurrentResidence</th>
<th align="right">Speakers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Belfast</td>
<td align="right">98</td>
</tr>
<tr class="even">
<td align="left">Down</td>
<td align="right">20</td>
</tr>
<tr class="odd">
<td align="left">Dublin (city)</td>
<td align="right">110</td>
</tr>
<tr class="even">
<td align="left">Limerick</td>
<td align="right">13</td>
</tr>
<tr class="odd">
<td align="left">Tipperary</td>
<td align="right">19</td>
</tr>
</tbody>
</table>
<p><img src="descriptives_files/figure-html/unnamed-chunk-7-1.png" width="960" /></p>
<p>The tabulated and visualized data show that the mode is “Dublin (City)”, because the largest group (110 speakers) of speakers in the corpus are speakers from Dublin (City). This means that the “average” speaker in in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE) is from Dublin city.</p>
<p>In  the mode is calculated as shown below:</p>
<pre class="r"><code># create a factor with different levels
CurrentResidence &lt;- c(rep(&quot;Belfast&quot;, 98), rep(&quot;Down&quot;, 20), rep(&quot;Dublin (city)&quot;, 110), rep(&quot;Limerick&quot;, 13), rep(&quot;Tipperary&quot;, 19))
# calculate mode
names(which.max(table(CurrentResidence)))</code></pre>
<pre><code>## [1] &quot;Dublin (city)&quot;</code></pre>
<p>A word of warning is in order here as only the first(!) maximal value is provided by R even if several categories have the same frequency.</p>
</div>
<div id="notes-on-measures-of-central-tendency" class="section level2">
<h2><span class="header-section-number">1.4</span> Notes on measures of central tendency</h2>
<p>Man kann sich nun fragen, warum es drei unterschiedliche Maße der zentralen Tendenz gibt und warum diese notwendig sind. Anhand eines fiktiven Beispiels soll dies erläutert werden. Nehmen wir an, sie untersuchen die Häufigkeit des Gebrauchs von Diskurspartikeln in zwei kleinen Korpora, die dieselben Sprecher enthalten, aber in unterschiedlichen Gesprächssituationen. Sie berechnen für jeden Sprecher die relative Häufigkeit von Diskurspartikeln pro 1,000 Wörtern pro Korpus und berichten anschließend einen Mittelwert von 13.4 für beide Korpora. Es scheint also so zu sein, dass sich die beiden Korpora hinsichtlich des Gebrauchs von Diskurspartikeln nicht unterscheiden. Wenn man allerdings Tabelle () und Grafik () betrachtet, so fällt sofort auf, dass die Angabe des arithmetischen Mittels keine gute Abbildung der Datenstruktur darstellt.</p>
<table>
<caption>Relative frequencies of discourse partciles per speaker in two corpora</caption>
<thead>
<tr class="header">
<th align="left">Corpus</th>
<th align="left">Speaker</th>
<th align="right">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">C1</td>
<td align="left">A</td>
<td align="right">5.2</td>
</tr>
<tr class="even">
<td align="left">C1</td>
<td align="left">B</td>
<td align="right">11.4</td>
</tr>
<tr class="odd">
<td align="left">C1</td>
<td align="left">C</td>
<td align="right">27.1</td>
</tr>
<tr class="even">
<td align="left">C1</td>
<td align="left">D</td>
<td align="right">13.7</td>
</tr>
<tr class="odd">
<td align="left">C1</td>
<td align="left">E</td>
<td align="right">9.6</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">A</td>
<td align="right">0.2</td>
</tr>
<tr class="odd">
<td align="left">C2</td>
<td align="left">B</td>
<td align="right">0.0</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">C</td>
<td align="right">1.1</td>
</tr>
<tr class="odd">
<td align="left">C2</td>
<td align="left">D</td>
<td align="right">93.7</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">E</td>
<td align="right">0.4</td>
</tr>
</tbody>
</table>
<p><img src="descriptives_files/figure-html/unnamed-chunk-9-1.png" width="960" /></p>
<p>Es wird deutlich, dass sich die Diskurspartikeln in Korpus 1 relativ gleichmäßig über die Sprecher verteilen, während vier der fünf Sprecher in Korpus 2 extrem wenige Diskurspartikeln verwenden und nun ein einzelner Sprecher für den hohen Mittelwert verantwortlich ist. In solchen Fällen ist es günstig neben dem arithmetischen Mittel noch den Median anzugeben, da so deutlich wird, dass sich die Verteilungen klar unterscheiden. In anderen Worten: Auch bei numerischen Variablen kann die Berechnung des Medians, als Maß der zentralen Tendenz sinnvoll sein, wenn die Verteilung der Daten einer Normalverteilung sehr unähnlich ist. Man würde dies etwa wie folgt zusammenfassen: Die Verteilung der relativen Häufigkeiten von Diskurspartikeln in Korpus 1 (arithmetisches Mittel: 13.7, Median: 11.4) unterscheiden sich deutlich von der Verteilung der Häufigkeiten in Korpus 2 (arithmetisches Mittel: 13.7, Median: 0.4).</p>
<p>Abschließend ist zu sagen, dass – ähnlich wie bei Variablen – die verschiedenen Maße der zentralen Tendenz zwar aufwärts- aber nicht abwärtskompatibel sind. Dies bedeutet, dass auch bei numerischen Variablen der Modus und Median berechnet werden kann, das arithmetische Mittel darf man jedoch nur mit numerischen Variablen berechnet werden. Wir werden nun auf eine andere Möglichkeit eingehen den Unterschied zwischen Korpus 1 und Korpus 2 zu verdeutlichen: Streuungsmaße.</p>
</div>
</div>
<div id="measures-of-variability" class="section level1">
<h1><span class="header-section-number">2</span> Measures of variability</h1>
<p>Streuungsmaße geben Aufschluss darüber, wie die Datenpunkte verteilt sind, d.h. ob die Werte der Datenpunkte relative homogen sind und wenig voneinander abweichen, oder ob sie sehr heterogen sind und stark voneinander abweichen. Wir werden im Folgenden zwei Streuungsmaße behandeln: die  und die . Auch hier soll zu Beginn ein Beispiel den Nutzen dieser Streuungsmaße aufzeigen. Nehmen wir an, wir haben es mit zwei Städten zu tun, deren Jahresdurchschnittstemperatur identisch ist, die sich allerdings, wie aus Tabelle () Grafik () ersichtlich, dennoch erheblich unterscheiden.</p>
<table>
<caption>Average temperature in two cities by month</caption>
<thead>
<tr class="header">
<th align="left">Month</th>
<th align="right">CityA</th>
<th align="right">CityB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">January</td>
<td align="right">-5.00</td>
<td align="right">7.00</td>
</tr>
<tr class="even">
<td align="left">February</td>
<td align="right">-12.00</td>
<td align="right">7.00</td>
</tr>
<tr class="odd">
<td align="left">March</td>
<td align="right">5.00</td>
<td align="right">8.00</td>
</tr>
<tr class="even">
<td align="left">April</td>
<td align="right">12.00</td>
<td align="right">9.00</td>
</tr>
<tr class="odd">
<td align="left">May</td>
<td align="right">15.00</td>
<td align="right">10.00</td>
</tr>
<tr class="even">
<td align="left">June</td>
<td align="right">18.00</td>
<td align="right">13.00</td>
</tr>
<tr class="odd">
<td align="left">July</td>
<td align="right">22.00</td>
<td align="right">15.00</td>
</tr>
<tr class="even">
<td align="left">August</td>
<td align="right">23.00</td>
<td align="right">15.00</td>
</tr>
<tr class="odd">
<td align="left">September</td>
<td align="right">20.00</td>
<td align="right">13.00</td>
</tr>
<tr class="even">
<td align="left">October</td>
<td align="right">16.00</td>
<td align="right">11.00</td>
</tr>
<tr class="odd">
<td align="left">November</td>
<td align="right">8.00</td>
<td align="right">8.00</td>
</tr>
<tr class="even">
<td align="left">December</td>
<td align="right">1.00</td>
<td align="right">7.00</td>
</tr>
<tr class="odd">
<td align="left">Mean</td>
<td align="right">10.25</td>
<td align="right">10.25</td>
</tr>
</tbody>
</table>
<p><img src="descriptives_files/figure-html/unnamed-chunk-11-1.png" width="960" /></p>
<p>Im Folgenden werden wir nun die verschiedenen Streuungsmaße für die Jahrestemperatur dieser zwei Städte berechnen.</p>
<div id="variance" class="section level2">
<h2><span class="header-section-number">2.1</span> Variance</h2>
<p>Die Varianz berechnet sich nach Formel (), d.h. jeder Wert wird von dem arithmetischen Mittel abgezogen und das Ergebnis wird dann quadriert. Diese quadrierten Werte werden addiert und durch die Größe der Stichprobe minus 1 geteilt.</p>
<p><span class="math inline">\(s = \sigma^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^{2}\)</span></p>
<p>For our example, the equaltion provides a value of 123.6591 for city A and a value of 9.477273 for city B.</p>
<p>In R, the variance is calculated like below:</p>
<pre class="r"><code># create a numeric vector
cityA &lt;- c(-5, -12, 5, 12, 15, 18, 22, 23, 20, 16, 8, 1)
# calculate variance
sd(cityA)^2</code></pre>
<pre><code>## [1] 123.6591</code></pre>
</div>
<div id="standard-deviation" class="section level2">
<h2><span class="header-section-number">2.2</span> Standard deviation</h2>
<p>The standard deviation (abbreviated with capital <span class="math inline">\(sigma\)</span> <span class="math inline">\(\sigma\)</span>) is calculated according to equation () or, alternatively, according to equation () and it is the square root of the squared variance.</p>
<p><span class="math inline">\(\sigma = \sqrt{s} = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}\)</span></p>
<p><span class="math inline">\(\sigma = \sqrt{\frac{ \sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}}\)</span></p>
<p>Für unser Beispiel ergeben sich nach Formel () für Stadt A eine Standardabweichung von 11.12 und für Stadt B eine Standardabweichung von 3.08.</p>
<p>The standard devaition is calculated like below in .</p>
<pre class="r"><code># create a numeric vector
CityA &lt;- c(-5, -12, 5, 12, 15, 18, 22, 23, 20, 16, 8, 1)
# calculate standard deviation
sd(CityA)</code></pre>
<pre><code>## [1] 11.12021</code></pre>
</div>
<div id="measures-of-variability-for-non-normal-data" class="section level2">
<h2><span class="header-section-number">2.3</span> Measures of variability for non-normal data</h2>
<p>Bislang haben wir nicht beachtet, wie die Daten, die wir betrachten normalverteilt sind oder nicht. Im Folgenden werden wir auf Möglichkeiten eingehen nicht normalverteilte Daten zu beschreiben. Im ersten Schritt erstellen wir Beispieldaten und bestimmen anschließend, ob die Daten normalverteilt sind oder nicht. Hierzu nutzen wir den Shapiro-Wilk Test, welcher darüber Auskunft gibt, ob die Zahlenreihe signifikant von der Normalverteilung abweicht oder nicht.</p>
<pre class="r"><code># anmerkungen
k1 &lt;- c(9.2, 11.4, 27.1, 13.7, 9.6)
k2 &lt;- c(0.7, 0.0, 1.1, 68.7, 0.5)
# apply shapiro-wilk test
shapiro.test(k1) # p &lt; .05 = non-normal</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  k1
## W = 0.75258, p-value = 0.03144</code></pre>
<pre class="r"><code>shapiro.test(k2) # p &lt; .05 = non-normal</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  k2
## W = 0.56501, p-value = 0.0002032</code></pre>
<p>The Shapiro-Wilk test shows that the distribution in the data differs significantly froma normal distribution. However, the Shapiro-Wilk test has been found to be too generous with small samples and too harsh when dealing with large samples. For this erason, it is recommended that the test should always be accompanied by additional eye-balling of the data.</p>
</div>
<div id="quantile" class="section level2">
<h2><span class="header-section-number">2.4</span> Quantile</h2>
<p>When dealing with non-normal data, the best option to provide a summary of the distribution is to report the quantiles.</p>
</div>
</div>
<div id="excercises" class="section level1">
<h1><span class="header-section-number">3</span> Excercises</h1>
<ol style="list-style-type: decimal">
<li>Calculate the mean, median, and mode as well as the standrad deviation for the follwoing two vactors.</li>
</ol>
<p>A: 1, 3, 6, 2, 1, 1, 6, 8, 4, 2, 3, 5, 0, 0, 2, 1, 2, 1, 0</p>
<p>B: 3, 2, 5, 1, 1, 4, 0, 0, 2, 3, 0, 3, 0, 5, 4, 5, 3, 3, 4</p>
<p>mean:</p>
<p>median:</p>
<p>mode:</p>
<p>standard deviation:</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Find a partner and discuss which meaure of central tendency is sppropriate when dealing with grades. Then, find another partner and see whether they hve come to teh same conclusion or discuss why if not. Finally, discuss the advantages and disadvantages of calculateing themmean when dealing with grades.</p></li>
<li><p>Where are mean, median, and mode when dealing with normal data?</p></li>
<li><p>Sie erhalten bei drei Untersuchungen mit jeweils zwei Gruppen einmal nahezu identische Steuungen, aber unterschiedliche Mittelwerte, einmal nahezu identische Mittelwerte, aber unterschiedliche Steuungen, und in der letzten Untersuchung sowohl unterschiedliche Mittelwerte und unterschiedliche Streuungen. \ Wie interpretieren Sie diese drei Ergebnisse?</p></li>
<li><p>Suchen Sie sich nun einen Partner und diskutieren Sie zusammen, was es auf der konzeptionellen und nicht auf der statistischen Ebene bedeuten könnte, dass zwei Gruppen unterschiedliche Streuungen aufweisen. (Vorsicht: Dies ist nicht so trivial, wie es auf den ersten Blick wirken könnte!)</p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
