<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="UQ SLC Digital Team" />

<meta name="date" content="2019-07-15" />

<title>Descriptive Statistics</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="introquant.html">Introduction To Quantitative Reasoning</a>
    </li>
    <li>
      <a href="basicquant.html">Basic Concepts In Quantitative Reasoning</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Research Designs</li>
    <li>
      <a href="researchdesigns.html">Overview</a>
    </li>
    <li>
      <a href="corpling.html">Corpus Linguistics</a>
    </li>
    <li>
      <a href="experiments.html">Experimental Designs</a>
    </li>
    <li>
      <a href="ca.html">Conversation Analysis</a>
    </li>
    <li>
      <a href="acoustic.html">Acoustic Analysis</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Data Collection</li>
    <li>
      <a href="introdatacollection.html">Introduction</a>
    </li>
    <li>
      <a href="fieldwork.html">Field Work</a>
    </li>
    <li>
      <a href="interviews.html">Interviews</a>
    </li>
    <li>
      <a href="questionnaires.html">Questionnaires and Surveys</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics: Getting started with R</a>
    </li>
    <li>
      <a href="introloading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="introtables.html">Tabulating data</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="dataprocessingexcel.html">Data Processing with Excel</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic Visualization with R</a>
    </li>
    <li>
      <a href="advancedgraphs.html">Basic Visualization with Excel</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics</li>
    <li>
      <a href="descriptivestatz.html">Descriptive Statistics</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Basic Interential Statistics</li>
    <li>
      <a href="basicstatz.html">Basic Inferential Tests</a>
    </li>
    <li>
      <a href="basicstatzchi.html">The Chi-Square Family</a>
    </li>
    <li>
      <a href="basicstatzregression.html">Simple Linear Regression</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Advanced Interential Statistics</li>
    <li>
      <a href="advancedstatzregressions.html">Regression Analysis</a>
    </li>
    <li>
      <a href="advancedstatztrees.html">Tree-Based Models</a>
    </li>
    <li>
      <a href="groupingstatz.html">Agglomerative Procedures</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis</li>
    <li>
      <a href="textanalysis.html">Introduction</a>
    </li>
    <li>
      <a href="webcrawling.html">Web Crawling</a>
    </li>
    <li>
      <a href="network.html">Network Analysis</a>
    </li>
    <li>
      <a href="topicmodels.html">Topic Modeling</a>
    </li>
    <li>
      <a href="classification.html">Classification</a>
    </li>
    <li>
      <a href="tagging.html">Tagging and Parsing</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Corpus Linguistics</li>
    <li>
      <a href="corplingr.html">Corpus Linguistics in R</a>
    </li>
    <li>
      <a href="corplingantconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="available.html">Available Software</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Descriptive Statistics</h1>
<h4 class="author"><em>UQ SLC Digital Team</em></h4>
<h4 class="date"><em>2019-07-15</em></h4>

</div>


<p><img src="images/uq1.jpg" width="100%" /></p>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>This chapter focuses on how to describe and summarize data. To show why this is necessary, think of the following: you are teaching two different classes in the same school, in the same grade, and at the same level. Both classes take the same exam and, after correcting and grading the exams, someone asks you which class performed better. You could of course say something along the lines of “Well, class A had 5 Bs, 10 Cs, 12 Ds, and 2 Fs while class B had 2 As, 8 Bs, 10 Ds, and 4 Fs” but this answer is not really satisfactory. Descriptive statistics enable you to summarize complex data sets in very few words and using only very basic, and easy to understand, concepts. And this is what we will be dealing with in the following.</p>
<p>Before delving deeper into what descriptive statistics is, it is useful to have a general idea of how it can be contextualized. Thus, on a more general note, we will be dealing only with one particular subbranch of statistics. Statistics in general can be defined as a branch of mathematics that deals with data collection, organization, analysis, interpretation, and presentation. As such, statistics can be subdivided into two main areas. <em>Descriptive statistics</em> deals with the description of data and their visualization, while <em>inferential statistics</em> deals with data analysis and interpretation (typically, this means testing assumptions about correlations between variables (&lt;www.slcladal.slcladal.github.io&gt;). As stated above, here, we will be dealing with the description of data, especially with <em>measures of central tendency</em>, <em>measures of variability</em> and <em>confidence interals</em>.</p>
</div>
<div id="measures-of-centrality" class="section level1">
<h1><span class="header-section-number">2</span> Measures of Centrality</h1>
<p>In linguistics three measures of centrality or measures of central tendency are of particular relevance: the <em>mean</em>, the <em>median</em> and the <em>mode</em>. In addition, there are two more measures of central tendency, the geometric and the harmonic mean which we will only briefly discuss as they are nto that relevant for language research. Which measure is appropriate depends on the type of variable scaling, the distribution of the data, and what is the intended aim of the data summary.</p>
<table>
<caption>Measures of central tendency and their use.</caption>
<thead>
<tr class="header">
<th align="left">Means</th>
<th align="left">Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Arithmetic) mean (average)</td>
<td align="left">Description of normally dsitributed numeric variables (most common measure of central tendency)</td>
</tr>
<tr class="even">
<td align="left">Median (middle value)</td>
<td align="left">Description of non-normal numeric variables or ordinal variables (skewed data or influential outliers)</td>
</tr>
<tr class="odd">
<td align="left">Mode (most frequent value)</td>
<td align="left">Description of nominal and categorical variables</td>
</tr>
<tr class="even">
<td align="left">Geometric mean (average factor)</td>
<td align="left">Description of dynamic processes such as growth rates</td>
</tr>
<tr class="odd">
<td align="left">Harmonic mean (average rate)</td>
<td align="left">Description of dynamic processes such as velocities</td>
</tr>
</tbody>
</table>
<p>In the following we will go over these types of measures of ecntral tendencies, exemplify their use, describe their strengths and weaknesses, and show how to calculate them in <code>R</code>.</p>
<div id="mean" class="section level2">
<h2><span class="header-section-number">2.1</span> Mean</h2>
<p>The mean is used when the data is numeric and normally distributed. The mean is calculated by applying the formula shown below.</p>
<span class="math display">\[\begin{equation}
  \bar{x}=\frac{1}{n} \sum_{i=1}^n x_i = \frac{x_{1}+x_{2}+ \dots + x_{n}}{n}
\end{equation}\]</span>
<p>To calculate the mean, sum up all values and divide by the number of values. See the example below for clarification.</p>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Consider, we are interested in the mean length of sentences ina short text, then the first thing we could do would be to list the sentences and their length ina table.</p>
<table>
<caption>Sentences of the first paragraph of Herman Melville’s <em>Moby Dick</em> and the number of words in each sentence.</caption>
<thead>
<tr class="header">
<th align="left">Sentences</th>
<th align="right">Words</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Call me Ishmael</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">Some years ago – never mind how long precisely – having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.</td>
<td align="right">40</td>
</tr>
<tr class="odd">
<td align="left">It is a way I have of driving off the spleen, and regulating the circulation.</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people’s hats off–then, I account it high time to get to sea as soon as I can.</td>
<td align="right">87</td>
</tr>
</tbody>
</table>
<p>To calculate the mean, we need to divide the sum of the number of words per sentence (145) by the number of sentences (7) (cf. equation ()).</p>
<span class="math display">\[\begin{equation}
\frac{3+40+15+87}{4} = \frac{145}{4} = 36.25
\label{eq:mittel2}
\end{equation}\]</span>
<p>The mean sentences length in our example is 36.25 words</p>
<p>In <code>R</code>, the mean is calculated as follows.</p>
<pre class="r"><code># create numeric vector
frequencies &lt;- c(3, 40, 15, 87)
# calculate mean
mean(frequencies)</code></pre>
<pre><code>## [1] 36.25</code></pre>
</div>
<div id="median" class="section level2">
<h2><span class="header-section-number">2.2</span> Median</h2>
<p>The median is typically used when dealing with ordinal variables, i.e. variables that are ordered but not truly numeric. The median is the central value in a de- or increasing ordering of values in a vector. In other words, 50 percent of values are above and 50 percent of values are below the median in a given vector.</p>
<p>If the vector contains an even number of elements, then the two central values are summed up and divided by 2. If the vector contains an uneven number of elements, the median represents the central value.</p>
<span class="math display">\[\begin{equation}
median_{x}=
\begin{cases}
x_{\frac{n+1}{2}} &amp; n\text{ uneven} \\
\frac{1}{2}\bigl(x_{\frac{n}{2}}+x_{\frac{n+1}{2}}\bigr) &amp; n\text{ even}
\end{cases}
\label{eq:median}
\end{equation}\]</span>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Let’s have a look at an example. Consider you are interested in the age stratification of speakers in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE). When tabulating and plotting the age variable you get the following table and graph.</p>
<table>
<caption>Number of speakers across age groups in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE)</caption>
<thead>
<tr class="header">
<th align="left">Age</th>
<th align="right">Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0-10</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">19-25</td>
<td align="right">160</td>
</tr>
<tr class="odd">
<td align="left">26-33</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="left">34-41</td>
<td align="right">15</td>
</tr>
<tr class="odd">
<td align="left">42-49</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">50+</td>
<td align="right">57</td>
</tr>
</tbody>
</table>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The age groups represent an order factor which means that there are categories with a natural order (here from old to young or vice versa). If we order speakers according to their age from young to old, we get a vector of length 320. If we then take the central value, i.e. the value of the 160^{th} speaker, we get the median age in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE).</p>
<p>In R, the median is calculated like below.</p>
<pre class="r"><code># create a vector consisting out of ranks
ranks &lt;- c(rep(1, 9), rep(2, 160), rep(3, 70), rep(4, 15), rep(5, 9), rep(6, 57))
# calculate median
median(ranks)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>In our case, the median age is <em>19-25</em> because the 160<span class="math inline">\(^{th}\)</span> speaker belongs to the 2<span class="math inline">\(^{nd}\)</span> age group, i.e. the age group with speakers between 19 and 25 years old.</p>
</div>
<div id="mode" class="section level2">
<h2><span class="header-section-number">2.3</span> Mode</h2>
<p>The mode is typically used when dealing with categorical variables and it reports which level of a factor or a categorical variable is the most frequent.</p>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Here is an example to illustrate the mode. Consider you are interested where most speakers in the private dialogue section of the Irish component of the <em>International Corpus of English</em> are currently residing and you get the following distribution.</p>
<table>
<caption>Number of speakers across counties of current residency in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE)</caption>
<thead>
<tr class="header">
<th align="left">CurrentResidence</th>
<th align="right">Speakers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Belfast</td>
<td align="right">98</td>
</tr>
<tr class="even">
<td align="left">Down</td>
<td align="right">20</td>
</tr>
<tr class="odd">
<td align="left">Dublin (city)</td>
<td align="right">110</td>
</tr>
<tr class="even">
<td align="left">Limerick</td>
<td align="right">13</td>
</tr>
<tr class="odd">
<td align="left">Tipperary</td>
<td align="right">19</td>
</tr>
</tbody>
</table>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The tabulated and visualized data show that the mode is <em>“Dublin (City)”</em>, because the largest group (110 speakers) of speakers in the corpus are speakers from the city of Dublin. This means that the “average” speaker in in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE) is from Dublin city.</p>
<p>In ´R´ the mode is calculated as shown below:</p>
<pre class="r"><code># create a factor with the current residence of speakers
CurrentResidence &lt;- c(rep(&quot;Belfast&quot;, 98),         # repeat &quot;Belfast&quot; 98 times
                      rep(&quot;Down&quot;, 20),            # repeat &quot;Down&quot; 20 times
                      rep(&quot;Dublin (city)&quot;, 110),  # repeat &quot;Dublin (city)&quot; 110 times
                      rep(&quot;Limerick&quot;, 13),        # repeat &quot;Limerick&quot; 13 times
                      rep(&quot;Tipperary&quot;, 19))       # repeat &quot;Tipperary&quot; 19 times
# calculate mode
names(which.max(table(CurrentResidence)))         # extract which level occurs most frequently</code></pre>
<pre><code>## [1] &quot;Dublin (city)&quot;</code></pre>
<p>A word of warning is in order here as only the first(!) maximal value is provided by R even if several categories have the same frequency.</p>
</div>
<div id="geometric-mean" class="section level2">
<h2><span class="header-section-number">2.4</span> Geometric mean</h2>
<p>The geometric mean represents a measure of central tendency that is used when dealing with dynamic processes where the later elements are dependent on the previous elements. The geometric mean is calculated according to the eqation below.</p>
<span class="math display">\[\begin{equation}
\bar{x}_{geometric} = \sqrt[n]{x_1 \times x_{i+1} \times \dots \times x_n}
\end{equation}\]</span>
<p>Imagine you have have the option to buy two different stock packages and you have to buy one of them. Which one would you buy?</p>
<table>
<caption>Performance of two stock packages.</caption>
<thead>
<tr class="header">
<th align="left">Year</th>
<th align="left">Package1</th>
<th align="left">Package2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Year 1</td>
<td align="left">+5%</td>
<td align="left">+20%</td>
</tr>
<tr class="even">
<td align="left">Year 2</td>
<td align="left">-5%</td>
<td align="left">-20%</td>
</tr>
<tr class="odd">
<td align="left">Year 3</td>
<td align="left">+5%</td>
<td align="left">+20%</td>
</tr>
<tr class="even">
<td align="left">Year 4</td>
<td align="left">-5%</td>
<td align="left">-20%</td>
</tr>
</tbody>
</table>
<p>Is one package better than the other? Did one package perform better than the other?</p>
<ul>
<li>Package 1:
<ul>
<li>Return: <span class="math inline">\(1.05 \times .95 \times 1.05 \times .95 = .995\)</span> (0.5% loss)</li>
<li>Year-over-year average: <span class="math inline">\(.995^{1/4}\)</span> = ~0.125% loss per year</li>
</ul></li>
<li>Package 2:
<ul>
<li>Return: <span class="math inline">\(1.2 \times .8 \times 1.2 \times .8 = 0.9216\)</span> (7.84% loss)</li>
<li>Year-over-year average: <span class="math inline">\(.9216^{1/4}\)</span> = ~2% loss per year.</li>
</ul></li>
</ul>
<p>Package 2 performs substantially worse because here, the changes in growth depend on the previous growth rates.</p>
</div>
<div id="harmonic-mean" class="section level2">
<h2><span class="header-section-number">2.5</span> Harmonic mean</h2>
<p>The harmonic mean is a measure of central tendency that provides us with the average rate and is used when dealing with dynamic processes that involve velocities and distances. The harmonic mean is calculated according to the eqation below.</p>
<span class="math display">\[\begin{equation}
\bar{x}_{harmonic} = 
\frac{n}{\frac{1}{x_i} + \frac{1}{x_{i+1}} + \frac{1}{x_{i+\dots}} + \frac{1}{x_n}}
\end{equation}\]</span>
<p>Let’s use an example to see what the harmonic mean describes. Imagine you assign group projects to students and you are interested in the average time it takes them to finalize the projects. The cruial thing is that the end state is the same: the finished project.</p>
<p>Let us say there are two groups, group A and group B. It takes group A 30 hours and group B 60 hours to finish their project. What is the average rate at which these two groups have finihed their projects. If we used the aritmetic mean, we would say it takes them on average 45 hours to finish their projects but this is not appropriate in the present case.</p>
<span class="math display">\[\begin{equation}
\bar{x}_{harmonic} = 
\frac{2}{\frac{1}{30} + \frac{1}{60}} = \frac{2}{\frac{2}{60} + \frac{1}{60}} = \frac{2}{\frac{3}{60}} = \frac{2}{1} \times \frac{60}{3} = \frac{120}{3} = 40
\end{equation}\]</span>
<p>The harmonic mean is used when two rates contribute to the same workload (for instance when we download a file). Each installment is in a relay race and contributes the same amount to the issue. For example, we make a round trip to work and back. The way to work is 60 kilometers. On the way to work, we can only travel at 30 kph while we can go 60 kph on the way back. The distance is the same. Half of the results (distance traveled) comes from the first rate (30 kilometers per hour) and the other half from the second rate (60 kilometers per hour). The result is that is takes us 3 hours to get to work and back.</p>
<p>The reason why using the arithmetic eman is inappropriate in such cases is the following: The idea behind the arithmetic mean is that we calculate a single value that can replace all values in a given distribution and the sum of the te mean values is identical to the sum of the observed values. So the average is a single element that replaces each element. In our example, we have to drive at 40 kilometers per hour (instead of 30) to work and 40 kilometers per hour (instead of 60) to get back from work in the same amount of time. If we went with 45 kilometers pe hour, then the result would not be 3 hours but 2 hours and 40 minutes so that the result would not be the same.</p>
</div>
<div id="notes-on-measures-of-centrality" class="section level2">
<h2><span class="header-section-number">2.6</span> Notes on Measures of Centrality</h2>
<p>You may ask yourself why there are three different types to calculate the central tendency of a why this is necessary. To answer these questions, consider the following example: Imagine you are interested whether the use of discourse particles differs across two corpora that represent the speech of the same five speakers but different registers. In a first step, you calculate the relative frequency of discourse particle use and both corpora have a mean of 13.4 particles per 1,000 words. Given the mean, the two corpora do not seem to differ. However, when tabulating and plotting the use of particles by speaker across these two corpora we will become immediately aware of the fact that the mean is not the appropriate measure of the central tendency in situations where distributions are very dissimilar.</p>
<table>
<caption>Relative frequencies of discourse partciles per speaker in two corpora</caption>
<thead>
<tr class="header">
<th align="left">Corpus</th>
<th align="left">Speaker</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">C1</td>
<td align="left">A</td>
<td align="right">5.2</td>
</tr>
<tr class="even">
<td align="left">C1</td>
<td align="left">B</td>
<td align="right">11.4</td>
</tr>
<tr class="odd">
<td align="left">C1</td>
<td align="left">C</td>
<td align="right">27.1</td>
</tr>
<tr class="even">
<td align="left">C1</td>
<td align="left">D</td>
<td align="right">13.7</td>
</tr>
<tr class="odd">
<td align="left">C1</td>
<td align="left">E</td>
<td align="right">9.6</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">A</td>
<td align="right">0.2</td>
</tr>
<tr class="odd">
<td align="left">C2</td>
<td align="left">B</td>
<td align="right">0.0</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">C</td>
<td align="right">1.1</td>
</tr>
<tr class="odd">
<td align="left">C2</td>
<td align="left">D</td>
<td align="right">93.7</td>
</tr>
<tr class="even">
<td align="left">C2</td>
<td align="left">E</td>
<td align="right">0.4</td>
</tr>
</tbody>
</table>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The Figure above shows that the use of discourse particles is distributed rather evenly across speakers in Corpus 1 while 4 out of 5 speakers use almost no discourse particles in Corpus 2 - only speaker D makes extensive use of discourse particles in corpus 2. The high usage frequency of discourse particles by speaker D in corpus 2 causes the mean of corpus 2 to be identical to the mean reported for corpus 1 although the distribution of usage rates differs drastically. This means that reporting the median in addition to the mean can be useful even for numeric variables if the distribution of values is very dissimilar.</p>
<p>To exemplify, we will summarize the distribution of discourse particles in the two corpora: The use of discourse particles in corpus 1 (mean = 13.7, median = 11.4) is substantially different from the use of discourse particles in corpus 2 (mean = 13.7, median = 0.4).</p>
<p>It is important to keep in mind that - similar to variable scales - measures of central tendency are downward compatible but not upward compatible. This means that one may report the median and mode for numeric variables but the mean may only be used for numeric variables but not for categorical variables. In the following, we have a look at another, more common, way to describe the differences in the distribution between the two corpora, namely, measures of variability.</p>
</div>
</div>
<div id="measures-of-variability" class="section level1">
<h1><span class="header-section-number">3</span> Measures of Variability</h1>
<p>Measures of variability provide information about the distribution of values such as whether the data are distributed evenly and do not differ substantially or whether the data are rather heterogeneous and are distributed very unevenly. In the following, we will have a look at the <em>variance</em> and the <em>standard deviation</em>.</p>
<p>As before, we will use a practical example to see the usefulness of applying measures of variability. Imagine you dealing with two cities that have the same mean temperature per year. However, the variability of temperatures varies differs dramatically between the two cities.</p>
<table>
<caption>Average temperature in two cities by month</caption>
<thead>
<tr class="header">
<th align="left">Month</th>
<th align="right">CityA</th>
<th align="right">CityB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">January</td>
<td align="right">-5.00</td>
<td align="right">7.00</td>
</tr>
<tr class="even">
<td align="left">February</td>
<td align="right">-12.00</td>
<td align="right">7.00</td>
</tr>
<tr class="odd">
<td align="left">March</td>
<td align="right">5.00</td>
<td align="right">8.00</td>
</tr>
<tr class="even">
<td align="left">April</td>
<td align="right">12.00</td>
<td align="right">9.00</td>
</tr>
<tr class="odd">
<td align="left">May</td>
<td align="right">15.00</td>
<td align="right">10.00</td>
</tr>
<tr class="even">
<td align="left">June</td>
<td align="right">18.00</td>
<td align="right">13.00</td>
</tr>
<tr class="odd">
<td align="left">July</td>
<td align="right">22.00</td>
<td align="right">15.00</td>
</tr>
<tr class="even">
<td align="left">August</td>
<td align="right">23.00</td>
<td align="right">15.00</td>
</tr>
<tr class="odd">
<td align="left">September</td>
<td align="right">20.00</td>
<td align="right">13.00</td>
</tr>
<tr class="even">
<td align="left">October</td>
<td align="right">16.00</td>
<td align="right">11.00</td>
</tr>
<tr class="odd">
<td align="left">November</td>
<td align="right">8.00</td>
<td align="right">8.00</td>
</tr>
<tr class="even">
<td align="left">December</td>
<td align="right">1.00</td>
<td align="right">7.00</td>
</tr>
<tr class="odd">
<td align="left">Mean</td>
<td align="right">10.25</td>
<td align="right">10.25</td>
</tr>
</tbody>
</table>
<p><img src="descriptivestatz_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>In the following, we will discuss and calculate different measures of variability for the two cities.</p>
<div id="range" class="section level2">
<h2><span class="header-section-number">3.1</span> Range</h2>
<p>The range is the simples measure of variability and reports the lowest and highest value of a distribution. That is, the range provides minimum and maximum of a vector to show the span of values within a distribution.</p>
<p>In <code>R</code>, the range is extracted as shown below.</p>
<pre class="r"><code># create a numeric vector
cityA &lt;- c(-5, -12, 5, 12, 15, 18, 22, 23, 20, 16, 8, 1)
min(cityA); max(cityA) # extract range</code></pre>
<pre><code>## [1] -12</code></pre>
<pre><code>## [1] 23</code></pre>
<p>The lowest temperature value for city A is -12 degrees Celsius and the highest value is 23 degrees Celsius. The range thus spans from -12 to 23.</p>
</div>
<div id="interquartile-range-iqr" class="section level2">
<h2><span class="header-section-number">3.2</span> Interquartile range (IQR)</h2>
<p>The interquartile range (IQR) informs about how values are distributed and it denotes the range that encompasses 50 perecnt of data points. This means that the IQR spnas from the first quantile that encompasses 25 percent of the data to the third quartile that encompasses 75 percent of the data.</p>
<p>The easiest way to extract the IQR in <code>R</code> is to apply the <code>summary</code> function to a vector as shown below.</p>
<pre class="r"><code>summary(cityA) # extract IQR</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -12.00    4.00   13.50   10.25   18.50   23.00</code></pre>
<p>The <code>summary</code> function reports that 25 percent od the data fall within -12 and 4 degrees Celsius. The second IQR ranges between 4 and 13.5 degrees Celsius (the median), the third IQR range between 13.5 and 18.5 degrees Celsius, while the fourth IQR ranges between 18.5 and the highest value in the data (23 degrees Celsius). The IQR represent identical width only if the data is distributed normally. Therefore, when dealing with non-normal data, the best option to provide a summary of the distribution is to report the IQRs</p>
</div>
<div id="variance" class="section level2">
<h2><span class="header-section-number">3.3</span> Variance</h2>
<p>The variance is calculated according to formula XXX (). To calculate the variance, each value is subtracted from the mean and the result is squared. The squared values are then added and the resulting sum is divided by the number of values minus 1.</p>
<p><span class="math inline">\(s = \sigma^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^{2}\)</span></p>
<p>For our example, the variance of temperatures for city A is 123.6591 and 9.477273 for city B.</p>
<p>In <code>R</code>, the variance is calculated as shown below:</p>
<pre class="r"><code>sd(cityA)^2</code></pre>
<pre><code>## [1] 123.6591</code></pre>
</div>
<div id="standard-deviation" class="section level2">
<h2><span class="header-section-number">3.4</span> Standard deviation</h2>
<p>The standard deviation (abbreviated with capital <span class="math inline">\(sigma\)</span> <span class="math inline">\(\sigma\)</span>) is calculated according to equation () or, alternatively, according to equation () and it is the square root of the squared variance.</p>
<p><span class="math inline">\(\sigma = \sqrt{s} = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}\)</span></p>
<p><span class="math inline">\(\sigma = \sqrt{\frac{ \sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}}\)</span></p>
<p>For our example, the equation () provides a standard deviation of 11.12 for city A and a standard deviation of 3.08 for city B.</p>
<p>In <code>R</code>, the standard deviation is calculated as shown below.</p>
<pre class="r"><code>sd(CityA) # calculate standard deviation</code></pre>
<pre><code>## [1] 10.64679</code></pre>
<p>The standard deviation of temperature values of city A is 11.12.</p>
<blockquote>
<p>Exercises</p>
<p>Calculate the mean, median, and mode as well as the standard deviation for the following two vectors (A: 1, 3, 6, 2, 1, 1, 6, 8, 4, 2, 3, 5, 0, 0, 2, 1, 2, 1, 0; B: 3, 2, 5, 1, 1, 4, 0, 0, 2, 3, 0, 3, 0, 5, 4, 5, 3, 3, 4).</p>
<p>Find a partner and discuss which measure of central tendency is appropriate when dealing with grades. Then, find another partner and see whether they have come to the same conclusion or discuss why if not. Finally, discuss the advantages and disadvantages of calculating the mean when dealing with grades.</p>
<p>Where are mean, median, and mode when dealing with normal data?</p>
<p>You are investigating differences between boys and girls and their respective use of discourse particles in three different locations. In the first location, you find that the variance in discourse particle use is almost identical for boys and girls but the means differ substantially. In the second location, they have almost identical means but drastically different variances, and in the third location you find that the means and variances differ substantially. How do you interpret the findings for the three locations?</p>
<p>Go and find a partner. Please discuss what it means - on a conceptual level rather than on a statistical/mathematical level - that two groups have different ranges for a certain feature (be careful, this is not as trivial as it may seem!).</p>
</blockquote>
</div>
<div id="standard-error" class="section level2">
<h2><span class="header-section-number">3.5</span> Standard Error</h2>
<p>The standard error is a measure of variability in the sense that it reports the average distance from some parameters (most often from the mean). It is calculated as the standard deviation of the residuals of the parameter in question. To exemplify the standard error, we will extract and tabulate the most frequent 20 words in the Irish component of the <em>International Corpus of English</em> (ICE Ireland 1.2.2)</p>
<table>
<caption>20 most frequent words in the sample corpus of ICE Ireland.</caption>
<thead>
<tr class="header">
<th align="left">WordType</th>
<th align="left">POS</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">i</td>
<td align="left">PPR</td>
<td align="right">1063</td>
</tr>
<tr class="even">
<td align="left">the</td>
<td align="left">ART</td>
<td align="right">1015</td>
</tr>
<tr class="odd">
<td align="left">you</td>
<td align="left">PPR</td>
<td align="right">953</td>
</tr>
<tr class="even">
<td align="left">and</td>
<td align="left">CON</td>
<td align="right">907</td>
</tr>
<tr class="odd">
<td align="left">’s</td>
<td align="left">OTH</td>
<td align="right">643</td>
</tr>
<tr class="even">
<td align="left">it</td>
<td align="left">PPR</td>
<td align="right">632</td>
</tr>
<tr class="odd">
<td align="left">to</td>
<td align="left">OTH</td>
<td align="right">610</td>
</tr>
<tr class="even">
<td align="left">a</td>
<td align="left">ART</td>
<td align="right">580</td>
</tr>
<tr class="odd">
<td align="left">was</td>
<td align="left">V</td>
<td align="right">521</td>
</tr>
<tr class="even">
<td align="left">that</td>
<td align="left">DPR</td>
<td align="right">515</td>
</tr>
<tr class="odd">
<td align="left">of</td>
<td align="left">PRP</td>
<td align="right">430</td>
</tr>
<tr class="even">
<td align="left">in</td>
<td align="left">PRP</td>
<td align="right">421</td>
</tr>
<tr class="odd">
<td align="left">he</td>
<td align="left">PPR</td>
<td align="right">373</td>
</tr>
<tr class="even">
<td align="left">know</td>
<td align="left">V</td>
<td align="right">328</td>
</tr>
<tr class="odd">
<td align="left">like</td>
<td align="left">V</td>
<td align="right">289</td>
</tr>
<tr class="even">
<td align="left">they</td>
<td align="left">PPR</td>
<td align="right">267</td>
</tr>
<tr class="odd">
<td align="left">she</td>
<td align="left">PPR</td>
<td align="right">253</td>
</tr>
<tr class="even">
<td align="left">but</td>
<td align="left">CON</td>
<td align="right">222</td>
</tr>
<tr class="odd">
<td align="left">there</td>
<td align="left">DPR</td>
<td align="right">214</td>
</tr>
<tr class="even">
<td align="left">on</td>
<td align="left">ART</td>
<td align="right">195</td>
</tr>
</tbody>
</table>
<p>The standard error of the mean is calculated using the equation below.</p>
<span class="math display">\[\begin{equation}
\sigma~{\bar{x}}~ =\frac{\sigma}{\sqrt{n}} 
\end{equation}\]</span>
<p>The standard error can be calculated manually (see below) by implementing the equation from above.</p>
<pre class="r"><code>sd(wordstb$Frequency, na.rm=TRUE) /  
   sqrt(length(wordstb$Frequency[!is.na(wordstb$Frequency)]))  </code></pre>
<pre><code>## [1] 62.18777</code></pre>
<p>An easier way to extract standard errors is to use the <code>describe</code> function from the <code>psych</code> package (see below)</p>
<pre class="r"><code>#install.packages(&quot;psych&quot;)   # install psych library (remove # to activate)
library(psych)               # activate psych library
describe(wordstb$Frequency,  # vector to be described
               type=2)       # determine of skew and kurtosis</code></pre>
<pre><code>##    vars  n   mean     sd median trimmed    mad min  max range skew
## X1    1 20 521.55 278.11  472.5   496.5 262.42 195 1063   868 0.73
##    kurtosis    se
## X1    -0.58 62.19</code></pre>
</div>
</div>
<div id="confidence-intervals" class="section level1">
<h1><span class="header-section-number">4</span> Confidence Intervals</h1>
<p>Confidence intervals provide an estimation of in-between which values the reported value would lie in the population with a confidence of 95 percent. There are several ways to extract that information and to exemplify how to extract confidence intervals for values, we will look at the frequency of the 20 most frequent words in a sample of the Irish component of the <em>International Corpus of English</em> (ICE Ireland 1.2.2). Below you see a table showing the data we will be working with here.</p>
<div id="confidence-intervals-for-simple-vectors" class="section level2">
<h2><span class="header-section-number">4.1</span> Confidence Intervals for Simple Vectors</h2>
<table>
<caption>20 most frequent words in the sample corpus of ICE Ireland.</caption>
<thead>
<tr class="header">
<th align="left">WordType</th>
<th align="left">POS</th>
<th align="right">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">i</td>
<td align="left">PPR</td>
<td align="right">1063</td>
</tr>
<tr class="even">
<td align="left">the</td>
<td align="left">ART</td>
<td align="right">1015</td>
</tr>
<tr class="odd">
<td align="left">you</td>
<td align="left">PPR</td>
<td align="right">953</td>
</tr>
<tr class="even">
<td align="left">and</td>
<td align="left">CON</td>
<td align="right">907</td>
</tr>
<tr class="odd">
<td align="left">’s</td>
<td align="left">OTH</td>
<td align="right">643</td>
</tr>
<tr class="even">
<td align="left">it</td>
<td align="left">PPR</td>
<td align="right">632</td>
</tr>
<tr class="odd">
<td align="left">to</td>
<td align="left">OTH</td>
<td align="right">610</td>
</tr>
<tr class="even">
<td align="left">a</td>
<td align="left">ART</td>
<td align="right">580</td>
</tr>
<tr class="odd">
<td align="left">was</td>
<td align="left">V</td>
<td align="right">521</td>
</tr>
<tr class="even">
<td align="left">that</td>
<td align="left">DPR</td>
<td align="right">515</td>
</tr>
<tr class="odd">
<td align="left">of</td>
<td align="left">PRP</td>
<td align="right">430</td>
</tr>
<tr class="even">
<td align="left">in</td>
<td align="left">PRP</td>
<td align="right">421</td>
</tr>
<tr class="odd">
<td align="left">he</td>
<td align="left">PPR</td>
<td align="right">373</td>
</tr>
<tr class="even">
<td align="left">know</td>
<td align="left">V</td>
<td align="right">328</td>
</tr>
<tr class="odd">
<td align="left">like</td>
<td align="left">V</td>
<td align="right">289</td>
</tr>
<tr class="even">
<td align="left">they</td>
<td align="left">PPR</td>
<td align="right">267</td>
</tr>
<tr class="odd">
<td align="left">she</td>
<td align="left">PPR</td>
<td align="right">253</td>
</tr>
<tr class="even">
<td align="left">but</td>
<td align="left">CON</td>
<td align="right">222</td>
</tr>
<tr class="odd">
<td align="left">there</td>
<td align="left">DPR</td>
<td align="right">214</td>
</tr>
<tr class="even">
<td align="left">on</td>
<td align="left">ART</td>
<td align="right">195</td>
</tr>
</tbody>
</table>
<p>One easy method for extracting confidence intervals is to apply the <code>t.test</code> function.</p>
<pre class="r"><code>t.test(wordstb$Frequency, conf.level=0.95)  # extract mean and confidence intervals</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  wordstb$Frequency
## t = 8.3867, df = 19, p-value = 8.255e-08
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  391.3895 651.7105
## sample estimates:
## mean of x 
##    521.55</code></pre>
<p>The <code>t.test</code> functionprovides the mean frequency of the 20 most freqeunt words in the corpus (521.55) and the 95 percent confidence band: With 95 percent confidence, the mean frequency of the top twenty word types across corpora of the same size and similar register will have a mean between 391.4 and 651.7 words.</p>
<p>Another way to extract the mean and its confidence intervals is by using the <code>CI</code> function from the <code>Rmisc</code> package.</p>
<pre class="r"><code>#install.packages(&quot;Rmisc&quot;) # install Rmisc library (remove # to activate)
library(Rmisc)            # activate Rmisc library
CI(wordstb$Frequency, ci=0.95)   # extract mean and confidence intervals</code></pre>
<pre><code>##    upper     mean    lower 
## 651.7105 521.5500 391.3895</code></pre>
<p>The next way to extract the mean and its confidence intervals we will exemplify here is by using the <code>MeanCI</code> function from the <code>DescTools</code> package.</p>
<pre class="r"><code>#install.packages(&quot;DescTools&quot;) # install Rmisc library (remove # to activate)
library(DescTools)            # activate Rmisc library
MeanCI(wordstb$Frequency, conf.level=0.95)   # extract mean and confidence intervals</code></pre>
<pre><code>##     mean   lwr.ci   upr.ci 
## 521.5500 391.3895 651.7105</code></pre>
<p>The last way to calculate the mean and its confidence intervals is by bootstrapping or resampling the data and calculating confidence intervals based on the distribution of the resamples data. This is also done via the <code>MeanCI</code> function from the <code>DescTools</code> package.</p>
<pre class="r"><code>#install.packages(&quot;DescTools&quot;) # install Rmisc library (remove # to activate)
library(DescTools)            # activate Rmisc library
MeanCI(wordstb$Frequency, method=&quot;boot&quot;, type=&quot;norm&quot;, R=1000)</code></pre>
<pre><code>##     mean   lwr.ci   upr.ci 
## 521.5500 404.6651 642.5534</code></pre>
<p>Because this is a data-driven approach, the results will vary, depending on the characteristsics of the resampled data. To illustrate, comapre the values provided above to the values generated below.</p>
<pre class="r"><code>#install.packages(&quot;DescTools&quot;) # install Rmisc library (remove # to activate)
library(DescTools)            # activate Rmisc library
MeanCI(wordstb$Frequency, method=&quot;boot&quot;, type=&quot;norm&quot;, R=1000)</code></pre>
<pre><code>##     mean   lwr.ci   upr.ci 
## 521.5500 403.8183 642.8145</code></pre>
</div>
<div id="confidence-intervals-for-grouped-data" class="section level2">
<h2><span class="header-section-number">4.2</span> Confidence Intervals for Grouped Data</h2>
<p>To extract the confidence intervals for grouped data, we can sue the <code>summarySE</code> function from the <code>Rmisc</code> package.</p>
<pre class="r"><code>#install.packages(&quot;Rmisc&quot;) # install Rmisc library (remove # to activate)
library(Rmisc)                    # activate Rmisc library
summarySE(data=wordstb,           # apply summarySE function to data
          measurevar=&quot;Frequency&quot;, # define variable representing ferquencies
          groupvars=&quot;POS&quot;,        # define grouping variabel
          conf.interval = 0.95)   # extract standard deviation, standard error, and confidence intervals</code></pre>
<pre><code>##   POS N Frequency         sd        se         ci
## 1 ART 3  596.6667 410.253986 236.86025 1019.12740
## 2 CON 2  564.5000 484.368145 342.50000 4351.87512
## 3 DPR 2  364.5000 212.839141 150.50000 1912.28381
## 4 OTH 2  626.5000  23.334524  16.50000  209.65238
## 5 PPR 6  590.1667 352.774385 144.01954  370.21401
## 6 PRP 2  425.5000   6.363961   4.50000   57.17792
## 7   V 3  379.3333 124.226943  71.72246  308.59683</code></pre>
<p>Confidence intervals for mean by bootstrap with boot package</p>
<pre class="r"><code>#install.packages(&quot;boot&quot;) # install boot library (remove # to activate)
library(boot)                    # activate boot library
BootFunction = function(x, index) {                        # function to extract values
                  return(c(mean(x[index]),
                           var(x[index]) / length(index)))
                    }
Bootstrapped = boot(data=wordstb$Frequency,                # apply function to data
            statistic=BootFunction,
            R=1000)
mean(Bootstrapped$t[,1])                                   # extract values</code></pre>
<pre><code>## [1] 522.1811</code></pre>
<pre class="r"><code>boot.ci(Bootstrapped, conf=0.95)                           # alternative to extract values</code></pre>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = Bootstrapped, conf = 0.95)
## 
## Intervals : 
## Level      Normal              Basic             Studentized     
## 95%   (396.9, 644.9 )   (389.3, 635.0 )   (392.3, 676.9 )  
## 
## Level     Percentile            BCa          
## 95%   (408.1, 653.8 )   (416.8, 671.9 )  
## Calculations and Intervals on Original Scale</code></pre>
<p>The advantage of using bootstrapping method lies in teh fact that the data is (frequently) not distributed normally which is not an isseu for the bootstrapping and it will thus provide more reliable results as it does not rely on distributional assumptions about the data.</p>
</div>
<div id="confidence-intervals-for-nominal-data" class="section level2">
<h2><span class="header-section-number">4.3</span> Confidence Intervals for Nominal Data</h2>
<p>We now turn to confidence intervals for nominal data. When dealing with nominal data, confidence intervals can be determined with the <code>binom.test</code> function in the in-built <code>stats</code> package. Alternative methods are available via the <code>BinomCI</code> and <code>MultinomCI</code> functions from the <code>DescTools</code> package. More advanced techniques for confidence intervals on nominal data are available via the <code>PropCIs</code> package.</p>
<pre class="r"><code>binom.test(2, 20, 0.5,              # binom.test(x, n, p = 0.5, ...)
           alternative=&quot;two.sided&quot;, # define sidedness
           conf.level=0.95)         # define confidence level</code></pre>
<pre><code>## 
##  Exact binomial test
## 
## data:  2 and 20
## number of successes = 2, number of trials = 20, p-value =
## 0.0004025
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.01234853 0.31698271
## sample estimates:
## probability of success 
##                    0.1</code></pre>
<pre class="r"><code>Input =(&quot;
 Paw
 right
 left
 right
 right
 right
 right
 left
 right
 right
 right  
&quot;)

Gus = read.table(textConnection(Input),header=TRUE)

Successes = sum(Gus$ Paw == &quot;left&quot;)      # Note the == operator
Failures  = sum(Gus$ Paw == &quot;right&quot;)

Total = Successes + Failures

Expected = 0.5

binom.test(Successes, Total, Expected,
           alternative=&quot;two.sided&quot;,
           conf.level=0.95)</code></pre>
<pre><code>## 
##  Exact binomial test
## 
## data:  Successes and Total
## number of successes = 2, number of trials = 10, p-value = 0.1094
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.02521073 0.55609546
## sample estimates:
## probability of success 
##                    0.2</code></pre>
<pre class="r"><code>#install.packages(&quot;DescTools&quot;)        # install DescTools library (remove # to activate)
library(DescTools)                    # activate DescTools library
BinomCI(2, 20,                        # apply BinomCI function
        conf.level = 0.95,            # define ci
        method = &quot;modified wilson&quot;)   # define method for ci extraction</code></pre>
<pre><code>##      est     lwr.ci    upr.ci
## [1,] 0.1 0.01776808 0.3010336</code></pre>
<p>Other methods: “wilson”, “wald”, “agresti-coull”, “jeffreys”, “modified wilson”, “modified jeffreys”, “clopper-pearson”, “arcsine”, “logit”, “witting”.</p>
</div>
<div id="confidence-intervals-for-multinomial-data" class="section level2">
<h2><span class="header-section-number">4.4</span> Confidence Intervals for Multinomial Data</h2>
<pre class="r"><code>#install.packages(&quot;DescTools&quot;)        # install DescTools library (remove # to activate)
library(DescTools)                    # activate DescTools library
observed = c(35,74,22,69)             # define multinominal vector
MultinomCI(observed,                  # apply MultinomCI function
           conf.level=0.95,           # define ci
           method=&quot;goodman&quot;)          # define method for ci extraction</code></pre>
<pre><code>##        est     lwr.ci    upr.ci
## [1,] 0.175 0.11253215 0.2619106
## [2,] 0.370 0.28113643 0.4686407
## [3,] 0.110 0.06224338 0.1870880
## [4,] 0.345 0.25846198 0.4431954</code></pre>
</div>
</div>
<div id="references" class="section level1">
<h1><span class="header-section-number">5</span> References</h1>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
