<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
<link rel="icon" 
      type="image/x-icon" 
      href="favicon.ico" />


<meta name="author" content="Martin Schweinberger" />

<meta name="date" content="2022-01-25" />

<title>Descriptive Statistics with R</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<link href="site_libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>


<!-- added by SKC for LADAL Style -->
<link rel="stylesheet" href="styles.css">
</head>

<body>


<div class="container-fluid main-container">





<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  
  <!-- Added by SKC - LADAL image and thicker top with   -->
  <div class="container-fluid navbar-top" >
    <a href="index.html"> <!-- Make entire top row and text clickable home link  -->
        <div class="row">
            <div class="navbar-brand col-md-12">
              <img src="ladal_icon_cas_tran_white_trimed.png" class="navbar-icon" alt="LADAL"/>
              <span class="navbar-title-note navbar-collapse collapse" >Language Technology and Data Analysis Laboratory</span>
            </div>
        </div>
    </a>
  </div>
  
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- SKC removed  navbar brand -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">HOME</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    ABOUT LADAL
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="people.html">People | Collabs</a>
    </li>
    <li>
      <a href="news.html">News</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    EVENTS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="opening.html">Opening Webinar Series</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R BASICS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Introduction to R</li>
    <li>
      <a href="intror.html">Getting started</a>
    </li>
    <li>
      <a href="string.html">String Processing</a>
    </li>
    <li>
      <a href="regex.html">Regular Expressions</a>
    </li>
    <li>
      <a href="table.html">Handling tables in R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    DATA SCIENCE BASICS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Introduction to Data Science</li>
    <li>
      <a href="comp.html">Working with Computers</a>
    </li>
    <li>
      <a href="repro.html">Data Management and Reproducibility</a>
    </li>
    <li>
      <a href="introquant.html">Introduction to Quantitative Reasoning</a>
    </li>
    <li>
      <a href="basicquant.html">Basic Concepts in Quantitative Research</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    TUTORIALS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Visualization</li>
    <li>
      <a href="introviz.html">Introduction to Data Viz</a>
    </li>
    <li>
      <a href="dviz.html">Data Visualization with R</a>
    </li>
    <li>
      <a href="maps.html">Displaying Geo-Spatial Data</a>
    </li>
    <li>
      <a href="motion.html">Interactive Charts</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Statistics</li>
    <li>
      <a href="dstats.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="basicstatz.html">Basic Inferential Statistics</a>
    </li>
    <li>
      <a href="regression.html">Regression Analysis</a>
    </li>
    <li>
      <a href="tree.html">Tree-Based Models</a>
    </li>
    <li>
      <a href="clust.html">Cluster and Correspondence Analysis</a>
    </li>
    <li>
      <a href="lexsim.html">Introduction to Lexical Similarity</a>
    </li>
    <li>
      <a href="svm.html">Semantic Vector Space Models</a>
    </li>
    <li>
      <a href="pwr.html">Power Analysis</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Text Analytics</li>
    <li>
      <a href="textanalysis.html">Text Analysis and Distant Reading</a>
    </li>
    <li>
      <a href="kwics.html">Concordancing (keywords-in-context)</a>
    </li>
    <li>
      <a href="net.html">Network Analysis</a>
    </li>
    <li>
      <a href="coll.html">Co-occurrence and Collocation Analysis</a>
    </li>
    <li>
      <a href="topicmodels.html">Topic Modeling</a>
    </li>
    <li>
      <a href="sentiment.html">Sentiment Analysis</a>
    </li>
    <li>
      <a href="tagging.html">Tagging and Parsing</a>
    </li>
    <li>
      <a href="txtsum.html">Automated Text Summarization</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    FOCUS STUDIES
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="corplingr.html">Corpus Linguistics with R</a>
    </li>
    <li>
      <a href="llr.html">Analyzing Learner Language using R</a>
    </li>
    <li>
      <a href="lex.html">Lexicography and Dictionaries with R</a>
    </li>
    <li>
      <a href="surveys.html">Questionnaires and Surveys with R</a>
    </li>
    <li>
      <a href="vc.html">Phonetics: Creating Vowel Charts with Praat and R</a>
    </li>
    <li>
      <a href="litsty.html">Computational Literary Stylistics with R</a>
    </li>
    <li>
      <a href="phylo.html">Phylogenetics for linguistic typology</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Useful How-To Tutorials</li>
    <li>
      <a href="pdf2txt.html">Converting PDFs to txt</a>
    </li>
    <li>
      <a href="webcrawling.html">Web Crawling using R</a>
    </li>
    <li>
      <a href="gutenberg.html">Downloading Texts from Project Gutenberg</a>
    </li>
    <li>
      <a href="rename.html">Renaming files with R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    RESOURCES
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="links.html">Links</a>
    </li>
    <li>
      <a href="services.html">Services | Contact</a>
    </li>
    <li>
      <a href="base.html">Tutorial stylesheet</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Descriptive Statistics with R</h1>
<h4 class="author">Martin Schweinberger</h4>
<h4 class="date">2022-01-25</h4>

</div>



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-130562131-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-130562131-1');
</script>

<p><img src="https://slcladal.github.io/images/uq1.jpg" width="100%" /></p>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>This tutorial focuses on how to describe and summarize data <span class="citation">(see e.g. Bickel and Lehmann <a href="#ref-bickel2012descriptive" role="doc-biblioref">2012</a>; Thompson <a href="#ref-thompson2009descriptive" role="doc-biblioref">2009</a>)</span>. This tutorial is aimed at beginners and intermediate users of R with the aim of showcasing how to summarize data using R. The aim is not to provide a fully-fledged analysis but rather to show and exemplify selected useful methods for summarizing data.</p>
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
The entire R Notebook for the tutorial can be downloaded <a href="https://slcladal.github.io/dstats.Rmd"><strong>here</strong></a>. If you want to render the R Notebook on your machine, i.e. knitting the document to html or a pdf, you need to make sure that you have R and RStudio installed and you also need to download the <a href="https://slcladal.github.io/bibliography.bib"><strong>bibliography file</strong></a> and store it in the same folder where you store the Rmd file. <br><br> <strong><a href="https://colab.research.google.com/drive/1TWDbp1_ceFOXFoHUkPoUU1EUa-Hva0u0?usp=sharing">Here</a></strong> is a <strong>link to an interactive version of this tutorial on Google Colab</strong>. The interactive tutorial is based on a Jupyter notebook of this tutorial. This interactive Jupyter notebook allows you to execute code yourself and - if you copy the Jupyter notebook - you can also change and edit the notebook, e.g. you can change code and upload your own data.<br>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<p><br></p>
<p>To show why data summaries are useful, think of the following: you are teaching two different classes in the same school, in the same grade, and at the same level. Both classes take the same exam and, after correcting and grading the exams, someone asks you which class performed better. You could of course say something along the lines of <em>Well, class A had 5 Bs, 10 Cs, 12 Ds, and 2 Fs while class B had 2 As, 8 Bs, 10 Ds, and 4 Fs</em> but this answer is not really satisfying. Descriptive statistics enable you to summarize complex data sets in very few words and using only very basic, and easy to understand, concepts. And this is what we will be dealing with in the following.</p>
<p>Before delving deeper into what descriptive statistics is, it is useful to have a general idea of how it can be contextualized. Thus, on a more general note, we will be dealing only with one particular subbranch of statistics. Statistics in general can be defined as a branch of mathematics that deals with data collection, organization, analysis, interpretation, and presentation. As such, statistics can be subdivided into two main areas. <em>Descriptive statistics</em> deals with the description of data and their visualization, while <em>inferential statistics</em> deals with data analysis and interpretation. Typically, this means testing assumptions about correlations between variables (see for example <a href="https://slcladal.github.io/basicstatzregression.html">here</a>). As stated above, here, we will be dealing with the description of data, especially with <em>measures of central tendency</em>, <em>measures of variability</em> and <em>confidence intervals</em>.</p>
<p><strong>Preparation and session set up</strong></p>
<p>This tutorial is based on R. If you have not installed R or are new to it, you will find an introduction to and more information how to use R <a href="https://slcladal.github.io/intror.html">here</a>. For this tutorials, we need to install certain <em>packages</em> from an R <em>library</em> so that the scripts shown below are executed without errors. Before turning to the code below, please install the packages by running the code below this paragraph. If you have already installed the packages mentioned below, then you can skip ahead and ignore this section. To install the necessary packages, simply run the following code - it may take some time (between 1 and 5 minutes to install all of the libraries so you do not need to worry if it takes some time).</p>
<pre class="r klippy"><code># install packages
install.packages(&quot;tidyverse&quot;)
install.packages(&quot;boot&quot;)
install.packages(&quot;DescTools&quot;)
install.packages(&quot;tidyverse&quot;)
install.packages(&quot;psych&quot;)
install.packages(&quot;Rmisc&quot;)
install.packages(&quot;ggpubr&quot;)
install.packages(&quot;flextable&quot;)
# install klippy for copy-to-clipboard button in code chunks
remotes::install_github(&quot;rlesur/klippy&quot;)</code></pre>
<p>Now that we have installed the packages, we activate them as shown below.</p>
<pre class="r klippy"><code># set options
options(stringsAsFactors = F)          # no automatic data transformation
options(&quot;scipen&quot; = 100, &quot;digits&quot; = 12) # suppress math annotation
# activate packages
library(boot)
library(DescTools)
library(tidyverse)
library(flextable)
library(psych)
library(Rmisc)
library(ggpubr)
# activate klippy for copy-to-clipboard button
klippy::klippy()</code></pre>
<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>Once you have installed R and RStudio and initiated the session by executing the code shown above, you are good to go.</p>
</div>
<div id="measures-of-centrality" class="section level1">
<h1><span class="header-section-number">2</span> Measures of Centrality</h1>
<p>In linguistics three measures of centrality or measures of central tendency are of particular relevance: the <em>mean</em>, the <em>median</em> and the <em>mode</em> <span class="citation">(Gaddis and Gaddis <a href="#ref-gaddis1990introduction" role="doc-biblioref">1990</a>)</span>. In addition, there are two more measures of central tendency, the geometric and the harmonic mean which we will only briefly discuss as they are not that relevant for language research. What measure is appropriate depends on the type of variable scaling, the distribution of the data, and what is the intended aim of the data summary.</p>
<template id="3e392a23-2c9b-4e69-9178-572b9a830970"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2e26d456{table-layout:auto;width:95%;}.cl-2e1e2900{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2e1e2901{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2e1e4ff2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2e1e76e4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76e5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76e6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76e7{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76e8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76e9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76ea{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e1e76eb{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2e26d456'>
<caption class="Table Caption">
<p>Measures of central tendency and their use.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76ea"><p class="cl-2e1e4ff2"><span class="cl-2e1e2900">Means</span></p></td><td class="cl-2e1e76eb"><p class="cl-2e1e4ff2"><span class="cl-2e1e2900">Use</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76e4"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">(Arithmetic) mean (average)</span></p></td><td class="cl-2e1e76e5"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Description of normally distributed numeric variables (most common measure of central tendency)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76e7"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Median (middle value)</span></p></td><td class="cl-2e1e76e6"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Description of non-normal numeric variables or ordinal variables (skewed data or influential outliers)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76e4"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Mode (most frequent value)</span></p></td><td class="cl-2e1e76e5"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Description of nominal and categorical variables</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76e7"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Geometric mean (average factor)</span></p></td><td class="cl-2e1e76e6"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Description of dynamic processes such as growth rates</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e1e76e8"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Harmonic mean (average rate)</span></p></td><td class="cl-2e1e76e9"><p class="cl-2e1e4ff2"><span class="cl-2e1e2901">Description of dynamic processes such as velocities</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="9b92d18c-c45f-4f8e-a839-e81263cc3f8d"></div>
<script>
var dest = document.getElementById("9b92d18c-c45f-4f8e-a839-e81263cc3f8d");
var template = document.getElementById("3e392a23-2c9b-4e69-9178-572b9a830970");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>In the following we will go over these types of measures of central tendencies, exemplify their use, describe their strengths and weaknesses, and show how to calculate them in R.</p>
<div id="mean" class="section level2 unnumbered">
<h2>Mean</h2>
<p>The mean is used when the data is numeric and normally distributed. The mean is calculated by applying the formula shown below.</p>
<p><span class="math display">\[\begin{equation}
  \bar{x}=\frac{1}{n} \sum_{i=1}^n x_i = \frac{x_{1}+x_{2}+ \dots + x_{n}}{n}
\end{equation}\]</span></p>
<p>To calculate the mean, sum up all values and divide by the number of values. See the example below for clarification.</p>
<p><img src="dstats_files/figure-html/ds03-1.png" width="672" /></p>
<p>Consider, we are interested in the mean length of sentences in a short text, then the first thing we could do would be to list the sentences and their length in a table.</p>
<template id="35cb8e05-69a1-4424-9813-987764878d93"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2e830e4c{table-layout:auto;width:95%;}.cl-2e76cde4{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2e76cde5{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2e76f4d6{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2e76f4d7{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2e7742d8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742d9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742da{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742db{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742dc{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742dd{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742de{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2e7742df{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2e830e4c'>
<caption class="Table Caption">
<p>Sentences of the first paragraph of Herman Melville’s <em>Moby Dick</em> and the number of words in each sentence.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2e7742de"><p class="cl-2e76f4d6"><span class="cl-2e76cde4">Sentences</span></p></td><td class="cl-2e7742df"><p class="cl-2e76f4d7"><span class="cl-2e76cde4">Words</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2e7742d9"><p class="cl-2e76f4d6"><span class="cl-2e76cde5">Call me Ishmael</span></p></td><td class="cl-2e7742d8"><p class="cl-2e76f4d7"><span class="cl-2e76cde5">3</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e7742db"><p class="cl-2e76f4d6"><span class="cl-2e76cde5">Some years ago -- never mind how long precisely -- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.</span></p></td><td class="cl-2e7742da"><p class="cl-2e76f4d7"><span class="cl-2e76cde5">40</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e7742d9"><p class="cl-2e76f4d6"><span class="cl-2e76cde5">It is a way I have of driving off the spleen, and regulating the circulation.</span></p></td><td class="cl-2e7742d8"><p class="cl-2e76f4d7"><span class="cl-2e76cde5">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2e7742dc"><p class="cl-2e76f4d6"><span class="cl-2e76cde5">Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off--then, I account it high time to get to sea as soon as I can.</span></p></td><td class="cl-2e7742dd"><p class="cl-2e76f4d7"><span class="cl-2e76cde5">87</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="c52db595-3ddf-4f06-acc3-2e32c706ae79"></div>
<script>
var dest = document.getElementById("c52db595-3ddf-4f06-acc3-2e32c706ae79");
var template = document.getElementById("35cb8e05-69a1-4424-9813-987764878d93");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>To calculate the mean, we need to divide the sum of the number of words per sentence (145) by the number of sentences (7) (see the equation below).</p>
<p><span class="math display">\[\begin{equation}
\frac{3+40+15+87}{4} = \frac{145}{4} = 36.25
\label{eq:mittel2}
\end{equation}\]</span></p>
<p>The mean sentences length in our example is 36.25 words</p>
<p>In R, the <em>mean</em> is calculated as follows.</p>
<pre class="r klippy"><code># create numeric vector
frequencies &lt;- c(3, 40, 15, 87)
# calculate mean
mean(frequencies)</code></pre>
<pre><code>## [1] 36.25</code></pre>
<p>The mean is the most common way to summarize numeric variables and it is very easy and intuitive to understand. A disadvantage of the mean is that it is very strongly affected by outliers which is why the median is the preferable measure of centrality when dealing with data that is not normal or that contains outliers.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Calculate the arithmetic mean: 1, 2, 3, 4, 5, 6<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  (1 + 2 + 3 + 4 + 5 + 6)/6</code></pre>
<pre><code>  ## [1] 3.5</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the arithmetic mean for the following values using the <code>mean</code> function: 4, 3, 6, 2, 1, 5, 6, 8<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  mean(c(4, 3, 6, 2, 1, 5, 6, 8))</code></pre>
<pre><code>  ## [1] 4.375</code></pre>
</details>
<ol start="3" style="list-style-type: decimal">
<li>Create a vector out of the following values and calculate the arithmetic mean using the <code>mean</code> function: 1, 5, 5, 9<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  vec &lt;- c(1, 5, 5, 9)
  mean(vec)</code></pre>
<pre><code>  ## [1] 5</code></pre>
</details>
</div>
<p>`</p>
<hr />
</div>
<div id="median" class="section level2 unnumbered">
<h2>Median</h2>
<p>The median can be used for both numeric and ordinal variables. In contract to the mean, it is more robust and not as easily affected by outliers. While the mean is commonly associated with numeric data that is normally distributed, the median is typically used when dealing with non-normal numeric or ordinal variables, i.e. variables that are ordered but not truly numeric. The median is the central value in a de- or increasing ordering of values in a vector. In other words, 50 percent of values are above and 50 percent of values are below the median in a given vector.</p>
<p>If the vector contains an even number of elements, then the two central values are summed up and divided by 2. If the vector contains an uneven number of elements, the median represents the central value.</p>
<p><span class="math display">\[\begin{equation}
median_{x}=
\begin{cases}
x_{\frac{n+1}{2}} &amp; n\text{ uneven} \\
\frac{1}{2}\bigl(x_{\frac{n}{2}}+x_{\frac{n+1}{2}}\bigr) &amp; n\text{ even}
\end{cases}
\label{eq:median}
\end{equation}\]</span></p>
<p><img src="dstats_files/figure-html/ds07-1.png" width="672" /></p>
<p>Let’s have a look at an example. Consider you are interested in the age stratification of speakers in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE). When tabulating and plotting the age variable you get the following table and graph.</p>
<template id="12f66221-4a6a-43d2-958b-6d9ea01c8c2b"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2edbe1fc{table-layout:auto;width:50%;}.cl-2ed24a52{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2ed24a53{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2ed2982c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2ed2982d{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2ed2c090{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c091{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c092{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c093{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c094{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c095{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c096{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2ed2c097{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2edbe1fc'>
<caption class="Table Caption">
<p>Number of speakers across age groups in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE).</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c096"><p class="cl-2ed2982c"><span class="cl-2ed24a52">Age</span></p></td><td class="cl-2ed2c097"><p class="cl-2ed2982d"><span class="cl-2ed24a52">Counts</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c090"><p class="cl-2ed2982c"><span class="cl-2ed24a53">0-18</span></p></td><td class="cl-2ed2c091"><p class="cl-2ed2982d"><span class="cl-2ed24a53">9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c092"><p class="cl-2ed2982c"><span class="cl-2ed24a53">19-25</span></p></td><td class="cl-2ed2c093"><p class="cl-2ed2982d"><span class="cl-2ed24a53">160</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c090"><p class="cl-2ed2982c"><span class="cl-2ed24a53">26-33</span></p></td><td class="cl-2ed2c091"><p class="cl-2ed2982d"><span class="cl-2ed24a53">70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c092"><p class="cl-2ed2982c"><span class="cl-2ed24a53">34-41</span></p></td><td class="cl-2ed2c093"><p class="cl-2ed2982d"><span class="cl-2ed24a53">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c090"><p class="cl-2ed2982c"><span class="cl-2ed24a53">42-49</span></p></td><td class="cl-2ed2c091"><p class="cl-2ed2982d"><span class="cl-2ed24a53">9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2ed2c094"><p class="cl-2ed2982c"><span class="cl-2ed24a53">50+</span></p></td><td class="cl-2ed2c095"><p class="cl-2ed2982d"><span class="cl-2ed24a53">57</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="721164e8-5880-4d05-92c6-9874ec5bb6c2"></div>
<script>
var dest = document.getElementById("721164e8-5880-4d05-92c6-9874ec5bb6c2");
var template = document.getElementById("12f66221-4a6a-43d2-958b-6d9ea01c8c2b");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p><img src="dstats_files/figure-html/ds09-1.png" width="672" /></p>
<p>The age groups represent an order factor which means that there are categories with a natural order (here from old to young or vice versa). If we order speakers according to their age from young to old, we get a vector of length 320. If we then take the central value, i.e. the value of the 160<sup>th</sup> speaker, we get the median age in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE).</p>
<p>In R, the <em>median</em> is calculated as shown below.</p>
<pre class="r"><code># create a vector consisting out of ranks
ranks &lt;- c(rep(1, 9), rep(2, 160), rep(3, 70), rep(4, 15), rep(5, 9), rep(6, 57))
# calculate median
median(ranks)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>In our case, the median age is <em>19-25</em> because the 160<sup>th</sup> speaker belongs to the 2<sup>nd</sup> age group, i.e. the age group with speakers between 19 and 25 years old.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Calculate the median: 1, 2, 3, 4, 5, 6<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  (3 + 4)/2</code></pre>
<pre><code>  ## [1] 3.5</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the median for the following values using the <code>median</code> function: 4, 3, 6, 2, 1, 5, 6, 8<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  median(c(4, 3, 6, 2, 1, 5, 6, 8))</code></pre>
<pre><code>  ## [1] 4.5</code></pre>
</details>
<ol start="3" style="list-style-type: decimal">
<li>Create a vector out of the following values and calculate the median using the <code>median</code> function: 1, 5, 5, 9<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  vec &lt;- c(1, 5, 5, 9)
  median(vec)</code></pre>
<pre><code>  ## [1] 5</code></pre>
</details>
</div>
<p>`</p>
<hr />
</div>
<div id="mode" class="section level2 unnumbered">
<h2>Mode</h2>
<p>The mode is typically used when dealing with categorical variables and it reports which level of a factor or a categorical variable is the most frequent.</p>
<p><img src="dstats_files/figure-html/ds13-1.png" width="672" /></p>
<p>Here is an example to illustrate the mode. Consider you are interested where most speakers in the private dialogue section of the Irish component of the <em>International Corpus of English</em> are currently residing and you get the following distribution.</p>
<template id="d77b0f1e-0977-4316-bf65-699577be79ad"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2f55dbec{table-layout:auto;width:50%;}.cl-2f4bf8d4{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f4bf8d5{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f4c1ecc{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2f4c1ecd{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2f4c45be{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45bf{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c1{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f4c45c5{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2f55dbec'>
<caption class="Table Caption">
<p>Number of speakers across counties of current residency in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE).</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45c4"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d4">CurrentResidence</span></p></td><td class="cl-2f4c45c5"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d4">Speakers</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45be"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d5">Belfast</span></p></td><td class="cl-2f4c45bf"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d5">98</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45c1"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d5">Down</span></p></td><td class="cl-2f4c45c0"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d5">20</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45be"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d5">Dublin (city)</span></p></td><td class="cl-2f4c45bf"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d5">110</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45c1"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d5">Limerick</span></p></td><td class="cl-2f4c45c0"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d5">13</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f4c45c2"><p class="cl-2f4c1ecc"><span class="cl-2f4bf8d5">Tipperary</span></p></td><td class="cl-2f4c45c3"><p class="cl-2f4c1ecd"><span class="cl-2f4bf8d5">19</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="f52013a7-f44b-4861-a7d3-f4c5cbd70d9a"></div>
<script>
var dest = document.getElementById("f52013a7-f44b-4861-a7d3-f4c5cbd70d9a");
var template = document.getElementById("d77b0f1e-0977-4316-bf65-699577be79ad");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p><img src="dstats_files/figure-html/ds15-1.png" width="672" /></p>
<p>The tabulated and visualized data show that the mode is <em>Dublin (City)</em>, because the largest group (110 speakers) of speakers in the corpus are speakers from the city of Dublin. This means that the <em>average</em> speaker in in the private dialogue section of the Irish component of the <em>International Corpus of English</em> (ICE) is from Dublin city.</p>
<p>In R the <em>mode</em> is calculated as shown below:</p>
<pre class="r"><code># create a factor with the current residence of speakers
CurrentResidence &lt;- c(rep(&quot;Belfast&quot;, 98),         # repeat &quot;Belfast&quot; 98 times
                      rep(&quot;Down&quot;, 20),            # repeat &quot;Down&quot; 20 times
                      rep(&quot;Dublin (city)&quot;, 110),  # repeat &quot;Dublin (city)&quot; 110 times
                      rep(&quot;Limerick&quot;, 13),        # repeat &quot;Limerick&quot; 13 times
                      rep(&quot;Tipperary&quot;, 19))       # repeat &quot;Tipperary&quot; 19 times
# calculate mode
names(which.max(table(CurrentResidence)))         # extract which level occurs most frequently</code></pre>
<pre><code>## [1] &quot;Dublin (city)&quot;</code></pre>
<p>A word of warning is in order here as only the first(!) maximal value is provided by R even if several categories have the same frequency.</p>
</div>
<div id="geometric-mean" class="section level2 unnumbered">
<h2>Geometric mean</h2>
<p>The geometric mean represents a measure of central tendency that is used when dealing with dynamic processes where the later elements are dependent on the previous elements. The geometric mean is calculated according to the equation below.</p>
<p><span class="math display">\[\begin{equation}
\bar{x}_{geometric} = \sqrt[n]{x_1 \times x_{i+1} \times \dots \times x_n}
\end{equation}\]</span></p>
<p>Imagine you have the option to buy two different stock packages and you have to buy one of them. Which one would you buy?</p>
<template id="84ebfa36-b517-469d-ab63-8c71efff57d2"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2f9ae7e6{table-layout:auto;width:75%;}.cl-2f9234d4{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f9234d5{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2f925be4{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2f92a9be{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9bf{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c1{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c2{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c3{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c4{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c5{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c6{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c7{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92a9c8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2f92d0b0{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2f9ae7e6'>
<caption class="Table Caption">
<p>Performance of two stock packages.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2f92d0b0"><p class="cl-2f925be4"><span class="cl-2f9234d4">Year</span></p></td><td class="cl-2f92a9c7"><p class="cl-2f925be4"><span class="cl-2f9234d4">Package1</span></p></td><td class="cl-2f92a9c8"><p class="cl-2f925be4"><span class="cl-2f9234d4">Package2</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2f92a9bf"><p class="cl-2f925be4"><span class="cl-2f9234d5">Year 1</span></p></td><td class="cl-2f92a9c0"><p class="cl-2f925be4"><span class="cl-2f9234d5">+5%</span></p></td><td class="cl-2f92a9be"><p class="cl-2f925be4"><span class="cl-2f9234d5">+20%</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f92a9c1"><p class="cl-2f925be4"><span class="cl-2f9234d5">Year 2</span></p></td><td class="cl-2f92a9c3"><p class="cl-2f925be4"><span class="cl-2f9234d5">-5%</span></p></td><td class="cl-2f92a9c2"><p class="cl-2f925be4"><span class="cl-2f9234d5">-20%</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f92a9bf"><p class="cl-2f925be4"><span class="cl-2f9234d5">Year 3</span></p></td><td class="cl-2f92a9c0"><p class="cl-2f925be4"><span class="cl-2f9234d5">+5%</span></p></td><td class="cl-2f92a9be"><p class="cl-2f925be4"><span class="cl-2f9234d5">+20%</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2f92a9c6"><p class="cl-2f925be4"><span class="cl-2f9234d5">Year 4</span></p></td><td class="cl-2f92a9c4"><p class="cl-2f925be4"><span class="cl-2f9234d5">-5%</span></p></td><td class="cl-2f92a9c5"><p class="cl-2f925be4"><span class="cl-2f9234d5">-20%</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="576126c1-ec6d-473f-aa31-bb640a01e401"></div>
<script>
var dest = document.getElementById("576126c1-ec6d-473f-aa31-bb640a01e401");
var template = document.getElementById("84ebfa36-b517-469d-ab63-8c71efff57d2");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>Is one package better than the other? Did one package perform better than the other?</p>
<ul>
<li>Package 1:
<ul>
<li>Return: <span class="math inline">\(1.05 \times .95 \times 1.05 \times .95 = .995\)</span> (0.5% loss)</li>
<li>Year-over-year average: <span class="math inline">\(.995^{1/4}\)</span> = ~0.125% loss per year</li>
</ul></li>
<li>Package 2:
<ul>
<li>Return: <span class="math inline">\(1.2 \times .8 \times 1.2 \times .8 = 0.9216\)</span> (7.84% loss)</li>
<li>Year-over-year average: <span class="math inline">\(.9216^{1/4}\)</span> = ~2% loss per year.</li>
</ul></li>
</ul>
<p>Package 2 performs substantially worse because here, the changes in growth depend on the previous growth rates.</p>
</div>
<div id="harmonic-mean" class="section level2 unnumbered">
<h2>Harmonic mean</h2>
<p>The harmonic mean is a measure of central tendency that provides us with the average rate and is used when dealing with dynamic processes that involve velocities and distances. The harmonic mean is calculated according to the equation below.</p>
<p><span class="math display">\[\begin{equation}
\bar{x}_{harmonic} = 
\frac{n}{\frac{1}{x_i} + \frac{1}{x_{i+1}} + \frac{1}{x_{i+\dots}} + \frac{1}{x_n}}
\end{equation}\]</span></p>
<p>Let’s use an example to see what the harmonic mean describes. Imagine you assign group projects to students and you are interested in the average time it takes them to finalize the projects. The crucial thing is that the end state is the same: the finished project.</p>
<p>Let us say there are two groups, group A and group B. It takes group A 30 hours and group B 60 hours to finish their project. What is the average rate at which these two groups have finished their projects? If we used the arithmetic mean, we would say it takes them on average 45 hours to finish their projects but this is not appropriate in the present case.</p>
<p><span class="math display">\[\begin{equation}
\bar{x}_{harmonic} = 
\frac{2}{\frac{1}{30} + \frac{1}{60}} = \frac{2}{\frac{2}{60} + \frac{1}{60}} = \frac{2}{\frac{3}{60}} = \frac{2}{1} \times \frac{60}{3} = \frac{120}{3} = 40
\end{equation}\]</span></p>
<p>The harmonic mean is used when two rates contribute to the same workload (for instance when we download a file). Each installment is in a relay race and contributes the same amount to the issue. For example, we make a round trip to work and back. The way to work is 60 kilometers. On the way to work, we can only travel at 30 kph while we can go 60 kph on the way back. The distance is the same. Half of the results (distance traveled) comes from the first rate (30 kilometers per hour) and the other half from the second rate (60 kilometers per hour). The result is that is takes us 3 hours to get to work and back.</p>
<p>The reason why using the arithmetic mean is inappropriate in such cases is the following: The idea behind the arithmetic mean is that we calculate a single value that can replace all values in a given distribution and the sum of the mean values is identical to the sum of the observed values. So, the average is a single element that replaces each element. In our example, we have to drive at 40 kilometers per hour (instead of 30) to work and 40 kilometers per hour (instead of 60) to get back from work in the same amount of time. If we went with 45 kilometers per hour, then the result would not be 3 hours but 2 hours and 40 minutes so that the result would not be the same.</p>
</div>
<div id="notes-on-measures-of-centrality" class="section level2 unnumbered">
<h2>Notes on Measures of Centrality</h2>
<p>As suggested above, the mean is strongly affected by outliers (which is why in sch cases, the median is the more appropriate measure fo central tendency). To illustrate this, imagine you are interested whether the use of discourse particles differs across two corpora. The two corpora represent the speech of the same five speakers but in different situations and the speech thus represents different registers. In a first step, you calculate the relative frequency of discourse particle use and both corpora have a mean of 13.4 particles per 1,000 words. Given the mean, the two corpora do not seem to differ. However, when tabulating and plotting the use of particles by speaker and across these two corpora, it becomes immediately clear that the mean is not the appropriate measure of central tendency as the distributions are very dissimilar.</p>
<template id="bcac433a-b835-4a9b-bbd4-761ba7e766a9"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-2fb770fa{table-layout:auto;width:50%;}.cl-2fae287e{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2fae287f{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2fae2880{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2fae2881{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-2fae9d86{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d87{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d88{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d89{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8a{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8b{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d8f{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2fae9d90{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-2faec45a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-2fb770fa'>
<caption class="Table Caption">
<p>Relative frequencies of discourse particles per speaker in two corpora.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d8f"><p class="cl-2fae2880"><span class="cl-2fae287e">Corpus</span></p></td><td class="cl-2fae9d90"><p class="cl-2fae2880"><span class="cl-2fae287e">Speaker</span></p></td><td class="cl-2faec45a"><p class="cl-2fae2881"><span class="cl-2fae287e">Frequency</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d86"><p class="cl-2fae2880"><span class="cl-2fae287f">C1</span></p></td><td class="cl-2fae9d88"><p class="cl-2fae2880"><span class="cl-2fae287f">A</span></p></td><td class="cl-2fae9d87"><p class="cl-2fae2881"><span class="cl-2fae287f">11.4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d8c"><p class="cl-2fae2880"><span class="cl-2fae287f">C1</span></p></td><td class="cl-2fae9d8e"><p class="cl-2fae2880"><span class="cl-2fae287f">B</span></p></td><td class="cl-2fae9d8d"><p class="cl-2fae2881"><span class="cl-2fae287f">5.2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d86"><p class="cl-2fae2880"><span class="cl-2fae287f">C1</span></p></td><td class="cl-2fae9d88"><p class="cl-2fae2880"><span class="cl-2fae287f">C</span></p></td><td class="cl-2fae9d87"><p class="cl-2fae2881"><span class="cl-2fae287f">27.1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d8c"><p class="cl-2fae2880"><span class="cl-2fae287f">C1</span></p></td><td class="cl-2fae9d8e"><p class="cl-2fae2880"><span class="cl-2fae287f">D</span></p></td><td class="cl-2fae9d8d"><p class="cl-2fae2881"><span class="cl-2fae287f">9.6</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d86"><p class="cl-2fae2880"><span class="cl-2fae287f">C1</span></p></td><td class="cl-2fae9d88"><p class="cl-2fae2880"><span class="cl-2fae287f">E</span></p></td><td class="cl-2fae9d87"><p class="cl-2fae2881"><span class="cl-2fae287f">13.7</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d8c"><p class="cl-2fae2880"><span class="cl-2fae287f">C2</span></p></td><td class="cl-2fae9d8e"><p class="cl-2fae2880"><span class="cl-2fae287f">A</span></p></td><td class="cl-2fae9d8d"><p class="cl-2fae2881"><span class="cl-2fae287f">0.2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d86"><p class="cl-2fae2880"><span class="cl-2fae287f">C2</span></p></td><td class="cl-2fae9d88"><p class="cl-2fae2880"><span class="cl-2fae287f">B</span></p></td><td class="cl-2fae9d87"><p class="cl-2fae2881"><span class="cl-2fae287f">0.0</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d8c"><p class="cl-2fae2880"><span class="cl-2fae287f">C2</span></p></td><td class="cl-2fae9d8e"><p class="cl-2fae2880"><span class="cl-2fae287f">C</span></p></td><td class="cl-2fae9d8d"><p class="cl-2fae2881"><span class="cl-2fae287f">1.1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d86"><p class="cl-2fae2880"><span class="cl-2fae287f">C2</span></p></td><td class="cl-2fae9d88"><p class="cl-2fae2880"><span class="cl-2fae287f">D</span></p></td><td class="cl-2fae9d87"><p class="cl-2fae2881"><span class="cl-2fae287f">65.3</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-2fae9d89"><p class="cl-2fae2880"><span class="cl-2fae287f">C2</span></p></td><td class="cl-2fae9d8b"><p class="cl-2fae2880"><span class="cl-2fae287f">E</span></p></td><td class="cl-2fae9d8a"><p class="cl-2fae2881"><span class="cl-2fae287f">0.4</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="1bebc76e-acd6-4a74-a4cb-90c17857c1d8"></div>
<script>
var dest = document.getElementById("1bebc76e-acd6-4a74-a4cb-90c17857c1d8");
var template = document.getElementById("bcac433a-b835-4a9b-bbd4-761ba7e766a9");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p><img src="dstats_files/figure-html/ds20a-1.png" width="672" /></p>
<p>The Figure above shows that the use of discourse particles is distributed rather evenly across speakers in Corpus 1 while the distribution is very uneven in corpus 2. In corpus 2, 4 out of 5 speakers use almost no discourse particles and only one speaker, speaker D, makes excessive use of discourse particles in corpus 2. The high usage frequency of discourse particles by speaker D in corpus 2 causes the mean of corpus 2 to be identical to the mean reported for corpus 1 although the distribution of usage rates differs drastically. This means that reporting the median in addition to the mean can be useful if the distribution of values is very uneven (or non-normal or skewed).</p>
<p>To exemplify, we will summarize the distribution of discourse particles in the two corpora: the use of discourse particles in corpus 1 (mean = 13.4, median = 11.4) is substantially different from the use of discourse particles in corpus 2 (mean = 13.4, median = 0.4).</p>
</div>
</div>
<div id="measures-of-variability" class="section level1">
<h1><span class="header-section-number">3</span> Measures of Variability</h1>
<p>Measures of variability provide information about the distribution of values such as whether the data are distributed evenly and do not differ substantially or whether the data are rather heterogeneous and are distributed very unevenly <span class="citation">(Thompson <a href="#ref-thompson2009descriptive" role="doc-biblioref">2009</a>)</span>. In the following, we will have a look at the <em>variance</em> and the <em>standard deviation</em>.</p>
<p>As before, we will use a practical example to see the usefulness of applying measures of variability. Imagine you dealing with two cities, let’s say Moscow and Hamburg, that have the same mean temperature per year. However, the variability of temperatures varies differs dramatically between the Moscow and Hamburg.</p>
<template id="a65505e5-c0c3-42b7-97fb-39a4133eacc4"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-300df2b8{table-layout:auto;width:75%;}.cl-3004aa50{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3004aa51{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3004aa52{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3004aa53{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3004f83e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f83f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f840{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f841{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f842{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f843{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f844{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f845{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f846{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f847{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3004f848{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-30051f26{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-300df2b8'>
<caption class="Table Caption">
<p>Average temperature in Hamburg and Moscow by month.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-3004f848"><p class="cl-3004aa52"><span class="cl-3004aa50">Month</span></p></td><td class="cl-30051f26"><p class="cl-3004aa53"><span class="cl-3004aa50">Moscow</span></p></td><td class="cl-3004f847"><p class="cl-3004aa53"><span class="cl-3004aa50">Hamburg</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">January</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">-5.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">7.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">February</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">-12.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">7.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">March</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">5.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">8.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">April</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">12.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">9.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">May</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">15.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">10.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">June</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">18.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">13.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">July</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">22.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">15.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">August</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">23.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">15.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">September</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">20.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">13.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">October</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">16.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">11.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f83f"><p class="cl-3004aa52"><span class="cl-3004aa51">November</span></p></td><td class="cl-3004f83e"><p class="cl-3004aa53"><span class="cl-3004aa51">8.00</span></p></td><td class="cl-3004f840"><p class="cl-3004aa53"><span class="cl-3004aa51">8.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f842"><p class="cl-3004aa52"><span class="cl-3004aa51">December</span></p></td><td class="cl-3004f841"><p class="cl-3004aa53"><span class="cl-3004aa51">1.00</span></p></td><td class="cl-3004f843"><p class="cl-3004aa53"><span class="cl-3004aa51">7.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-3004f845"><p class="cl-3004aa52"><span class="cl-3004aa51">Mean</span></p></td><td class="cl-3004f846"><p class="cl-3004aa53"><span class="cl-3004aa51">10.25</span></p></td><td class="cl-3004f844"><p class="cl-3004aa53"><span class="cl-3004aa51">10.25</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="ca2c635b-74b2-45f2-b6dd-63fee70da576"></div>
<script>
var dest = document.getElementById("ca2c635b-74b2-45f2-b6dd-63fee70da576");
var template = document.getElementById("a65505e5-c0c3-42b7-97fb-39a4133eacc4");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p><img src="dstats_files/figure-html/ds22-1.png" width="672" /></p>
<p>In the following, we will discuss and calculate different measures of variability for the two cities.</p>
<div id="range" class="section level2 unnumbered">
<h2>Range</h2>
<p>The range is the simplest measure of variability and reports the lowest and highest value of a distribution. That is, the range provides minimum and maximum of a vector to show the span of values within a distribution.</p>
<p>In R, the <em>range</em> is extracted as shown below.</p>
<pre class="r"><code># create a numeric vector
Moscow &lt;- c(-5, -12, 5, 12, 15, 18, 22, 23, 20, 16, 8, 1)
min(Moscow); max(Moscow) # extract range</code></pre>
<pre><code>## [1] -12</code></pre>
<pre><code>## [1] 23</code></pre>
<p>The lowest temperature value for Moscow is -12 degrees Celsius and the highest value is 23 degrees Celsius. The range thus spans from -12 to 23.</p>
</div>
<div id="interquartile-range-iqr" class="section level2 unnumbered">
<h2>Interquartile range (IQR)</h2>
<p>The interquartile range (IQR) denotes the range that encompasses the central 50 percent of data points and thus informs about how values are distributed. This means that the IQR spans from the first quartile that encompasses 25 percent of the data to the third quartile that encompasses 75 percent of the data.</p>
<p>The easiest way to extract the IQR in R is to apply the <code>summary</code> function to a vector as shown below and then subtract the value of the 1<sup>st</sup> quartile from the value of the 3<sup>rd</sup> quartile.</p>
<pre class="r"><code>summary(Moscow) # extract IQR</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -12.00    4.00   13.50   10.25   18.50   23.00</code></pre>
<p>The <code>summary</code> function reports that the minimum temperature is -12 degrees Celsius and that the maximum temperature is 23 degrees Celsius. Also, the lower 25 percent of the data fall within -12 and 4 degrees Celsius (from the minimum value to the 1<sup>st</sup> quartile) and the upper 25 percent fall within 18.5 and 23 degrees Celsius (from the 3<sup>rd</sup> quartile to the maximum value). The IQR range represents a range that encompasses the central 50% of the data and thus represents the value that can be calculated by subtracting the value of the 1<sup>st</sup> from the value of the 3<sup>rd</sup> quartile..</p>
<p>Thus, the IQR is 18.5 - 4 = 14.5</p>
<p>.</p>
</div>
<div id="variance" class="section level2 unnumbered">
<h2>Variance</h2>
<p>The variance is calculated according to the formula below. To calculate the variance, each value is subtracted from the mean and the result is squared. The squared values are then added and the resulting sum is divided by the number of values minus 1.</p>
<p><span class="math inline">\(s = \sigma^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^{2}\)</span></p>
<p>For our example, the variance of temperatures for Moscow is 123.6591 and 9.477273 for Hamburg.</p>
<p>In R, the <em>variance</em> is calculated as shown below.</p>
<pre class="r"><code>sd(Moscow)^2</code></pre>
<pre><code>## [1] 123.659090909</code></pre>
</div>
<div id="standard-deviation" class="section level2 unnumbered">
<h2>Standard deviation</h2>
<p>The standard deviation (abbreviated with capital <span class="math inline">\(sigma\)</span> <span class="math inline">\(\sigma\)</span>) is calculated according to first equation shown below or, alternatively, according to second equation shown below and it is the square root of the squared variance.</p>
<p><span class="math inline">\(\sigma = \sqrt{s} = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}\)</span></p>
<p><span class="math inline">\(\sigma = \sqrt{\frac{ \sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}}\)</span></p>
<p>For our example, the first equation shown above provides a standard deviation of 11.12 for Moscow and a standard deviation of 3.08 for Hamburg.</p>
<p>In R, the <em>standard deviation</em> is calculated as shown below.</p>
<pre class="r"><code># calculate standard deviation
sd(Moscow) </code></pre>
<pre><code>## [1] 11.1202109202</code></pre>
<p>The standard deviation of temperature values of Moscow is 11.12.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Calculate the mean, median, and mode as well as the standard deviation for the following two vectors<br>A: 1, 3, 6, 2, 1, 1, 6, 8, 4, 2, 3, 5, 0, 0, 2, 1, 2, 1, 0<br>B: 3, 2, 5, 1, 1, 4, 0, 0, 2, 3, 0, 3, 0, 5, 4, 5, 3, 3, 4<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  A &lt;- c(1, 3, 6, 2, 1, 1, 6, 8, 4, 2, 3, 5, 0, 0, 2, 1, 2, 1, 0)
  B &lt;- c(3, 2, 5, 1, 1, 4, 0, 0, 2, 3, 0, 3, 0, 5, 4, 5, 3, 3, 4)
  mean(A)
  median(A)
  max(A)
  sd(A)
  mean(B)
  median(B)
  max(B)
  sd(B)</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>Find a partner and discuss which measure of central tendency is appropriate when dealing with grades. Then, find another partner and see whether they have come to the same conclusion or discuss why if not. Finally, discuss the advantages and disadvantages of calculating the mean when dealing with grades.</li>
</ol>
<details>
<summary>Answer</summary> The problem is that - strictly speaking - grades are ordinal and not numeric (i.e., interval- or ratio-scaled). This means that calculating the arithmetic mean is somewhat controversial. To resolve this issue, it is recommendable to either calculate the median (rather than the mean) or to be transparent about this issue and inform readers that the mean was used despite dealing with an ordinal variable.
</details>
<ol start="3" style="list-style-type: decimal">
<li>Where are mean, median, and mode when dealing with normal data (i.e., when the data approximate a normal distribution)?</li>
</ol>
<details>
<summary>Answer</summary> When dealing with normally distributed data, the arithmetic mean, median, and mode would ideally be identical (which is extremely rare when working with empirical data) or, at least, very similar.
</details>
<ol start="4" style="list-style-type: decimal">
<li>Go and find a partner and discuss what it means - on a conceptual level rather than on a statistical/mathematical level - that two groups have different ranges for a certain feature (be careful, this is not as trivial as it may seem!).</li>
</ol>
</div>
<p>`</p>
<hr />
</div>
<div id="standard-error" class="section level2 unnumbered">
<h2>Standard Error</h2>
<p>The standard error is a measure of variability and it reports the average distance from some parameters (most often from the mean). It is calculated as the standard deviation of the residuals of the parameter in question. To exemplify the standard error, we will have a look at reaction times which show how fast participants realized that a sequence of letters were either existing words or just a sequence of letters.</p>
<template id="31aa6ea2-62cb-4e4d-8cf9-4e0e74b809d4"><style>
.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-307d9848{table-layout:auto;width:75%;}.cl-3073b3fa{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3073b3fb{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3073db14{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-3073db15{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-307429f2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f3{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f5{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f7{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f8{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429f9{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429fa{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429fb{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-307429fc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-30745120{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-307d9848'>
<caption class="Table Caption">
<p>Reaction times while sober and drunk.</p>
</caption>
<thead><tr style="overflow-wrap:break-word;"><td class="cl-30745120"><p class="cl-3073db14"><span class="cl-3073b3fa">RT</span></p></td><td class="cl-307429fb"><p class="cl-3073db15"><span class="cl-3073b3fa">State</span></p></td><td class="cl-307429fc"><p class="cl-3073db15"><span class="cl-3073b3fa">Gender</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">429.276</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">435.473</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">394.535</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">377.325</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">430.294</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">289.102</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">411.505</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">366.191</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">365.792</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">334.034</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Sober</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">444.188</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">540.866</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">468.531</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">476.011</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">412.473</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Male</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">520.845</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">435.682</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f5"><p class="cl-3073db14"><span class="cl-3073b3fb">463.421</span></p></td><td class="cl-307429f6"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f7"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f3"><p class="cl-3073db14"><span class="cl-3073b3fb">536.036</span></p></td><td class="cl-307429f2"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f4"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-307429f8"><p class="cl-3073db14"><span class="cl-3073b3fb">494.936</span></p></td><td class="cl-307429fa"><p class="cl-3073db15"><span class="cl-3073b3fb">Drunk</span></p></td><td class="cl-307429f9"><p class="cl-3073db15"><span class="cl-3073b3fb">Female</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="38a732cc-e530-47fd-8a95-51ca694572a0"></div>
<script>
var dest = document.getElementById("38a732cc-e530-47fd-8a95-51ca694572a0");
var template = document.getElementById("31aa6ea2-62cb-4e4d-8cf9-4e0e74b809d4");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

<p>The standard error of the mean is calculated using the equation below.</p>
<p><span class="math display">\[\begin{equation}
\sigma~{\bar{x}}~ =\frac{\sigma}{\sqrt{n}} 
\end{equation}\]</span></p>
<p>The standard error can be calculated manually (see below) by implementing the equation from above.</p>
<pre class="r"><code>sd(rts$RT, na.rm=TRUE) /  
   sqrt(length(rts$RT[!is.na(rts$RT)]))  </code></pre>
<pre><code>## [1] 14.7692485022</code></pre>
<p>An easier way to extract standard errors is to use the <code>describe</code> function from the <code>psych</code> package (see below)</p>
<pre class="r"><code># describe data
psych::describe(rts$RT, type=2)</code></pre>
<pre><code>##    vars  n   mean    sd median trimmed  mad   min    max  range skew kurtosis
## X1    1 20 431.33 66.05 432.88   432.9 60.4 289.1 540.87 251.76 -0.2    -0.13
##       se
## X1 14.77</code></pre>
</div>
</div>
<div id="confidence-intervals" class="section level1">
<h1><span class="header-section-number">4</span> Confidence Intervals</h1>
<p>Confidence intervals provide an estimation of in-between which values the reported value would lie in the population with a confidence of, e.g., 95 percent.</p>
<p><span class="math display">\[\begin{equation}
  \bar{x} \mp z \frac{s}{\sqrt{n}}
\end{equation}\]</span></p>
<p>The z-value for 95% probability (a two-tailed) of a normal distribution is 1.96. To check this, we can use the <code>qnorm</code> function and extract the z-value for a probability of .975 - we do not use .95 because we want 2.5% of the lower tail (-1.96) and 2.5% of the higher tail (1.96).</p>
<pre class="r"><code>qnorm(0.975)   </code></pre>
<pre><code>## [1] 1.95996398454</code></pre>
<p>This means that for a 95% confidence interval for normally distributed data, we can use the formula shown below.</p>
<p><span class="math display">\[\begin{equation}
  \bar{x} \mp 1.96 \frac{s}{\sqrt{n}}
\end{equation}\]</span></p>
<p>If we have a vector of values (e.g., 4,5,2,3,1,4,3,6,3,2,4,1), we can easily calculate the confidence intervals for the mean as follows.</p>
<pre class="r"><code># calculate mean
m &lt;- mean(c(4,5,2,3,1,4,3,6,3,2,4,1))
# calculate standard deviation
s &lt;- sd(c(4,5,2,3,1,4,3,6,3,2,4,1))
# calculate n
n &lt;- length(c(4,5,2,3,1,4,3,6,3,2,4,1))
# calculate lower and upper ci
lower &lt;- m-1.96*(s/sqrt(n))
upper &lt;- m+1.96*(s/sqrt(n))
# show lower ci, mean, and upper ci
lower; m; upper</code></pre>
<pre><code>## [1] 2.30238790505</code></pre>
<pre><code>## [1] 3.16666666667</code></pre>
<pre><code>## [1] 4.03094542828</code></pre>
<p>There are several functions in R to extract confidence intervals. To show how you can do this for different types of elements, we will continue to work with the reaction times data.</p>
<hr />
<div class="warning" style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Calculate the mean and confidence interval: 1, 2, 3, 4, 5, 6, 7, 8, 9<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  # calculate mean
  m &lt;- mean(c(1, 2, 3, 4, 5, 6, 7, 8, 9))
  # calculate standard deviation
  s &lt;- sd(c(1, 2, 3, 4, 5, 6, 7, 8, 9))
  # calculate n
  n &lt;- length(c(1, 2, 3, 4, 5, 6, 7, 8, 9))
  # calculate lower and upper ci
  lower &lt;- m-1.96*(s/sqrt(n))
  upper &lt;- m+1.96*(s/sqrt(n))
  # show lower ci, mean, and upper ci
  lower; m; upper</code></pre>
<pre><code>  ## [1] 3.21077297882</code></pre>
<pre><code>  ## [1] 5</code></pre>
<pre><code>  ## [1] 6.78922702118</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the mean and confidence interval: 3, 4, 5, 4, 3, 4, 5, 4, 3<br></li>
</ol>
<details>
<p><summary>Answer</summary></p>
<pre class="r"><code>  # calculate mean
  m &lt;- mean(c(3, 4, 5, 4, 3, 4, 5, 4, 3))
  # calculate standard deviation
  s &lt;- sd(c(3, 4, 5, 4, 3, 4, 5, 4, 3))
  # calculate n
  n &lt;- length(c(3, 4, 5, 4, 3, 4, 5, 4, 3))
  # calculate lower and upper ci
  lower &lt;- m-1.96*(s/sqrt(n))
  upper &lt;- m+1.96*(s/sqrt(n))
  # show lower ci, mean, and upper ci
  lower; m; upper</code></pre>
<pre><code>  ## [1] 3.37815472837</code></pre>
<pre><code>  ## [1] 3.88888888889</code></pre>
<pre><code>  ## [1] 4.3996230494</code></pre>
</details>
</div>
<p>`</p>
<hr />
<div id="confidence-intervals-for-simple-vectors" class="section level2 unnumbered">
<h2>Confidence Intervals for Simple Vectors</h2>
<p>Confidence intervals (CIs) give a range that’s likely to include a population value with a certain degree of confidence. As such, CIs tell us how likely it is to get a value within a certain range if we drew another sample from the same population.</p>
<p>One easy method for extracting confidence intervals is to apply the <code>CI</code> function from the <code>Rmisc</code> package.</p>
<pre class="r"><code># extract mean and confidence intervals
Rmisc::CI(rts$RT, ci=0.95)   </code></pre>
<pre><code>##         upper          mean         lower 
## 462.238192381 431.325800000 400.413407619</code></pre>
<p>The ´CI´ function provides the mean reaction time (431.3258) and the 95 percent confidence band. With 95 percent confidence, the mean reaction time will have a mean between 400.41 and 462.24 miliseconds (ms).</p>
<p>Another way to extract the mean and its confidence intervals is by using <code>t.test</code> function.</p>
<pre class="r"><code># extract mean and confidence intervals
stats::t.test(rts$RT, conf.level=0.95)  </code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  rts$RT
## t = 29.20431598, df = 19, p-value &lt; 0.0000000000000002220446
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  400.413407619 462.238192381
## sample estimates:
## mean of x 
##  431.3258</code></pre>
<p>Another alternative to extract the man ans the confidence interval from a range of values is to use the <code>MeanCI</code> function from the <code>DescTools</code> package.</p>
<pre class="r"><code># extract mean and confidence intervals
DescTools::MeanCI(rts$RT, conf.level=0.95)   </code></pre>
<pre><code>##          mean        lwr.ci        upr.ci 
## 431.325800000 400.413407619 462.238192381</code></pre>
<p>A very interesting alternative to extract the mean and the confidence intervals from a range of values is to apply the <code>MeanCI</code> function from the <code>DescTools</code> package. This method is particularly interesting because it uses bootstrapping or resampling the data. As such, it is an empirical method to extract the mean and the confidence intervals. The values will differ given how many samples are drawn and we can get very precise estimates using this method.</p>
<pre class="r"><code># extract mean CIs
DescTools::MeanCI(rts$RT, method=&quot;boot&quot;, type=&quot;norm&quot;, R=1000)</code></pre>
<pre><code>##          mean        lwr.ci        upr.ci 
## 431.325800000 402.065920019 459.599597681</code></pre>
<p>Because this is a data-driven approach, the results will vary, depending on the characteristics of the resampled data. To illustrate, compare the values provided above to the values generated below.</p>
<pre class="r"><code># extract mean CIs
DescTools::MeanCI(rts$RT, method=&quot;boot&quot;, type=&quot;norm&quot;, R=1000)</code></pre>
<pre><code>##          mean        lwr.ci        upr.ci 
## 431.325800000 403.272504877 458.846973023</code></pre>
<p>Another method for extracting the mean and the confidence intervals from a range of values using bootstrapping is to use the <code>boot</code> function from the <code>boot</code> package.</p>
<pre class="r"><code># function to extract values
BootFunction = function(x, index) {                        
                  return(c(mean(x[index]),
                           var(x[index]) / length(index)))
}
# apply function to data
Bootstrapped = boot(data=rts$RT,     
                    statistic=BootFunction,
                    R=1000)
# extract values
mean(Bootstrapped$t[,1])                                   </code></pre>
<pre><code>## [1] 431.4550746</code></pre>
<pre class="r"><code># alternative to extract values
boot.ci(Bootstrapped, conf=0.95)                           </code></pre>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = Bootstrapped, conf = 0.95)
## 
## Intervals : 
## Level      Normal              Basic             Studentized     
## 95%   (402.9, 459.5 )   (402.8, 460.4 )   (397.6, 463.3 )  
## 
## Level     Percentile            BCa          
## 95%   (402.2, 459.9 )   (400.1, 457.6 )  
## Calculations and Intervals on Original Scale</code></pre>
<p>The advantage of using bootstrapping methods lies in the fact that the data is (frequently) not distributed normally which is not an issue for the bootstrapping and it will thus provide more reliable results as it does not rely on distributional assumptions about the data.</p>
</div>
<div id="confidence-intervals-for-grouped-data" class="section level2 unnumbered">
<h2>Confidence Intervals for Grouped Data</h2>
<p>To extract the confidence intervals for grouped data, we can sue the <code>summarySE</code> function from the <code>Rmisc</code> package.</p>
<pre class="r"><code># apply summarySE function to data
Rmisc::summarySE(data=rts,   
                 # define variable representing frequencies
                 measurevar=&quot;RT&quot;, 
                 # define grouping variabel
                 groupvars=&quot;Gender&quot;,
                 # extract standard deviation, standard error, and confidence intervals
                 conf.interval = 0.95)   </code></pre>
<pre><code>##   Gender  N       RT            sd            se            ci
## 1 Female 10 421.7544 82.8522922089 26.2001952746 59.2689594071
## 2   Male 10 440.8972 46.2804393809 14.6351599557 33.1070319225</code></pre>
</div>
<div id="confidence-intervals-for-nominal-data" class="section level2 unnumbered">
<h2>Confidence Intervals for Nominal Data</h2>
<p>We now turn to confidence intervals for nominal data <span class="citation">(see also Thomas and Grunkemeier <a href="#ref-thomas1975confidence" role="doc-biblioref">1975</a>)</span>. When dealing with nominal data, confidence intervals can be determined with the <code>binom.test</code> function in the in-built <code>stats</code> package. Alternative methods are available via the <code>BinomCI</code> and <code>MultinomCI</code> functions from the <code>DescTools</code> package. More advanced techniques for confidence intervals on nominal data are available via the <code>PropCIs</code> package.</p>
<pre class="r"><code>stats::binom.test(2, 20, 0.5,              # binom.test(x, n, p = 0.5, ...)
                  alternative=&quot;two.sided&quot;, # define sidedness
                  conf.level=0.95)         # define confidence level</code></pre>
<pre><code>## 
##  Exact binomial test
## 
## data:  2 and 20
## number of successes = 2, number of trials = 20, p-value =
## 0.000402450562
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.0123485271703 0.3169827140191
## sample estimates:
## probability of success 
##                    0.1</code></pre>
<p>Another way to use the <code>BinomCI</code> function is shown below.</p>
<pre class="r"><code># extract CIs                  
BinomCI(2, 20,                        # apply BinomCI function
        conf.level = 0.95,            # define ci
        method = &quot;modified wilson&quot;)   # define method for ci extraction</code></pre>
<pre><code>##      est          lwr.ci         upr.ci
## [1,] 0.1 0.0177680755349 0.301033645228</code></pre>
</div>
<div id="confidence-intervals-for-multinomial-data" class="section level2 unnumbered">
<h2>Confidence Intervals for Multinomial Data</h2>
<p>We use the <code>MultinomCI</code> function to extract the confidence intervals form multinominal data.</p>
<pre class="r"><code>observed = c(35,74,22,69)       # define multinominal vector
MultinomCI(observed,            # apply MultinomCI function
           conf.level=0.95,     # define ci
           method=&quot;goodman&quot;)    # define method for ci extraction</code></pre>
<pre><code>##        est          lwr.ci         upr.ci
## [1,] 0.175 0.1125321503865 0.261910646274
## [2,] 0.370 0.2811364343551 0.468640684309
## [3,] 0.110 0.0622433796475 0.187087976345
## [4,] 0.345 0.2584619757815 0.443195358010</code></pre>
</div>
</div>
<div id="citation-session-info" class="section level1 unnumbered">
<h1>Citation &amp; Session Info</h1>
<p>Schweinberger, Martin. 2022. <em>Descriptive Statistics with R</em>. Brisbane: The University of Queensland. url: <a href="https://slcladal.github.io/dstats.html" class="uri">https://slcladal.github.io/dstats.html</a> (Version 2022.01.25).</p>
<pre><code>@manual{schweinberger2022desc,
  author = {Schweinberger, Martin},
  title = {Descriptive Statistics with R},
  note = {https://slcladal.github.io/dstats.html},
  year = {2022},
  organization = &quot;The University of Queensland, Australia. School of Languages and Cultures},
  address = {Brisbane},
  edition = {2022.01.25}
}</code></pre>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.1.2 (2021-11-01)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19043)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices datasets  utils     methods   base     
## 
## other attached packages:
##  [1] ggpubr_0.4.0      Rmisc_1.5         plyr_1.8.6        lattice_0.20-45  
##  [5] psych_2.1.9       flextable_0.6.10  forcats_0.5.1     stringr_1.4.0    
##  [9] dplyr_1.0.7       purrr_0.3.4       readr_2.1.1       tidyr_1.1.4      
## [13] tibble_3.1.6      ggplot2_3.3.5     tidyverse_1.3.1   DescTools_0.99.44
## [17] boot_1.3-28      
## 
## loaded via a namespace (and not attached):
##  [1] nlme_3.1-153      fs_1.5.2          lubridate_1.8.0   httr_1.4.2       
##  [5] tools_4.1.2       backports_1.4.1   utf8_1.2.2        R6_2.5.1         
##  [9] DBI_1.1.2         colorspace_2.0-2  withr_2.4.3       tidyselect_1.1.1 
## [13] Exact_3.1         mnormt_2.0.2      compiler_4.1.2    cli_3.1.0        
## [17] rvest_1.0.2       expm_0.999-6      xml2_1.3.3        officer_0.4.1    
## [21] labeling_0.4.2    scales_1.1.1      mvtnorm_1.1-3     proxy_0.4-26     
## [25] systemfonts_1.0.3 digest_0.6.29     rmarkdown_2.5     base64enc_0.1-3  
## [29] pkgconfig_2.0.3   htmltools_0.5.2   dbplyr_2.1.1      fastmap_1.1.0    
## [33] highr_0.9         rlang_0.4.12      readxl_1.3.1      rstudioapi_0.13  
## [37] farver_2.1.0      generics_0.1.1    jsonlite_1.7.2    car_3.0-12       
## [41] zip_2.2.0         magrittr_2.0.1    Matrix_1.3-4      Rcpp_1.0.7       
## [45] munsell_0.5.0     fansi_1.0.0       abind_1.4-5       gdtools_0.2.3    
## [49] lifecycle_1.0.1   stringi_1.7.6     yaml_2.2.1        carData_3.0-4    
## [53] MASS_7.3-54       rootSolve_1.8.2.3 grid_4.1.2        parallel_4.1.2   
## [57] crayon_1.4.2      lmom_2.8          haven_2.4.3       hms_1.1.1        
## [61] tmvnsim_1.0-2     klippy_0.0.0.9500 knitr_1.37        pillar_1.6.4     
## [65] uuid_1.0-3        gld_2.6.4         ggsignif_0.6.3    reprex_2.0.1     
## [69] glue_1.6.0        evaluate_0.14     data.table_1.14.2 renv_0.14.0      
## [73] modelr_0.1.8      vctrs_0.3.8       tzdb_0.2.0        cellranger_1.1.0 
## [77] gtable_0.3.0      assertthat_0.2.1  xfun_0.29         broom_0.7.10     
## [81] e1071_1.7-9       rstatix_0.7.0     class_7.3-19      ellipsis_0.3.2</code></pre>
<hr />
<p><a href="#introduction">Back to top</a></p>
<p><a href="https://slcladal.github.io/index.html">Back to HOME</a></p>
<hr />
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-bickel2012descriptive">
<p>Bickel, Peter J, and Erich L Lehmann. 2012. “Descriptive Statistics for Nonparametric Models Iv. Spread.” In <em>Selected Works of El Lehmann</em>, 519–26. Springer.</p>
</div>
<div id="ref-gaddis1990introduction">
<p>Gaddis, Gary M, and Monica L Gaddis. 1990. “Introduction to Biostatistics: Part 2, Descriptive Statistics.” <em>Annals of Emergency Medicine</em> 19 (3): 309–15.</p>
</div>
<div id="ref-thomas1975confidence">
<p>Thomas, David R, and Gary L Grunkemeier. 1975. “Confidence Interval Estimation of Survival Probabilities for Censored Data.” <em>Journal of the American Statistical Association</em> 70 (352): 865–71.</p>
</div>
<div id="ref-thompson2009descriptive">
<p>Thompson, Cheryl Bagley. 2009. “Descriptive Data Analysis.” <em>Air Medical Journal</em> 28 (2): 56–59.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>
</html>
