<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Martin Schweinberger" />

<meta name="date" content="2020-09-29" />

<title>Cluster and Correspondence Analysis in R</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="site_libs/datatables-binding-0.15/datatables.js"></script>
<link href="site_libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="site_libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="site_libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="site_libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="site_libs/selectize-0.12.0/selectize.min.js"></script>
<link href="site_libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="people.html">OUR PEOPLE</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    NEWS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="news.html">News &amp; Announcements</a>
    </li>
    <li>
      <a href="conferences.html">Events &amp; Presentations</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    DATA SCIENCE BASICS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Introduction to Data Science</li>
    <li>
      <a href="introcomputer.html">Working with Computers: Tips and Tricks</a>
    </li>
    <li>
      <a href="reproducibility.html">Data Management, Version Control, and Reproducibility</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Quantitative Research</li>
    <li>
      <a href="introquant.html">Introduction to Quantitative Reasoning</a>
    </li>
    <li>
      <a href="basicquant.html">Basic Concepts in Quantitative Research</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Introduction to R</li>
    <li>
      <a href="IntroR_workshop.html">Getting started</a>
    </li>
    <li>
      <a href="stringprocessing.html">String Processing</a>
    </li>
    <li>
      <a href="regularexpressions.html">Regular Expressions</a>
    </li>
    <li>
      <a href="introtables.html">Working with Tables</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    TUTORIALS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Visualization</li>
    <li>
      <a href="introviz.html">Introduction to Data Viz</a>
    </li>
    <li>
      <a href="basicgraphs.html">Common Visualization Types</a>
    </li>
    <li>
      <a href="basicgraphs.html">Advanced Visualization Methods</a>
    </li>
    <li>
      <a href="maps.html">Displaying Geo-Spatial Data</a>
    </li>
    <li>
      <a href="motion.html">Interactive Charts</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Statistics</li>
    <li>
      <a href="descriptivestatz.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="basicstatz.html">Basic Inferential Statistics</a>
    </li>
    <li>
      <a href="regression.html">Regression Analysis</a>
    </li>
    <li>
      <a href="advancedstatztrees.html">Tree-Based Models</a>
    </li>
    <li>
      <a href="groupingstatz.html">Cluster and Correspondence Analysis</a>
    </li>
    <li>
      <a href="svm.html">Semantic Vector Space Models</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Text Analytics</li>
    <li>
      <a href="textanalysis.html">Text Analysis and Distant Reading</a>
    </li>
    <li>
      <a href="kwics.html">Concordancing (keywords-in-context)</a>
    </li>
    <li>
      <a href="basicnetwork.html">Network Analysis</a>
    </li>
    <li>
      <a href="collocations.html">Co-occurrence and Collocation Analysis</a>
    </li>
    <li>
      <a href="topicmodels.html">Topic Modeling</a>
    </li>
    <li>
      <a href="sentiment.html">Sentiment Analysis</a>
    </li>
    <li>
      <a href="tagging.html">Tagging and Parsing</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    FOCUS &amp; CASE STUDIES
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lex.html">Lexicography with R: Generating Dictionaries</a>
    </li>
    <li>
      <a href="surveys.html">Questionnaires and Surveys: Analyses with R</a>
    </li>
    <li>
      <a href="corplingr.html">Corpus Linguistics with R: Swearing in Irish English</a>
    </li>
    <li>
      <a href="convertpdf2txt.html">Converting PDFs to txt</a>
    </li>
    <li>
      <a href="webcrawling.html">Web Crawling using R</a>
    </li>
    <li>
      <a href="vc.html">Creating Vowel Charts with Praat and R</a>
    </li>
  </ul>
</li>
<li>
  <a href="services.html">SERVICES &amp; CONTACT</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Cluster and Correspondence Analysis in R</h1>
<h4 class="author">Martin Schweinberger</h4>
<h4 class="date">2020-09-29</h4>

</div>


<p><img src="images/uq1.jpg" width="100%" /></p>
<div id="introduction" class="section level1 unnumbered">
<h1>Introduction</h1>
<p>This tutorial introduces classification and clustering using R. The entire R markdown document for this tutorial can be downloaded <a href="https://slcladal.github.io/groupingstatz.Rmd">here</a>. A more elaborate and highly recommendable introduction to cluster analysis is <span class="citation">Kassambara (<a href="#ref-kassambara2017practical" role="doc-biblioref">2017</a>)</span>. Other very useful resources are, e.g., <span class="citation">King (<a href="#ref-king2015cluster" role="doc-biblioref">2015</a>)</span>; <span class="citation">Kettenring (<a href="#ref-kettenring2006practice" role="doc-biblioref">2006</a>)</span>; <span class="citation">Romesburg (<a href="#ref-romesburg2004cluster" role="doc-biblioref">2004</a>)</span>; and <span class="citation">Blashfield and Aldenderfer (<a href="#ref-blashfield1988methods" role="doc-biblioref">1988</a>)</span>.</p>
<p>Cluster analyses fall within the domain of classification methods which are used to find groups or patterns in data or to predict group membership. As such, they are widely used and applied in machine learning. For linguists, classification is not only common when it comes to phylogenetics but also in annotation-based procedures such as part-of-speech tagging and syntactic parsing.</p>
<div id="preparation-and-session-set-up" class="section level2 unnumbered">
<h2>Preparation and session set up</h2>
<p>This tutorial is based on R. If you have not installed R or are new to it, you will find an introduction to and more information how to use R <a href="https://slcladal.github.io/IntroR_workshop.html">here</a>. For this tutorials, we need to install certain <em>packages</em> from an R <em>library</em> so that the scripts shown below are executed without errors. Before turning to the code below, please install the packages by running the code below this paragraph. If you have already installed the packages mentioned below, then you can skip ahead ignore this section. To install the necessary packages, simply run the following code - it may take some time (between 1 and 5 minutes to install all of the libraries so you do not need to worry if it takes some time).</p>
<pre class="r"><code># clean current workspace
rm(list=ls(all=T))
# set options
options(stringsAsFactors = F)         # no automatic data transformation
options(&quot;scipen&quot; = 100, &quot;digits&quot; = 4) # suppress math annotation
# install libraries
install.packages(c(&quot;cluster&quot;, &quot;factoextra&quot;, &quot;cluster&quot;, 
                   &quot;seriation&quot;, &quot;pvclust&quot;, &quot;ape&quot;, &quot;vcd&quot;, 
                   &quot;exact2x2&quot;, &quot;factoextra&quot;, &quot;seriation&quot;, 
                   &quot;NbClust&quot;, &quot;pvclust&quot;))</code></pre>
<p>Once you have installed R-Studio and initiated the session by executing the code shown above, you are good to go.</p>
</div>
</div>
<div id="cluster-analysis" class="section level1">
<h1><span class="header-section-number">1</span> Cluster Analysis</h1>
<p>The most common method in linguistics that is sued to detect groups in data are cluster analyses. Cluster analyses are common in linguistics because they not only detect commonalities based on the frequency or occurrence of features but they also allow to visualize when splits between groups have occurred and are thus the method of choice in historical linguistics to determine and show genealogical relationships.</p>
<div id="underlying-concepts" class="section level2 unnumbered">
<h2>Underlying Concepts</h2>
<p>The next section focuses on the basic idea that underlies all cluster analyses. WE will have a look at some very basic examples to highlight and discuss the principles that cluster analyses rely on.</p>
<p>The underlying idea of cluster analysis is very simple and rather intuitive as we ourselves perform cluster analyses every day in our lives. This is so because we group things together under certain labels and into concepts. The first example used to show this, deals with types of trees and how we group these types of trees based on their outward appearance.</p>
<p>Imagine you see six trees representing different types of trees: a pine tree, a fir tree, an oak tree, a beech tree, a phoenix palm tree, and a nikau palm tree. Now, you were asked to group these trees according to similarity. Have a look at the plot below and see whether you would have come up with a similar type of grouping.</p>
<p><img src="groupingstatz_files/figure-html/cl1-1.png" width="672" /></p>
<p>An alternative way to group the trees would be the following.</p>
<p><img src="groupingstatz_files/figure-html/cl2-1.png" width="672" /></p>
<p>In this display, conifers and broad-leaf trees are grouped together because there are more similar to each other compared to palm trees. This poses the question of what is meant by similarity. Consider the display below.</p>
<p><img src="groupingstatz_files/figure-html/cl3-1.png" width="672" /></p>
<p>Are the red and the blue line more similar because they have the same shape or are the red and the black line more similar because they are closer together? There is no single correct answer here. Rather the plot intends to raise awareness about the fact that how cluster analyses group data depends on how similarity is defined in the respective algorithm.</p>
<p>Let’s consider another example to better understand how cluster analyses determine which data points should be merged when. Imagine you have five students and want to group them together based on their overall performance in school. The data that you rely on are their grades in math, music, and biology (with 1 being the best grade and 6 being the worst).</p>
<table>
<caption>Sample of five students and their grades in math, music, and biology</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Math</th>
<th align="right">Music</th>
<th align="right">Biology</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">StudentA</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">StudentB</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">StudentC</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">StudentD</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">StudentE</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">3</td>
</tr>
</tbody>
</table>
<p>The first step in determining the similarity among students is to create a distance matrix.</p>
<pre class="r"><code>diststudents &lt;- dist(students, method = &quot;manhattan&quot;) # create a distance matrix</code></pre>
<p>The distance matrix below shows that Student A and Student B only differ by one grade. Student B and Student C differ by 2 grades. Student A and Student C differ by 3 grades and so on.</p>
<table>
<caption>Distance matrix based of students based on grades in math, music, and biology.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">StudentA</th>
<th align="left">StudentB</th>
<th align="left">StudentC</th>
<th align="left">StudentD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">StudentB</td>
<td align="left">1</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">StudentC</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">StudentD</td>
<td align="left">3</td>
<td align="left">4</td>
<td align="left">6</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">StudentE</td>
<td align="left">3</td>
<td align="left">4</td>
<td align="left">6</td>
<td align="left">2</td>
</tr>
</tbody>
</table>
<p>Based on this distance matrix, we can now implement a cluster analysis in <code>R</code>.</p>
</div>
<div id="cluster-analysis-on-numeric-data" class="section level2 unnumbered">
<h2>Cluster Analysis on Numeric Data</h2>
<p>To create a simple cluster object in R, we use the “hclust” function from the “cluster” package. The resulting object is then plotted to create a dendrogram which shows how students have been amalgamated (combined) by the clustering algorithm (which, in the present case, is called “ward.D”).</p>
<pre class="r"><code># activate library
library(&quot;cluster&quot;)    
library(&quot;factoextra&quot;)
library(&quot;seriation&quot;)
library(&quot;NbClust&quot;)
library(&quot;pvclust&quot;)
# create hierarchical cluster object with ward.D as linkage method
clusterstudents &lt;- hclust(diststudents, method=&quot;ward.D&quot;)
# plot result as dendrogram
plot(clusterstudents, hang = 0)</code></pre>
<p><img src="groupingstatz_files/figure-html/cl8-1.png" width="672" /></p>
<p>Let us have a look at how the clustering algorithm has amalgamated the students. The amalgamation process takes the distance matrix from above as a starting point and, in a first step, has merged Student A and Student B (because they were the most similar students in the data based on the distance matrix). After collapsing Student A and Student B, the resulting distance matrix looks like the distance matrix below (notice that Student A and Student B now form a cluster that is represented by the means of the grades of the two students).</p>
<pre class="r"><code>students2 &lt;- matrix(c(1.5, 3, 2, 1,  2,  1, 2,  4,  4, 3,  4,  3),
  nrow = 4, byrow = T)
students2 &lt;- as.data.frame(students2)
rownames(students2) &lt;- c(&quot;Cluster1&quot;, &quot;StudentC&quot;, &quot;StudentD&quot;, &quot;StudentE&quot;)
diststudents2 &lt;- dist(students2, method = &quot;manhattan&quot;)</code></pre>
<table>
<caption>Distance matrix of students based on grades in math, music, and biology.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Cluster 1</th>
<th align="left">Student C</th>
<th align="left">Student D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Student C</td>
<td align="left">2.5</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Student D</td>
<td align="left">3.5</td>
<td align="left">6.0</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Student E</td>
<td align="left">3.5</td>
<td align="left">6.0</td>
<td align="left">2.0</td>
</tr>
</tbody>
</table>
<p>The next lowest distance now is 2.0 between Student D and Student E which means that these two students are merged next. The resulting distance matrix is shown below.</p>
<pre class="r"><code>students3 &lt;- matrix(c(1.5,3,2,1,2,1,2.5,4,3.5),
  nrow = 3, byrow = T)
students3 &lt;- as.data.frame(students3)
rownames(students3) &lt;- c(&quot;Cluster1&quot;, &quot;StudentC&quot;, &quot;Cluster2&quot;)
diststudents3 &lt;- dist(students3, 
                      method = &quot;manhattan&quot;)</code></pre>
<table>
<caption>Distance matrix based of students based on grades in math, music, and biology.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Cluster 1</th>
<th align="left">Student C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Student C</td>
<td align="left">2.5</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Cluster 2</td>
<td align="left">3.5</td>
<td align="left">6.0</td>
</tr>
</tbody>
</table>
<p>Now, the lowest distance value occurs between Cluster 1 and Student C. Thus, Student C and Cluster 1 are merged. In the final step, the Cluster 2 is merged with the new cluster encompassing Student C and Cluster 1. This amalgamation process can then be displayed visually as a dendrogram (see above).</p>
<p>How and which elements are merged depends on the what is understood as distance. Since “distance” is such an important concept in cluster analyses, we will briefly discuss this notion to understand why there are so many different types of clustering algorithms and this cluster analyses.</p>
</div>
<div id="distance-and-similarity-measures" class="section level2 unnumbered">
<h2>Distance and Similarity Measures</h2>
<p>To understand how a cluster analysis determines to which cluster a given data point belongs, we need to understand what different distance measures represent. Have a look at the Figure below which visually represents three different ways to conceptualize distance.</p>
<pre class="r"><code>par(mar=c(1,1,1,1))  # define margine width of the plot
x &lt;- c(1,5)          # define an x value
y &lt;- c(1,5)          # define a y value
plot(x, y, 
     pch = 20, 
     cex = 1, 
     axes = F, 
     las = 1, 
     xlab = &quot;&quot;, 
     ylab = &quot;&quot;, 
     xlim = c(0,7), 
     ylim = c(0,10))
text(0.5, .5, &quot;Point A&quot;, cex = 1)
text(5, 5.5, &quot;Point B&quot;, cex = 1)
lines(x = c(1, 5), y = c(1, 5), type = &quot;l&quot;, lty = 3, lwd = 2, col = &quot;red&quot;)
lines(x = c(1, 5), y = c(1, 1), type = &quot;l&quot;, lty = 2, lwd = 2, col = &quot;blue&quot;)
lines(x = c(5, 5), y = c(1, 5), type = &quot;l&quot;, lty = 4, lwd = 2, col = &quot;green&quot;)
lines(x = c(.9, 5), y = c(.9, .9), type = &quot;l&quot;, lty = 4, lwd = 2, col = &quot;green&quot;)
legend(&quot;topleft&quot;, inset=.05, title=&quot;&quot;, bty = &quot;n&quot;, lty = c(3, 2, 4), lwd = 2,
   c(&quot;euclidean distance&quot;, &quot;maximum distance&quot;, &quot;manhatten distance&quot;), col=c(&quot;red&quot;, &quot;blue&quot;, &quot;green&quot;), horiz=F, cex = 1)</code></pre>
<p><img src="groupingstatz_files/figure-html/cl13-1.png" width="672" /></p>
<pre class="r"><code>par(mar=c(5.1,4.1,4.1,2.1))</code></pre>
<p>The Figure above depicts three ways to measure distance: the “eucledian distance” represents the distance between points as the hypothenuse of the x- and y-axis distances while the “maximum distance” represents distance as the longer distance of either the distance on the x- or the y-axis. The manhatten distance (or block distance) is the sum of the distances on the x- and the y-axis.</p>
<p>We will now turn to another example in order to delve a little deeper into how clustering algorithms work. In this example, we will find cluster of varieties of English based on the relative frequency of selected non-standard features (such as the relative frequencies of cleft constructions and tag questions). As a first step, we generate some fictional data set for this analysis.</p>
<pre class="r"><code># generate data
IrishEnglish &lt;- round(sqrt((rnorm(10, 9.5, .5))^2), 3)
ScottishEnglish &lt;- round(sqrt((rnorm(10, 9.3, .4))^2), 3)
BritishEnglish &lt;- round(sqrt((rnorm(10, 6.4, .7))^2), 3)
AustralianEnglish &lt;- round(sqrt((rnorm(10, 6.6, .5))^2), 3)
NewZealandEnglish &lt;- round(sqrt((rnorm(10, 6.5, .4))^2), 3)
AmericanEnglish &lt;- round(sqrt((rnorm(10, 4.6, .8))^2), 3)
CanadianEnglish &lt;- round(sqrt((rnorm(10, 4.5, .7))^2), 3)
JamaicanEnglish &lt;- round(sqrt((rnorm(10, 1.4, .2))^2), 3)
PhillipineEnglish &lt;- round(sqrt((rnorm(10, 1.5, .4))^2), 3)
IndianEnglish &lt;- round(sqrt((rnorm(10, 1.3, .5))^2), 3)
clus &lt;- data.frame(IrishEnglish, ScottishEnglish, BritishEnglish, 
                   AustralianEnglish, NewZealandEnglish, AmericanEnglish, 
                   CanadianEnglish, JamaicanEnglish, PhillipineEnglish, IndianEnglish)
# add row names
rownames(clus) &lt;- c(&quot;nae_neg&quot;, &quot;like&quot;, &quot;clefts&quot;, &quot;tags&quot;, &quot;youse&quot;, &quot;soitwas&quot;, &quot;dt&quot;, &quot;nsr&quot;, &quot;invartag&quot;, &quot;wh_cleft&quot;)
# inspect results
summary(clus) </code></pre>
<pre><code>##   IrishEnglish   ScottishEnglish BritishEnglish  AustralianEnglish
##  Min.   :9.004   Min.   :8.814   Min.   :5.153   Min.   :5.683    
##  1st Qu.:9.207   1st Qu.:9.207   1st Qu.:6.355   1st Qu.:6.292    
##  Median :9.477   Median :9.335   Median :6.840   Median :6.644    
##  Mean   :9.465   Mean   :9.333   Mean   :6.652   Mean   :6.688    
##  3rd Qu.:9.775   3rd Qu.:9.555   3rd Qu.:7.210   3rd Qu.:6.969    
##  Max.   :9.842   Max.   :9.609   Max.   :7.648   Max.   :7.736    
##  NewZealandEnglish AmericanEnglish CanadianEnglish JamaicanEnglish
##  Min.   :5.647     Min.   :3.914   Min.   :2.951   Min.   :1.158  
##  1st Qu.:6.151     1st Qu.:4.276   1st Qu.:3.778   1st Qu.:1.245  
##  Median :6.512     Median :4.522   Median :4.527   Median :1.313  
##  Mean   :6.455     Mean   :4.739   Mean   :4.194   Mean   :1.346  
##  3rd Qu.:6.698     3rd Qu.:4.876   3rd Qu.:4.749   3rd Qu.:1.425  
##  Max.   :7.279     Max.   :6.038   Max.   :4.923   Max.   :1.642  
##  PhillipineEnglish IndianEnglish  
##  Min.   :0.3820    Min.   :0.574  
##  1st Qu.:0.9677    1st Qu.:0.976  
##  Median :1.4880    Median :1.272  
##  Mean   :1.3247    Mean   :1.418  
##  3rd Qu.:1.6098    3rd Qu.:1.799  
##  Max.   :1.9490    Max.   :2.731</code></pre>
<p>As a next step, we create a cluster object based on the data we have just generated.</p>
<pre class="r"><code># clean data
clust &lt;- t(clus)            # transpose data
clust &lt;- na.omit(clust)     # remove missing values
clusts &lt;- scale(clust)      # standardize variables
clusts &lt;- as.matrix(clusts) # convert into matrix
clust</code></pre>
<pre><code>##                   nae_neg  like clefts  tags youse soitwas    dt   nsr invartag
## IrishEnglish        9.827 9.649  9.364 9.569 9.154   9.386 9.004 9.034    9.817
## ScottishEnglish     9.312 8.814  9.359 9.595 9.226   9.535 9.115 9.609    9.562
## BritishEnglish      5.153 7.251  7.648 5.412 6.703   6.239 6.930 6.749    7.085
## AustralianEnglish   6.750 6.243  7.736 6.567 6.440   7.611 6.721 6.086    7.042
## NewZealandEnglish   6.711 6.937  5.647 6.536 7.279   6.658 6.145 6.169    6.488
## AmericanEnglish     4.464 4.801  5.927 4.309 4.265   4.901 3.914 4.580    6.038
## CanadianEnglish     4.652 4.859  2.951 4.923 3.742   3.092 4.781 4.447    3.887
## JamaicanEnglish     1.393 1.642  1.158 1.243 1.328   1.231 1.299 1.251    1.477
## PhillipineEnglish   1.198 0.382  1.949 0.746 1.458   1.920 1.627 1.518    1.558
## IndianEnglish       2.731 2.030  0.912 1.185 0.857   0.574 1.915 1.168    1.452
##                   wh_cleft
## IrishEnglish         9.842
## ScottishEnglish      9.200
## BritishEnglish       7.353
## AustralianEnglish    5.683
## NewZealandEnglish    5.976
## AmericanEnglish      4.193
## CanadianEnglish      4.608
## JamaicanEnglish      1.436
## PhillipineEnglish    0.891
## IndianEnglish        1.360</code></pre>
<p>We now assess if data is clusterable by testing whether or not the data includes nonrandom structures. To means to determine whether the data contains nonrandomness, we calculate the Hopkins statistic which informs how similar the data is to a random distribution. If the values of the Hopkins statistic are higher than 0.5 then this indicates that the data is random and that there are no inherent clusters. However, if the Hopkins statistic is close to 0, then the data is clusterable. The “n” in the “get_clust_tendency” functions represents the maximum number of clusters to be tested which should be number of predictors in the data.</p>
<pre class="r"><code>library(&quot;factoextra&quot;)         # load library to extract cluster tendency
clusttendency &lt;- get_clust_tendency(clusts,    # apply get_clust_tendency to cluster object
                   n = 9,     # define number of points from sampe speace 
                   gradient = list(low = &quot;steelblue&quot;,  # define color for low values 
                                   high = &quot;white&quot;))    # define color for high values
clusttendency[1]</code></pre>
<pre><code>## $hopkins_stat
## [1] 0.737918</code></pre>
<p>As the Hopkins statistic above shows, there is sufficient structure in the data and we can assume that there are actual clusters in the data. Next, we create a distance matrix based on Euclidian distances.</p>
<pre class="r"><code>clustd &lt;- dist(clusts,                 # create distance matrix
               method = &quot;euclidean&quot;)   # use eucledian (!) distance
round(clustd, 2)                       # display distance matrix</code></pre>
<pre><code>##                   IrishEnglish ScottishEnglish BritishEnglish AustralianEnglish
## ScottishEnglish           0.43                                                 
## BritishEnglish            2.98            2.85                                 
## AustralianEnglish         2.89            2.73           1.01                  
## NewZealandEnglish         3.07            2.94           1.07              0.83
## AmericanEnglish           4.83            4.69           2.12              2.05
## CanadianEnglish           5.31            5.19           2.70              2.73
## JamaicanEnglish           8.17            8.04           5.38              5.40
## PhillipineEnglish         8.22            8.07           5.43              5.41
## IndianEnglish             8.08            7.96           5.35              5.34
##                   NewZealandEnglish AmericanEnglish CanadianEnglish
## ScottishEnglish                                                    
## BritishEnglish                                                     
## AustralianEnglish                                                  
## NewZealandEnglish                                                  
## AmericanEnglish                1.97                                
## CanadianEnglish                2.37            1.32                
## JamaicanEnglish                5.16            3.45            2.97
## PhillipineEnglish              5.23            3.48            3.13
## IndianEnglish                  5.09            3.44            2.84
##                   JamaicanEnglish PhillipineEnglish
## ScottishEnglish                                    
## BritishEnglish                                     
## AustralianEnglish                                  
## NewZealandEnglish                                  
## AmericanEnglish                                    
## CanadianEnglish                                    
## JamaicanEnglish                                    
## PhillipineEnglish            0.59                  
## IndianEnglish                0.57              0.95</code></pre>
<p>Below are other methods to cerate distance matrices.</p>
<pre class="r"><code># create distance matrix (eucledian method: not good when dealing with many dimensions)
clustd &lt;- dist(clusts, method = &quot;euclidean&quot;)
# create distance matrix (maximum method: here the difference between points dominates)
clustd_maximum &lt;- round(dist(clusts, method = &quot;maximum&quot;), 2)
# create distance matrix (manhattan method: most popular choice)
clustd_manhatten &lt;- round(dist(clusts, method = &quot;manhattan&quot;), 2) 
# create distance matrix (canberra method: for count data only - focuses on small differences and neglects larger differences)
clustd_canberra &lt;- round(dist(clusts, method = &quot;canberra&quot;), 2)
# create distance matrix (binary method: for binary data only!)
clustd_binary &lt;- round(dist(clusts, method = &quot;binary&quot;), 2) 
# create distance matrix (minkowski method: is not a true distance measure)
clustd_minkowski &lt;- round(dist(clusts, method = &quot;minkowski&quot;), 2) 
# distance method for words: daisy (other possible distances are &quot;manhattan&quot; and &quot;gower&quot;)
library(cluster)
clustd_daisy &lt;- round(daisy(clusts, metric = &quot;euclidean&quot;), 2) </code></pre>
<p>If you call the individual distance matrices, you will see that depending on which distance measure is used, the distance matrices differ dramatically! Have a look at the distance matrix created using the manhatten metric and compare it to the distance matrix created using the Euclidian metric (see above).</p>
<pre class="r"><code>clustd_maximum </code></pre>
<pre><code>##                   IrishEnglish ScottishEnglish BritishEnglish AustralianEnglish
## ScottishEnglish           0.27                                                 
## BritishEnglish            1.56            1.39                                 
## AustralianEnglish         1.30            1.15           0.53                  
## NewZealandEnglish         1.21            1.12           0.61              0.63
## AmericanEnglish           1.79            1.78           1.03              0.96
## CanadianEnglish           1.94            1.96           1.42              1.45
## JamaicanEnglish           2.82            2.73           1.97              1.99
## PhillipineEnglish         2.98            2.73           2.21              1.88
## IndianEnglish             2.67            2.76           2.04              2.14
##                   NewZealandEnglish AmericanEnglish CanadianEnglish
## ScottishEnglish                                                    
## BritishEnglish                                                     
## AustralianEnglish                                                  
## NewZealandEnglish                                                  
## AmericanEnglish                0.95                                
## CanadianEnglish                1.11            0.90                
## JamaicanEnglish                1.88            1.44            1.19
## PhillipineEnglish              2.10            1.42            1.44
## IndianEnglish                  2.02            1.52            1.16
##                   JamaicanEnglish PhillipineEnglish
## ScottishEnglish                                    
## BritishEnglish                                     
## AustralianEnglish                                  
## NewZealandEnglish                                  
## AmericanEnglish                                    
## CanadianEnglish                                    
## JamaicanEnglish                                    
## PhillipineEnglish            0.40                  
## IndianEnglish                0.45              0.53</code></pre>
<p>Next, we create a distance plot using the “distplot” function. If the distance plot shows different regions (non-random, non-uniform grey areas) then clustering the data is permittable as the data contains actual structures.</p>
<pre class="r"><code># load library
library(seriation)
# create distance plot
dissplot(clustd) </code></pre>
<p><img src="groupingstatz_files/figure-html/cl20-1.png" width="672" /></p>
<p>The most common method for clustering is called “ward.D” or “ward.D2”. Both of these linkage functions seek to minimize variance. This means that they cluster in a way that the amount of variance is at a minimum (comparable to the regression line in an <em>ordinary least squares</em> (OLS) design).</p>
<pre class="r"><code># create cluster object
cd &lt;- hclust(clustd, method=&quot;ward.D2&quot;) 
# display dendogram              
plot(cd, hang = -1)              </code></pre>
<p><img src="groupingstatz_files/figure-html/cl21-1.png" width="672" /></p>
<p>We will briefly go over some other, alternative linkage methods. Which linkage method is and should be used depends on various factors, for example, the type of variables (nominal versus numeric) or whether the focus should be placed on commonalities or differences.</p>
<pre class="r"><code># single linkage: cluster with nearest data point
cd_single &lt;- hclust(clustd, method=&quot;single&quot;) 
# create cluster object (ward.D linkage)
cd_wardd &lt;- hclust(clustd, method=&quot;ward.D&quot;)
# create cluster object (ward.D2 linkage): 
# cluster in a way to achieve minimum variance
cd_wardd2 &lt;- hclust(clustd, method=&quot;ward.D2&quot;)
# average linkage: cluster with closest mean
cd_average &lt;- hclust(clustd, method=&quot;average&quot;) 
# mcquitty linkage
cd_mcquitty &lt;- hclust(clustd, method=&quot;mcquitty&quot;) 
# median linkage: cluster with closest median
cd_median &lt;- hclust(clustd, method=&quot;median&quot;)
# centroid linkage: cluster with closest prototypical point of target cluster
cd_centroid &lt;- hclust(clustd, method=&quot;centroid&quot;) 
# complete linkage: cluster with nearest/furthest data point of target cluster
cd_complete &lt;- hclust(clustd, method=&quot;complete&quot;)  </code></pre>
<p>Now, we determine the optimal number of clusters based on silhouette widths which shows the ratio of internal similarity of clusters against the similarity between clusters. If the silhouette widths have values lower than .2 then this indicates that clustering is not appropriate <span class="citation">(Levshina <a href="#ref-levshina2015linguistics" role="doc-biblioref">2015</a>, 311)</span>. The function below displays the silhouette width values of 2 to 8 clusters.</p>
<pre class="r"><code>optclus &lt;- sapply(2:8, function(x) summary(silhouette(cutree(cd, k = x), clustd))$avg.width)
optclus # inspect results</code></pre>
<pre><code>## [1] 0.5749136 0.6291383 0.6640209 0.5570907 0.4405094 0.2534828 0.2111441</code></pre>
<pre class="r"><code>optnclust &lt;- which(optclus == max(optclus)) # determine optimal number of clusters
groups &lt;- cutree(cd, k=optnclust) # cut tree into optimal number of clusters</code></pre>
<p>The optimal number of clusters is the cluster solution with the highest silhouette width. We cut the tree into the optimal number of clusters and plot the result.</p>
<pre class="r"><code>groups &lt;- cutree(cd, k=optnclust)          # cut tree into optimal clusters
plot(cd, hang = -1, cex = .75)             # plot result as dendrogram
rect.hclust(cd, k=optnclust, border=&quot;red&quot;) # draw red borders around clusters</code></pre>
<p><img src="groupingstatz_files/figure-html/cl24-1.png" width="672" /></p>
<p>In a next step, we aim to determine which factors are particularly important for the clustering - this step is comparable to measuring the effect size in inferential designs.</p>
<pre class="r"><code># which factors are particularly important
celtic &lt;- clusts[c(1,2),]
others &lt;- clusts[-c(1,2),]
# calculate column means
celtic.cm &lt;- colMeans(celtic)
others.cm &lt;- colMeans(others)
# calcualte difference between celtic and other englishes
diff &lt;- celtic.cm - others.cm
sort(diff, decreasing = F)</code></pre>
<pre><code>##   clefts     like    youse  soitwas invartag       dt      nsr wh_cleft 
## 1.550972 1.593405 1.633135 1.648707 1.661453 1.677501 1.738740 1.749675 
##     tags  nae_neg 
## 1.766859 1.818863</code></pre>
<pre class="r"><code>plot(sort(diff),           # y-values
  1:length(diff),       # x-values 
  type= &quot;n&quot;,            # plot type (empty)
  cex.axis = .75,       # axis font size
  cex.lab = .75,        # label font size
  xlab =&quot;Prototypical for Non-Celtic Varieties (Cluster 2) &lt;-----&gt; Prototypical for Celtic Varieties (Cluster 1)&quot;, # x-axis label
  yaxt = &quot;n&quot;,           # no y-axis tick marks
  ylab = &quot;&quot;)            # no y-axis label
text(sort(diff), 1:length(diff), names(sort(diff)), cex = .75) # plot text into plot</code></pre>
<p><img src="groupingstatz_files/figure-html/cl26-1.png" width="672" /></p>
<pre class="r"><code>Outer &lt;- clusts[c(6:8),]     # data of outer circle varieties
Inner &lt;- clusts[-c(6:8),]    # data of inner circle varieties
Outer.cm &lt;- colMeans(Outer)  # column means for outer circle
Inner.cm &lt;- colMeans(Inner)  # column means for inner circle
diff &lt;- Outer.cm - Inner.cm  # difference between inner and outer circle
sort(diff, decreasing = F)   # order difference between inner and outer circle</code></pre>
<pre><code>##         dt    soitwas      youse     clefts    nae_neg        nsr   wh_cleft 
## -0.8883228 -0.8845106 -0.8706870 -0.8306956 -0.8199838 -0.7626418 -0.7350057 
##   invartag       like       tags 
## -0.7328745 -0.6849308 -0.6697043</code></pre>
<pre class="r"><code>plot(                   # start plot
  sort(diff),           # y-values
  1:length(diff),       # x-values 
  type= &quot;n&quot;,            # plot type (empty)
  cex.axis = .75,       # axis font size
  cex.lab = .75,        # label font size
  xlab =&quot;Prototypical for Inner Circle Varieties (Cluster 2) &lt;-----&gt; Prototypical for Outer Circle Varieties (Cluster 1)&quot;, # x-axis label
  yaxt = &quot;n&quot;,           # no y-axis tick marks
  ylab = &quot;&quot;)            # no y-axis label
text(sort(diff), 1:length(diff), names(sort(diff)), cex = .75) # plot text into plot</code></pre>
<p><img src="groupingstatz_files/figure-html/cl28-1.png" width="672" /></p>
<p>We see that discourse <em>like</em> is typical for other varieties and that the use of <em>youse</em> as 2<sup>nd</sup> person plural pronoun and invariant tags are typical for Celtic Englishes.</p>
<p>We will now test whether the cluster is justified by validating the cluster solution using bootstrapping.</p>
<pre class="r"><code>library(pvclust) # activate library
res.pv &lt;- pvclust(clus,                     # apply pvclust method to clus data
                  method.dist=&quot;euclidean&quot;,  # use eucledian distance
                  method.hclust=&quot;ward.D2&quot;,  # use ward.d2 linkage
                  nboot = 100)              # use 100 bootstrap runs</code></pre>
<pre><code>## Bootstrap (r = 0.5)... Done.
## Bootstrap (r = 0.6)... Done.
## Bootstrap (r = 0.7)... Done.
## Bootstrap (r = 0.8)... Done.
## Bootstrap (r = 0.9)... Done.
## Bootstrap (r = 1.0)... Done.
## Bootstrap (r = 1.1)... Done.
## Bootstrap (r = 1.2)... Done.
## Bootstrap (r = 1.3)... Done.
## Bootstrap (r = 1.4)... Done.</code></pre>
<p>The clustering provides approximately unbiased p-values and bootstrap probability value <span class="citation">(see <span class="citeproc-not-found" data-reference-id="levlevshina2015linguistics"><strong>???</strong></span>)</span>.</p>
<pre class="r"><code>plot(res.pv, 
     cex = .75)
pvrect(res.pv)</code></pre>
<p><img src="groupingstatz_files/figure-html/cl30-1.png" width="672" /></p>
<p>We can alsouse other libraries to customize the dendrograms.</p>
<pre class="r"><code>library(ape)            # load package ape
plot(as.phylo(cd),      # plot cluster object
     cex = 0.75,        # .75 font size
     label.offset = .5) # .5 label offset</code></pre>
<p><img src="groupingstatz_files/figure-html/cl31-1.png" width="672" /></p>
<p>One useful customization is to display an unrooted rather than a rooted tree diagram.</p>
<pre class="r"><code># plot as unrooted tree
plot(as.phylo(cd),      # plot cluster object
     type = &quot;unrooted&quot;, # plot as unrooted tree
     cex = .75,         # .75 font size
     label.offset = 1)  # .5 label offset</code></pre>
<p><img src="groupingstatz_files/figure-html/cl32-1.png" width="672" /></p>
</div>
<div id="cluster-analysis-on-nominal-data" class="section level2 unnumbered">
<h2>Cluster Analysis on Nominal Data</h2>
<p>So far, all analyses were based on numeric data. However, especially when working with language data, the data is nominal or categorical rather than numeric. The following will thus show to implement a clustering method for nominal data.</p>
<p>In a first step, we will create a simple data set representing the presence and absence of features across varities of English.</p>
<pre class="r"><code># generate data
IrishEnglish &lt;- c(1,1,1,1,1,1,1,1,1,1)
ScottishEnglish &lt;- c(1,1,1,1,1,1,1,1,1,1)
BritishEnglish &lt;- c(0,1,1,1,0,0,1,0,1,1)
AustralianEnglish &lt;- c(0,1,1,1,0,0,1,0,1,1)
NewZealandEnglish &lt;- c(0,1,1,1,0,0,1,0,1,1)
AmericanEnglish &lt;- c(0,1,1,1,0,0,0,0,1,0)
CanadianEnglish &lt;- c(0,1,1,1,0,0,0,0,1,0)
JamaicanEnglish &lt;- c(0,0,1,0,0,0,0,0,1,0)
PhillipineEnglish &lt;- c(0,0,1,0,0,0,0,0,1,0)
IndianEnglish &lt;- c(0,0,1,0,0,0,0,0,1,0)
clus &lt;- data.frame(IrishEnglish, ScottishEnglish, BritishEnglish, 
                   AustralianEnglish, NewZealandEnglish, AmericanEnglish, 
                   CanadianEnglish, JamaicanEnglish, PhillipineEnglish, IndianEnglish)
# add row names
rownames(clus) &lt;- c(&quot;nae_neg&quot;, &quot;like&quot;, &quot;clefts&quot;, &quot;tags&quot;, &quot;youse&quot;, &quot;soitwas&quot;, &quot;dt&quot;, &quot;nsr&quot;, &quot;invartag&quot;, &quot;wh_cleft&quot;)
# convert into factors
clus &lt;- apply(clus, 1, function(x){
  x &lt;- as.factor(x) })
# inspect data
clus</code></pre>
<pre><code>##                   nae_neg like clefts tags youse soitwas dt  nsr invartag
## IrishEnglish      &quot;1&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;1&quot;   &quot;1&quot;     &quot;1&quot; &quot;1&quot; &quot;1&quot;     
## ScottishEnglish   &quot;1&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;1&quot;   &quot;1&quot;     &quot;1&quot; &quot;1&quot; &quot;1&quot;     
## BritishEnglish    &quot;0&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;0&quot;   &quot;0&quot;     &quot;1&quot; &quot;0&quot; &quot;1&quot;     
## AustralianEnglish &quot;0&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;0&quot;   &quot;0&quot;     &quot;1&quot; &quot;0&quot; &quot;1&quot;     
## NewZealandEnglish &quot;0&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;0&quot;   &quot;0&quot;     &quot;1&quot; &quot;0&quot; &quot;1&quot;     
## AmericanEnglish   &quot;0&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;0&quot;   &quot;0&quot;     &quot;0&quot; &quot;0&quot; &quot;1&quot;     
## CanadianEnglish   &quot;0&quot;     &quot;1&quot;  &quot;1&quot;    &quot;1&quot;  &quot;0&quot;   &quot;0&quot;     &quot;0&quot; &quot;0&quot; &quot;1&quot;     
## JamaicanEnglish   &quot;0&quot;     &quot;0&quot;  &quot;1&quot;    &quot;0&quot;  &quot;0&quot;   &quot;0&quot;     &quot;0&quot; &quot;0&quot; &quot;1&quot;     
## PhillipineEnglish &quot;0&quot;     &quot;0&quot;  &quot;1&quot;    &quot;0&quot;  &quot;0&quot;   &quot;0&quot;     &quot;0&quot; &quot;0&quot; &quot;1&quot;     
## IndianEnglish     &quot;0&quot;     &quot;0&quot;  &quot;1&quot;    &quot;0&quot;  &quot;0&quot;   &quot;0&quot;     &quot;0&quot; &quot;0&quot; &quot;1&quot;     
##                   wh_cleft
## IrishEnglish      &quot;1&quot;     
## ScottishEnglish   &quot;1&quot;     
## BritishEnglish    &quot;1&quot;     
## AustralianEnglish &quot;1&quot;     
## NewZealandEnglish &quot;1&quot;     
## AmericanEnglish   &quot;0&quot;     
## CanadianEnglish   &quot;0&quot;     
## JamaicanEnglish   &quot;0&quot;     
## PhillipineEnglish &quot;0&quot;     
## IndianEnglish     &quot;0&quot;</code></pre>
<p>Now that we have our data, we will create a distance matrix but in contrast to previous methods, we will use a different distance measure that takes into account that we are dealing with nominal (or binary) data.</p>
<pre class="r"><code># clean data
clusts &lt;- as.matrix(clus)
# create distance matrix
clustd &lt;- dist(clusts, method = &quot;binary&quot;)   # create a distance object with binary (!) distance
# display distance matrix
round(clustd, 2)</code></pre>
<pre><code>##                   IrishEnglish ScottishEnglish BritishEnglish AustralianEnglish
## ScottishEnglish           0.00                                                 
## BritishEnglish            0.40            0.40                                 
## AustralianEnglish         0.40            0.40           0.00                  
## NewZealandEnglish         0.40            0.40           0.00              0.00
## AmericanEnglish           0.60            0.60           0.33              0.33
## CanadianEnglish           0.60            0.60           0.33              0.33
## JamaicanEnglish           0.80            0.80           0.67              0.67
## PhillipineEnglish         0.80            0.80           0.67              0.67
## IndianEnglish             0.80            0.80           0.67              0.67
##                   NewZealandEnglish AmericanEnglish CanadianEnglish
## ScottishEnglish                                                    
## BritishEnglish                                                     
## AustralianEnglish                                                  
## NewZealandEnglish                                                  
## AmericanEnglish                0.33                                
## CanadianEnglish                0.33            0.00                
## JamaicanEnglish                0.67            0.50            0.50
## PhillipineEnglish              0.67            0.50            0.50
## IndianEnglish                  0.67            0.50            0.50
##                   JamaicanEnglish PhillipineEnglish
## ScottishEnglish                                    
## BritishEnglish                                     
## AustralianEnglish                                  
## NewZealandEnglish                                  
## AmericanEnglish                                    
## CanadianEnglish                                    
## JamaicanEnglish                                    
## PhillipineEnglish            0.00                  
## IndianEnglish                0.00              0.00</code></pre>
<p>As before, we can now use hierarchical clustering to display the results as a dendrogram</p>
<pre class="r"><code># create cluster object (ward.D2 linkage)   : cluster in a way to achieve minimum variance
cd &lt;- hclust(clustd, method=&quot;ward.D2&quot;)
# plot result as dendrogram
plot(cd, hang = -1)              # display dendogram</code></pre>
<p><img src="groupingstatz_files/figure-html/cl35-1.png" width="672" /></p>
<p>In a next step, we want to determine which features are particularly distinctive for one cluster (the “Celtic” cluster containing Irish and Scottish English).</p>
<pre class="r"><code># create factor with celtic varieties on one hand and other varieties on other
cluster &lt;- as.factor(ifelse(as.character(rownames(clusts)) == &quot;IrishEnglish&quot;, &quot;1&quot;,
  ifelse(as.character(rownames(clusts)) == &quot;ScottishEnglish&quot;, &quot;1&quot;, &quot;0&quot;)))
# load library
library(vcd)
clsts.df &lt;- as.data.frame(clusts)
# determine significance
library(exact2x2)
pfish &lt;- fisher.exact(table(cluster, clsts.df$youse))
pfish[[1]]</code></pre>
<pre><code>## [1] 0.02222222</code></pre>
<pre class="r"><code># determine effect size
assocstats(table(cluster, clsts.df$youse))</code></pre>
<pre><code>##                     X^2 df  P(&gt; X^2)
## Likelihood Ratio 10.008  1 0.0015586
## Pearson          10.000  1 0.0015654
## 
## Phi-Coefficient   : 1 
## Contingency Coeff.: 0.707 
## Cramer&#39;s V        : 1</code></pre>
<pre class="r"><code>assocstats(table(cluster, clsts.df$like))</code></pre>
<pre><code>##                     X^2 df P(&gt; X^2)
## Likelihood Ratio 1.6323  1  0.20139
## Pearson          1.0714  1  0.30062
## 
## Phi-Coefficient   : 0.327 
## Contingency Coeff.: 0.311 
## Cramer&#39;s V        : 0.327</code></pre>
<p>Clustering is a highly complex topic and there many more complexities to it. However, this should have helped to get you started.</p>
</div>
</div>
<div id="correspondence-analysis" class="section level1">
<h1><span class="header-section-number">2</span> Correspondence Analysis</h1>
<p>Correspondence analysis (CA) represents a multivariate statistical technique that provides a graphic method of exploring the relationship between variables in a contingency table. CA is conceptually similar to principal component analysis (PCA), but applies to categorical rather than continuous data.</p>
<p>CA consists out of the following four steps:</p>
<ol style="list-style-type: decimal">
<li>Computing row and column averages</li>
<li>Computing expected values</li>
<li>Computing the residuals</li>
<li>Plotting residuals</li>
</ol>
<p>In this tutorial, we investigate similarities among amplifiers based on their co-occurrences (word embeddings) with adjectives. Adjective amplifiers are elements such as those in 1. to 5.</p>
<ol style="list-style-type: decimal">
<li>The <em>very</em><sub>amplifier</sub> <em>nice</em><sub>adjective</sub> man.</li>
<li>A <em>truely</em><sub>amplifier</sub> <em>remarkable</em><sub>adjective</sub> woman.</li>
<li>He was <em>really</em><sub>amplifier</sub> <em>hesitant</em><sub>adjective</sub>.</li>
<li>The child was <em>awefully</em><sub>amplifier</sub> <em>loud</em><sub>adjective</sub>.</li>
<li>The festival was <em>so</em><sub>amplifier</sub> <em>amazing</em><sub>adjective</sub>!</li>
</ol>
<p>The similarity among adjective amplifiers can then be used to find clusters or groups of amplifiers that <em>behave</em> similarly and are interchangeable. To elaborate, adjective amplifiers are interchangeable with some variants but not with others (consider 6. to 8.; the question mark signifies that the example is unlikely to be used or grammatically not acceptable by L1 speakers of English).</p>
<ol start="6" style="list-style-type: decimal">
<li>The <em>very</em><sub>amplifier</sub> <em>nice</em><sub>adjective</sub> man.</li>
<li>The <em>really</em><sub>amplifier</sub> <em>nice</em><sub>adjective</sub> man.</li>
<li><sup>?</sup>The <em>completely</em><sub>amplifier</sub> <em>nice</em><sub>adjective</sub> man.</li>
</ol>
<p>We start by loading the required packages, the data, and then displaying the data which is called “vsmdata” and consist of 5,000 observations of adjectives and contains two columns: one column with the adjectives (Adjectives) and another column which has the amplifiers (“0” means that the adjective occurred without an amplifier).</p>
<pre class="r"><code># load packages
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(FactoMineR)
library(factoextra)
library(gplots)</code></pre>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:seriation&#39;:
## 
##     bluered, greenred</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<pre class="r"><code>library(DT)
# load data
vsmdata &lt;- read.delim(&quot;https://slcladal.github.io/data/vsmdata.txt&quot;, sep = &quot;\t&quot;, header = T)
# inspect data
datatable(vsmdata, rownames = FALSE, filter=&quot;top&quot;, options = list(pageLength = 5, scrollX=T))</code></pre>
<div id="htmlwidget-144b68f99bdf415447ae" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-144b68f99bdf415447ae">{"x":{"filter":"top","filterHTML":"<tr>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["0","0","so","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","so","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","very","0","0","0","0","really","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","very","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","really","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","bloody","0","0","0","0","0","0","0","really","0","0","so","really","0","0","0","very","0","0","0","0","0","absolutely","0","0","really","0","0","0","really","so","0","0","0","0","0","0","extremely","0","very","very","0","0","0","very","0","0","0","0","so","really","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","particularly","0","0","0","really","extremely","0","0","0","0","really","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","very","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","absolutely","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","really","0","0","so","0","0","really","0","0","very","0","0","very","0","0","0","0","really","0","0","0","0","0","0","0","very","so","very","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","so","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","very","0","0","0","0","0","0","0","0","very","very","0","0","0","0","0","extremely","0","0","very","particularly","0","0","very","0","0","0","0","0","0","0","0","0","0","really","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","very","0","very","very","0","0","0","0","0","0","0","0","0","really","0","very","0","0","0","0","very","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","particularly","0","0","0","0","0","very","so","0","0","0","0","0","0","0","0","0","so","0","0","0","0","really","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","very","0","0","0","0","0","0","so","0","very","real","0","0","0","0","0","0","0","0","0","0","0","0","really","very","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","extraordinarily","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","very","0","0","completely","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","so","0","0","0","0","very","0","0","0","very","0","0","0","0","0","0","0","very","0","0","very","0","0","really","0","0","0","very","0","very","particularly","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","absolutely","0","0","0","0","0","very","0","0","0","0","0","0","real","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","very","0","very","0","0","very","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","really","so","0","0","0","0","very","very","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","very","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","really","totally","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","very","0","0","0","very","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","certainly","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","very","0","0","so","0","0","so","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","very","0","0","enormously","0","0","0","0","0","0","0","0","0","0","0","really","0","really","0","0","0","0","0","0","very","pretty","0","0","0","really","0","0","very","0","0","0","0","really","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","0","0","so","very","0","0","0","0","0","0","0","0","0","0","0","really","very","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","very","0","0","0","0","so","0","0","0","highly","0","0","0","0","really","0","0","0","very","so","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","so","very","0","0","0","0","0","very","so","0","0","0","0","0","0","so","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","very","0","0","0","really","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","so","0","really","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","very","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","very","0","0","0","0","so","pretty","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","so","0","0","very","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","very","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","especially","0","0","0","0","0","0","complete","0","0","pretty","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","really","very","0","0","0","0","0","very","0","0","0","totally","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","really","0","0","very","pretty","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","pretty","0","0","0","0","0","0","0","0","0","0","really","0","0","very","0","really","really","0","pretty","0","0","0","0","0","really","0","0","0","very","0","0","0","0","really","0","0","very","0","0","0","0","0","0","0","0","0","0","0","very","very","0","0","0","0","0","very","0","0","0","0","0","0","very","0","0","0","0","0","extremely","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","amazingly","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","so","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","very","really","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","very","so","0","0","0","0","0","0","very","so","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","very","0","0","0","so","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","very","so","0","0","0","0","0","0","completely","0","0","0","0","so","very","0","0","0","0","completely","0","very","0","0","0","0","very","0","0","very","0","0","0","0","0","very","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","so","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","really","very","0","0","0","0","0","0","0","0","0","0","really","really","0","0","0","very","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","pretty","0","0","0","0","totally","0","0","very","0","0","0","0","0","0","0","0","really","0","0","very","0","0","pretty","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","really","really","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","extremely","very","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","really","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","very","0","0","very","0","0","0","really","0","0","especially","0","0","0","0","0","0","0","0","0","very","0","0","very","0","very","really","very","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","extremely","really","0","0","0","0","0","0","0","0","0","very","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","very","0","0","pretty","0","0","0","0","0","completely","0","0","0","0","0","0","0","0","really","0","0","0","so","0","0","0","very","0","0","0","0","0","0","0","0","really","0","really","0","very","really","so","0","0","0","0","0","really","very","0","0","0","very","0","0","very","0","0","0","0","0","0","very","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","very","0","0","0","0","0","0","0","completely","0","0","0","0","0","very","very","really","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","very","0","0","very","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","totally","0","0","0","0","0","0","0","0","0","0","0","very","so","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","very","pretty","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","completely","0","0","0","0","0","0","0","0","0","0","0","0","so","0","particularly","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","certainly","0","very","0","0","0","0","0","0","0","very","0","0","0","0","particularly","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","so","0","0","0","0","0","0","0","0","0","so","totally","0","0","0","0","0","0","0","0","0","0","0","pretty","very","0","0","very","0","0","0","0","0","0","absolute","0","0","very","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","very","0","real","0","0","0","0","0","0","0","very","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","really","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","so","0","0","very","very","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","so","0","0","0","0","really","0","0","0","very","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","so","0","0","0","0","very","0","so","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","very","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","totally","0","0","0","0","0","0","so","0","0","very","really","0","0","0","0","0","0","0","0","0","0","0","0","0","so","very","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","really","0","0","very","0","very","0","very","0","0","actually","0","0","0","so","0","0","0","0","0","0","so","0","so","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","really","0","0","0","0","0","0","0","0","0","awfully","0","0","0","0","really","0","0","really","0","0","0","so","pretty","0","0","0","0","0","0","0","0","0","0","0","0","0","very","very","very","0","0","0","0","0","so","very","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","so","extremely","0","0","0","0","0","0","pretty","0","very","0","0","0","0","0","very","really","0","really","0","0","0","0","0","0","completely","0","0","0","very","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","dead","0","very","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","very","0","0","0","0","0","0","0","0","very","0","0","0","pretty","so","0","0","0","0","0","0","0","so","very","0","0","0","0","0","so","0","0","0","really","0","0","very","0","0","0","very","0","0","0","0","0","0","0","0","very","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","very","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","so","0","0","0","0","0","0","0","0","0","very","0","0","very","0","0","0","0","0","0","0","very","real","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","absolutely","0","0","0","0","0","0","so","really","0","0","0","very","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","bloody","0","very","0","0","0","0","so","so","0","really","0","0","0","0","0","0","0","0","very","0","0","0","0","very","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","absolutely","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","very","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","so","very","really","0","0","0","very","0","very","0","0","0","very","0","0","0","0","0","0","very","0","0","0","0","so","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","very","0","0","0","0","0","0","0","abundantly","0","so","very","really","0","0","0","0","0","0","0","very","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","purely","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","very","0","0","particularly","0","0","0","0","0","pretty","very","0","0","0","0","0","0","0","0","0","0","0","0","extremely","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","so","0","very","0","0","0","0","0","0","0","pretty","0","0","0","0","0","very","0","0","0","0","very","0","very","0","0","0","0","0","0","0","really","0","0","pretty","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","really","0","0","very","0","0","0","0","0","very","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","so","0","0","0","0","0","0","0","0","0","0","very","0","very","0","0","0","so","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","really","0","0","0","0","0","0","0","0","very","0","very","0","0","0","0","0","0","0","0","0","0","0","very","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","pretty","0","0"],["serious","sure","many","many","good","much","good","good","last","nice","competitive","simple","good","good","small","sad","real","new","big","many","comfortable","hard","new","new","great","last","many","total","good","big","strong","clear","new","real","last","big","strong","many","like","long","bad","easy","much","much","different","nice","long","big","useful","serious","fantastic","dominant","good","expensive","old","serious","old","lucky","original","little","dark","last","comfortable","last","much","good","late","long","large","new","sure","last","last","bad","wrong","simple","sure","last","real","big","little","obvious","healthy","different","sure","small","strong","slow","bloody","friendly","nice","hot","exciting","little","lucky","same","bad","large","weak","different","relevant","many","long","last","sure","great","same","little","weak","strong","open","much","aware","open","deep","little","good","last","same","last","young","last","second","good","interesting","high","special","last","young","early","dark","keen","last","last","important","different","funny","obvious","bad","fantastic","little","bad","high","great","last","much","same","high","real","real","little","comfortable","last","interested","many","many","large","new","bloody","bad","great","many","last","aggressive","great","good","stupid","sure","great","little","little","much","same","great","wrong","open","hard","little","many","early","true","last","bad","great","good","last","real","hard","nervous","wonderful","different","great","small","last","funny","last","nice","different","middle","deep","hard","good","old","same","last","real","similar","little","special","same","nice","total","interested","effective","little","many","simple","little","sure","last","nice","big","many","little","good","real","hard","dark","good","much","last","like","nice","high","second","many","good","hot","obvious","great","old","clear","funny","wonderful","good","good","fantastic","good","many","different","same","wrong","little","easy","little","big","real","long","same","last","serious","difficult","long","difficult","happy","second","clever","big","long","new","many","long","last","prominent","good","happy","much","second","simple","early","hard","last","serious","sorry","young","great","bad","important","last","hard","big","sensitive","real","much","tough","high","great","much","good","like","last","last","same","new","last","much","many","early","same","sure","new","similar","last","open","significant","bad","small","second","big","difficult","good","many","second","beautiful","many","vivid","last","same","long","good","small","same","much","little","middle","good","little","great","last","little","good","real","little","good","nice","difficult","new","different","real","hard","grateful","different","smooth","relevant","great","good","small","green","old","many","late","good","good","little","sure","second","second","sorry","genuine","early","much","cold","funny","sure","great","same","old","second","hard","new","last","strong","real","long","young","like","clear","hot","little","great","second","same","aware","different","good","little","interesting","little","important","sad","different","old","small","long","little","sure","many","true","slow","sure","like","many","many","wide","interesting","old","great","wonderful","wrong","great","good","much","good","big","little","many","little","friendly","much","sad","real","little","same","great","beautiful","difficult","beautiful","bad","slow","dangerous","great","competitive","difficult","important","open","special","relevant","last","little","serious","aware","important","small","old","small","obvious","same","high","different","real","good","interesting","open","aggressive","like","good","last","old","real","different","real","small","last","last","much","new","dangerous","great","little","small","hard","sure","good","significant","high","important","angry","nice","real","bad","quiet","green","serious","old","little","important","long","much","small","open","sad","wrong","high","long","easy","high","difficult","different","interesting","pleased","important","little","long","bad","same","good","bad","lucky","old","long","easy","new","real","same","large","light","new","difficult","little","economic","big","many","nice","new","many","difficult","real","sure","second","hard","stupid","new","great","last","same","good","good","odd","aggressive","interesting","old","many","same","same","good","good","simple","long","high","happy","clear","economic","important","interesting","aware","bloody","good","new","little","little","hectic","same","important","sure","little","exciting","important","many","little","large","bad","good","special","dangerous","little","little","little","last","old","last","cool","like","same","new","many","obvious","late","green","new","small","good","wrong","clear","bad","busy","good","much","long","strict","nice","sure","much","little","good","long","small","large","little","real","high","last","true","new","total","bloody","economic","different","great","large","different","tough","great","similar","aggressive","second","old","last","many","different","little","difficult","cold","aware","last","many","economic","many","nice","stupid","interesting","new","big","big","second","little","bad","little","true","expensive","long","big","great","friendly","sure","much","young","big","many","last","same","big","good","little","little","popular","young","little","happy","aware","real","sure","quick","much","same","last","little","new","aware","second","basic","sure","appropriate","great","many","small","good","wrong","bad","young","strong","little","young","little","great","new","relevant","great","open","same","real","old","different","strong","open","economic","same","long","wonderful","effective","long","new","wide","great","big","nice","obvious","true","second","little","interested","many","sure","much","last","good","interesting","basic","long","big","great","old","little","strong","sure","stupid","same","large","new","second","hard","long","much","early","little","many","high","sure","great","last","sure","familiar","small","long","same","young","last","important","conscious","prominent","old","low","special","little","easy","big","green","pleased","glad","sure","little","true","sure","open","open","good","quiet","serious","angry","professional","angry","healthy","different","bad","new","big","sure","low","good","last","effective","nice","different","many","expensive","many","real","sure","sad","bright","little","long","effective","new","long","last","bloody","sure","new","comfortable","many","last","many","big","strong","similar","effective","wonderful","second","effective","new","obvious","same","interesting","last","wide","economic","nice","wrong","good","second","sure","effective","clear","good","last","strong","good","relevant","large","good","open","good","old","big","same","good","real","different","good","good","nice","last","cold","bad","real","last","serious","old","important","new","little","open","real","last","nice","strong","many","big","many","second","great","different","good","sure","last","new","little","last","hectic","difficult","dangerous","important","lucky","little","beautiful","same","old","nice","important","little","good","aware","different","relevant","busy","little","beautiful","heavy","new","good","young","healthy","hard","good","cold","bad","little","new","old","difficult","good","small","high","special","real","great","little","good","little","happy","same","difficult","much","old","old","last","good","original","sure","small","true","big","good","deep","slow","long","interested","sure","special","different","hard","bright","much","many","little","dark","young","high","many","many","nice","new","same","comprehensive","obvious","good","clear","many","cold","second","little","hard","good","different","good","new","great","nice","last","last","long","wonderful","big","sorry","happy","high","wide","little","last","new","strange","bad","good","sure","hard","much","different","high","second","second","little","early","much","large","high","little","big","close","interested","new","new","nice","much","little","last","large","big","sure","nice","expensive","good","second","same","different","long","good","like","same","last","good","little","significant","proud","last","many","big","nice","much","wonderful","great","little","sorry","good","aware","new","different","familiar","little","many","second","dangerous","different","little","strong","last","high","green","little","long","little","aware","second","effective","busy","long","old","wrong","little","last","large","important","same","clear","good","stupid","old","long","last","basic","good","sure","open","second","last","great","wrong","last","sure","true","careful","many","little","good","good","little","good","last","good","strong","big","wonderful","small","funny","big","small","late","new","quick","bad","same","big","last","strong","useful","bloody","strong","same","real","same","quick","high","last","same","happy","good","similar","long","difficult","sure","little","last","new","high","big","last","new","like","like","little","good","deep","many","many","good","last","good","last","good","nice","same","interesting","fantastic","wide","old","little","difficult","early","second","sorry","stupid","green","bloody","strong","little","deep","good","great","new","good","good","fantastic","wrong","interesting","strong","many","early","close","little","bloody","good","good","big","big","like","different","hard","good","good","great","many","last","good","good","old","last","different","funny","same","last","real","last","green","important","sorry","nice","sure","real","fantastic","good","odd","popular","new","cool","deep","easy","obvious","same","good","strange","interesting","great","little","hard","wrong","big","important","last","same","great","significant","bad","small","small","strong","little","last","sorry","sure","easy","unrelated","small","competitive","funny","different","late","old","great","new","last","different","strong","dark","masculine","same","hot","last","quick","long","sure","high","much","big","good","big","odd","much","wide","last","great","sure","last","old","sure","good","little","much","true","interested","stupid","expensive","lucky","professional","old","big","small","many","good","good","many","last","long","important","bad","new","last","bloody","little","difficult","middle","new","same","excited","beautiful","sorry","large","difficult","hard","same","same","nice","special","old","nice","difficult","light","last","good","interesting","big","new","good","total","sure","much","total","heavy","old","bad","economic","big","special","old","open","sure","old","keen","significant","young","last","important","different","bad","nice","little","new","economic","dark","green","little","special","last","difficult","open","deep","real","big","much","last","good","real","special","new","small","dark","good","slow","long","low","happy","interesting","important","big","little","second","special","great","beautiful","little","genuine","wonderful","original","popular","good","sorry","new","significant","little","different","last","bad","real","hot","old","little","little","new","different","different","much","big","same","many","appropriate","professional","funny","loud","new","second","great","appropriate","good","dark","different","good","long","new","same","early","early","sure","large","last","happy","long","interesting","good","small","last","many","wonderful","great","high","different","new","long","big","early","new","late","big","long","bloody","true","dangerous","difficult","serious","happy","cold","disappointing","cold","heavy","difficult","interesting","many","high","cold","hard","total","reluctant","like","low","little","small","hot","appropriate","good","last","real","second","important","appropriate","hot","little","keen","new","good","little","good","last","different","large","high","great","good","great","good","true","great","strong","good","useful","real","last","good","much","wonderful","last","old","large","real","odd","old","much","many","strong","sure","dark","good","good","sure","good","old","good","heavy","bloody","many","big","important","little","high","aware","big","great","nervous","high","busy","economic","big","good","same","wonderful","interested","big","strong","little","economic","familiar","real","like","long","open","old","little","little","old","dark","small","open","interesting","different","much","aware","slow","quiet","new","strange","same","good","deep","strong","noticeable","difficult","important","last","many","second","old","same","idealistic","small","sure","obvious","different","big","second","high","important","good","many","same","long","different","same","green","different","little","last","second","much","hot","little","little","tough","little","long","long","second","interesting","popular","hard","long","last","second","last","true","dangerous","old","expensive","many","clear","long","easy","good","little","good","difficult","close","new","good","like","long","obvious","little","long","great","expensive","sure","good","open","much","early","hard","old","real","sorry","aware","good","fantastic","clear","high","wide","same","old","busy","little","good","small","much","aware","last","same","happy","many","large","bad","new","many","quiet","lucky","open","sure","strange","same","large","last","good","sure","sure","economic","low","good","good","great","little","nice","strange","difficult","little","great","good","nice","important","clear","early","good","happy","new","similar","big","conscious","great","strong","strong","clear","simple","nice","difficult","happy","many","last","great","busy","little","aggressive","dark","fantastic","second","tough","nice","true","nervous","new","new","little","same","aggressive","aware","different","fantastic","much","heavy","many","different","new","much","little","clear","important","different","difficult","sorry","much","old","high","different","many","high","many","many","second","little","interested","like","good","special","sure","high","small","cold","old","sure","special","exciting","little","many","old","little","useful","prominent","many","big","middle","good","comfortable","last","useful","strange","bloody","odd","good","large","effective","tough","open","open","homesick","good","new","significant","last","bloody","small","quick","big","little","strong","high","vulnerable","heavy","new","similar","strange","great","open","young","big","total","last","bad","many","dominant","little","open","significant","hard","same","wide","little","clear","sure","weird","sure","bad","wrong","dangerous","wonderful","sure","wide","second","new","new","different","tough","old","cool","weak","funny","little","nice","little","same","good","good","small","large","open","little","expensive","dominant","different","high","different","total","comfortable","last","comfortable","new","little","important","sure","good","young","busy","wonderful","bad","interesting","cold","real","big","big","easy","little","little","early","similar","dark","important","little","different","obvious","wide","long","interesting","good","different","interested","easy","great","easy","professional","nice","dangerous","professional","cold","light","new","old","good","strong","much","good","exciting","small","last","clear","new","old","big","late","great","nice","last","many","young","interesting","sure","last","big","same","happy","great","many","much","economic","different","second","similar","true","little","second","same","great","strong","good","important","last","new","effective","big","beautiful","different","last","beautiful","middle","long","healthy","good","second","little","last","second","happy","old","difficult","open","last","long","popular","little","sorry","many","original","stupid","young","old","nice","little","little","new","same","much","same","last","wide","big","little","keen","old","nice","serious","stupid","different","high","stupid","glad","new","good","pleased","close","big","bloody","different","wonderful","relevant","old","nice","many","nice","different","old","wonderful","much","small","young","same","nice","like","big","great","popular","long","sure","good","new","appropriate","small","interesting","much","hard","second","good","much","sure","quiet","different","little","new","last","wonderful","long","same","stupid","much","real","beautiful","wrong","second","same","long","sure","sure","aware","last","different","beautiful","good","new","different","like","clear","genuine","great","second","long","little","sorry","bad","little","many","different","important","low","last","old","easy","young","similar","hard","cold","proud","same","little","same","new","good","good","dark","real","sore","different","little","last","sure","obvious","new","second","many","hard","dark","good","last","little","large","cold","important","much","great","real","little","little","interested","useful","little","simple","long","economic","early","sure","nice","good","big","last","idealistic","keen","little","little","funny","good","important","nice","real","many","little","little","basic","young","sure","great","sorry","late","new","good","last","good","good","different","different","great","good","aware","new","weird","bloody","sorry","long","wrong","many","good","effective","new","smooth","new","good","old","great","last","wide","hard","many","many","different","bad","new","last","important","aggressive","nice","good","true","sensitive","large","nice","original","little","great","cold","small","sorry","exciting","important","new","good","little","long","early","interesting","nice","good","last","aware","bloody","sure","great","long","important","aware","different","pleased","homesick","large","lucky","old","little","cold","second","new","clear","last","long","new","good","interesting","many","wide","last","good","great","many","special","important","last","interesting","green","old","economic","economic","special","odd","large","same","long","hard","good","different","big","genuine","real","special","good","effective","little","same","important","important","difficult","low","clever","good","much","big","close","appropriate","little","real","big","last","little","much","many","bright","good","big","great","old","good","young","open","same","popular","little","many","old","old","many","aware","many","same","difficult","great","sorry","new","many","stupid","total","wrong","interested","bad","dark","strong","good","economic","last","great","same","new","many","good","big","loud","good","sure","great","wrong","open","little","old","bloody","same","nice","little","big","little","wrong","difficult","great","scary","little","little","different","big","great","happy","keen","strict","good","important","little","important","big","glad","many","disappointing","big","many","popular","little","old","hard","many","hard","little","new","different","sure","many","same","wonderful","popular","good","low","familiar","difficult","real","little","old","same","nice","second","last","last","high","easy","great","good","wrong","close","early","bloody","many","small","new","great","same","old","disappointing","last","little","last","easy","large","conscious","great","large","open","little","dumb","last","many","total","new","many","busy","strange","old","much","big","homesick","nice","sorry","stupid","good","hot","difficult","good","bright","new","good","much","different","like","angry","good","young","sure","second","good","same","low","long","same","many","nice","little","great","little","large","large","last","economic","last","happy","economic","genuine","interesting","large","last","great","green","different","good","genuine","tough","last","important","dangerous","good","big","different","large","good","good","old","wonderful","second","sorry","appropriate","little","many","hot","last","open","great","nice","nice","new","different","good","strong","long","different","big","hot","comfortable","true","bad","popular","good","bloody","good","little","serious","wrong","similar","nice","wonderful","different","economic","same","effective","early","same","good","basic","last","different","little","long","sure","effective","sure","high","last","clear","good","important","odd","weird","aware","little","large","different","easy","odd","much","professional","good","many","second","happy","many","important","much","many","old","last","sure","old","old","new","significant","big","real","big","many","tough","many","little","same","wrong","unrelated","many","big","same","much","appropriate","good","much","high","special","much","happy","economic","last","good","last","familiar","little","sure","strong","nice","great","total","easy","expensive","fantastic","healthy","funny","nice","many","like","interested","beautiful","high","sure","strict","many","good","like","happy","new","long","difficult","small","healthy","different","different","large","scary","small","great","wide","great","early","little","second","funny","stupid","much","little","interesting","glad","hard","new","different","dark","new","similar","good","similar","little","open","wrong","interesting","close","last","big","great","different","easy","long","same","relevant","great","sure","much","wonderful","professional","last","basic","last","hard","last","interesting","early","interested","old","clear","good","great","beautiful","same","old","last","good","many","little","good","nice","different","little","dangerous","nervous","good","bad","same","old","real","slow","little","great","long","different","great","important","young","different","little","hot","genuine","low","important","nice","simple","small","tough","many","clever","old","good","second","last","same","last","different","green","new","bad","last","exciting","many","real","good","exciting","many","wonderful","like","sure","reluctant","good","different","different","serious","total","good","new","good","big","same","little","good","stupid","high","new","last","expensive","sure","many","true","green","nice","same","good","heavy","wonderful","real","nice","new","great","small","green","important","hard","little","little","glad","original","large","many","long","high","familiar","clear","long","high","hard","hard","cool","great","little","big","big","same","similar","original","young","important","basic","important","bad","special","difficult","many","long","many","lucky","many","new","big","bad","young","new","different","last","clear","great","little","good","open","big","last","important","small","nice","small","last","bloody","boring","last","second","sorry","good","odd","easy","open","little","little","small","sure","last","exciting","special","long","good","great","different","good","popular","beautiful","new","same","easy","second","last","last","cold","different","hard","interesting","much","young","good","same","important","good","interesting","second","hard","professional","hard","early","little","much","good","different","good","old","happy","beautiful","little","new","interesting","large","funny","big","special","hard","sore","wonderful","wrong","dark","simple","new","important","early","new","open","long","old","many","much","early","old","sorry","big","interested","young","good","much","high","good","little","many","much","small","good","real","new","comfortable","good","deep","new","good","deep","bright","economic","scary","interesting","good","proud","little","much","similar","strong","good","easy","wonderful","conscious","long","easy","strange","different","effective","same","great","new","difficult","many","different","much","nice","good","good","nice","hot","old","great","same","nice","good","tough","different","new","last","last","real","much","busy","high","great","quiet","bad","long","much","great","new","nice","real","little","new","many","much","high","different","funny","good","good","interesting","popular","last","last","early","sure","little","little","same","real","great","real","many","like","high","early","important","little","big","good","great","hard","small","effective","small","new","second","little","old","wonderful","like","long","aware","same","different","serious","young","clear","second","wonderful","little","different","young","aggressive","sure","same","bad","strong","many","heavy","slow","new","many","much","many","odd","little","bad","clever","new","different","good","different","great","many","new","similar","nice","total","easy","young","happy","scary","many","last","same","great","small","happy","close","interesting","interesting","basic","sure","difficult","good","many","low","sure","bad","long","new","same","big","good","happy","little","young","clear","sorry","many","second","good","big","happy","green","original","hot","hot","last","glad","second","new","many","second","easy","popular","much","same","long","good","sure","healthy","analytic","old","hard","little","big","good","good","nice","clear","interesting","many","many","little","green","quick","special","funny","little","total","clear","low","last","aggressive","effective","many","economic","big","hard","old","different","aggressive","cold","old","great","old","many","good","late","good","clear","quick","serious","happy","nice","good","sure","same","old","close","little","last","early","wrong","sure","good","good","little","sad","long","sure","last","second","long","big","little","careful","beautiful","late","much","lucky","good","same","last","big","new","great","many","old","hard","new","quiet","little","important","many","nice","little","new","last","weird","last","heavy","same","strong","same","same","important","old","bad","beautiful","sore","bright","many","young","great","young","last","different","new","real","old","big","sorry","young","big","good","big","last","important","open","hard","cool","effective","comfortable","second","many","interesting","interested","green","effective","good","dangerous","big","popular","green","much","second","bad","hard","big","fantastic","many","many","bloody","relevant","wide","second","last","real","many","sure","different","special","early","great","aware","many","second","great","happy","good","important","young","good","sure","great","early","great","good","different","easy","great","late","different","weird","sorry","same","little","special","true","large","little","new","hot","good","last","big","difficult","bad","little","nice","good","low","bad","important","last","sad","new","young","great","friendly","large","new","same","easy","serious","little","significant","deep","many","much","big","good","expensive","last","high","similar","economic","old","funny","same","same","dangerous","strong","last","real","new","good","quick","last","happy","early","big","old","wrong","strong","bloody","bad","cold","good","slow","great","great","high","wrong","interested","clear","great","interesting","noticeable","good","little","high","vulnerable","little","important","economic","good","old","small","much","difficult","good","high","vivid","dark","hard","long","keen","easy","lucky","important","second","good","high","little","young","sorry","strong","appropriate","second","little","long","sensitive","old","new","simple","last","new","different","good","little","many","different","last","significant","much","same","real","relevant","happy","little","great","familiar","new","last","important","real","last","big","different","beautiful","special","big","same","new","real","good","good","good","many","dark","good","nice","same","true","strange","big","last","hard","same","good","sure","great","early","large","long","clear","last","young","big","second","last","interested","much","long","dangerous","interested","significant","much","nice","close","small","new","interesting","good","beautiful","dumb","new","big","hot","open","much","aware","deep","sure","sure","last","professional","yummy","good","clear","hard","low","same","wonderful","total","much","many","small","angry","like","many","lucky","like","different","cool","strict","old","young","high","hard","different","large","same","good","beautiful","long","many","much","last","different","small","big","high","big","old","funny","much","nice","many","funny","interested","great","important","busy","last","same","long","important","little","last","late","happy","last","nice","dangerous","last","many","little","sorry","vivid","original","many","great","total","bad","strong","much","deep","sure","big","familiar","great","big","good","angry","good","little","nice","little","early","new","little","little","real","great","second","new","clever","important","many","stupid","little","special","last","much","last","great","true","much","many","same","lucky","good","sure","last","last","important","important","second","great","professional","last","cold","lucky","last","much","little","much","true","same","important","new","second","great","strong","good","happy","weird","difficult","nice","real","last","great","high","aggressive","low","last","last","easy","easy","special","close","little","big","real","different","important","new","good","last","young","last","wide","different","real","funny","proud","real","wrong","long","healthy","small","middle","long","second","wrong","important","long","competitive","bad","economic","large","sore","good","last","much","primitive","good","last","hot","little","lucky","same","little","open","weak","little","great","aware","good","little","busy","little","same","hot","low","good","new","true","great","little","little","good","second","last","second","strong","real","second","hard","little","young","many","good","new","important","open","same","important","similar","large","young","high","last","hard","second","early","last","total","simple","good","special","sure","good","last","new","last","appropriate","same","inaccessible","good","happy","large","little","last","hot","open","many","old","many","old","big","many","good","last","hot","second","high","different","popular","real","old","like","young","many","long","happy","sorry","sure","many","little","small","different","second","small","little","serious","many","loud","strange","good","same","happy","good","old","bad","good","different","important","real","boring","second","little","much","little","great","sure","good","easy","big","same","interesting","careful","pleased","sore","serious","last","good","little","lucky","sure","important","great","basic","big","new","same","appropriate","long","difficult","total","little","interested","sure","exciting","long","high","effective","bloody","special","scary","aggressive","big","many","great","little","little","total","great","appropriate","boring","great","much","different","real","good","real","open","second","special","similar","last","many","second","little","different","strong","much","new","new","dangerous","aware","middle","high","second","easy","sure","great","serious","interesting","sure","little","open","new","big","little","significant","interesting","big","different","new","strong","same","wrong","real","new","different","big","sure","bad","total","cool","interesting","basic","last","interested","long","second","good","long","great","same","middle","many","cool","wide","serious","good","sure","different","low","cold","good","interesting","many","cold","old","last","aware","angry","last","great","like","wrong","long","hard","early","hard","important","new","much","bad","much","great","much","vulnerable","good","long","difficult","same","good","great","real","many","many","low","difficult","true","relevant","new","good","important","large","nice","new","true","different","good","last","economic","same","total","different","last","busy","like","real","last","young","friendly","interested","good","nice","great","long","good","small","dark","easy","little","fantastic","many","last","aggressive","strange","quiet","last","aware","young","good","good","open","hard","nice","sad","good","last","serious","important","great","happy","little","last","great","good","wrong","dark","old","glad","much","real","long","many","great","nice","great","old","many","serious","different","high","old","great","great","little","sure","last","much","special","little","wonderful","little","big","important","important","old","good","like","many","relevant","many","same","economic","different","last","similar","true","clear","last","low","much","appropriate","happy","good","important","little","interesting","big","little","economic","different","old","middle","big","good","small","special","early","big","long","young","sure","great","nice","clear","real","glad","big","big","lucky","much","nice","special","new","popular","big","small","little","interesting","last","cold","young","last","little","good","many","special","long","good","good","simple","hard","good","aware","much","great","economic","last","good","much","real","similar","simple","great","much","wonderful","last","big","same","wrong","difficult","economic","true","economic","last","many","little","great","many","good","high","old","little","happy","same","different","sore","sorry","hard","new","open","different","many","real","last","good","bad","new","last","special","bloody","old","big","good","total","big","second","busy","young","good","like","open","early","simple","true","economic","early","cold","genuine","happy","last","hard","good","much","little","strong","last","green","wrong","long","effective","much","strong","good","different","many","wrong","clear","many","odd","interesting","genuine","difficult","young","large","good","great","last","obvious","good","strong","second","high","significant","same","cold","different","exciting","interesting","little","happy","same","little","clear","nice","same","same","little","real","high","good","long","great","same","serious","many","good","much","new","sure","serious","clear","true","similar","little","good","like","great","good","hard","new","little","little","great","little","quiet","big","good","many","last","strange","important","wrong","good","second","good","economic","sure","late","strange","wide","little","young","great","last","good","little","high","good","last","little","good","last","total","same","hot","simple","vulnerable","many","good","many","last","many","bad","little","little","little","large","same","different","vulnerable","new","interesting","happy","many","second","large","big","wrong","vivid","high","good","proud","little","great","last","same","good","new","nice","same","new","high","appropriate","same","bloody","big","large","high","good","good","bad","bad","large","funny","many","new","old","good","real","bad","much","different","old","stupid","important","significant","last","competitive","sorry","great","same","wrong","young","sure","good","new","last","great","bad","many","funny","many","second","much","great","sure","aggressive","cold","old","last","last","interesting","good","interesting","hard","genuine","same","special","low","proud","large","real","quick","nice","good","aware","large","long","last","little","important","angry","young","old","like","wide","good","good","sure","real","new","hot","good","long","good","competitive","big","new","new","little","much","difficult","relevant","last","last","old","large","second","last","many","great","funny","happy","same","significant","bad","last","last","difficult","easy","young","smooth","little","wrong","different","little","clear","hot","economic","hot","hot","good","old","interested","easy","last","last","old","hard","much","many","good","sure","good","important","nice","real","little","conscious","little","great","long","good","old","early","exciting","funny","different","same","small","interesting","real","sore","last","clear","sure","much","much","new","hot","young","wrong","little","second","real","last","second","competitive","hard","large","last","same","great","significant","great","sure","last","bad","simple","last","good","good","sure","last","wide","true","little","difficult","last","bloody","high","old","nice","good","little","real","young","beautiful","cold","different","sure","happy","old","same","wrong","second","strong","cold","old","serious","low","last","hard","new","good","different","last","little","different","cold","green","sure","many","sure","much","young","great","true","bloody","interesting","middle","big","high","disappointing","green","different","last","many","good","good","beautiful","little","sure","great","basic","different","last","cold","good","different","little","stupid","young","deep","funny","great","like","great","little","nice","last","important","much","long","new","great","good","conscious","different","nice","light","long","early","little","big","aware","little","different","primitive","difficult","many","second","big","same","aggressive","many","same","bad","aggressive","new","old","sorry","second","great","special","same","nice","real","similar","good","large","little","small","last","quiet","last","good","bloody","good","healthy","much","bad","good","same","nice","little","comfortable","little","great","large","economic","big","real","sorry","great","small","nice","strong","big","lucky","last","hard","good","expensive","quick","bloody","old","same","hard","last","big","many","same","special","good","new","last","nice","big","long","dark","real","long","last","many","last","same","interested","good","middle","genuine","wonderful","wonderful","relevant","last","close","small","noticeable","important","nice","good","good","hard","difficult","dark","simple","bad","funny","bad","good","beautiful","different","economic","little","little","different","good","new","different","same","fantastic","long","last","good","many","simple","little","same","much","good","good","little","relevant","small","quick","last","old","sure","much","tough","big","late","last","different","young","new","sure","weird","deep","wrong","many","obvious","strong","little","many","last","many","big","familiar","last","important","significant","sure","fantastic","long","good","many","weird","tough","small","last","many","deep","old","strange","cold","small","strange","little","weird","happy","last","much","little","great","new","new","old","clear","small","many","sad","hard","expensive","second","good","important","great","busy","clear","difficult","good","big","small","great","big","long","much","new","same","different","same","interesting","sure","strict","little","new","sure","sure","old","second","important","little","sure","last","big","economic","early","big","good","great","second","much","hard","large","old","similar","professional","quick","little","new","long","true","interesting","good","different","little","new","good","late","high","great","new","many","last","simple","high","good","old","many","old","little","bad","high","last","beautiful","much","same","good","important","high","old","big","big","important","much","second","high","same","sure","unrelated","similar","difficult","real","good","bad","fantastic","same","great","wrong","big","primitive","sure","last","many","like","little","good","good","big","good","different","small","good","bloody","deep","familiar","young","original","much","big","true","same","clear","green","small","early","good","new","new","difficult","last","long","interested","comfortable","proud","good","difficult","much","special","great","bright","second","sure","long","good","interesting","sure","good","good","beautiful","big","good","basic","last","old","last","excited","fantastic","good","last","same","different","effective","nice","old","interested","interesting","different","little","hard","bad","sure","grateful","strong","clear","big","last","bad","old","big","strange","new","bright","dark","big","bad","second","much","different","little","new","sorry","much","last","odd","much","small","nice","total","sure","different","great","hot","big","good","important","hard","great","difficult","bad","interested","many","significant","relevant","great","dark","big","last","sure","important","late","bad","much","hard","sorry","effective","nice","hard","economic","real","inaccessible","different","big","little","last","comprehensive","same","low","last","same","big","good","young","big","different","expensive","genuine","dark","quick","familiar","happy","second","little","relevant","last","last","similar","special","good","interesting","last","real","different","young","aware","easy","relevant","second","simple","old","total","little","real","real","important","open","new","great","sorry","great","bad","many","deep","cool","different","different","last","same","big","light","little","stupid","great","young","familiar","simple","long","special"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Amplifier<\/th>\n      <th>Adjective<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":5,"scrollX":true,"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
<p>For this tutorial, we will reduce the number of amplifiers and adjectives and thus simplify the data to render it easier to understand what is going on. To simplify the data, we remove</p>
<ul>
<li>all non-amplified adjectives</li>
<li>the adjectives many and much</li>
<li>adjectives that are amplified less than 10 times</li>
</ul>
<p>In addition, we collapse all amplifiers that occur less than 20 times into a bin category (<em>other</em>).</p>
<pre class="r"><code># simplify data
vsmdata_simp &lt;- vsmdata %&gt;%
  # remove non-amplifier adjectives
  dplyr::filter(Amplifier != 0,
         Adjective != &quot;many&quot;,
         Adjective != &quot;much&quot;) %&gt;%
  # collapse infrequent amplifiers
  dplyr::group_by(Amplifier) %&gt;%
  dplyr::mutate(AmpFreq = dplyr::n()) %&gt;%
  dplyr::ungroup() %&gt;%
  dplyr::mutate(Amplifier = ifelse(AmpFreq &gt; 20, Amplifier, &quot;other&quot;)) %&gt;%
  # collapse infrequent adjectives
  dplyr::group_by(Adjective) %&gt;%
  dplyr::mutate(AdjFreq = dplyr::n()) %&gt;%
  dplyr::ungroup() %&gt;%
  dplyr::mutate(Adjective = ifelse(AdjFreq &gt; 10, Adjective, &quot;other&quot;)) %&gt;%
  dplyr::filter(Adjective != &quot;other&quot;) %&gt;%
  dplyr::select(-AmpFreq, -AdjFreq)
# inspect data
datatable(vsmdata_simp, rownames = FALSE, filter=&quot;top&quot;, options = list(pageLength = 5, scrollX=T))</code></pre>
<div id="htmlwidget-c28b29fe83d567b4212d" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-c28b29fe83d567b4212d">{"x":{"filter":"top","filterHTML":"<tr>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n  <td data-type=\"character\" style=\"vertical-align: top;\">\n    <div class=\"form-group has-feedback\" style=\"margin-bottom: auto;\">\n      <input type=\"search\" placeholder=\"All\" class=\"form-control\" style=\"width: 100%;\"/>\n      <span class=\"glyphicon glyphicon-remove-circle form-control-feedback\"><\/span>\n    <\/div>\n  <\/td>\n<\/tr>","data":[["very","really","really","really","very","really","very","other","really","really","really","other","very","really","very","very","other","really","other","very","very","very","so","very","really","very","very","very","very","very","very","very","very","other","other","really","very","really","very","pretty","really","very","very","so","very","really","really","very","other","very","very","really","very","very","very","other","really","really","really","very","very","really","very","very","pretty","very","very","very","very","really","very","other","really","really","really","very","very","very","really","very","so","very","really","very","very","so","very","very","really","so","so","really","very","so","very","very","pretty","very","other","very","really","really","pretty","very","pretty","really","really","very","really","very","really","really","very","very","very","other","really","very","really","very","so","very","very","very","very","very","very","very","very","very","really","very","very","pretty","other","very","really","really","other","really","very","really","very","really","very","very","really","very","really","very","other","really","very","very","very","very","very","really","so","really","very","very","very","pretty","pretty","other","so","other","really","very","very","so","other","pretty","very","other","very","very","very","very","very","very","really","other","really","so","very","really","very","very","very","really","really","pretty","very","very","very","really","really","very","really","really","other","very","very","so","very","very","very","pretty","very","really","very","very","very","pretty","very","very","really","so","very","really","very","very","very","really","very","really","very","really","very","very","very","pretty","other","really","very","really","really","other","pretty","very","other","pretty","very","very","really","pretty","really","very","very","very","very","so","really","very","very"],["good","nice","good","bad","nice","nice","hard","good","nice","good","different","difficult","difficult","good","hard","difficult","good","nice","difficult","interesting","important","difficult","bad","important","bad","important","interesting","important","bad","nice","difficult","good","good","important","important","nice","good","different","difficult","bad","bad","good","strong","interesting","good","hard","hard","nice","different","good","nice","good","good","big","clear","good","good","good","good","interesting","difficult","strong","good","good","good","interesting","strong","difficult","good","good","interesting","difficult","good","good","good","strong","good","strong","big","important","strong","strong","big","good","good","bad","good","nice","good","important","good","good","hard","nice","good","good","difficult","different","different","nice","clear","hard","hard","good","big","nice","good","good","bad","important","nice","good","important","good","clear","important","interesting","difficult","bad","good","difficult","hard","difficult","good","nice","important","big","nice","difficult","hard","interesting","different","good","good","different","important","good","nice","important","big","interesting","good","good","strong","difficult","good","good","nice","bad","hard","different","nice","interesting","difficult","good","good","nice","clear","clear","good","important","hard","hard","big","good","different","big","bad","good","strong","hard","big","different","good","nice","clear","bad","strong","important","difficult","important","strong","hard","different","good","good","important","difficult","good","interesting","big","bad","good","good","hard","important","difficult","nice","nice","important","important","good","different","clear","interesting","clear","nice","good","good","good","strong","difficult","good","good","interesting","clear","clear","hard","good","good","important","bad","interesting","interesting","good","nice","strong","nice","important","nice","difficult","good","good","big","clear","hard","difficult","big","interesting","bad","good","important","difficult","good","difficult","difficult","good","good","nice","interesting","strong","big","important","bad","nice","different","good"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Amplifier<\/th>\n      <th>Adjective<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":5,"scrollX":true,"order":[],"autoWidth":false,"orderClasses":false,"orderCellsTop":true,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
<p>We now use a balloon plot to see if tehre are any potential correlations between amplifiers and adjectives.</p>
<pre class="r"><code># 1. convert the data as a table
dt &lt;- as.matrix(table(vsmdata_simp))
# 2. Graph
balloonplot(t(dt), main =&quot;vsmdata_simp&quot;, xlab =&quot;&quot;, ylab=&quot;&quot;,
            label = FALSE, show.margins = FALSE)</code></pre>
<p><img src="groupingstatz_files/figure-html/ca3-1.png" width="672" /></p>
<p>The balloon plot suggests that there are potential correlations as the dots (balloons) are not distributed evenly according to frequency. To validate if there is significant correlation between the amplifier types and the adjectives using a <span class="math inline">\(\chi\)</span><sup>2</sup>- test.</p>
<pre class="r"><code>chisq &lt;- chisq.test(dt)</code></pre>
<pre><code>## Warning in chisq.test(dt): Chi-squared approximation may be incorrect</code></pre>
<pre class="r"><code>chisq</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  dt
## X-squared = 124.4, df = 40, p-value = 1.375e-10</code></pre>
<p>The <span class="math inline">\(\chi\)</span><sup>2</sup>- test confirms that there is a significant correlations between amplifier types and the adjectives.</p>
<pre class="r"><code>res.ca &lt;- CA(dt, graph = FALSE)
# inpsect results of the CA
#print(res.ca)
eig.val &lt;- get_eigenvalue(res.ca)
eig.val</code></pre>
<pre><code>##       eigenvalue variance.percent cumulative.variance.percent
## Dim.1 0.24138007        49.868237                    49.86824
## Dim.2 0.14687839        30.344536                    80.21277
## Dim.3 0.06125177        12.654392                    92.86716
## Dim.4 0.03452547         7.132836                   100.00000</code></pre>
<p>The display of the <em>eigenvalues</em> provides information on the amount of variance that is explained by each dimension. The first dimension explains 49.87 percent of the variance, the second dimension explains another 30.34 percent of the variance, leaving all other variables with relative moderate explanatory power as they only account for 20 percent variance. We now plot and interpret the results of the CA.</p>
<pre class="r"><code># repel= TRUE to avoid text overlapping (slow if many point)
fviz_ca_biplot(res.ca, 
               repel = TRUE,
               col.row = &quot;orange&quot;,
               col.col = &quot;darkgray&quot;)</code></pre>
<p><img src="groupingstatz_files/figure-html/ca6-1.png" width="672" /></p>
<p>The results of the CA show that the adjective <em>different</em> is collocating with <em>other</em> amplifiers while <em>very</em> is collocating with <em>difficult</em> and <em>important</em>, <em>pretty</em> is collocating with <em>big</em>, <em>really</em> is collocating with <em>nice</em>, and <em>so</em> is collocating with <em>bad</em>.</p>
</div>
<div id="citation-session-info" class="section level1 unnumbered">
<h1>Citation &amp; Session Info</h1>
<p>Schweinberger, Martin. 2020. <em>Cluster and Correspondence Analysis in R</em>. Brisbane: The University of Queensland. url: <a href="https://slcladal.github.io/groupingstatz.html" class="uri">https://slcladal.github.io/groupingstatz.html</a> (Version 2020/09/25).</p>
<pre><code>@manual{schweinberger2020clust,
  author = {Schweinberger, Martin},
  title = {Cluster and Correspondence Analysis in R},
  note = {https://slcladal.github.io/groupingstatz.html},
  year = {2020},
  organization = &quot;The University of Queensland, Australia. School of Languages and Cultures},
  address = {Brisbane},
  edition = {2020/09/23}
}</code></pre>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.0.2 (2020-06-22)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18362)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] grid      stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] DT_0.15          gplots_3.1.0     FactoMineR_2.3   dplyr_1.0.2     
##  [5] exact2x2_1.6.5   exactci_1.3-3    ssanv_1.1        vcd_1.4-8       
##  [9] ape_5.4-1        pvclust_2.2-0    NbClust_3.0      seriation_1.2-8 
## [13] factoextra_1.0.7 ggplot2_3.3.2    cluster_2.1.0    knitr_1.30      
## 
## loaded via a namespace (and not attached):
##  [1] viridis_0.5.1        tidyr_1.1.2          jsonlite_1.7.1      
##  [4] viridisLite_0.3.0    foreach_1.5.0        carData_3.0-4       
##  [7] gtools_3.8.2         highr_0.8            cellranger_1.1.0    
## [10] yaml_2.2.1           ggrepel_0.8.2        pillar_1.4.6        
## [13] backports_1.1.10     lattice_0.20-41      glue_1.4.2          
## [16] digest_0.6.25        ggsignif_0.6.0       colorspace_1.4-1    
## [19] htmltools_0.5.0      plyr_1.8.6           pkgconfig_2.0.3     
## [22] broom_0.7.0          haven_2.3.1          purrr_0.3.4         
## [25] scales_1.1.1         openxlsx_4.2.2       rio_0.5.16          
## [28] tibble_3.0.3         car_3.0-9            generics_0.0.2      
## [31] farver_2.0.3         ellipsis_0.3.1       ggpubr_0.4.0        
## [34] withr_2.3.0          readxl_1.3.1         magrittr_1.5        
## [37] crayon_1.3.4         evaluate_0.14        nlme_3.1-148        
## [40] MASS_7.3-51.6        forcats_0.5.0        foreign_0.8-80      
## [43] rstatix_0.6.0        data.table_1.13.0    tools_4.0.2         
## [46] registry_0.5-1       hms_0.5.3            lifecycle_0.2.0     
## [49] stringr_1.4.0        munsell_0.5.0        zip_2.1.1           
## [52] flashClust_1.01-2    compiler_4.0.2       caTools_1.18.0      
## [55] rlang_0.4.7          iterators_1.0.12     htmlwidgets_1.5.1   
## [58] crosstalk_1.1.0.1    leaps_3.1            labeling_0.3        
## [61] bitops_1.0-6         rmarkdown_2.3        gtable_0.3.0        
## [64] codetools_0.2-16     abind_1.4-5          curl_4.3            
## [67] TSP_1.1-10           reshape2_1.4.4       R6_2.4.1            
## [70] gridExtra_2.3        zoo_1.8-8            KernSmooth_2.23-17  
## [73] dendextend_1.14.0    stringi_1.5.3        parallel_4.0.2      
## [76] Rcpp_1.0.5           vctrs_0.3.4          gclus_1.3.2         
## [79] scatterplot3d_0.3-41 tidyselect_1.1.0     xfun_0.16           
## [82] lmtest_0.9-38</code></pre>
<hr />
<p><a href="https://slcladal.github.io/index.html">Main page</a></p>
<hr />
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-blashfield1988methods">
<p>Blashfield, Roger K, and Mark S Aldenderfer. 1988. “The Methods and Problems of Cluster Analysis.” In <em>Handbook of Multivariate Experimental Psychology</em>, 447–73. Springer.</p>
</div>
<div id="ref-kassambara2017practical">
<p>Kassambara, Alboukadel. 2017. <em>Practical Guide to Cluster Analysis in R: Unsupervised Machine Learning</em>. Vol. 1. Sthda.</p>
</div>
<div id="ref-kettenring2006practice">
<p>Kettenring, Jon R. 2006. “The Practice of Cluster Analysis.” <em>Journal of Classification</em> 23 (1): 3–30.</p>
</div>
<div id="ref-king2015cluster">
<p>King, Ronald S. 2015. <em>Cluster Analysis and Data Mining: An Introduction</em>. Stylus Publishing, LLC.</p>
</div>
<div id="ref-levshina2015linguistics">
<p>Levshina, Natalia. 2015. <em>How to Do Linguistics with R: Data Exploration and Statistical Analysis</em>. Amsterdam: John Benjamins.</p>
</div>
<div id="ref-romesburg2004cluster">
<p>Romesburg, Charles. 2004. <em>Cluster Analysis for Researchers</em>. Lulu. com.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
