---
title: "**Language Technology and Data Analysis Laboratory (LADAL)**"
---


This is the website of the **Language Technology and Data Analysis Laboratory (LADAL)** of the [School of Languages and Cultures](https://languages-cultures.uq.edu.au/) at the [University of Queensland](https://www.uq.edu.au/), Australia.


# About LADAL 

LADAL is there to assist SLC staff and students with respect to data analysis, digital research tools, and other forms of technology. The focus of this site is to provide hands-on tutorials, to provide links to further resources, and short descriptions of digital tools relevant for SLC research.

# Tutorials and Resources

The website offers hands-on tutorials on various topics relating to digital approaches to language. 

1. Data processing": tutorials which introduce R as an language technology environment and show how to handle language data.

2. "Visualization": tutorials which show how to create graphs from very simple plots to quite sophisticated visualizations.

3. "Statistics": tutorials that focus on how to sumarize and analyze data using statistical methods.

4. "Text Analysis/Corpus Linguistics": tutorials that exemplify how to use R for Text Analysis but also provides links to software that are useful when you do not want to use R.

# Why R?

The majority of utorials on this site focus on R. This poses the question of why this is so and why learning and using R is better than sticking to ready-made software such as AntConc, SPSS, and Excel.

## R is free, open source, and cutting edge

In contrast to many commercial software packages, R is entirely free and it runs on almost any machine - no matter if you use a PC, a Mac or a Linux machine, R will be up and running after a few seconds without having to pay and fees. R is the most comprehensive statistical analysis environment and new technologies, ideas, and methods often appear first in R before being adapted and sold as commercial software packages.

Also, R is widely used and understood. And due to the creativity and diligence of its users, R is expanding rapidly and becoming more popular and more versatile every day. This is great because if you encounter a problem, there is a huge community of R users that are willing to help - simply type in you problem in your favourite search engine search box and it is highly likely that your issue has already been answered on sites such as <www.stackoverflow.com> or some other R forum or help page. This also means that errors are often very quickly detected and solved as anyone is welcome to provide bug fixes, code enhancements, and new packages.

## R is a programming language 

In contrast to SPSS, R is not only a statistics "package" but a fully-fledged programming language (or programming environment). This means that R is extremely flexible and can be used not only for statistics but for all kinds of different tasks: from extracting strings from a corpus, to processing and visualizing data to performing statistics, and even for creating apps and websites (this website, for instance, was created in R and is written in R Markdown).
This also means that once you have a working knowledge of R you will be able to use R for all the things that you need when dealing with language. This is a real advantage because you do not need to learn all sorts of different pieces of software for specific aspects of your work anymore - rather, you only need R and once you have good command of R you will be able to modify existing functions or even write new functions that enable you to do things that were not available in R previously.

## R is simple and good for jobs

Although it may not seem to be when you first encounter R, R is, in fact, very simple and easy to sue compared to almost any other programming language. This is true because R was specifically designed with human users in mind. This is particularly true when R is compared with C (or its direct daughters such as C++), for instance, which is designed for efficiency and is therefore much faster but also much more difficult to learn.
Furthermore, R is very open minded in the sense that you can access many other pieces of software or programming environments from R. Also, R works without a Compiler and is therefore an interpreted language which makes the development of code much easier. R is a vector language is thus more powerful and faster than most other languages (except for languages which are specifically designed for efficiency).
The most important reason why R is so useful is that it is great for visualization, statistics, and data science as well as handing big data. 
Finally, R is becoming so wide-spread that many companies use and require knowledge of R form potential employees. This means that being able to program in R is an advantage on the labour market. 

## R allows replication

When you do your research in R, you simply write a script that contains the entire analysis. This allows true and honest replication of research. In the humanities replications is not as deeply ingrained in the cultures as it is in the sciences. As a consequence, research in the humanities is not as reliable because only once research has been successfully replicated can it be considered valid.  Unfortunately, the humanities do not consider replication as vital as they should and also because replication in the humanities was not as easy as it has been in the sciences. This can change with R because a script which contains all the steps of an analysis can simply be distributed and can therefore be read, understood, and run by other researchers. This is a huge advantage over using ready-made software in which case replications is almost impossible given the various steps that cannot be described properly in the methods sections of articles and papers.

## Disadvantages of R 
Since R is open source, the quality of some packages is less than perfect and although errors are often detected and fixed quickly, errors do occur and there is no warranty whatsoever when using R. 

As R is designed with the human in mind, code in R can be rather slow and may take up all of the available working memory. While this can be fixed by writing more efficient code in R, often contributors do not optimize their code for efficiency. 

Because R is a communal project, it is changing rather quickly and packages that worked some time ago may have become outdated, they can be taken down by the people who have contributed them and the packages may therefore not be available anymore or they may simply be incompatible with a more modern version of R.


