<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Martin Schweinberger" />


<title>Regression Modellling and ANOVAs</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">LADAL</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-play-circle"></span>
     
    Basics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Basics</li>
    <li>
      <a href="hypotheses.html">Hypotheses</a>
    </li>
    <li>
      <a href="significance.html">Significance</a>
    </li>
    <li>
      <a href="errors.html">Errors</a>
    </li>
    <li>
      <a href="researchdesigns.html">Research Designs</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Data Processing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Data Processing</li>
    <li>
      <a href="intror.html">Basics</a>
    </li>
    <li>
      <a href="intror.html">Getting started with R</a>
    </li>
    <li>
      <a href="loading.html">Loading and saving data</a>
    </li>
    <li>
      <a href="page-b.html">Web Crawling</a>
    </li>
    <li>
      <a href="tabulating.html">Tabulating data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Visualization</li>
    <li>
      <a href="basicgraphs.html">Basic graphs</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (lattice)</a>
    </li>
    <li>
      <a href="page-d.html">Advanced graphs (ggplot2)</a>
    </li>
    <li>
      <a href="page-d.html">Wordclouds</a>
    </li>
    <li>
      <a href="page-d.html">Mapping</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-eye"></span>
     
    Statistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Statistics: Analyzing Data</li>
    <li>
      <a href="descriptives.html">Descriptive Statistics</a>
    </li>
    <li>
      <a href="chi.html">Chi-Square test</a>
    </li>
    <li>
      <a href="regression.html">Regression and ANOVA</a>
    </li>
    <li>
      <a href="forests.html">Variable Seclection</a>
    </li>
    <li>
      <a href="cluster.html">Classification</a>
    </li>
    <li>
      <a href="page-c.html">Dimension Reduction</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
    Text Analysis/Corpus Linguistics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Text Analysis/Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Network Analysis</a>
    </li>
    <li>
      <a href="page-c.html">Topic Modeling</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Corpus Linguistics</li>
    <li>
      <a href="page-c.html">Available Software</a>
    </li>
    <li>
      <a href="antconcexcel.html">Corpus Linguistics with AntConc, TextPad and Excel</a>
    </li>
    <li>
      <a href="page-c.html">Corpus Linguistics in R</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    Contact
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Regression Modellling and ANOVAs</h1>
<h4 class="author"><em>Martin Schweinberger</em></h4>
<h4 class="date"><em>2 Dezember 2018</em></h4>

</div>


<div id="simple-linear-regression" class="section level1">
<h1><span class="header-section-number">1</span> Simple Linear Regression</h1>
<p>Wir wenden uns nun einem sehr weit verbreiteten statistischen Verfahren zu, der Regression. Wir werden zunächst den einfachen Fall einer einfachen Regression mittels zweier Beispiele anschauen, um relevante Konzepte besser zu verstehen. Anschließend werden wir uns der multivariaten oder multiplen linearen Regression zuwenden. Der -Code, der in den Beispielen verwendet wird, basiert auf . Regressionen werden genutzt, um zu schauen, ob eine oder mehrere der unabhängigen Variablen (oder Prädikatoren) mit einer abhängigen Variable korrelieren.</p>
<p>Obwohl die zugrundeliegende Logik bei Regressionen dieselbe ist wie bei Varianzanalysen (ANOVA), einem verwandten Verfahren, wurden in der Soziolinguistik traditionell Regressionen für die Auswertung von Korpusdaten genutzt, während Varianzanalysen die bevorzugte Analysemethode der Psycholinguisten darstellte. Diese Vorliebe von linguistischen Subdisziplinen für bestimmt Methoden lässt sich eher historisch und kulturell als durch methodologische Vorteile der einen oder anderen Methode. Ein kleinerer Unterschied zwischen Varianzanalysen und Regressionen besteht jedoch darin, dass Regressionen auf die <span class="math inline">\(t\)</span>-Verteilung zurückgreifen, während Varianzanalysen auf die <span class="math inline">\(F\)</span>-Verteilung zurückgreifen (allerdings ist der <span class="math inline">\(F\)</span>-Wert nichts anderes als der quadrierte <span class="math inline">\(t\)</span>-Wert). Sowohl <span class="math inline">\(t\)</span>-Werte als auch <span class="math inline">\(F\)</span>-Werte geben Auskunft über das Verhältnis von erklärter und nicht-erklärter Varianz.</p>
<p>Die Idee einer Regression ist in Formel () dargestellt und lässt sich am Besten graphisch darstellen: Stellen sie sich eine Grade vor, die durch eine die Punkte in einem Koordinatensystem gezogen wird (Grafik  linkes Panel).</p>
<p><span class="math inline">\(f_{(x)} = \alpha + \beta_{1}x_{i} + \epsilon\)</span></p>
<p>Regressionen versuchen nun, diejenige Grade zu finden, die insgesamt den geringsten Abstand zu den Punkten hat (Grafik  mittleres Panel). Technisch gesprochen besteht das Ziel einer Regression also darin diejenige Grade zu finden, die die geringste Summe der Residuen (Varianz) hat (Grafik  rechtes Panel). Hiermit ist gemeint, dass die Summe der Längen der Linien, die man von der Graden weg zu den jeweiligen Punkten führen, so klein wie möglich sein soll. Die Neigung dieser Regressionsgeraden wird Koeffizient genannt und der Punkt an dem die Regressionsgerade die y-Achse schneidet wird als Intercept bezeichnet.</p>
<div class="figure">
<img src="regression_files/figure-html/unnamed-chunk-1-1.png" alt="Scatterplots mit Regressionsgeraden (mitte) und Residuen (rechts)" width="960" />
<p class="caption">
Scatterplots mit Regressionsgeraden (mitte) und Residuen (rechts)
</p>
</div>
<p>In diesem Zusammenhang sollte noch der Begriff Standardfehler (standard error (SE)) erklärt werden, da dieser Wert in von allen gängigen Statistikprogrammen ausgegeben wird, wenn man eine Regression gerechnet hat. Der Standardfehler gibt Auskunft darüber, wie sehr der Koeffizient variieren wird, wenn man dieselbe Regression auf viele Stichproben derselben Population anwendet. Ein kleiner Standradfehler sagt somit, dass der Wert des Koeffizienten nicht stark variieren wird, wenn man dieselbe Regression auf viele Stichproben mit den gleichen Eigenschaften anwendet, während ein großer Standradfehler besagt, dass man eine hohe Variation erwarten kann.</p>
<div id="a-practical-example-of-a-simple-linear-regression---preposition-use-across-real-time" class="section level2">
<h2><span class="header-section-number">1.1</span> A practical example of a simple linear regression - preposition use across real time</h2>
<p>In diesem Beispiel werden wir die Häufigkeiten von Präpositionen im Laufe der Geschichte des Englischen anschauen und testen, ob Präpositionen als Wortklasse zu- oder abgenommen haben.</p>
<p>Die Analyse basiert auf den Daten der <em>Penn Corpora of Historical English</em> (siehe <a href="http://www.ling.upenn.edu/hist-corpora/" class="uri">http://www.ling.upenn.edu/hist-corpora/</a>), die aus 603 Texten, die zwischen 1125 und 1900 geschrieben wurden, bestehen. Zuvor wurden alle als Präposition getaggten Elemente aus diesen Korpora extrahiert, indem nach dem Part-of-Speech Tag  gesucht wurde. Anschließend wurden die relativen Häufigkeiten der Präpositionen in den Texten anhand der Wörterzahl der Texte ermittelt. Bei dieser relativen Frequenz, die unsere abhängige Variable darstellt, handelt es sich also um pro-1.000-Wörter Frequenzen von Präpositionen in historischen Texten. Im nächsten Schritt wurde neben die jeweilige relative Häufigkeit die Jahreszahl, in der der Text geschrieben wurde, gestellt.</p>
<p>Die Tabelle auf die wir die einfache Regression anwenden hat folglich zwei Spalten: Eine Spalte mit den relativen Häufigkeiten (abhängige Variable) und eine Spalte mit der Jahreszahl, in der der jeweilige Text geschrieben wurde (unabhängige Variable).</p>
<p>Die folgende Ablauf ist typisch für Regressionsanalysen.</p>
<ol style="list-style-type: decimal">
<li>Extrahieren und Aufbereiten der Daten</li>
<li>Visualisierung der Daten</li>
<li>Durchführen der Regressionsanalyse</li>
<li>Prüfung, ob Annahmen der Regressionsanalyse verletzt wurden</li>
</ol>
<p>Wir werden nun beginnen, dass Beispiel in  zu implementieren. Im ersten Schritt leeren wir den gegenwärtigen Workspace, installieren und initialisieren/aktivieren notwendige Pakete und laden zusätzliche Funktionen.</p>
<pre class="r"><code># entfernen aller objekte aus dem aktuellen workspace
rm(list=ls(all=T))
# installieren der notwendigen pakete (falls nicht schon geschehen)
# (um die befehle zu aktivieren # entfernen)
#install.packages(&quot;QuantPsyc&quot;)
#install.packages(&quot;car&quot;)
# pakete initialisieren
library(QuantPsyc)
library(car)
library(ggplot2)
source(&quot;http://martinschweinberger.de/docs/scripts/multiplot_ggplot2.r&quot;) # funktion um mehrere grafiken in einem fenster anzuzeigen
source(&quot;http://martinschweinberger.de/docs/scripts/slr.summary.tb.r&quot;) # funktion zum erstellen von summary tabellen</code></pre>
<p>Nachdem wir die notwendigen Pakete usw. in  eingelesen haben, können wir nun die Daten laden und uns einen ersten Eindruck über deren Struktur und Eigenschaften verschaffen.</p>
<pre class="r"><code># load data
slr.data &lt;- read.delim(&quot;http://martinschweinberger.de/docs/data/slr.data.txt&quot;, header = TRUE)
# attach data
attach(slr.data)
# unnoetige spalten entfernen
slr.data &lt;- as.data.frame(cbind(slr.data$datems, slr.data$P.ptw))
# spaltennamen hinzufuegen
colnames(slr.data) &lt;- c(&quot;year&quot;, &quot;prep.ptw&quot;)
# entfernen unvollstaendiger datenpunkte
slr.data &lt;- slr.data[!is.na(slr.data$year) == T, ]
# erste zeilen des datensatzes betrachten
head(slr.data)</code></pre>
<pre><code>##   year prep.ptw
## 1 1736   166.01
## 2 1711   139.86
## 3 1808   130.78
## 4 1878   151.29
## 5 1743   145.72
## 6 1807   152.59</code></pre>
<pre class="r"><code># struktur des datensatzes betrachten
str(slr.data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    603 obs. of  2 variables:
##  $ year    : num  1736 1711 1808 1878 1743 ...
##  $ prep.ptw: num  166 140 131 151 146 ...</code></pre>
<pre class="r"><code># eigenschaften des datensatzes betrachten
summary(slr.data)</code></pre>
<pre><code>##       year         prep.ptw     
##  Min.   :1125   Min.   : 63.97  
##  1st Qu.:1545   1st Qu.:115.66  
##  Median :1615   Median :130.78  
##  Mean   :1619   Mean   :129.81  
##  3rd Qu.:1687   3rd Qu.:144.08  
##  Max.   :1913   Max.   :195.86</code></pre>
<p>Wir haben nun den Datensatz eingelesen und seine Eigenschaften und seine Struktur betrachtet. Dies ist wichtig, da es durchaus vorkommen kann, dass Variablen, die ursprünglich numerisch waren in kategoriale Variablen umgewandelt wurden. Im nächsten Schritt werden wir die Daten visualisieren, um einen Eindruck der Daten zu gewinnen.</p>
<pre class="r"><code># visualisieren der daten
p2 &lt;- ggplot(slr.data, aes(year, prep.ptw)) +
geom_point() +
labs(x = &quot;Year&quot;) +
labs(y = &quot;Prepositions per 1,000 words&quot;) +
geom_smooth()

p3 &lt;- ggplot(slr.data, aes(year, prep.ptw)) +
geom_point() +
labs(x = &quot;Year&quot;) +
labs(y = &quot;Prepositions per 1,000 words&quot;) +
geom_smooth(method = &quot;lm&quot;) # with linear model smoothing!

multiplot(p2, p3, cols = 2)</code></pre>
<pre><code>## Loading required package: grid</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="regression_files/figure-html/plotting-1.png" width="672" /></p>
<p>Bevor wir mit der Regression beginnen, werden wir die Jahreszahlen skalieren, d.h. wir ziehen vom jeweiligen Wert der Jahreszahl den Mittelwert der Jahreszahlen ab. Bei numerischen Variablen kann dies sehr hilfreich bei der Interpretation sein, denn wenn beispielsweise die numerische Variable  nicht skaliert werden würde, würde die Regression die Effekte im Jahr 0 angeben(!). Wenn eine Variable hingegen skaliert ist, dann werden die anderen Variablen nicht relativ zum Nullwert der Variable, sondern zu deren Mittelwert ins Verhältnis gesetzt, d.h. wir erhalten den Effekt der anderen Variablen, wenn die Variable  ihren Mittelwert annimmt.</p>
<pre class="r"><code># scaling date
slr.data$prep.ptw &lt;- slr.data$prep.ptw - mean(slr.data$prep.ptw)</code></pre>
<p>Wir beginnen nun mit der Regression, indem wir eine erste Regression rechnen und anschließend deren Ergebnisse und diagnostische Plots betrachten.</p>
<pre class="r"><code># create initial model
prep.lm &lt;- lm(prep.ptw ~ year, data = slr.data)
# inspect results
summary(prep.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prep.ptw ~ year, data = slr.data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -66.842 -13.523   1.183  14.086  65.117 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) -27.723706  10.863978  -2.552   0.0110 *
## year          0.017128   0.006691   2.560   0.0107 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.11 on 601 degrees of freedom
## Multiple R-squared:  0.01079,    Adjusted R-squared:  0.00914 
## F-statistic: 6.553 on 1 and 601 DF,  p-value: 0.01071</code></pre>
<pre class="r"><code># plot model: 3 plots per row in one window
par(mfrow = c(1, 3))
plot(resid(prep.lm))
plot(rstandard(prep.lm))
plot(rstudent(prep.lm))</code></pre>
<p><img src="regression_files/figure-html/initialmodel-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1)) # restroe default parameters</code></pre>
<p>Die linke Grafik zeigt die Residuen des Modells (d.h. die Unterscheide zwischen den beobachteten und den durch das Modell vorhergesagten Werten). Das Problem bei diesem Plot ist, dass die Residuen nicht standardisiert sind und man sie so nicht mit den Residuen anderer Modelle vergleichen kann. Um diesen Mangel zu beheben standardisiert man die Residuen, indem man die Residuen durch deren Standartabweichung dividiert, und plottet sie gegen die beobachteten Werte (mittlerer Plot). Auf diese Weise erhält man nicht nur standardisierte Residuen, sondern die Werte der Residuen sind nun zu z-Werten geworden und man kann die z-Verteilung nutzen, um problematische Punkte zu finden. Es gibt drei Daumenregeln bezüglich des Findens problematischer Datenpunkte aufgrund von Residuen :</p>
<ol style="list-style-type: decimal">
<li>Punkte mit extremen Werten, d.h. Werten <span class="math inline">\(\ge\)</span> 3 (um genau zu sein, Werten <span class="math inline">\(\ge\)</span> 3.29), sollten aus den Daten entfernt werden.</li>
<li>Falls mehr als 1% der Datenpunkte Werte <span class="math inline">\(\ge\)</span> 2.5 haben (2.58 um genau zu sein), dann sind die Fehler unseres Models zu groß.</li>
<li>Falls mehr als 5% der Datenpunkte Werte <span class="math inline">\(\ge\)</span> 2 haben (1.96 um genau zu sein), dann sind die Fehler unseres Models ebenfalls zu groß.</li>
</ol>
<p>Die rechte Grafik zeigt die <em>studentized Residuen</em>, d.h. die angepassten vorhergesagten Werte jedes Datenpunkts werden durch den Standardfehler der Residuen dividiert. Auf diesem Weg ist es möglich die Student’s t-Verteilung zu nutzen, um unser Model zu diagnostizieren.</p>
<p>Angepasste vorhergesagte Werte sind ebenfalls Residuen, aber einer besonderen Art: Das Model wird ohne einen Datenpunkt gerechnet und dann genutzt um diesen Datenpunkt vorherzusagen. Der Unterschied zwischen dem beobachteten Datenpunkt und dem vorhergesagten Datenpunkt wird dann angepasster vorhergesagter Wert genannt. Zusammenfassend kann gesagt werden, dass studentized Residuen sehr nützlich dahingehend sind, dass Sie einflussreiche Datenpunkte erkennen lassen.</p>
<p>Die Plots zeigen, dass es zwei potentiell problematische Datenpunkte gibt (die Punkte ganz oben und ganz unten). diese zwei Punkte setzten sich deutlich von den anderen Punkten ab und können demnach Ausreißer (outlier) darstellen. Wir werden später testen, ob diese punkte entfernt werden müssen.</p>
<p>Wir werden nun weitere modelldiagnostische Grafiken generieren.</p>
<pre class="r"><code># generiere eine 2x2 matrize diagnostischer grafiken
par(mfrow = c(2, 2))
plot(prep.lm)</code></pre>
<p><img src="regression_files/figure-html/diagnosticplots-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>Die diagnostischen Grafiken sehen sehr gut aus und wir werden im Folgenden erklären warum. Die Grafik im oberen linken Panel ist nützlich, um (a) Oulier zu finden oder (b) die Korrelation zwischen Residuen und vorhergesagten Werten zu bestimmen: Wenn ein Trend in der Linie oder den Punkten sichtbar wird (bspw. ein aufsteigender Trend oder eine Zickzacklinie), dann hätte unser Model ein Problem und wir müssten wahrscheinlich Datenpunkte entfernen.</p>
<p>Die Grafik im oberen rechten Panel zeigt an, ob die Residuen normal verteilt sind (was wünschenswert ist), ober ob die Residuen nicht einer Normalverteilung folgen. Liegen die Punkte auf der Linie, so folgen die Residuen einer Normalverteilung. Wenn die Punkte beispielsweise am oberen und unteren Ende nicht auf der Linie liegen, so zeigt dies, dass das Model kleine und große Werte nicht gut vorhersagt und daher nicht gut auf die Daten angepasst ist.</p>
<p>Die Grafik im unteren linken Panel gibt Aufschluss über Homoskedastizität. Homoskedastizität bedeutet, dass die Varianz der Residuen konstant bleibt und nicht mit dem Wert der unabhängigen Variable korrelieren. In unproblematischen Fällen zeigt die Grafik eine flache Linie. Liegt eine Trend in der Linie vor, so haben wir es mit Heteroskedastizität, also mit einer Korrelation zwischen unabhängigen Variablen und den Residuen, zu tun, die für Regressionen sehr problematisch ist.</p>
<p>Die Grafik im unteren rechten Panel zeigt problematische einflussreiche Datenpunkte, die die Regression überproportional beeinflussen (dies sollte nicht der Fall sein). Falls solche einflussreichen Datenpunkte vorliegen, so sollten diese entweder (a) gewichtet werden (robuste Regression) oder (b) entfernt werden. Die Grafik zeigt die Cookdistanz, welche zeigt, wie sich die Regression verändert, wenn ein Model ohne diesen Datenpunkt gerechnet wird. Die Cookdistanz zeigt also, welchen Einfluss ein Datenpunkt auf die Regression als ganzes hat. Datenpunkte, die eine Cookdistanz <span class="math inline">\(\ge\)</span> 1 haben sind problematisch .</p>
<p>Die sogenannte Leverage ist ebenso ein Maß, das anzeigt, wie stark ein Datenpunkt die Genauigkeit der Regression beeinflusst. Leveragewerte liegen zwischen 0 (kein Einfluss) und 1 (starker Einfluss: suboptimal!). Um zu testen, ob ein spezifischer Datenpunkt einen hohen Leveragewert besitzt, muss man einen Cut-Off-Punkt berechnen, der anzeigt, ob die Leverage zu stark oder noch akzeptabel ist. Folgende zwei Formeln werden hierzu genutzt:</p>
<p><span class="math inline">\(\frac{3(k + 1)}{n}\)</span></p>
<p>oder</p>
<p><span class="math inline">\(\frac{2(k + 1)}{n}\)</span></p>
<p>Wir werden im Kontext der multiplen linearen regression genauer auf Leverage eingehen und nun nur noch eine Überblicktabelle der Ergebnisse der Regression generieren.</p>
<pre class="r"><code># tabulate results
slr.summary(prep.lm)</code></pre>
<pre><code>##                                   Estimate Std. Beta Pearson&#39;s r
## (Intercept)                         -27.72                      
## year                                  0.02    0.1039         0.1
## Model statistics                                                
## Number of cases in model                                        
## Residual standard error on 601 DF                               
## Multiple R-squared                                              
## Adjusted R-squared                                              
## F-statistic (1, 601)                                            
## Model p-value                                                   
##                                   Std. Error t value Pr(&gt;|t|) P-value sig.
## (Intercept)                            10.86   -2.55    0.011     p &lt; .05*
## year                                    0.01    2.56   0.0107     p &lt; .05*
## Model statistics                                                     Value
## Number of cases in model                                               603
## Residual standard error on 601 DF                                    21.11
## Multiple R-squared                                                  0.0108
## Adjusted R-squared                                                  0.0091
## F-statistic (1, 601)                                                  6.55
## Model p-value                                                       0.0107</code></pre>
<p>Typischer weise werden die Ergebnisse von Regressionen in solchen Tabellen wiedergegeben, da diese aller wichtigen Kennzahlen der Modellgüte und die Signifikanz wie auch die Stärke der Effekte beinhalten. Die Tabelle ist hier noch einmal abgebildet.</p>

<p>Zusätzlich sollten die Ergebnisse von einfachen linearen Regressionen schriftlich in etwa wie folgt zusammengefasst werden:\[.2cm]</p>
<p>Eine einfache lineare Regression wurde auf die Daten angepasst. Eine visuelle Begutachtung der modelldiagostischen Grafiken zeigten keine problematischen Datenpunkte (Ausreißer) oder überproportional einflussreiche Datenpunkte an und wiesen auf einen guten Modellfit hin. Das finale lineare Regressionsmodell basiert auf 603 Datenpunkten und korreliert hoch signifikant mit den Daten (<span class="math inline">\(R^{2}\)</span>: 0.0108, F-Statistik (1, 601): 6.553, p-Wert: 0.0107<em>) und bestätigt eine signifikante positive Korrelation zwischen dem Jahr in dem der Text geschrieben wurde und der relativen Häufigkeit von Präpositionen in den Texten nach (Koeffizient: .02, Std. <span class="math inline">\(\beta\)</span>: 0.1039, SE: 0.01, t-Wert: 2.560, p-Wert: .0107</em>).</p>
</div>
<div id="a-practical-example-of-a-simple-linear-regression---teaching-styles" class="section level2">
<h2><span class="header-section-number">1.2</span> A practical example of a simple linear regression - teaching styles</h2>
<p>Im vorhergehenden Beispiel haben wir es mit zwei numerischen Variablen zu tun gehabt, während es sich in dem folgenden Beispiel um eine kategoriale und eine numerische abhängige Variable handelt. Die Eigenschaft, dass Regressionen mit sehr verschiedenen Variablenarten umgehen können, macht Regressionen zu einer weit verbreiteten und robusten Analysemethode.</p>
<p>In diesem Beispiel haben wir es mit zwei Gruppen von Schülern zu tun, die zufällig einer Gruppe zugewiesen wurden und unterschiedlichen Lehrmethoden ausgesetzt waren. Beide Gruppen unterziehen sich im Anschluss an die Lehreinheit einem Sprachlerntest mit einer Höchstpunktzahl von 20 Punkten. Die Schüler der ersten Gruppen haben folgende Punktzahlen erreicht:</p>
<ul>
<li>Gruppe A: 15, 12, 11, 18, 15, 15, 9, 19, 14, 13, 11, 12, 18, 15, 16, 14, 16, 17, 15, 17, 13, 14, 13, 15, 17, 19, 17, 18, 16, 14 (mean: 14,93)</li>
</ul>
<p>Die Schüler der zweiten Gruppe haben diese Punktzahlen erreicht.</p>
<ul>
<li>Gruppe B: 11, 16, 14, 18, 6, 8, 9, 14, 12, 12, 10, 15, 12, 9, 13, 16, 17, 12, 8, 7, 15, 5, 14, 13, 13, 12, 11, 13, 11, 7 (mean: 11,77)</li>
</ul>
<p>Unsere Frage ist nun, ob Gruppe A wirklich besser ist oder ob das Ergebnis Zufall ist?</p>
<p>Gehen wir nun dazu über, die Regression in <code>R</code> zu implementieren. Wie im vorherigen Beispiel leeren wir den gegenwärtigen Workspace, installieren und initialisieren/aktivieren notwendige Pakete und laden zusätzliche Funktionen.</p>
<pre class="r"><code># entfernen aller objekte aus dem aktuellen workspace
rm(list=ls(all=T))
# installieren der notwendigen pakete
# (falls nicht schon geschehen)
# (um die befehle zu aktivieren # entfernen)
#install.packages(&quot;QuantPsyc&quot;)
#install.packages(&quot;car&quot;)
# pakete initialisieren
library(QuantPsyc)
library(car)
library(ggplot2)
source(&quot;http://martinschweinberger.de/docs/scripts/multiplot_ggplot2.r&quot;) # mehrere ggplots in einem fenster
source(&quot;http://martinschweinberger.de/docs/scripts/slr.summary.tb.r&quot;) # funktion zum erstellen von summary tabellen</code></pre>
<p>Nachdem die notwendigen Spezifikationen durchgeführt wurden, werden wir nun unser Datenset generieren und es anschließend betrachten.</p>
<pre class="r"><code># einladen der daten
g1 &lt;- c(15, 12, 11, 18, 15, 15, 9, 19, 14, 13, 11, 12, 18, 15, 16, 14, 16, 17, 15, 17, 13, 14, 13, 15, 17, 19, 17, 18, 16, 14)
g2 &lt;- c(11, 16, 14, 18, 6, 8, 9, 14, 12, 12, 10, 15, 12, 9, 13, 16, 17, 12, 8, 7, 15, 5, 14, 13, 13, 12, 11, 13, 11, 7)
g &lt;- c(rep(&quot;A&quot;, length(g1)), rep(&quot;B&quot;, length(g2)))
sprtestdata &lt;- data.frame(g, c(g1, g2))
# spaltennamen hinzufuegen
colnames(sprtestdata) &lt;- c(&quot;gruppe&quot;, &quot;punkte&quot;)
# erste zeilen des datensatzes betrachten
head(sprtestdata)</code></pre>
<pre><code>##   gruppe punkte
## 1      A     15
## 2      A     12
## 3      A     11
## 4      A     18
## 5      A     15
## 6      A     15</code></pre>
<pre class="r"><code># struktur des datensatzes betrachten
str(sprtestdata)</code></pre>
<pre><code>## &#39;data.frame&#39;:    60 obs. of  2 variables:
##  $ gruppe: Factor w/ 2 levels &quot;A&quot;,&quot;B&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ punkte: num  15 12 11 18 15 15 9 19 14 13 ...</code></pre>
<pre class="r"><code># eigenschaften des datensatzes betrachten
summary(sprtestdata)</code></pre>
<pre><code>##  gruppe     punkte     
##  A:30   Min.   : 5.00  
##  B:30   1st Qu.:11.75  
##         Median :14.00  
##         Mean   :13.35  
##         3rd Qu.:16.00  
##         Max.   :19.00</code></pre>
<p>Nun stellen wir die Daten grafisch dar. In diesem Fall bietet sich ein Boxplot zur Visualisierung an.</p>
<pre class="r"><code># erstelle boxplot
boxplot(punkte ~ gruppe,
data = sprtestdata, # the data we want to display
main = &quot;&quot;, # you could specify a title here
ylab = &quot;Punkte&quot;, # titel der y-achse
ylim = c(0, 20), # grenzen der y-achse festlegen
xlab = c(&quot;Gruppen&quot;), # titel der x-achse
notch = T, # notches einfuegen
col = c(&quot;lightgreen&quot;, &quot;lightblue&quot;)) # box einfaerben
# text darstellen
text(1:2,
c(4.0, 4.0),
cex = 0.85,
labels = paste(&quot;mean\n&quot;,
c(round(as.vector(by(sprtestdata$punkte, sprtestdata$gruppe, mean))[1], 2),
round(as.vector(by(sprtestdata$punkte, sprtestdata$gruppe, mean))[2], 2),
sep = &quot;&quot;)))
rug(jitter(sprtestdata$punkte),
side=4)
grid()
box()</code></pre>
<div class="figure">
<img src="regression_files/figure-html/boxplot-1.png" alt="Darstellung der Sprachtestdaten" width="672" />
<p class="caption">
Darstellung der Sprachtestdaten
</p>
</div>
<p>Die Daten weisen darauf hin, dass Gruppe A signifikant besser abgeschnitten hat als Gruppe B. Wir werden diesen Eindruck dadurch testen, dass wir im nächsten Schritt das Regressionsmodell und erstellen die modelldiagnostischen Grafiken generieren.</p>


<p>Die Grafiken weisen nicht auf Ausreißer oder andere Probleme hin und wir können daher mit weiteren diagnostischen Grafiken fortfahren.</p>


<p>Auch diese Grafiken weisen auf keine Probleme hin. In diesem Fall können die Daten im nächsten Schritt zusammengefasst werden.</p>


<p>Die Ergebnisse dieser einfachen linearen Regressionen können wie folgt zusammengefasst werden:\[.2cm]</p>
<p>Eine einfache lineare Regression wurde auf die Daten angepasst. Eine visuelle Begutachtung der modelldiagostischen Grafiken zeigten keine problematischen Datenpunkte (Ausreißer) oder überproportional einflussreiche Datenpunkte an und wiesen auf einen guten Modellfit hin. Das finale lineare Regressionsmodell basiert auf 60 Datenpunkten und korreliert hoch signifikant mit den Daten (<span class="math inline">\(R^{2}\)</span>: 0.2322, <span class="math inline">\(F\)</span>-Statistik (1, 58): 2.93, p-Wert <span class="math inline">\(&lt;\)</span>.001<strong><em>) und bestätigt, dass Gruppe A signifikant besser bei dem Sprachlerntest abgeschnitten hat als Gruppe B (Koeffizient: -3.17, Std. <span class="math inline">\(\beta\)</span>: -0.4819, SE: 0.48, t-Wert: -4.19, p-Wert <span class="math inline">\(&lt;\)</span>.001</em></strong>).</p>
</div>
</div>
<div id="multiple-linear-regression" class="section level1">
<h1><span class="header-section-number">2</span> (Multiple) Linear Regression</h1>
<p>Im Gegensatz zu der einfachen linearen Regression, die den Zusammenhang zwischen einer unabhängigen und einer abhängigen Variable testet, kann eine multiple lineare Regression den Einfluss mehrerer unterschiedlicher unabhängiger Variablen und deren Interaktionen auf die abhängige Variable bestimmen (vgl. Formel ()). Eine einfache lineare Regression kann somit nicht gleichzeitig den Einfluss mehrerer Variablen oder derer Interaktionen bestimmen.</p>
<span class="math display">\[\begin{equation}
f_{(x)} = \alpha + \beta_{1}x_{i} + \beta_{2}x_{i+1} + \dots + \beta_{n}x_{i+n} + \epsilon
\label{eq:mlr}
\end{equation}\]</span>
<p>Es gibt ausgiebige Fachliteratur zu multiplen Regressionen und den zugrundeliegenden Konzepten. Insbesondere seien hier , , , ,  (mein persönlicher Favorit!), und  zu nennen. Sehr gute Einführungen dazu, wie Regressionen in  implementiert werden können, finden sich u.a. in ,  oder .</p>
<p>Eine weitere Anmerkung vorweg: Die modelldiagnostischen Verfahren werden teilweise identisch sein mit denen, die im Kapitel zur einfachen linearen Regression besprochen wurden und sie werden daher nur dann ausgiebiger erläutert, insofern dies nicht bereits geschehen ist.</p>
<p>Eine letzte Anmerkung betrifft die Stichprobengröße, die notwendig ist um eine Regression zu rechnen. Obwohl die Angabe, dass 25 Datenpunkte pro Gruppe ausreichen weit verbreitet ist, ist diese Angabe nicht korrekt, da sich die benötigte Stichprobengröße nach der Größe des Effekts, der bestimmt werden soll, und nach der Anzahl der untersuchten Variablen richtet. Gehen viele unabhängige Variablen in die Regression ein und die Effektstärke der zu testenden Variable(n) ist sehr klein, dann kann man von einer Mindestgröße der Stichprobe von 600 Datenpunkten ausgehen.  geben zur Mindestgröße der benötigten Stichprobe Daumenregeln an die Hand (k = Anzahl der Prädikatoren; kategorische Prädikatoren mit mehr als 2 Levels sollten in Dummy-variablen transformiert werden):</p>

<p>%Grafik  einfügen. XXX</p>
<p>Sie werden im -code sehen, dass hierzu eine Funktion existiert, die testet, ob die Stichprobe für die Untersuchung angemessen war.</p>
<p>Hinsichtlich der Modellanpassung wird nur auf step-wise step-down Prozeduren, die auf dem AIC (Akaike information criterion) beruhen, eingegangen werden. Es gibt eine Vielzahl von möglichen Prozeduren, die genutzt werden können forced entry, stepwise, hierarchical) und innerhalb dieser Prozeduren gibt es Unterklassen, sodass eine Diskussion den Rahmen dieser Sektion sprengen würde.</p>
<div id="practical-example-of-a-multiple-linear-regression---presents" class="section level2">
<h2><span class="header-section-number">2.1</span> Practical example of a multiple linear regression - presents</h2>
<p>In diesem Beispiel werden wir untersuchen, ob der Geldbetrag, den Männer für Geschenke ausgeben, mit der Attraktivität und dem Beziehungsstatus der Frauen, für die Geschenke gekauft wurden, korreliert. Das Beispiel ist  entnommen. Wir werden nun das Beispiel in  implementieren und leeren dazu, wie üblich, den gegenwärtigen Workspace, installieren und initialisieren/aktivieren notwendige Pakete und laden zusätzliche Funktionen.</p>

Nachdem wir die notwendigen Pakete usw. in  eingelesen haben, können wir nun die Daten laden und uns einen ersten Eindruck über deren Struktur und Eigenschaften verschaffen.

Wir haben nun den Datensatz eingelesen und seine Struktur betrachtet. Im nächsten Schritt werden wir die Daten visualisieren, um einen Eindruck der Daten und der Verteilungen der Variablen zu gewinnen. Wir werden vier Grafiken erstellen und diese dann in einem Fenster darstellen.


<p>Die Grafik im oberen linken Panel scheint anzudeuten, dass Männer mehr Geld für Frauen ausgeben, die Single sind, allerdings relativiert sich dieser Eindruck, denn die Grafik im unteren rechten Panel deutet darauf hin, dass Männer nur dann mehr Geld für ein Geschenk ausgeben, wenn die Frau Single ist UND sie an ihr interessiert sind. Den der Beziehungsstatus hat keinen Einfluss auf das Geld für Geschenke für Frauen, an denen Männer nicht interessiert sind. Die Grafik im oberen rechten Panel weist darauf hin, dass Männer substantiell mehr Geld für Geschenke für Frauen ausgeben, an denen sie interessiert sind.</p>
Gehen wir nun dazu über mit der Regression zu beginnen. Im ersten Schritt erzeugen wir vier Baselinemodelle: Zwei minimale Modelle, die nur den Gesamtmittelwert (Intercept) als Prädiktor beinhalten und zwei gesättigte Modelle (saturated models), die alle möglichen Prädikatoren und Interaktionen beinhalten.

<p>Nachdem wir die Baselinemodelle generiert haben, werden wir nun mit dem Modellanpassung (model fitting)beginnen. Modellanpassung bezeichnet den Prozess mit dem man zu demjenigen Modell gelangt, dass das Maximum an Varianz mit einem Minimum an Variablen erklärt. Das zugrunde liegende Prinzip ist daher das  oder , welches im Englischen häufig als Ockham’s Rasiermesser bezeichnet wird.</p>
<p>Wir werden einen automatischen step-wise step-down Prozess bei der Modellanpassung nutzen, der dasjenige Modell mit dem niedrigsten AIC (Akaike information criterion) Wert sucht. Das AIC berechnet sich nach Formel () und ist ein Maß der Sparsamkeit, dass einen Wert dafür bildet, wie viel Varianz mit wie vielen Variablen erklärt werden kann . Um so niedriger der AIC-Wert, umso besser die Balance zwischen erklärter Varianz und der Anzahl der dafür nötigen Variablen. Die AIC-Werte können nun zwischen Modellen verglichen werden, die auf die selben Datenpunkte angepasst sind (<span class="math inline">\(LL\)</span> steht für LogLikelihood und <span class="math inline">\(k\)</span> für die Anzahl der unabhängigen Variablen im Modell).</p>
<span class="math display">\[\begin{equation}
-2LL + 2k
\label{eq:aic}
\end{equation}\]</span>
Beginnen wir nun mit der Modellanpassung.

<p>Basierend auf dem Modell mit dem kleinsten AIC-Wert haben wir das minimale adäquate Modell (minimal adequate model) generiert und anschließend haben wir die Zusammenfassung der Ergebnisse des Modells auswerfen lassen. Im Folgenden werden wir den Output, d.h. die Zusammenfassung der Ergebnisse des minimalen adäquaten Modells beleuchten und die verschiedenen Konzepte erläutern.</p>
<p>Das erste Objekt, was die Zusammenfassung berichtet ist der , d.h. die Formel des des minimalen adäquaten Modells. Daran anschließend wird die Verteilung der Residuen, also der Unterschiede zwischen den vorhergesagten und beobachteten Werten, berichtet. Dann folgt das wichtigste Element der Modellzusammenfassung: Die Tabelle mit den Koeffizienten der Prädikatoren des Modells (dies sind die Koeffizienten der Fixed Effects). Wir werden uns mit dieser Tabelle später genauer beschäftigen. Nach der Tabelle folgen die Modellstatistiken, die Aufschluss darüber geben, wie gut das Modell die Daten modelliert, d.h. wie gut das Modell den beobachteten Daten entspricht. Der Unterschied zwischen diesen Werten und der Tabelle mit den Koeffizienten besteht darin, dass die Modellstatistiken über die Gesamtgüte des Modells berichten, während die Tabelle mit den Koeffizienten nur etwas über die individuellen Faktoren aussagt.</p>
<p>Der multiple <span class="math inline">\(R^{2}\)</span>-Wert gibt an, wie viel Varianz das Modell erklärt. Ein Wert von 0 würde bedeuten, dass das Modell gar keine Varianz erklärt, während ein Wert von 1 bedeuten würde, dass das Modell 100% der Varianz erklärt und somit die Vorhersage des Modells genau den beobachteten Daten entspricht. Dies bedeutet, dass, wenn man den <span class="math inline">\(R^{2}\)</span>-Wert mit 100 multipliziert, man den Prozentwert der Varianz erhält, den das Modell erklärt. In unserem Fall sagt der multiple <span class="math inline">\(R^{2}\)</span>-Wert von 0.852 also aus, dass unser minimales adäquates Modell 85.2% der Varianz erklärt. Modelle, die einen multiplen <span class="math inline">\(R^{2}\)</span>-Wert von <span class="math inline">\(ge\)</span>.05 haben, gelten als substantiell signifikant (substantially significant) . Manche gehen soweit zu sagen, dass Modelle mindestens einen <span class="math inline">\(R^{2}\)</span>-Wert von <span class="math inline">\(\ge\)</span>.05 haben müssen, aber dies ist problematisch, da es durchaus vorkommen kann, dass man an sehr schwachen (aber signifikanten) Effekten interessiert ist, die aber zu einem sehr kleinen <span class="math inline">\(R^{2}\)</span>-Wert führen. Wichtiger ist, dass das Modell insgesamt signifikant ist, da dies aussagt, dass das Modell zu signifikant besseren Vorhersagen kommt, als es durch Zufall der Fall wäre.</p>
<p>Der angepasste <span class="math inline">\(R^{2}\)</span>-Wert (adjusted <span class="math inline">\(R^{2}\)</span>) berücksichtigt die Anzahl der Prädikatoren. Darüber hinaus gibt der angepasste <span class="math inline">\(R^{2}\)</span>-Wert darüber Aufschluss, wie gut sich das Modell eignet, um Aussagen über die Population (und nicht nur über die Stichprobe) zu tätigen. Wenn der Unterschied zwischen dem multiplen <span class="math inline">\(R^{2}\)</span>-Wert und dem angepassten <span class="math inline">\(R^{2}\)</span>-Wert sehr gering ist, dann bedeutet dies, dass sich das Modell dazu eignet Aussagen über die Population als Ganzes zu machen. Wenn der Unterschied allerdings relativ groß ist, dann bedeutet dies, dass das Modell instabil ist und die Datenstruktur, auf die das Modell angepasst wurde, eine suboptimale Verteilung aufweist, z.B. wegen Ausreißern. In anderen Worten bedeutet der Unterschied, dass wenn die Regression auf die Population anstatt der Stichprobe angewandt worden wäre, dann würde sie .5% weniger Varianz (85.2-84.7) erklären.</p>
<p>Kommen wir nun zu der Tabelle mit den Koeffizienten zurück. Alle Haupteffekte und eine Interaktion zwischen  und  sind signifikant. Eine Interaktion besteht dann, wenn die Korrelation zwischen einer unabhängigen und der abhängigen variable von einer anderen unabhängigen variable beeinflusst wird. In unserem Szenario geben Männer nur dann mehr Geld für ein Geschenk für eine Frau aus, wenn sie an ihr (a) interessiert sind und (b) sie Single ist. Die Korrelation zwischen  und  wird also von einer anderen Variable  beeinflusst. Wir haben es also mit einer Interaktion zwischen  und  zu tun.</p>
<p>Hinsichtlich der Interpretation dieser Ergebnisse ist festzuhalten, dass man Haupteffekte, die an Interaktionen beteiligt sind, nicht interpretieren sollte, da nicht klar ist, wie sich der Anteil an erklärter Varianz zwischen dem Haupteffekten und den Interaktionen aufteilt. Zusätzlich ist festzuhalten, dass, insofern nur Haupteffekte signifikant sind, die Koeffizienten die Korrelation zwischen der abhängigen und der unabhängigen Variable abbilden, wenn die anderen Variablen einen Wert von 0 oder das jeweilige Baseline-Level annehmen.</p>
<p>Bevor wir die Tabelle mit den Koeffizienten weiter interpretieren, werden wir noch die Konfidenzintervalle berechnen und das Baselinemodell mit dem minimalen adäquaten Modell vergleichen, um zu schauen, ob das minimale adäquate Modell zu signifikant besseren Vorhersagen kommt als das Baselinemodell.</p>

Der Vergleich der Modelle zeigt eindeutig, dass das minimale adäquate Modell zu signifikant besseren Vorhersagen kommt als das Baselinemodell. Wir werden nun mit der Modelldiagnose fortfahren, indem wir schauen, ob Datenpunkte entfernt werden sollten, da sie die Passgenauigkeit des Modells (modelfit) überproportional verschlechtern.

Die Grafiken deuten darauf hin, dass drei Datenpunkte potentiell problematisch sind (Datenpunkte 52, 64, 83). Wir werden nun diesen Eindruck statistisch evaluieren und die Datenpunkte, falls nötig entfernen.

Die Zeilenzahl weist darauf hin, dass zwei potentielle Problemfälle entfernt wurden, da deren Werte inakzeptabel waren, während einer der Punkte im Modell verbleiben durfte. Da wir es nun mit einem veränderten Datensatz zu tun haben, müssen wir die bisherigen Schritte wiederholen. Die einzelnen wiederholten Schritte werden nun nicht weiter erläutert, insofern die Erläuterungen mit den bereits oben ausgeführten weitgehend identisch wäre.

Die diagnostischen Grafiken zeigen nun zwar weitere potentiell problematische Datenpunkte an, allerdings weichen diese Punkte weitaus weniger vom allgemeinen Trend ab, als dies bei den entfernten Punkten der Fall war. Wir berechnen dennoch diagnostische Statistiken und fügen diese zum Datensatz hinzu, um sicher zu gehen, dass nun alle Datenpunkte akzeptabel sind.

Wir nutzen nun die hinzugefügten Diagnosewerte um neue diagnostische Grafiken zu erstellen.

Die Grafiken zeigen keine auffälligen Ausreißer. Wir überprüfen diesen Eindruck dennoch statistisch. Hierzu lässt sich folgendes sagen:


Bis auf den Mittelwert der VIFs, der <span class="math inline">\(&lt;\)</span> 1 sein sollte, tatsächlich aber 2.307 beträgt, sind alle diagnostischen Werte völlig akzeptabel. Wir werden nun testen, ob die Stichprobengröße in unserer Untersuchung ausreicht. Basierend auf  geben  zur Mindestgröße der benötigten Stichprobe Daumenregeln an die Hand (k = Anzahl der Prädikatoren; kategorische Prädikatoren mit mehr als 2 Levels sollten in Dummy-variablen transformiert werden):

Zusätzlich werden wir prüfen, wie groß der Wert für  basierend auf einer Zufallsstichprobe wäre, um abschätzen zu können, wie groß die Wahrscheinlichkeit eines <span class="math inline">\(\beta\)</span>-Fehlers bei der vorliegenden Stichprobengröße ist . Bei <span class="math inline">\(\beta\)</span>-Fehlern handelt es sich um die Annahme, ein Prädikator ist nicht signifikant, obwohl er tatsächlich einen signifikanten Einfluss hat (siehe Sektion ). Die Prüfgröße schwankt zwischen 0 und 1. Umso kleiner der Wert ist, umso besser. Wenn der Wert <span class="math inline">\(\ge\)</span> 1 liegt, dann gibt es Grund zur Sorge und es sollte eine größere Stichprobe gezogen werden.

Die Funktion  teilt mit, dass die Stichprobengröße nicht optimal ist und 9 Datenpunkte fehlen, um der Anforderung von  zu genügen. Die Wahrscheinlichkeit einen <span class="math inline">\(\beta\)</span>-Fehler zu begehen ist hingegen sehr klein (0.0309). Als letzten Schritt tabellarisieren wir die Ergebnisse und fassen diese anschließend in Textform zusammen.


<p>Zusätzlich werden die Ergebnisse von multiplen linearen Regressionen schriftlich wie folgt zusammengefasst:\[.2cm]</p>
<p>(Falls signifikante Interaktionen vorliegen, sollten die Haupteffekte der Prädikatoren, die an der/n Interaktion/en beteiligt sind, nicht interpretiert werden. Sie werden hier dennoch interpretiert, um zu verdeutlichen, wie die Ergebnisse einer multiplen linearen Regression verschriftlicht werden können.)</p>
<p>Eine multiple lineare Regression wurde mit AIC-basierter (Akaike’s Information Criterion) step-wise step-down Prozedur auf die Daten angepasst, um zum finalen minimalen adäquaten Modell zu gelangen. Während der Modelldiagnose wurden zwei Datenpunkte als Ausreißer ermittelt und aus dem Datensatz entfernt. Weitere modelldiagnostischen Grafiken und zusätzliche statistische Modelldiagnosen ergaben nach dem Entfernen der Ausreißer keine weiteren Auffälligkeiten.</p>
<p>Das finale minimale adäquate Modell basiert auf 98 Datenpunkten und korreliert hoch signifikant mit dem Datensatz (Multipler <span class="math inline">\(R^{2}\)</span>: .857, Angepasster <span class="math inline">\(R^{2}\)</span>: .853, F-statistic (3, 94): 154.4, AIC: 850.4, BIC: 863.32, p<span class="math inline">\(&lt;.001***\)</span>). Das finale minimale adäquate Modell enthält sowohl  und  als signifikante Haupteffekte. Der Status von Geschenk-empfängern korreliert hoch signifikant positiv mit dem Geldbetrag, der für ihre Geschenke ausgegeben wird (SE: 5.14, <span class="math inline">\(t\)</span>-Wert: 10.87, p<span class="math inline">\(&lt;.001***\)</span>). Dies zeigt, dass wenn eine Person single ist, ihr Geschenk {55,85} mehr wert ist, verglichen mit dem Fall, dass sie in einer Beziehung ist (in diesem Fall ist das Geschenk {99.15}, wenn der Schenker nicht an der Beschenkten interessiert ist. Der Faktor  korreliert ebenfalls hoch signifikant positiv mit dem Geldbetrag, der für ihre Geschenke ausgegeben wird (SE: 5.09, <span class="math inline">\(t\)</span>-Wert: -9.37, p<span class="math inline">\(&lt;.001***\)</span>). Falls der Schenkende nicht an der Beschenkten interessiert ist, dann gibt er {-47.66} weniger für ein Geschenk aus, verglichen mit dem Fall, dass er sie attraktiv findet (vorausgesetzt die Beschenkte ist in einer Beziehung). Schließlich weist das finale minimale adäquate Modell eine hoch signifikante Interaktion zwischen  und  nach (SE: 7.27, <span class="math inline">\(t\)</span>-Wert: -8.18, p<span class="math inline">\(&lt;\)</span>.001***): Wenn die Beschenkte ein Single ist, aber der Schenker nicht an ihr interessiert ist, dann gibt der Schenker {59,46} weniger für ein Geschenk aus, verglichen mit dem Fall, dass er an der Beschenkten interessiert ist (vgl. Figure ).</p>




<p>Ohne es genauer zu spezifizieren haben wir bisher nur mit Fixed-Effects gearbeitet, d.h. alle Datenpunkte werden so betrachtet, als ob sie auf der gleichen Hierarchieebene liegen. Häufig ist es aber so, dass Datenpunkte keine flache, sondern eine hierarchische Struktur haben, da beispielsweise mehrere Datenpunkte von demselben Sprecher stammen. Um der hierarchischen Struktur Rechnung zu tragen, muss man diese auch modellieren, was mit Hilfe von  geschehen kann.</p>

<p> haben zwei Ausprägungen:  (rechtes Panel Grafik ) und  (mittleres Panel Grafik ). Wir werden uns im Folgenden auf  konzentrieren, da dies die weitaus gebräuchlichere Variante ist. Um zu beschreiben, worum es sich bei  handelt, fokussieren wir uns auf Grafik .</p>

<p>Im mittleren Panel von Grafik  wird genau eine Regressionsgrade genutzt, um Werte vorherzusagen. Wenn wir  für die drei Gruppen einführen, so entsteht für jede Ausprägung des , d.h. für jede Gruppe, eine eigene Regressionsgerade.</p>
<p>Nachdem Random Slopes eingeführt sind, werden, wie bei der multiplen Regression, Prädiktoren (Ffixed Effekte) hinzugefügt, d.h. Mixed-Effects Modelle werden Mixed-Effects Modelle genannt, weil Sie sowohl Random Effekte (meistens Random Intercepts) und einfache Prädiktoren (Fixed Effekte) beinhalten.</p>
<p>Was die Vorgehensweise betrifft, so lässt sich sagen, dass zuerst die Random Effektstruktur eingebaut und evaluiert wird und erst im Anschluß die Fixed Effekte in das Model aufgenommen werden . Man testet, ob das Einfügen von Random Effekten berechtigt ist, indem man ein Model, das nur den Intercept als Prädiktoren hat gegen ein Model, welches nur die Random Intercepts als Prädiktoren hat. Ist die Varianz bei dem Random Effects Modell geringer, so war das Einfügen der Random Intercepts berechtigt.</p>
%

<p>% %Nachdem die Sitzung nun vorbereitet ist, kann mit dem Einlesen der Daten begonnen werden. Es ist allerdings unbedingt zu bedenken, dass, um de folgenden Code nutzen zu können, eine aktive Internetverbindung benötigt wird und, dass die %Pfade auf den eigenen Rechner angepasst werden müssen!</p>
%

%Wie bereits bei edr einfachen linearen Regression werden wir die numerischen Variablen skalieren. Skalieren bedeutet, dass der Mittelwert der numerischen Variable von jedem Wert dieser Variable abgezogen wird. % %

</div>
<div id="r-markdown" class="section level2">
<h2><span class="header-section-number">2.2</span> R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<pre class="r"><code>summary(cars)</code></pre>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
</div>
<div id="including-plots" class="section level2">
<h2><span class="header-section-number">2.3</span> Including Plots</h2>
<p>You can also embed plots, for example:</p>
<p><img src="regression_files/figure-html/pressure-1.png" width="672" /></p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
