#!/bin/bash

# Remove the version of notebooks stored in the repo version we use to build the Binder
# image
rm -rf ~/content
# Download latest notebooks from LADAL
svn export https://github.com/SLCLADAL/SLCLADAL.github.io/trunk/content ~/content
# Create a backup copy, if the user needs originals
cp -r ~/content ~/originals

# Create .Rprofile (which we deleted in postBuild), setting a hook
# for Rstudio, so that it opens in the 'content' folder
echo "setwd('~/content')" >> ~/.Rprofile
echo "setHook('rstudio.sessionInit', function(newSession) {" >> ~/.Rprofile
echo "if (newSession)" >> ~/.Rprofile
echo "rstudioapi::filesPaneNavigate('~/content')" >> ~/.Rprofile
echo "}, action = 'append')" >> ~/.Rprofile

# This line is required according to Binder manual
exec "$@"
