---
title: "R Notebook"
output: html_notebook
---

# Tranforming data

From txt to rda

```{r}
data03 <- read.delim("https://slcladal.github.io/data/data01.txt", header = TRUE)
base::saveRDS(data01, file = here::here("data", "d01.rda"))
data01  <- base::readRDS(url("https://slcladal.github.io/data/d01.rda", "rb"))

# data03
tdata <- read.delim("https://slcladal.github.io/data/data03.txt", 
                      header = T, sep = "\t")
base::saveRDS(tdata, file = here::here("data", "d03.rda"))
data03  <- base::readRDS(url("https://slcladal.github.io/data/d03.rda", "rb"))

#data04
degree_adverbs <- read.delim("https://slcladal.github.io/data/data04.txt", sep = "\t", header = T)
base::saveRDS(degree_adverbs, file = here::here("data", "dad.rda"))
degree_adverbs  <- base::readRDS(url("https://slcladal.github.io/data/dad.rda", "rb"))


# ldat
ldat <- read.delim("https://slcladal.github.io/data/likertdata1.txt", header = TRUE)
base::saveRDS(ldat, file = here::here("data", "lid.rda"))
ldat  <- base::readRDS(url("https://slcladal.github.io/data/lid.rda", "rb"))

#sud
surveydata <- read.delim("https://slcladal.github.io/data/surveydata1.txt", sep = "\t", header = T)
base::saveRDS(surveydata, file = here::here("data", "sud.rda"))
sud  <- base::readRDS(url("https://slcladal.github.io/data/sud.rda", "rb"))


#  sud2
sdat <- read.delim("https://slcladal.github.io/data/survey.txt", header = TRUE)
base::saveRDS(sdat, file = here::here("data", "sdd.rda"))
sdd  <- base::readRDS(url("https://slcladal.github.io/data/sdd.rda", "rb"))

# German
German <- readLines("https://slcladal.github.io/data/phonemictext1.txt")
base::saveRDS(German, file = here::here("data", "ged.rda"))
German  <- base::readRDS(url("https://slcladal.github.io/data/ged.rda", "rb"))

English <- readLines("https://slcladal.github.io/data/phonemictext2.txt")
Spanish <- readLines("https://slcladal.github.io/data/phonemictext3.txt")
Unknown <- readLines("https://slcladal.github.io/data/phonemictext4.txt")

base::saveRDS(English, file = here::here("data", "end.rda"))
base::saveRDS(Spanish, file = here::here("data", "spd.rda"))
base::saveRDS(Unknown, file = here::here("data", "und.rda"))

German  <- base::readRDS(url("https://slcladal.github.io/data/ged.rda", "rb"))
English  <- base::readRDS(url("https://slcladal.github.io/data/end.rda", "rb"))
Spanish  <- base::readRDS(url("https://slcladal.github.io/data/apd.rda", "rb"))
Unknown  <- base::readRDS(url("https://slcladal.github.io/data/und.rda", "rb"))

# cfa data
cfadata <- read.delim("https://slcladal.github.io/data/cfadata.txt", header = T, sep = "\t")
base::saveRDS(cfadata, file = here::here("data", "cfd.rda"))
cfadata  <- base::readRDS(url("https://slcladal.github.io/data/cfd.rda", "rb"))

# vector space data
vsmdata <- read.delim("https://slcladal.github.io/data/vsmdata.txt", sep = "\t", header = T)
base::saveRDS(vsmdata, file = here::here("data", "vsd.rda"))
vsmdata  <- base::readRDS(url("https://slcladal.github.io/data/vsd.rda", "rb"))

# ampaus
ampaus <- read.table("https://SLCLADAL.github.io/data/ampaus.txt",  sep = "\t", header = T)
base::saveRDS(ampaus, file = here::here("data", "ozd.rda"))
vsmdata  <- base::readRDS(url("https://slcladal.github.io/data/ozd.rda", "rb"))

#slrdata2 <- read.delim("https://slcladal.github.io/data/slrdata2.txt", sep = "\t", header = T)
#base::saveRDS(slrdata2, file = here::here("data", "sgd.rda"))
slrdata2  <- base::readRDS(url("https://slcladal.github.io/data/sgd.rda", "rb"))

# load data
#mlrdata <- read.delim("https://slcladal.github.io/data/mlrdata.txt", header = TRUE)
#base::saveRDS(mlrdata, file = here::here("data", "mld.rda"))
mlrdata  <- base::readRDS(url("https://slcladal.github.io/data/mld.rda", "rb"))

# load data
#blrdata <- read.table("https://slcladal.github.io/data/blrdata.txt",
#                      comment.char = "",  # data does not contain comments
#                      quote = "",         # data does not contain quotes
#                      sep = "\t",         # data is tab separated
#                      header = T)         # variables have headers
#base::saveRDS(blrdata, file = here::here("data", "bld.rda"))
blrdata  <- base::readRDS(url("https://slcladal.github.io/data/bld.rda", "rb"))

```


```{r}
# load data
#ordata <- read.delim("https://slcladal.github.io/data/ordinaldata.txt", 
#                     sep = "\t", header = T)
#base::saveRDS(ordata, file = here::here("data", "ord.rda"))
ordata  <- base::readRDS(url("https://slcladal.github.io/data/ord.rda", "rb")) %>%
  dplyr::rename(Recommend = 1, 
              Internal = 2, 
              Exchange = 3, 
              FinalScore = 4) %>%
  dplyr::mutate(FinalScore = round(FinalScore, 2))
```


```{r}
# load data
#poissondata <- read.delim("https://slcladal.github.io/data/posdata.txt", sep = "\t", header = T, skipNul = T, quote = "")
#base::saveRDS(poissondata, file = here::here("data", "prd.rda"))
poissondata  <- base::readRDS(url("https://slcladal.github.io/data/prd.rda", "rb"))

```


```{r rr1}
# load data
#robustdata <- read.delim("https://slcladal.github.io/data/mlrdata.txt", sep = "\t", header = T)
#base::saveRDS(robustdata, file = here::here("data", "mld.rda"))
robustdata  <- base::readRDS(url("https://slcladal.github.io/data/mld.rda", "rb"))
```

```{r lmm3}
# read in data
#lmmdata <- read.delim("https://slcladal.github.io/data/lmmdata.txt", header = TRUE)
#base::saveRDS(lmmdata, file = here::here("data", "lmd.rda"))
lmmdata  <- base::readRDS(url("https://slcladal.github.io/data/lmd.rda", "rb")) %>%
  # convert date into a numeric variable
  dplyr::mutate(Date = as.numeric(Date))
```

```{r blmm3}
# load data
#mblrdata <- read.table("https://slcladal.github.io/data/mblrdata.txt", 
#                       comment.char = "",# data does not contain comments
#                       quote = "",       # data does not contain quotes
#                       sep = "\t",       # data is tab separated
#                       header = T)       # data has column names
#base::saveRDS(mblrdata, file = here::here("data", "mbd.rda"))
mblrdata  <- base::readRDS(url("https://slcladal.github.io/data/mbd.rda", "rb"))
```

```{r pmm1}
# load data
#countdata <- read.table("https://slcladal.github.io/data/countdata.txt", 
#                       comment.char = "",quote = "", sep = "\t", header = T) 
#base::saveRDS(countdata, file = here::here("data", "cld.rda"))
countdata  <- base::readRDS(url("https://slcladal.github.io/data/cld.rda", "rb"))
```

```{r slr4, message=FALSE, warning=FALSE}
# load data
#slrdata <- read.delim("https://slcladal.github.io/data/lmmdata.txt", header = TRUE)
#base::saveRDS(slrdata, file = here::here("data", "sld.rda"))
slrdata  <- base::readRDS(url("https://slcladal.github.io/data/sld.rda", "rb"))
```

```{r}
# vector space data
cdo <- readLines("https://slcladal.github.io/data/origindarwin.txt")
base::saveRDS(cdo, file = here::here("data", "cdo.rda"))
cdo  <- base::readRDS(url("https://slcladal.github.io/data/cdo.rda", "rb"))

```



