project:
  title: "LADAL"
  output-dir: "../docs"
  type: website
  render:
    - "*.qmd"

toc: true
bibliography: bibliography.bib
csl: springer.csl
link-citations: true
toc_float: true
toc-location: left

execute:
  freeze: auto
  cache: true
  
format:
  html:
    theme: cosmo
    # css: styles.css
    number-sections: true

website:
  google-analytics: "G-VSGK4KYDQZ"
  navbar:
    # background: primary
    logo: "ladal_icon_cas_tran_white_trimed.png"
    title: "Language Technology and Data Analysis Laboratory"
    search: true
    left:
      - text: "HOME"
        file: index.qmd
      - text: "ABOUT LADAL"
        menu:
        - text: "People | Collabs"
          file: people.qmd
        - text: "News"
          file: news.qmd
      - text: "EVENTS"
        menu:
        - text: "Workshops"
          file: workshops.qmd
        - text: "Computational Thinking in HASS"
          file: compthinking.qmd
        - text: "LADAL Webinar Series 2022"
          file: webinars2022.html
        - text: "LADAL Webinar Series 2021"
          file: opening.qmd
        - text: "ATAP Events"
          file: atapevents.qmd
      - text: "TUTORIALS"
        file: tutorials.qmd
      - text: "RESOURCES"
        menu:
        - text: "Links"
          file: links.qmd
        - text: "Tutorial stylesheet"
          file: base.qmd
      - text: "CONTACT"
        file: contact.qmd

# name: "my-website"
# output: 
#   html_document:
#     includes: 
#       in_header: header.html
#     toc: true
#     #theme: united
#     theme: cosmo

# highlight: tango
# bibliography: references.bib
# csl: springer.csl
# #css: styles.css



