<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Martin Schweinberger" />


<title>Basic Concepts in Quantitative Research</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>
<link rel="stylesheet" href="styles.css" />

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VSGK4KYDQZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VSGK4KYDQZ');
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">



<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  
  <!-- Added by SKC - LADAL image and thicker top with   -->
  <div class="container-fluid navbar-top" >
    <a href="index.html"> <!-- Make entire top row and text clickable home link  -->
        <div class="row">
            <div class="navbar-brand col-md-12">
              <img src="/content/ladal_icon_cas_tran_white_trimed.png" class="navbar-icon" alt="LADAL"/>
              <span class="navbar-title-note navbar-collapse collapse" >Language Technology and Data Analysis Laboratory</span>
            </div>
        </div>
    </a>
  </div>
  
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- SKC removed  navbar brand -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">HOME</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    ABOUT LADAL
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="people.html">People | Collabs</a>
    </li>
    <li>
      <a href="news.html">News</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    EVENTS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="workshops.html">Workshops</a>
    </li>
    <li>
      <a href="compthinking.html">Computational Thinking in HASS</a>
    </li>
    <li>
      <a href="webinars2022.html">LADAL Webinar Series 2022</a>
    </li>
    <li>
      <a href="opening.html">LADAL Webinar Series 2021</a>
    </li>
    <li>
      <a href="atapevents.html">ATAP Events</a>
    </li>
  </ul>
</li>
<li>
  <a href="tutorials.html">TUTORIALS</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    RESOURCES
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="links.html">Links</a>
    </li>
    <li>
      <a href="base.html">Tutorial stylesheet</a>
    </li>
  </ul>
</li>
<li>
  <a href="contact.html">CONTACT</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Basic Concepts in Quantitative
Research</h1>
<h4 class="author">Martin Schweinberger</h4>
<h4 class="date">31 May, 2023</h4>

</div>


<p><img src="https://slcladal.github.io/images/uq1.jpg" width="100%" /></p>
<div id="introduction" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>Perhaps the most trivial and important issues related to the
processing and analysis of data are the questions <em>What is
statistics?</em> and <em>Why should I use statistics?</em>. A simple
answer to the first question is that statistics is a way to find out
about the world around us in quantitative terms. Statistics therefore
comprises methods that perform <em>quantitative analyses</em>.
Quantitative analyses use numeric information to understand the world
and they are very important in science (which I take here to refer to
any approach that uses the scientific method to gain a reliable
understanding of the world around us). The answer to the second question
is more complicated but we can say that we use statistics for three main
purposes:</p>
<ol style="list-style-type: lower-alpha">
<li>to summarize data (descriptive statistics)</li>
<li>to explore data, and (exploratory statistics)</li>
<li>to see how something is related or influenced by something else.
(inference statistics)</li>
</ol>
<p>I also have a very practical approach to statistics and like to think
of statistics as a kind of labor-saving device which helps me minimize
labor - either the effort associated with reporting a result or in the
effort of finding out about how two or more things are related based on
some form of data. As such, statistics comprises methods (quantitative
analyses) that we use in science to understand the world around us.
Science can be defined as a systematic enterprise that builds and
organizes knowledge in the form of testable explanations and predictions
about the universe <span class="citation">(<a
href="#ref-wilson1999natural" role="doc-biblioref">Wilson 1999,
58</a>)</span>. One of the most fundamental concepts in that definition
is the concept of testable explanations. Another name for such
explanations is <em>hypothesis</em>. Thus, Edward Wilson’s definition of
science can be rephrased (somewhat crudely) as the methodological
testing of hypotheses. This goes to show that hypotheses are at the very
heart of the scientific endeavor.</p>
<p>To get a better understanding of how we <em>do science</em>, this
tutorial introduces basic concepts that underpin (all) quantitative
analyses. To this end, we will try to understand what hypotheses are,
how to formulate them, and what logic underpins hypothesis testing. To
begin with, we will focus on a practical example to avoid talking merely
about abstract ideas. The example we will look at is the English
comparative construction.</p>
</div>
<div id="primer-english-comparatives" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Primer: English
Comparatives</h1>
<p>In English, the comparative forms of adjectives can be formed
according to two strategies: either synthetically (also called
morphologically) as in <a href="#id_1ex">(1)</a> or analytically (also
called periphrastically) as in <a href="#id_2ex">(2)</a>.</p>
<p>As a general rule, the comparative of adjectives that have only one
syllable are formed by using the morphological strategy while adjectives
that have three or more syllables are formed using the periphrastic
strategy. However, in some cases where adjectives consist of two
syllables, speakers may choose which strategy they apply. In our
example, we want to find out, how to proceed when trying to understand
the reasons why a speakers chooses the first strategy in one case and
the second strategy in another.</p>
<ol style="list-style-type: decimal">
<li><p>synthetic/morphological comparative<br />
proud <span class="math inline">\(\rightarrow\)</span> prouder</p></li>
<li><p>analytic/periphrastic comparative<br />
proud <span class="math inline">\(\rightarrow\)</span> more
proud</p></li>
</ol>
<p>To investigate this phenomenon more closely, we should first
determine which variables or factors influence which comparative
strategy a speaker uses. To answer which factors affect the comparative
choice, we need to have a look at the respective literature. In the
literature on the English comparative constructions the following
influencing factors have been named:</p>
<div id="length-of-the-adjective" class="section level3 unnumbered">
<h3 class="unnumbered">Length of the adjective</h3>
<p>Adjectives that consist of a single syllable tend to form the
comparative form via the morphological strategy as in (3) while
multi-syllabic adjectives tend to form the comparative via the
periphrastic strategy as in (4).</p>
<ol start="3" style="list-style-type: decimal">
<li><p>synthetic/morphological comparative: cool <span
class="math inline">\(\rightarrow\)</span> cooler</p></li>
<li><p>analytic/periphrastic comparative: attractive <span
class="math inline">\(\rightarrow\)</span> more attractive</p></li>
</ol>
</div>
<div id="syntactic-function" class="section level3 unnumbered">
<h3 class="unnumbered">Syntactic Function</h3>
<p>Adjectives in attributive position prefer the morphological strategy,
while adjectives in predicative position prefer the the periphrastic
strategy.</p>
<ol start="5" style="list-style-type: decimal">
<li><p>“<em>The prouder boy of the two was smiling</em>.”</p></li>
<li><p>“<em>The boy to the left was more proud</em>.”</p></li>
</ol>
</div>
<div id="ending" class="section level3 unnumbered">
<h3 class="unnumbered">Ending</h3>
<p>Adjectives which end in –ly or -y prefer the morphological
strategy.</p>
</div>
<div id="subsequent-than" class="section level3 unnumbered">
<h3 class="unnumbered">Subsequent <em>than</em></h3>
<p>If a <em>than</em> follows the comparative, then the adjective
prefers the morphological strategy as in (7).</p>
<ol start="7" style="list-style-type: decimal">
<li>“<em>This joke is funnier than the other one</em>.”</li>
</ol>
<p>It helps to create an overview table for the variables that have been
shown in the literature to significantly affect the choice of the
comparative strategy. Both better and worse examples of such overview
tables are shown in <span class="citation">(<a
href="#ref-gries2009statistics" role="doc-biblioref">Gries 2009,
27–30</a>)</span>. To answer our example question, we have to define the
variables in order to formulate a proper hypothesis in the next
step.</p>
<p>An example for such a hypothesis would, for instance, be <em>If an
adjectives has only one syllable, then a typical native speaker will
prefer the morphological variant</em>. The next question then is how to
test such a hypothesis and which concepts underlie hypothesis testing.
And these questions and issues are addressed below.</p>
</div>
</div>
<div id="hypotheses" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Hypotheses</h1>
<p>Probably the most important task in empirical research is hypothesis
testing. A proper scientific hypothesis is commonly - but not
necessarily - a general assumption in the form of a statement.
Hypotheses are tested by comparing systematic observation with the
predictions of the hypothesis. More specifically, in order to test
hypothesis one seeks for observations which contradict and are at odds
with the hypothesis. If we find such a counter example and we have
determined that it is an accurate observation, then the hypothesis is
falsified, i.e. is is not correct.</p>
<p>If we proposed the hypothesis <em>Apples always fall down.</em> and
we find an example of an apple not falling down, then our hypothesis
would be falsified.</p>
<hr />
<div class="warning"
style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Can you think of cases where apples do not fall down?<br></li>
</ol>
<details>
<summary>
Answer
</summary>
For example in space when there is no gravity or if another center of
gravity were so close that it would <em>pull</em> the apple towards that
more powerful center of gravity.
</details>
<ol start="2" style="list-style-type: decimal">
<li>How would we have to modify our hypothesis to accommodate potential
counter-examples?<br></li>
</ol>
<details>
<summary>
Answer
</summary>
Instead of saying <em>Apples always fall down.</em>, you could say
<em>Apples always fall towards</em> <em>the dominant center of
gravity.</em>
</details>
</div>
<p>`</p>
<hr />
<p>The fact that hypothesis must be falsifiable is a defining feature of
hypotheses and it means that for a statement to be a hypothesis, it must
be falsifiable (which does not mean that it must be false!).</p>
<p>The for trying to falsifying rather than proving or validating
hypothesis, lies in the act that falsification is possible while
providing proof for an empirical fact is impossible: If we make only one
observation which refutes a hypothesis, the hypothesis is falsified. No
matter how many evidence we have for that hypothesis, the hypothesis
remains falsified. It is therefore impossible to prove an empirical
hypothesis! There are, however, statements that cannot be disproved or
falsified - either for technical reasons (1) or because they are
subjective (2).</p>
<ol style="list-style-type: decimal">
<li><p><em>There are forms of life in the Andromeda
galaxy.</em></p></li>
<li><p><em>I like chocolate ice cream better than vanilla ice
cream.</em></p></li>
</ol>
<p>Statements that cannot be falsified are called <em>speculation</em>.
Speculation is nothing bad or something worthless - on the contrary! -
but they simply fall outside of the realm of empirical science. Examples
for the creativity and the usefulness of speculation are, for instance,
art, literature, music, and philosophy.</p>
<p>Summing up, hypotheses can be defined as possessing at least four
criteria:</p>
<ul>
<li><p>Hypotheses are falsifiable statements about empirical
reality.</p></li>
<li><p>Hypotheses are testable statements about the empirical
world.</p></li>
<li><p>Hypotheses are unambiguous.</p></li>
<li><p>Hypotheses are inherently consistent.</p></li>
</ul>
<p>Universality cannot be considered a defining feature of hypotheses,
because it is - strictly speaking - not necessary. For instance, we
could formulate the hypothesis that a certain archaeological model is
correct, if we find certain artifacts at a specific place in a certain
layer of earth. This hypothesis relates to a a very specific singular
event but it would still be a falsifiable and testable statement (and
thus a hypothesis).</p>
<hr />
<div class="warning"
style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Which of the following are hypotheses? Please provide reasons.<br>a.
Smoking could have negative effects on one’s health.<br>b. Alcohol is a
gateway drug.<br>c. If alcohol is a gateway drug, then it should be
criminalized.<br>d. If alcohol is a gateway drug but tobacco is not,
then a significantly higher proportion of drug addicts have consumed
alcohol compared with the proportion of drug addicts who have smoked
before taking drugs.<br>e. Alcohol is a gateway drug, when/if it is
illegal.<br>f. Colorless green ideas sleep furiously.<br>g. Nightingales
dream in Italian.</li>
</ol>
<details>
<summary>
Answer
</summary>
<ol style="list-style-type: lower-alpha">
<li>no hypothesis (ambiguous because it contains a modal:
<em>could</em>)<br>b. hypothesis (all criteria are met)<br>c. hypothesis
(all criteria are met)<br>d. hypothesis (all criteria are met)<br>e.
hypothesis (all criteria are met)<br>f. no hypothesis (not inherently
consistent)<br>g. no hypothesis (not testable).</li>
</ol>
</details>
</div>
<p>`</p>
<hr />
<div id="types-of-hypotheses" class="section level2 unnumbered">
<h2 class="unnumbered">Types of Hypotheses</h2>
<p>On a very fundamental level, we can differentiate between
null-hypotheses (H<span class="math inline">\(_{0}\)</span>), that claim
non-existence of either a state of being or a difference, and
alternative or test-hypothesis (H<span
class="math inline">\(_{1}\)</span>) that claim or postulate the
existence of of either a state of being or a difference. Among
test-hypotheses, we can furthermore distinguish between non-directed
hypotheses which claim that one sample is different from another sample,
and directed hypotheses which claim that a feature of one sample is
bigger, smaller, more frequent, or less frequent, etc. Thus, a
hypothesis that group A will perform better in an exam is a directed
test-hypothesis while an non-directed hypothesis would merely claim that
they differ in their test results. In contrast, the null-hypothesis
would claim that there is no difference between the groups in terms of
their performance in that exam.</p>
<p>An additional distinction among hypotheses is the difference between
deterministic and probabilistic hypotheses. While we are dealing with a
deterministic hypotheses in (10) because it is a categorical claim, we
are dealing with a probabilistic hypothesis in (11) because, here, the
hypothesis simply claims that the likelihood of Y is higher if X is the
case (but not necessarily categorically).</p>
<ol start="10" style="list-style-type: decimal">
<li><p>If the length of two words in an English phrase is different,
then the shorter word will always proceed the longer word.</p></li>
<li><p>If the length of two words in an English phrase is different,
then it is more likely for the shorter word to proceed the longer word
than vice versa.</p></li>
</ol>
</div>
<div id="why-test-the-h0" class="section level2 unnumbered">
<h2 class="unnumbered">Why test the H0?!</h2>
<p>Although it is counter-intuitive, we do not actually test the
test-hypothesis but we test the null-hypothesis. We will now have a
closer look at how to formulate hypotheses and that formulating
hypotheses is formulating expected outcomes/explanations in a formal
description.</p>
<ul>
<li><p>Null hypothesis (H<sub>0</sub>) Groups A and B do not differ
systematically! (<span class="math inline">\(\mu\)</span>A = <span
class="math inline">\(\mu\)</span>B)</p></li>
<li><p>Test hypothesis (H<span class="math inline">\(_{1a}\)</span>)
Groups A and B differ systematically! (<span
class="math inline">\(\mu\)</span>A <span
class="math inline">\(\neq\)</span> <span
class="math inline">\(\mu\)</span>B; non-directed)</p></li>
<li><p>Test hypothesis (H<span class="math inline">\(_{1b}\)</span>)
Group A has significantly better results/higher levels of x compared
with group B. (<span class="math inline">\(\mu\)</span>A <span
class="math inline">\(&gt;\)</span> <span
class="math inline">\(\mu\)</span>B; directed)</p></li>
</ul>
<p>What does that mean and what are we testing? In non-technical terms,
we test how likely it is that the results came about by accident. If the
probability is high (p &gt; .05) that the results happen to be random,
then we do not discard the H<sub>0</sub>. If the likelihood is low (p
&lt; .05) that the results came about randomly, then we discard the
H<sub>0</sub> and assume the H<sub>1</sub> instead! To better understand
this logic, we will discuss probabilities and their role in quantitative
research.</p>
<hr />
<div class="warning"
style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>What four characteristics do hypotheses have?</li>
</ol>
<details>
<summary>
Answer
</summary>
They are are <em>falsifiable</em> (either true or false), they are
<em>testable</em>, they are <em>unambiguous</em>, and they are
<em>inherently consistent</em> (logically coherent).
</details>
<ol start="2" style="list-style-type: decimal">
<li>Come up with (a) three directed hypotheses and (b) three
non-directed hypotheses.</li>
</ol>
<details>
<summary>
Answer (examples)
</summary>
<br><strong>Directed</strong><br>In a 100 meter dash, Martin runs faster
than Jack.<br>In informal conversations, Martin uses fewer swearwords
than Michael.<br> Per minute, Martin can produce more words than
Erich.<br><br><strong>Non-directed</strong><br>Martin and Michael differ
in their use of swear words.<br>Martin and Erich differ in their speech
speed.<br>Stefan and Martin differ in their need for sleep.<br>
</details>
<ol start="3" style="list-style-type: decimal">
<li><p>Oftentimes, it is not that easy to differentiate between
hypotheses and other types of statements. Find a partner and come with
statements that are not hypotheses and discuss why these statements are
not hypotheses.</p></li>
<li><p>Find a partner and come up with statements that can be classified
as both hypotheses and non-hypotheses and be prepared to explain your
reasoning to the group.</p></li>
</ol>
</div>
<p>`</p>
<hr />
</div>
</div>
<div id="data-and-research-designs" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Data and Research
Designs</h1>
<p>In the previous section, we have dealt with hypotheses and in this
section, we want to focus on how we can test hypotheses. To this end, we
will focus on data and different research designs.</p>
<p>Before we turn to different designs that are used to test hypotheses,
however, let us briefly talk about the terms <strong>sample</strong> and
<strong>population</strong> as this will be important to our discussion
of how we can test hypotheses. A <em>sample</em> is a selection from a
<em>population</em> that should reflect the features of the population
one is interested in. We speak of <em>a</em> population instead of
<em>the</em> population, because there are many different populations
and we need to be very conscious about what population we are able to
infer something about. For example, if the sample includes only Germans
between 20 and 30, then the population the sample is drawn from is not
the totality of all Germans, but only the population of Germans between
20 and 30 at this point in time. Of course, this is very simplistic, as
other factors are ignored in this example.</p>
<div id="research-designs" class="section level2 unnumbered">
<h2 class="unnumbered">Research Designs</h2>
<p>Now that the terms sample and population are clear, we can continue
to think about how we could test hypotheses. In the empirical sciences,
we try to answer questions we have by analyzing data. However, before we
can attempt to answer a question and test if we are right with the
answer we have in mind (our hypothesis), we have to decide on how to
tackle the question. Thus, we have to come up with a plan about how to
test our hypothesis. This plan is called a <strong>research
design</strong>. The research design informs how to collect, process,
visualize, and analyze the data. As such, the research design focuses on
all aspects of research that are related to the data.</p>
<p>Thus, after comping up with a research question and a hypothesis, the
next step typically consists in collecting the right type of data. There
are different ways to collecting data and these different ways to
collect data represent different research designs. We cannot go over all
the different designs (and they can be combined, for instance,
introspection is often a part of questionnaire designs), but we will
focus and briefly discuss the most common ones.</p>
<p>In general, we can distinguish between experimental and observational
designs. In contrast to observational designs (which can only confirm
correlations, i.e. that X and Y occur together), experimental designs
are more powerful in that they can determine causality (i.e., if X
causes Y). We the most common research designs in the language sciences
are</p>
<ul>
<li>experimental
<ul>
<li>experimental designs (e.g., reaction times, eye-tracking)</li>
</ul></li>
<li>observational
<ul>
<li>behavioral designs (e.g., corpora)</li>
<li>archival/reviews (e.g., grammars, systematic literature
reviews)</li>
<li>introspection (e.g., grammaticality judgements)</li>
<li>questionnaire designs (e.g., elicitation via surveys and
questionnaires)</li>
</ul></li>
</ul>
<p>There are more designs(e.g. meta-studies) and also other
classifications, but in the language sciences, I think that the ones
listed above are the most frequent ones. Each of these designs has
advantages and disadvantages which are briefly summarized in the table
below.</p>
<pre class="r"><code>install.packages(&quot;e1071&quot;)
install.packages(&quot;flextable&quot;)
install.packages(&quot;ggplot2&quot;)
install.packages(&quot;ggpubr&quot;)
install.packages(&quot;graphics&quot;)
install.packages(&quot;grDevices&quot;)
install.packages(&quot;knitr&quot;)
install.packages(&quot;tidyverse&quot;)</code></pre>
<div class="tabwid"><style>.cl-09e49252{table-layout:auto;width:75%;}.cl-09d8cdc8{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-09d8cdd2{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-09dd48b2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-09dd681a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd681b{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd6824{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd682e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd682f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd6838{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd6839{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd683a{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd6842{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd6843{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd684c{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09dd684d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-09e49252'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Overview of advantages and disadvantages of different research designs.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-09dd681a"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Type</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Research design</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Example</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Directness of access to phenomenon</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Cost/Labor intensity</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">External validity (generalizability)</span></p></th><th class="cl-09dd681b"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Internal validity</span></p></th><th class="cl-09dd6824"><p class="cl-09dd48b2"><span class="cl-09d8cdc8">Ease of data collection (e.g. access to participants)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-09dd682e"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Experimental research</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Experimental</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Reaction time measurements</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high/variable</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high/variable</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low/variable</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd6838"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td></tr><tr style="overflow-wrap:break-word;"><td  rowspan="4"class="cl-09dd6839"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Observational research</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Behavioral</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Corpus study</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low/variable</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd6842"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">medium</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Archival/Review</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Systematic literature review</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td><td class="cl-09dd682f"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">medium</span></p></td><td class="cl-09dd6838"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Introspection</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Grammaticality judgements</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low/variable</span></p></td><td class="cl-09dd683a"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td><td class="cl-09dd6842"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Questionnaire</span></p></td><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">Language use survey</span></p></td><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">medium</span></p></td><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">low</span></p></td><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">medium</span></p></td><td class="cl-09dd684c"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">medium</span></p></td><td class="cl-09dd684d"><p class="cl-09dd48b2"><span class="cl-09d8cdd2">high</span></p></td></tr></tbody></table></div>
<p>We will now briefly focus on each design and discuss it.</p>
<div id="experimental-research" class="section level3 unnumbered">
<h3 class="unnumbered">Experimental research</h3>
<p>Experimental designs can determine if there is a causal link between
predictors and response which sets experimental designs apart from
observational designs. Experiments typically take place in very
well-controlled, but unnatural environments, .e.g, in laboratories.</p>
<p>In experimental designs, subjects are typically <em>randomly</em>
assigned into <em>test groups</em> and <em>control groups</em> and the
experimenter. If the subjects are not assigned randomly to test and
control groups, the design is referred to as <em>quasi-experimental</em>
(while experimental designs with randomized allocation of subjects are
referred to as <em>true experiments</em>). The aim of experiments, in
the most basic sense, is to determine if a result differs based on a
change in some condition. The experimenter would change the condition
only in the test group while not changing it in the control group while
everything else remains constant. That way, it is possible to test if
the change in the condition is responsible for the change in the
outcome.</p>
<p>During an experiment, subjects are shown <em>stimuli</em> (e.g.,
sentences, words, pictures) and the subjects (should) react to those
stimuli showing a <em>response</em> (pressing buttons, providing
judgments). The response does not have to be voluntary, meaning that
responses can also simply be neuronal activity that the subject has no
control over. In repeated measure designs, the same subjects are tested
repeatedly while different subjects are tested in between-subjects
designs.</p>
<p>In addition to the ability to establish causality, experimental
designs allow a very direct access to a phenomenon and have <em>high
internal validity</em> which means that experiments can test the
phenomena in a very well-circumscribed and precise manner. Disadvantages
of experimental designs are that they are typically rather costly and
labor intensive and that the results are not necessarily generalizable
due to the un-natural setting of most experiments (<em>low external
validity</em>).</p>
</div>
<div id="quasi-experimental-research" class="section level3 unnumbered">
<h3 class="unnumbered">Quasi-experimental research</h3>
<p>In contract to experimental designs, subjects (or participants) in
quasi-experimental designs are <em>not randomly</em> assigned to groups.
Because of this, quasi-experimental designs can be affected by
confounding (i.e., that changes in the dependent variable are caused by
a variable that is not controlled for). As such, quasi-experimental
designs are <strong>not</strong> experimental designs but can be
considered observational. Examples for quasi-experimental designs are
corpus-based variationist studies of the occurrence of linguistics
variants in a variable context.</p>
<p>Quasi-experimental designs encompass studies where subjects cannot be
randomly assigned into test groups because either, this is not
practically possible because the observation has already taken place or
because the characteristic is inherent in the participants themselves.
For instance, analyses of historical data can at best be
quasi-experimental because the data have already been collected and the
experimenter cannot assign participants to test groups. Also, some
studies that analyze sex differences via the behavior of men and women
cannot be experimental because participants cannot be randomly assigned
to the <em>male</em> or <em>female</em> group.</p>
</div>
<div id="observational-designs" class="section level3 unnumbered">
<h3 class="unnumbered">Observational designs</h3>
<p>In the language sciences, observational designs encompass all forms
of data acquisition and collection where the subjects are observed in
their “natural habitat”. Hence, observational or behavioral designs are
the most natural and thus have <em>high external validity</em> which
means that we can assume that the results are transferable to the
<em>real world</em>. The most common type of this design are corpus
studies in which texts (which encompasses both written and transcribed
spoken language) are searched for the occurrence of certain linguistic
patterns and then correlated with some other feature, the use of a
certain linguistic construction such as a specific suffix or a fixed
expression like <em>in order that</em> in two different time periods or
dialects.</p>
<p>The cost and labor intensity of corpus studies depends heavily upon
if the corpus that you want to use has already been compiled - if the
corpus is already available, the the costs and labor intensity are
minimal but they can be high if the corpus has to be compiled first.
However, even compiling a corpus can be comparatively easy and cheap,
for example, if you compile a corpus consisting of a collection of texts
that are available online but the costs can be substantive if you, for
example, first need to record and transcribe spoken language in the
field).</p>
<p>The problem with observational designs are that the contexts in which
the data were collected were not controlled with means that the results
are more likely to be affected by contextual or confounding factors that
the researchers have no control over or don’t even know about.</p>
</div>
<div id="archival-research-and-reviews"
class="section level3 unnumbered">
<h3 class="unnumbered">Archival research and reviews</h3>
<p>Archival research is more common in historical linguistics where
researchers look for primary texts or records in archives. However,
archival research also encompasses digital archives such as libraries
which means that systematic literature reviews also fall under this
research design.</p>
<p>The advantages of archival research designs are that the data
collections is typically comparatively easy and associated with minimal
costs. Also, depending on the phenomenon, the access to the phenomenon
can be quite indirect, for example, entirely filtered through the eyes
of eye witnesses or experts.</p>
</div>
<div id="introspection" class="section level3 unnumbered">
<h3 class="unnumbered">Introspection</h3>
<p>Introspection has been the dominant form of “data collection” in the
20^th century and it is strongly connected to what is called
<em>armchair linguistics</em> (linguists coming to insights about
language by musing about what they can or would say and what they could
or would not say). Introspection is, of course, by far the easiest and
cheapest way to “collect data”. Unfortunately, introspection is
<em>subjective</em> and can be heavily biased by the expectations and
theoretical framework of subjects. Nonetheless, introspection can be and
is extremely useful in particular regarding hypothesis generation and
finding potential predictors for a certain linguistic behavior that can
then be tested empirically.</p>
<p>Since the 1990s and the rise of empirical linguistics, which is
characterized by the employment of both experimental designs as well as
corpus linguistics and increased use of questionnaire designs,
introspection has been relegated to playing a part of other designs
while only rarely being used as the sole source of data collection.</p>
</div>
<div id="questionnaire-designs" class="section level3 unnumbered">
<h3 class="unnumbered">Questionnaire designs</h3>
<p>Questionnaire designs represent any method of data collection where
respondents are asked to provide (conscious) information to answers or
ratings/evaluations to prompts (such as statements). The process to ask
for information from respondents is called <em>elicitation</em>.</p>
<p>In addition to <em>surveys</em> which ask for socio-demographic
information about speakers or about language use and language background
information, <em>questionnaires</em> frequently ask respondents to rate
their agreement with items, or the likelihood, frequency, or
acceptability of items on <em>Likert scales</em>. A Likert scale,
pronounced /lick.ert/ and named after the psychologist Rensis Likert,
and often ranges from <em>strongly disagree</em> to <em>strongly
agree</em> (or analogously from <em>never</em> to <em>very
frequently</em> or <em>extremely unlikely</em> to <em>extremely
likely</em>). Typically, respondents are given 5 or 7 options with the
endpoints noted above representing the endpoints and respondents are
asked to select the options that best matches their evaluation.</p>
<p>A type of elicitation that is special in the language science is
called <em>discourse completion task</em> or DCT. In DCTs, respondents
are asked to imagine a certain discourse context or situation and are
then asked how they would answer, respond, or express something. While
DCTs have been shown to provide data that mirrors real-world behaviors,
it is less reliable compared to corpus data as respondents cannot
necessarily provide accurate information about their linguistic
behavior.</p>
<p>To counter <em>fatigue effects</em> (respondents get tired or annoyed
and do no longer answer to the best of their knowledge/ability),
questionnaire items are often randomized so that their order differs
between respondents. To counter what is called <em>agreeability
effects</em>, researchers commonly have respondents rate test items
(items that contain the phenomenon researchers are interested in) and
fillers (items that do not contain what researchers are interested in).
Fillers are included to disguise what the questionnaire aim to test so
that respondents cannot (unconsciously) try to provide agreeable answers
(the answers that researchers hope to get).</p>
</div>
</div>
</div>
<div id="variables-and-validity" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Variables and
Validity</h1>
<p>A statistical variable is a characteristic that can take on a
specific form. A variable, in contrast to the constant, can take on at
least two different stages or levels. The variables in your hypothesis
must be operationalized, i.e., you need to determine what exactly needs
to be investigated, what counts, what is measured. In other words,
<em>operationalization</em> is the measurement of a variable. If
possible, a variable should be operationalized so that its measurement
is as good as possible reflects the underlying concept.</p>
<p>The correspondence between the concept and the variable that
operationalizes the concept is referred to as <em>intrinsic
validity</em>. An example of intrinsic validity would be, for example,
an operationalization of linguistic complexity that reproduces them well
measurable (for example, number of morphemes in a phrase, number of
syntactic nodes, or similar).</p>
<p>The counterpart, <em>external validity</em>, denotes the
applicability of the insights gained, for example, from an experimental
investigation to the real empirical world. For instance, one could
experimentally investigate which methods lead to better recall of
nonsense-syllables (syllables not occurring in the speakers’ natural L1)
but this would not necessarily allow us to generalize these finding to
the “real” world. External validity in this context would mean that the
findings can also be transferred to other real-world memory tasks, such
as vocabulary learning.</p>
<p>There are two types of variables, <em>dependent</em> and
<em>independent</em>. The independent variable(s) represents the
predictor(s). In research, we typically want to investigate how
predictors (independent variables) affect and outcome or result (the
dependent variable). In experiments, the independent variable(s) are
manipulated to investigate its influence on the dependent variable. Let
us take the example of a medical study to illustrate this: in a typical
medical study, the influence of a particular drug (independent variable)
on the presence of symptoms (dependent variable) is measured.</p>
<p>It is extremely important to know the type of variable, as this has a
direct impact on what statistical analysis is possible for the data at
hand. We will therefore discuss various types of variables and their
properties below.</p>
<div id="variable-types-scaling" class="section level2 unnumbered">
<h2 class="unnumbered">Variable Types (Scaling)</h2>
<p>In the following, variable types (also referred to as <em>scaling
level</em> or <em>scaling</em>) are discussed. It is very important to
know which type of variables one is dealing with because the type of
variable has affects many of the methods discussed, both in descriptive
and in inferential statistics.</p>
<div id="nominal-and-categorical-variables"
class="section level3 unnumbered">
<h3 class="unnumbered">Nominal and Categorical Variables</h3>
<p>Nominal and categorical variables only list the membership of a
particular class. For nominal variables, there are exactly two
occurrences (yes/no or on/off), while for categorical variables there
can be several groups, e.g. the state in which someone was born.</p>
</div>
<div id="ordinal-variables" class="section level3 unnumbered">
<h3 class="unnumbered">Ordinal Variables</h3>
<p>With <em>ordinal variables</em> it is possible to rank the values,
but the distances between the ranks can not be exactly quantified. An
example of an ordinal variable is the ranking in a 100-meter dash. The
2<sup>nd</sup> in a 100-meter dash did not go twice as fast as the
4<sup>th</sup>. It is often the case that ordinal variables consist of
integer, positive numbers (1, 2, 3, 4, etc.).</p>
</div>
<div id="true-numeric-variables" class="section level3 unnumbered">
<h3 class="unnumbered">(True) Numeric Variables</h3>
<p>There are two basic types of numeric variables: <em>interval-scaled
variables</em> and <em>ratio-scaled variables</em>. For <em>interval
scaled variables</em>, the differences between levels are significant,
but not the relationship between levels. For instance, 20 degree Celsius
is not twice as hot as 10 degree Celsius.</p>
<p>With respect to <em>ratio-scaled variables</em>, both the differences
and the relationship between the levels are significant. An example of
this is the times in a 100-meter dash. For ratio-scaled variables, 10 is
exactly twice as high as 5 and half as much as 20.</p>
<p>It is very important to keep in mind that both <em>interval-scaled
variables</em> and <em>ratio-scaled variables</em> are numeric
variables. This will play a role later because many tests can either
only or never be applied to numeric variables.</p>
<div class="tabwid"><style>.cl-09fc430c{table-layout:auto;width:75%;}.cl-09f1b374{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-09f1b37e{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-09f5e53e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-09f63426{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f6343a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f63444{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f63445{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f6344e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f6344f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f63458{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-09f63459{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-09fc430c'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Variable types/Variable scales with examples.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-09f63426"><p class="cl-09f5e53e"><span class="cl-09f1b374">Variable Type</span></p></th><th class="cl-09f6343a"><p class="cl-09f5e53e"><span class="cl-09f1b374">Variable Level</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-09f63444"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Nominal Scaled / Categorical Variables</span></p></td><td class="cl-09f63445"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Gender, Nationality, Part of Speech</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09f6344e"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Ordinal Scaled Variables</span></p></td><td class="cl-09f6344f"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Graduation, School Grades, Military Rank</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09f63444"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Interval Scaled Variables</span></p></td><td class="cl-09f63445"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Temperature, Acceptability Judgments</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-09f63458"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Ratio-scaled Variables</span></p></td><td class="cl-09f63459"><p class="cl-09f5e53e"><span class="cl-09f1b37e">Age, Duration, Number of Syllables</span></p></td></tr></tbody></table></div>
<p>It is enormously important to know variable types and levels, as the
type of variable requires which tests are possible and which are not.
For example, a <span
class="math inline">\(\chi\)</span><sup>2</sup>-test can only be applied
to nominal or categorical variables, and a t-test to numeric variables
only.</p>
<p>It is often necessary to translate variables into another type of
variable. It should be noted that variables can only be transferred to
variable types with less information content. The least informative
variables are nominal, while the most informative variables are ratio
scaled. The variable types thus form an implicit hierarchy:</p>
<p>nominal/categorical &lt; ordinal &lt; interval/ratio</p>
<p>Here is an example to illustrate this: let’s say you are
investigating gender differences in the use of swear words in spoken
Irish English and you find that you cannot use a linear regression or an
ANOVA because too many speakers use no swear words (which violates the
requirement that the errors must be normally distributed). In such a
case, what one can do is to rank the speakers by their frequency of
swear or curse words. Rank 1 would represent the speaker with the
highest frequency of swear words, rank 2 would represent the speaker
with the second highest frequency of swear words and so on. After you do
this, you can, for example, use a Mann-Whitney U test to determine the
relationship between the gender of speakers and their swear word
ranking. You could also split the speakers into two groups (swear word
users and non-swear-word users) and then perform a <span
class="math inline">\(\chi\)</span><sup>2</sup>-test of the frequencies
of men and women in these groups. The important thing is that you cannot
transform a categorical variable into a numeric variable as this would
mean that you transform a less information-rich variable into a more
information-rich variable.</p>
<hr />
<div class="warning"
style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>For each of the variables listed below, consider how you could
operationalize them and what kind of variables it would be.<br>a.
weather (cloudy, sunny, rainy, etc.)<br>b. citizenship<br>c. Tense of
matrix verbs<br>d. Structural complexity<br>e. word length<br>f. Number
of syllables in a word<br>g. The length of pauses in a sample of
conversations<br>h. The appearance or non-appearance of finite verbs in
a particular text<br>i. Estimation of words on an acceptability scale
from 1 to 5</li>
</ol>
<details>
<summary>
Answer (examples)
</summary>
<br><strong>There are other solutions so the following are just possible
options!</strong><br>a. weather could, e.g., be operationalized as the
number of sunny days or the amount of rain per year. Optimally, we would
want weather to be operationalized as a <em>numeric</em>
variable.<br>b).citizenship would typically be operationalized as a
<em>categorical</em> variable (e.g. German or Norwegian or Australian or
other).<br>c. This answer depends on the grammatical structure of the
language in question. In English, we would probably operationalize the
tense of matrix verbs as a <em>nominal</em> variable with the levels
<em>present</em> and <em>non-present</em>.<br>d. Structural complexity
can be operationalized in many different ways, e.g., as the number of
syntactic nodes, sentence length, number of phrases, average phrase
length, etc. Optimally, we would want structural complexity to be
operationalized as a <em>numeric</em> variable.<br>e. Word length
could,e.g. be operationalized as number of letters, number of phonemes,
or the time it takes to produce that word. Thus, word length would
typically be operationalized as a numerically scaled variable or an
integer (which, in R, would be a type of <em>numeric</em>
variable).<br>f. The number of syllables per word would be
operationalized as an integer (which, in R, would be a type of
<em>numeric</em> variable).<br>g. The length of pauses in a sample of
conversations could be operationalized as the time of the pause
(numeric) or even just as an ordered factor (short, middle, long).
Optimally, however, we would want the length of pauses to be
operationalized as a <em>numeric</em> variable.<br>h. The appearance or
non-appearance of finite verbs in a particular text would be a
<em>nominal</em> variable (present versus absent).<br>i. (The estimation
of words on an acceptability scale from 1 to 5 represents judgements on
a Likert scale which means that the resulting variable would represent
an order factor (<em>ordinal</em> variable).<br>
</details>
<ol start="3" style="list-style-type: decimal">
<li><p>As you have seen from the above exercise, concepts can be
operationalized differently. Find a partner and imagine that you are
tasked with performing a study in which age of subjects is an important
variable. Discuss with a partner how you would age. What advantages and
disadvantages do the different operationalizations have?</p></li>
<li><p>Example: <em>When it rains, more people get wet than when it’s
not raining. (If X, then Y)</em><br>What is the dependent variable here
and what is the independent variable?</p></li>
</ol>
<details>
<summary>
Answer
</summary>
<br>Dependent variable: wet people<br> Independent variable: rain<br>
</details>
<ol start="5" style="list-style-type: decimal">
<li>Which variable scales are <em>time</em>, <em>rank</em>, and
<em>name</em> in the table below?</li>
</ol>
<div class="tabwid"><style>.cl-0a139854{table-layout:auto;width:75%;}.cl-0a0948a4{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0a0948ae{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0a0d683a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0a0d8374{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d837e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d837f{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d8380{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d8388{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d8389{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d8392{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d8393{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d839c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d839d{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d83a6{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0a0d83a7{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0a139854'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Results of a 100 meter dash.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-0a0d8374"><p class="cl-0a0d683a"><span class="cl-0a0948a4">Name</span></p></th><th class="cl-0a0d837e"><p class="cl-0a0d683a"><span class="cl-0a0948a4">Rank</span></p></th><th class="cl-0a0d837f"><p class="cl-0a0d683a"><span class="cl-0a0948a4">Time</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-0a0d8380"><p class="cl-0a0d683a"><span class="cl-0a0948ae">Carl Lewis</span></p></td><td class="cl-0a0d8388"><p class="cl-0a0d683a"><span class="cl-0a0948ae">1</span></p></td><td class="cl-0a0d8389"><p class="cl-0a0d683a"><span class="cl-0a0948ae">9.86</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0a0d8392"><p class="cl-0a0d683a"><span class="cl-0a0948ae">Ben Johnson</span></p></td><td class="cl-0a0d8393"><p class="cl-0a0d683a"><span class="cl-0a0948ae">2</span></p></td><td class="cl-0a0d839c"><p class="cl-0a0d683a"><span class="cl-0a0948ae">9.97</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0a0d839d"><p class="cl-0a0d683a"><span class="cl-0a0948ae">Steve Davis</span></p></td><td class="cl-0a0d83a6"><p class="cl-0a0d683a"><span class="cl-0a0948ae">3</span></p></td><td class="cl-0a0d83a7"><p class="cl-0a0d683a"><span class="cl-0a0948ae">10.06</span></p></td></tr></tbody></table></div>
<details>
<summary>
Answer
</summary>
<br><em>Name</em> is categorical, <em>Rank</em> is ordinal, and
<em>Time</em> is numeric.<br>
</details>
<ol start="6" style="list-style-type: decimal">
<li><p>Discuss with a partner: what obstacles might exist, so that a
well operationalized variable has low extrinsic validity?</p></li>
<li><p>Consider the following scenario: in a large representative study,
shoe size is found to be an excellent predictor of intelligence. Given
this result, find a partner and discuss if intrinsic validity is
necessary?</p></li>
</ol>
</div>
<p>`</p>
<hr />
</div>
</div>
</div>
<div id="relationsships-between-variables" class="section level1"
number="6">
<h1><span class="header-section-number">6</span> Relationsships between
variables</h1>
<p>Most research aims to understand how something (or many things)
influence something else. This means that research is interested in the
relationships between variables. In statistics, a relationship between
variables is commonly referred to as <em>correlation</em>. There are
different types of relationships (correlations) and they can be
classified along several dimensions:</p>
<ul>
<li><p><em>strength</em>: how strong is the relationship between the
variables?</p></li>
<li><p><em>direction</em>: is the relationship positive or
negative?</p></li>
<li><p><em>linearity</em>: is the relationship steady?</p></li>
<li><p><em>homogeneity</em>: is the relationship consistent?</p></li>
</ul>
<p>The visualizations below show linear positive correlations of varying
strength. The strength of a correlation (relationship) represents how
well one variable explains variability in the other variable: the better
a variable explains the variability of another variable, the stronger
the correlation between the two variables. In the visualizations below,
we can see that the variability or dispersion in substantively more
pronounced in the plot showing a weak correlation (indicated by the
distances between the data points and the regression line) compared to
the visualization that depicts a strong correlation (where the data
points are very close to the regression line).</p>
<p><img src="basicquant_files/figure-html/coor1-1.png" width="672" /></p>
<p>In contrast to the positive linear correlations depicted above, where
the variables have a <em>the higher the values of x, the higher the
values of y</em> correspondence, negative correlations have a <em>the
higher the values of x, the lower the values of y</em> correspondence.
The strength of the correlations is, however, not affected by its
direction.</p>
<p><img src="basicquant_files/figure-html/coor2-1.png" width="672" /></p>
</div>
<div id="significance-and-probability" class="section level1"
number="7">
<h1><span class="header-section-number">7</span> Significance and
Probability</h1>
<p>Hypothesis testing fundamentally builds on probabilities - or more
precisely probabilities of error which is an estimation for the
likelihood of the H<sub>0</sub> being true given the data. In other
words, we are interested in how likely the null hypothesis
(H<sub>0</sub>) is. If the null hypothesis (H<sub>0</sub>) is very
unlikely, for instance lower than 5 percent, we can assume that the null
hypothesis is not true and thus reject it and instead assume that our
test hypothesis (H<sub>1</sub>) is correct.</p>
<p>This type of probability, the probability ( the probability that the
null hypothesis is true) is typically provided in the form of p-values.
In a more prosaic (and also coarse-grained, imprecise manner), p-values
are an estimate of how likely an outcome is a result of chance. We will
delve a little deeper into probabilities and how they relate to
hypothesis testing below.</p>
<div id="significance-levels" class="section level2 unnumbered">
<h2 class="unnumbered">Significance Levels</h2>
<p>Before conducting a study, it is advisable to determine the so-called
significance level or <span class="math inline">\(\alpha\)</span> level.
This <span class="math inline">\(\alpha\)</span> level or level of
significance indicates how high the p-value can be without having to
assume that there is a significant relationship between the variables.
It is customary to differentiate between three levels of significance
(also called <span class="math inline">\(\alpha\)</span> levels):</p>
<ul>
<li><p>p &lt; .001: <em>highly significant</em> - indicated by three
stars (***)</p></li>
<li><p>p &lt; .01: <em>very significant</em> - indicated by two stars
(**)</p></li>
<li><p>p &lt; .05: <em>significant</em> - indicated by one star
(*)</p></li>
</ul>
<p>Variables with a p value that is smaller than .1 but larger than .05
are sometimes referred to as being <em>marginally significant</em>
(+).</p>
<p>Variables that are not significant are commonly referred to or
labeled as <em>n.s.</em> (not significant). As we stated above, before
we perform a test, we determine a value above which we reject the null
hypothesis, the so-called significance level. It’s usually 5%. If the
error probability is less than 5% (p &lt;. 05), we reject the null
hypothesis. Conclusion: The relationship between the variables is
statistically significant. It is important to note here that the
H<sub>1</sub> (or Test Hypothesis) is correct only because the null
hypothesis can be rejected! Statistics can NEVER prove hypotheses but
only reject Null Hypotheses which leads us to accept the H<sub>1</sub>
as preliminary accepted or not-yet-rejected. So all knowledge is
preliminary in the empirical sciences.</p>
</div>
<div id="probability" class="section level2 unnumbered">
<h2 class="unnumbered">Probability</h2>
<p>In the following, we will turn to probability and try to understand
why probability is relevant for testing hypotheses. This is important at
this point because statistics, and thus hypothesis testing,
fundamentally builds upon probabilities and probability distributions.
In order to understand how probability works, we will investigate what
happens when we flip a coin. The first question that we will be
addressing is “<em>What is the probability of getting three Heads when
flipping a coin three times?</em>”.</p>
<p>The probability of getting three heads when flipping a coin three
times is .5 to the power of 3: .5<sup>3</sup> = .5 times .5 times .5 =
.125. The probability of getting Heads twice when flipping the coin
three times is .375. How do we know?</p>
<p>The probability of getting 3 heads in tree tosses is 12.5
percent:</p>
<p>.5<sup>3</sup> = .5 * .5 * .5 = .125</p>
<p>The probability of getting 2 heads in tree tosses is 37.5
percent:</p>
<p>.125 + .125 + .125 = 0.375</p>
<p>But how do we know this? Well, have look at the table below.</p>
<hr />
<div class="tabwid"><style>.cl-0b5321a8{table-layout:auto;width:75%;}.cl-0b48101a{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0b481024{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0b4c4004{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0b4c5d64{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d65{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d6e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d6f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d70{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d78{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d79{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d82{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d83{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d8c{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d8d{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0b4c5d96{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0b5321a8'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>All possible results of 3 coin tosses.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-0b4c5d64"><p class="cl-0b4c4004"><span class="cl-0b48101a">Toss 1</span></p></th><th class="cl-0b4c5d65"><p class="cl-0b4c4004"><span class="cl-0b48101a">Toss 2</span></p></th><th class="cl-0b4c5d65"><p class="cl-0b4c4004"><span class="cl-0b48101a">Toss 3</span></p></th><th class="cl-0b4c5d65"><p class="cl-0b4c4004"><span class="cl-0b48101a">Heads</span></p></th><th class="cl-0b4c5d65"><p class="cl-0b4c4004"><span class="cl-0b48101a">Tails</span></p></th><th class="cl-0b4c5d6e"><p class="cl-0b4c4004"><span class="cl-0b48101a">Probabilty</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d6f"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">3</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">0</span></p></td><td class="cl-0b4c5d78"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d79"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d83"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d6f"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d78"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d79"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d83"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d6f"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d78"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d79"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d82"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d83"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d6f"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">Head</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">1</span></p></td><td class="cl-0b4c5d70"><p class="cl-0b4c4004"><span class="cl-0b481024">2</span></p></td><td class="cl-0b4c5d78"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0b4c5d8c"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d8d"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d8d"><p class="cl-0b4c4004"><span class="cl-0b481024">Tails</span></p></td><td class="cl-0b4c5d8d"><p class="cl-0b4c4004"><span class="cl-0b481024">0</span></p></td><td class="cl-0b4c5d8d"><p class="cl-0b4c4004"><span class="cl-0b481024">3</span></p></td><td class="cl-0b4c5d96"><p class="cl-0b4c4004"><span class="cl-0b481024">0.125</span></p></td></tr></tbody></table></div>
<hr />
<p>Given this table, we are in fact, in a position to calculate the
probability of getting 100 heads in 100 coin tosses because we can
simply fill in the numbers in the formulas used above: .5<sup>100</sup>
= 7.888609 * 10<sup>-31</sup></p>
<p>Okay, let us make a bet..</p>
<ul>
<li><p>If head shows, I win a dollar.</p></li>
<li><p>If tails shows, you win a dollar.</p></li>
</ul>
<p>But given that you know I am cheeky bastard, you do not trust me and
claim that I will cheat. But how will you know that I cheat? At which
point can you claim that the result is so unlikely that you are
(scientifically backed) allowed to claim that I cheat and have
manipulated the coin?</p>
<p><img src="basicquant_files/figure-html/normal2-1.png" width="672" /></p>
<p>So before we actually start with the coin tossing, you operationalize
your hypothesis:</p>
<ul>
<li><p>H<sub>0</sub>: The author (Martin) is not cheating (heads shows
just as often as tails).</p></li>
<li><p>H<sub>1</sub>: The author (Martin) is cheating (heads shows so
often that the probability of the author not cheating is lower than 5
percent)</p></li>
</ul>
<p>We now toss the coin and head shows twice. The question now is
whether head showing twice is lower than 5 percent.</p>
<p>We toss the coin 3 times. Head shows twice. How likely is it that I
do not cheat and head falls more than twice anyway? (In other words,
what is the probability p that I win twice or more and not cheat?) If
you set the significance level at .05, could you then accuse me of being
a cheater?</p>
<p>As you can see in the fourth column, there are three options that
lead to heads showing twice (rows 2, 3, and 4). If we add these up
(0.125 + 0.125 + 0.125 = 0.375). Also, we need to add the case where
head shows 3 times which is another .125 (0.375 + 0.125 = .5), then we
find out that the probability of heads showing at least twice in three
coin tosses is 50 percent and thus 10 times more than the 5-percent
threshold that we set initially. Therefore, you cannot claim that I
cheated.</p>
<div class="tabwid"><style>.cl-0cbb87ce{table-layout:auto;width:75%;}.cl-0cb0276c{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0cb02776{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0cb4824e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0cb49f9a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0cb49fa4{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0cb49fa5{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0cb49fae{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0cb49faf{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0cb49fb0{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0cbb87ce'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Probability of successes in coin tosses.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-0cb49f9a"><p class="cl-0cb4824e"><span class="cl-0cb0276c">0 Heads</span></p></th><th class="cl-0cb49fa4"><p class="cl-0cb4824e"><span class="cl-0cb0276c">1 Head</span></p></th><th class="cl-0cb49fa4"><p class="cl-0cb4824e"><span class="cl-0cb0276c">2 Heads</span></p></th><th class="cl-0cb49fa5"><p class="cl-0cb4824e"><span class="cl-0cb0276c">3 Heads</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-0cb49fae"><p class="cl-0cb4824e"><span class="cl-0cb02776">0.125</span></p></td><td class="cl-0cb49faf"><p class="cl-0cb4824e"><span class="cl-0cb02776">0.375</span></p></td><td class="cl-0cb49faf"><p class="cl-0cb4824e"><span class="cl-0cb02776">0.375</span></p></td><td class="cl-0cb49fb0"><p class="cl-0cb4824e"><span class="cl-0cb02776">0.125</span></p></td></tr></tbody></table></div>
<p><img src="basicquant_files/figure-html/probcoin01-1.png" width="672" /></p>
<p>We can do the same and check the probabilities of having heads in 10
coin tosses - if we plot the resulting probabilities, we get the bar
plot shown below.</p>
<p><img src="basicquant_files/figure-html/probcoin02-1.png" width="672" /></p>
<p>The distribution looks more bell-shaped with very low probabilities
of getting 0 or 1 as well as 9 or 10 times heads in the 10 coin tosses
and a maximum at 5 times heads in 10 coin tosses. In fact, the
probability of having 0 and 10 times head is .001 (or 1 in a 1000
attempts - one attempt is tossing a coin 10 times) - the probability of
having heads once and 9 times is.01 or 1 in 100 attempts. In contrast,
the probability of having 5 times head is .246 or about 25% (1 in 4
attempts will have 5 heads). Also, we can sum up probabilities: the
probability of getting 8 or more heads in 10 coin tosses is the
probability of getting 8, 9, and 10 times heads (.044 + .010 + 0.001 =
.055 = 5.5 percent).</p>
<p>Calculating the probabilities for three or even 10 coin tosses is
still manageable manually but is there an easier way to calculate
probabilities? A handier way is have a computer calculate probabilities
and the code below shows how to do that in R - a very powerful and
flexible programming environment that has been designed for quantitative
analysis (but R can, in fact, do much more - this website, for instance,
is programmed in R).</p>
<p>The code chunk below calculates the probabilities of having 0, 1, 2,
and 3 times head in 3 tosses.</p>
<pre class="r"><code># probabilities of  0, 1, 2 and 3 times head in 3 coin tosses
dbinom(0:3, 3, 0.5)</code></pre>
<pre><code>## [1] 0.125 0.375 0.375 0.125</code></pre>
<p>The code chunk below calculates the probabilities of having 2 or 3
times head in 3 tosses.</p>
<pre class="r"><code># probabilities of  2 or 3 times head in 3 coin tosses
sum(dbinom(2:3, 3, 0.5))</code></pre>
<pre><code>## [1] 0.5</code></pre>
<p>The code chunk below calculates the probabilities of having 100 head
in 100 tosses.</p>
<pre class="r"><code># probability of  100 times head in 100 coin tosses
dbinom(100, 100, 0.5)</code></pre>
<pre><code>## [1] 7.888609e-31</code></pre>
<p>The code chunk below calculates the probabilities of having 58 or
more times head in 100 tosses.</p>
<pre class="r"><code># probability of  58 to a 100 times head in 100 coin tosses
sum(dbinom(58:100, 100, 0.5))</code></pre>
<pre><code>## [1] 0.06660531</code></pre>
<p>The code chunk below calculates the probabilities of having 59 or
more times head in 100 tosses.</p>
<pre class="r"><code># probability of  59 to a 100 times head in 100 coin tosses
sum(dbinom(59:100, 100, 0.5))</code></pre>
<pre><code>## [1] 0.04431304</code></pre>
<p>The code chunk below calculates the number of heads in 100 tosses
where the probability of getting that number of heads or more sums up to
5 percent (0.05).</p>
<pre class="r"><code># at which point does the probability of getting head 
# dip below 5 percent in 100 coin tosses?
qbinom(0.05, 100, 0.5, lower.tail=FALSE)</code></pre>
<pre><code>## [1] 58</code></pre>
<p>Let’s go back to our example scenario. In our example scenario, we
are dealing with a directed hypothesis and not with an
un-directed/non-directed hypothesis because we claimed in our
H<sub>1</sub> that I was cheating and would get <em>more</em> heads than
would be expected by chance (<span
class="math inline">\(\mu_{Martin}\)</span> <span
class="math inline">\(&gt;\)</span> <span
class="math inline">\(\mu_{NormalCoin}\)</span>). For this reason, the
test we use is one-tailed. When dealing with un-directed hypotheses, you
simply claim that the outcome is either higher or lower - in other words
the test is two-tailed as you do not know in which direction the effect
will manifest itself.</p>
<p>To understand this a more thoroughly, we will consider tossing a coin
not merely 3 but 100 times. The Figure below shows the probabilities for
the number of heads showing when we toss a coin 100 from 0 occurrences
to 100 occurrences.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The next figure shows at which number of heads the cumulative
probabilities dip below 5 percent for two-tailed hypotheses. According
to the graph, if head shows up to 40 or more often than 60 times, the
cumulative probability dips below 5 percent. Applied to our initial bet,
you could thus claim that I cheated if head shows less than 41 times or
more than 60 times (if out hypothesis were two-tailed - which it is
not).</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>The Figure below shows at which point the probability of heads
showing dips below 5 percent for one-tailed hypotheses. Thus, according
to the figure below, if we toss a coin 100 times and head shows 59 or
more often, then you are justified in claiming that I cheated.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>When comparing the two figures above, it is notable that the number
at which you can claim I cheated differs according to whether the
H<sub>1</sub> as one- or two-tailed. When formulating a one-tailed
hypothesis, then the number is lower compared with the the number at
which you can reject the H<sub>0</sub> if your H<sub>1</sub> is
two-tailed. This is actually the reason for why it is preferable to
formulate more precise, one-tailed hypotheses (because then, it is
easier for the data to be sufficient to reject the H<sub>0</sub>).</p>
</div>
<div id="the-normal-distribution" class="section level2 unnumbered">
<h2 class="unnumbered">The Normal Distribution</h2>
<p>It is important to note here that the above described calculation of
probabilities does not work for numeric variables that are
interval-scaled. The reason for this is that it is not possible to
calculate the probabilities for all possible outcomes of a reaction time
experiment (where time is a continuous variable). In such cases, we rely
on <em>distributions</em> in order to determine how likely or probable a
certain outcome is.</p>
<p>When relying on distributions, we determine whether a certain value
falls within or outside of the area of a distribution that accounts for
5 percent of the entire area of the distribution - if it falls within
the area that accounts for less than 5 percent of the total area, then
the result is called <em>statistically significant</em> (see the normal
distribution below) because the outcome is very unlikely.</p>
<p>The normal distribution (or Gaussian curve or Gaussian distribution)
shown in the figure above has certain characteristics that can be
derived mathematically. Some of these characteristics relate to the area
of certain sections of that distribution. More generally, the normal
distribution is a symmetric, bell-shaped probability distribution, used
as the theoretical model for the distribution of physical and
psychological variables. In fact, many variables in the real world are
normally distributed: shoe sizes, IQs, sleep lengths, and many , many
more.</p>
<p>The normal distribution is very important because it underlies many
statistical procedures in one form or another. The normal distribution
is a symmetrical, continuous distribution where</p>
<ul>
<li>the arithmetic mean, the median, and the mode are identical and have
a value of 0 (and are thus identical);<br />
</li>
<li>50% of the area under the bell-shaped curve are smaller than the
mean;<br />
</li>
<li>50% of the area under the bell-shaped curve are bigger than the
mean;<br />
</li>
<li>50% of the area under the bell-shaped curve are within -0.675 and
+0.675 standard deviations from the mean (0);<br />
</li>
<li>95% of the area under the bell-shaped curve are within -1.96 and
+1.96 standard deviations from the mean (0);<br />
</li>
<li>99% of the area under the bell-shaped curve are within -2.576 and
+2.576 standard deviations from the mean (0).</li>
</ul>
<p>There is also a very interesting aspect to the normal distribution
that relates to the means (averages) of samples drawn from any type of
distribution: no matter what type of distribution we draw samples from,
the distribution of the means will approximate a normal distribution. In
other words, if we draw samples form a very weird looking distribution,
the means of these samples will approximate a normal distribution. This
fact is called the <em>Central Limit Theorem</em>. What makes the
central limit theorem so remarkable is that this result holds no matter
what shape the original population distribution may have been.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As shown above, 50 percent of the total area under the curve are to
left and 50 percent of the right of the mean value. Furthermore, 68
percent of the area are within -1 and +1 standard deviations from the
mean; 95 percent of the area lie between -2 and +2 standard deviations
from the mean; 99.7 percent of the area lie between -3 and +3 standard
deviations from the mean. Also, 5 percent of the area lie outside -1.96
and +1.96 standard deviations from the mean (if these areas are
combined) (see the Figure below). This is important. because we can
reject null hypotheses if the probability of them being true is lower
than 5 percent. This means that we can use the normal distribution to
reject null hypotheses if our dependent variable is normally
distributed.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Finally, 5 percent of the area lies beyond +1.68 standard deviations
from the mean (see the Figure below).</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>These properties are extremely useful when determining the likelihood
of values or outcomes that reflect certain interval-scaled
variables.</p>
<hr />
<div class="warning"
style="padding:0.1em; background-color:#51247a; color:#f2f2f2">
<span>
<p style="margin-top:1em; text-align:center">
<b>EXERCISE TIME!</b>
</p>
<p style="margin-left:1em;">
</p>
<p></span></p>
</div>
<div class="question">
<p>`</p>
<ol style="list-style-type: decimal">
<li>Create a table with the possible outcomes and probabilities of 4
coin tosses (you can consider the table showing the outcomes of three
coin tosses above as a guideline).</li>
</ol>
<details>
<summary>
Answer
</summary>
<pre class="r"><code>  sum(dbinom(4, 7, 0.5))</code></pre>
<pre><code>  ## [1] 0.2734375</code></pre>
</details>
<ol start="2" style="list-style-type: decimal">
<li>How likely is it for heads to show exactly 3 times when tossing a
coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<pre class="r"><code>  sum(dbinom(3, 7, 0.5))</code></pre>
<pre><code>  ## [1] 0.2734375</code></pre>
</details>
<ol start="3" style="list-style-type: decimal">
<li>How likely is it for heads to show exactly 2 or 5 times when tossing
a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<pre class="r"><code>  sum(dbinom(c(2, 5), 7, 0.5))</code></pre>
<pre><code>  ## [1] 0.328125</code></pre>
</details>
<ol start="4" style="list-style-type: decimal">
<li>How likely is it for heads to show 5 or more times when tossing a
coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<pre class="r"><code>  sum(dbinom(5:7, 7, 0.5))</code></pre>
<pre><code>  ## [1] 0.2265625</code></pre>
</details>
<ol start="5" style="list-style-type: decimal">
<li>How likely is it for heads to show between 3 and 6 times when
tossing a coin 7 times?</li>
</ol>
<details>
<summary>
Answer
</summary>
<pre class="r"><code>  sum(dbinom(3:6, 7, 0.5))</code></pre>
<pre><code>  ## [1] 0.765625</code></pre>
</details>
</div>
<p>`</p>
<hr />
</div>
<div id="non-normality-skewness-and-kurtosis"
class="section level2 unnumbered">
<h2 class="unnumbered">Non-normality: skewness and kurtosis</h2>
<p>Depending on the phenomenon you are investigating, the distribution
of that phenomenon can be distributed non-normally. Two factors causing
distributions to differ from the normal distribution (that is two
factors causing distributions to be non-normal) are <em>skewness</em>
and <em>kurtosis</em>.</p>
<div id="skewness" class="section level3 unnumbered">
<h3 class="unnumbered">Skewness</h3>
<p>Skewed distributions are asymmetrical and they can be positively or
negatively skewed. The tail of a <em>negatively skewed distribution</em>
points towards negative values (to the left) which means that the
distribution leans towards the right (towards positive values) while the
tail of a <em>positively skewed distribution</em> points towards
positive values (to the right) which means that the distribution leans
towards the left (towards negative values).</p>
<p>Another characteristic of skewed distributions is that the mean and
median of a distribution differ. If the median is greater than the mean,
the distribution is negatively skewed (the long tail points towards
negative values). If the median is smaller than the mean, the
distribution is positively skewed (the long tail points towards positive
values).</p>
<p>Negatively skewed</p>
<ul>
<li>Tail points towards negative values (to the left)</li>
<li>Median is greater than the mean</li>
</ul>
<p>Positively skewed</p>
<ul>
<li>Tail points towards positive values (to the right)</li>
<li>Median is lower than the mean</li>
</ul>
<p><img src="basicquant_files/figure-html/skewness-1.png" width="672" /></p>
<p>To show how we can calculate skewness (or if a distribution is
skewed), we generate a sample of values.</p>
<pre class="r"><code>SampleValues &lt;- sample(1:100, 50)
# inspect data
summary(SampleValues)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00   18.25   55.00   51.08   76.75  100.00</code></pre>
<p>We apply the <code>skewness</code> function from the
<code>e1071</code> package to the sample scores to calculated skewness.
The <code>skewness</code> function allows to calculate skewness in three
different ways:</p>
<p>Type 1 (This is the typical definition used in many older textbooks):
<span class="math display">\[\begin{equation}
g_1 = m_3 / m_2^{(3/2)}.
\end{equation}\]</span></p>
<p>Type 2 (Used in SAS and SPSS): <span
class="math display">\[\begin{equation}
G_1 = g_1 * sqrt(n(n-1)) / (n-2)
\end{equation}\]</span></p>
<p>Type 3 (Used in MINITAB and BMDP): <span
class="math display">\[\begin{equation}
b_1 = m_3 / s^3 = g_1 ((n-1)/n)^{(3/2)}
\end{equation}\]</span></p>
<p>All three formulas have in common that the more negative values are,
the more strongly positively skewed are the data (distribution leans to
the left) and the more positive the values are, the more strongly
negatively skewed are the data (distribution leans to the right). Here
we use the second formula (by setting <code>type = 2</code>) that is
also used in SPSS.</p>
<pre class="r"><code>library(e1071)
skewness(SampleValues, type = 2)</code></pre>
<pre><code>## [1] -0.1567544</code></pre>
<p>If the reported skewness value is negative, then the distribution is
positively skewed. If the value is positive, then the distribution is
negatively skewed. If the value is lower than -1 or greater than +1,
then the distribution can be assumed to be substantively skewed <span
class="citation">(<a href="#ref-hair2017dist" role="doc-biblioref">Hair
et al. 2017</a>)</span>.</p>
</div>
<div id="kurtosis" class="section level3 unnumbered">
<h3 class="unnumbered">Kurtosis</h3>
<p>Another way in which distributions can differ from the normal
distribution relates to the thickness of the tails and the spikiness of
the distribution. If distributions are bell-shaped like the normal
distribution, they are called <em>mesokurtic</em>. If distributions are
symmetrical but they are more spiky than the normal distribution, they
are called <em>leptokurtic</em>. If symmetrical distributions are
flatter and have bigger tails than the normal distribution, the
distributions are called <em>platykurtic</em>.</p>
<p><img src="basicquant_files/figure-html/kurtosis-1.png" width="672" /></p>
<p>To show how we can calculate kurtosis (or if a distribution suffers
from kurtosis), we apply the <code>kurtosis</code> function from the
<code>e1071</code> package to the sample scores we generated above /when
we calculated skewness).</p>
<pre class="r"><code>kurtosis(SampleValues)</code></pre>
<pre><code>## [1] -1.415066</code></pre>
<p>As the kurtosis value is positive, the distribution is leptokurtic
(if it were negative, the distribution would be platykurtic). As a rule
of thumb, values greater than +1 indicate that the distribution is too
peaked while values lower than –1 indicate that the distribution is
substantively platykurtic <span class="citation">(<a
href="#ref-hair2017dist" role="doc-biblioref">Hair et al. 2017,
pp61</a>)</span>.</p>
<p>The kurtosis score can thus be interpreted as follows:</p>
<ul>
<li><p>A values of 0 means that the distribution is perfectly
<em>mesokurtic</em> with Values between -0.5 and 0.5 suggesting that the
distribution is <em>approximately mesokurtic</em></p></li>
<li><p>Values between -0.5 and -1 mean that the distribution is
<em>moderately platykurtic</em> with values smaller than -1 indicating
that the distribution is <em>platykurtic</em>.</p></li>
<li><p>Values between 0.5 and 1 mean that the distribution is
<em>moderately leptokurtic</em> with values greater than 1 indicating
that the distribution is <em>leptokurtic</em></p></li>
</ul>
</div>
</div>
<div id="the-binomial-distribution" class="section level2 unnumbered">
<h2 class="unnumbered">The Binomial Distribution</h2>
<p>A distribution which is very similar to the normal distribution is
the “binomial distribution”. The binomial distribution displays the
probability of binary outcomes. So, in fact, the distribution of the
coin flips above represents a binomial distribution. However, the
binomial distribution cane be (as above in case of the coin flips) but
does not have to be symmetric (like the normal distribution).</p>
<p>To illustrate this, let us consider the following example: we are
interested in how many people use discourse <em>like</em> in Australian
English. We have analyzed a corpus, for instance the Australian
component of the <a
href="https://www.ice-corpora.uzh.ch/en.html">International Corpus of
English</a> and found that 10 percent of all speakers have used
discourse <em>like</em>. In this example, the corpus encompasses 100
speakers (actually the the spoken section of the Australian component of
the ICE represents more than 100 speakers but it will make things easier
for us in this example).</p>
<p>Now, given the result of our corpus analysis, we would like to know
what percentage of speakers of Australian English use discourse
<em>like</em> with a confidence of 95 percent. Given the corpus study
results, we can plot the expected binomial distribution of discourse
<em>like</em> users in Australian English.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>The bar graph above shows the probability distribution of discourse
<em>like</em> users in Australian English. The first thing we notice is
that the binomial distribution is not symmetric as it is slightly
left-skewed. If we would increase the number of draws or speakers in our
example, the distribution would, however, approximate the normal
distribution very quickly because the binomial distribution approximates
the normal distribution for large N or if the probability is close to
.5. Thus, it is common practice to use the normal distribution instead
of the binomial distribution.</p>
<p>The bar graph below also shows the probability distribution of
discourse <em>like</em> users in Australian English but, in addition, it
is color-coded: bars within the 95 percent confidence interval are
<em>lightgray</em>, the bars in red are outside the 95 percent
confidence interval. In other words, if we repeated the corpus analysis,
for instance 1000 times, on corpora which represent speakers from the
same population, then 95 percent of samples would have between 1 and 8
discourse <em>like</em> users.</p>
<p><img src="basicquant_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>In addition to the normal distribution and the binomial distribution,
there are many other distributions which underlay common procedures in
quantitative analyses. For instance, the t- and the F-distribution or
the Chi-distribution. However, we will not deal with these distributions
here.</p>
</div>
</div>
<div id="z-scores" class="section level1" number="8">
<h1><span class="header-section-number">8</span> z-scores</h1>
<p>We have encountered z-scores before - the values on the x-axis in the
figures showing the normal distributions are, in fact, z-scores. This
means that z-scores reflect how many standard deviations a score is
distant from the mean of a distribution. But why are these z-scores
useful?</p>
<p>Imagine you want to compare the performance of two students that have
written tests in different classes. Student A had a score of 50 out of
80 and student B had a score of 70 out of 100. We would be tempted to
simply state that student A performed worse because 50 divided by 80 is
0.625 while 70 divided by 100 is 0.7. However, the tests could have
differed in how hard or difficult they were.</p>
<p>Assuming the students in the two classes are equally intelligent, we
can calculate a z-score which allows us to see how likely a score is
relative to the mean and standard deviation of a sample (in this case
the scores of the other students in each class). To calculate a z-score,
we subtract the mean from the observed score and then divide the result
by the standard deviation.</p>
<p><span class="math display">\[\begin{equation}
z =\frac{x_{i} - \mu} {\sigma}   
\end{equation}\]</span></p>
<p>or</p>
<p><span class="math display">\[\begin{equation}  
z =\frac{x_{i} - \bar{x}} {s}
\end{equation}\]</span></p>
<p>A z-score shows how many standard deviations a score is from the mean
(which has a value of 0). Positive numbers indicate that the z-score
(and thus the original value) is higher or better than the mean while
negative z-scores indicate that the z-score (and thus the original
value) is lower or worse than the mean.</p>
<p>Let’s use an example to better understand this. We will continue with
the example of the two students but we will also take the scores for
their class mates into account. The scores are shown below.</p>
<div class="tabwid"><style>.cl-1012e160{table-layout:auto;width:40%;}.cl-1008270c{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-10082716{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-100c6664{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-100c8b26{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b27{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b30{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b3a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b44{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b45{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b4e{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c8b58{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1012e160'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Results of two tests at university (class1 had a maximum score of 80, class2 had a maximum score of 100.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-100c8b26"><p class="cl-100c6664"><span class="cl-1008270c">Score_c1</span></p></th><th class="cl-100c8b27"><p class="cl-100c6664"><span class="cl-1008270c">Score_c2</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">71</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">78</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">78</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">45</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">67</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">89</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">41</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">88</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">68</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">52</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">98</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">47</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">52</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">46</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">63</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">44</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">78</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">52</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">45</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">53</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">66</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">40</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">60</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">80</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">50</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">73</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">40</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">40</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">71</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">88</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">69</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">92</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b44"><p class="cl-100c6664"><span class="cl-10082716">74</span></p></td><td class="cl-100c8b45"><p class="cl-100c6664"><span class="cl-10082716">44</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b30"><p class="cl-100c6664"><span class="cl-10082716">54</span></p></td><td class="cl-100c8b3a"><p class="cl-100c6664"><span class="cl-10082716">58</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-100c8b4e"><p class="cl-100c6664"><span class="cl-10082716">50</span></p></td><td class="cl-100c8b58"><p class="cl-100c6664"><span class="cl-10082716">70</span></p></td></tr></tbody></table></div>
<p>The z-score for the student in class 1 (who scored 50 out of 80)
would be calculated as 50 minus 59.5 (the mean score of class 1) divided
by 12.505 (the standard deviation of class 1). This would result in a
z-score of -0.76 which means that student A’s score is -0.76 standard
deviations below the mean of class1.</p>
<p><span class="math display">\[\begin{equation}
  z_{studentA} =\frac{50 - 59.5} {12.505}
  = -0.76
\end{equation}\]</span></p>
<p>The z-score of student B in class 2 (who scored 70 out of 100) would
be calculated as 70 minus 64.65 (the mean score of class 2) divided by
19.64 (the standard deviation of class 2). This would result in a
z-score of 0.2724091 which means that student B’s score is -0.746
standard deviations below the mean of class2.</p>
<p><span class="math display">\[\begin{equation}
  z_{studentB} =\frac{70 - 64.65} {19.64}
  = -0.746
\end{equation}\]</span></p>
<p>Both students perform below average in their class (this is confirmed
by the negative z-scores) and, because the z-score of student A is even
lower than the z-score of student B, student A has performed worse
compared to student B.</p>
<p>We can also easily calculate the z-scores of both classes by
calculating the mean of each class, then calculating the standard
deviation of each class and then subtracting each score from the mean
and dividing the result by the standard deviation as shown below:</p>
<pre class="r"><code>zdf &lt;- zdf %&gt;%
  dplyr::mutate(Mean_c1 = mean(Score_c1),
                SD_c1 = round(sd(Score_c1), 2),
                z_c1 = round((Score_c1-Mean_c1)/SD_c1, 2),
                Mean_c2 = mean(Score_c2),
                SD_c2 = round(sd(Score_c2), 2),
                z_c2 = round((Score_c2-Mean_c2)/SD_c2, 2)) %&gt;%
  dplyr::relocate(Score_c1, Mean_c1, SD_c1, z_c1, Score_c2, Mean_c2, SD_c2, z_c2)</code></pre>
<div class="tabwid"><style>.cl-10391a88{table-layout:auto;width:75%;}.cl-102d7174{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-102d7188{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-103201c6{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-10321e40{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e4a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e54{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e55{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e56{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e57{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e5e{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e5f{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e68{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e69{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e72{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10321e7c{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-10391a88'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Scores, means, standrad deviations, and z-scores of two tests at university.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-10321e40"><p class="cl-103201c6"><span class="cl-102d7174">Score_c1</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">Mean_c1</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">SD_c1</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">z_c1</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">Score_c2</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">Mean_c2</span></p></th><th class="cl-10321e4a"><p class="cl-103201c6"><span class="cl-102d7174">SD_c2</span></p></th><th class="cl-10321e54"><p class="cl-103201c6"><span class="cl-102d7174">z_c2</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">71</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.92</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">78</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">0.68</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">78</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">1.48</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">45</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">-1.00</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">67</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.60</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">89</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">1.24</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">41</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">-1.48</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">88</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">1.19</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">68</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.68</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">47</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-0.90</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">52</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">-0.60</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">98</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">1.70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">47</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">-1.00</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">52</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-0.64</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">46</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">-1.08</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">62</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">-0.13</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">63</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.28</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">44</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-1.05</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">78</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">1.48</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">52</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">-0.64</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">45</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">-1.16</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">53</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-0.59</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">66</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">0.52</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">40</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">-1.26</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">60</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.04</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">80</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">0.78</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">50</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">-0.76</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">73</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">0.43</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">40</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">-1.56</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">40</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-1.26</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">71</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">0.92</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">88</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">1.19</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">69</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">0.76</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">92</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">1.39</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e5e"><p class="cl-103201c6"><span class="cl-102d7188">74</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">1.16</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">44</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e5f"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e68"><p class="cl-103201c6"><span class="cl-102d7188">-1.05</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e55"><p class="cl-103201c6"><span class="cl-102d7188">54</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">-0.44</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">58</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e56"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e57"><p class="cl-103201c6"><span class="cl-102d7188">-0.34</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10321e69"><p class="cl-103201c6"><span class="cl-102d7188">50</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">59.5</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">12.5</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">-0.76</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">70</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">64.65</span></p></td><td class="cl-10321e72"><p class="cl-103201c6"><span class="cl-102d7188">19.64</span></p></td><td class="cl-10321e7c"><p class="cl-103201c6"><span class="cl-102d7188">0.27</span></p></td></tr></tbody></table></div>
<p>The table now shows us for each score if the score is below or above
the class average (indicated by positive and negative score) and we can
compare each score from both classes to see which score is relatively
better or worse across the two classes.</p>
</div>
<div id="alpha-and-beta-errors" class="section level1" number="9">
<h1><span class="header-section-number">9</span> Alpha and Beta
Errors</h1>
<p>One practice that unfortunately still very frequent, which is a very
serious problem in data analysis, and which has led to the development
of multivariate techniques is the increase of the error rates in
multiple or repeated testing.</p>
<p>We have stated before that we usually assume a significance level of
5%. However, this also means that, on average, every 20<sup>th</sup>
test result, which has a significance value of .05, is misinterpreted
because, on average, one out of 20 results shown to be significant
<em>is actually not caused by a real effect but the result of normally
distributed probabilities and a fixed significance level</em>. If we
perform several tests, the probability that we obtain a significant
result for something which is, in fact, not significant adds up and
increases exponentially. Indeed, even with only four tests the
likelihood of a significant result in the test - although there is in
actually no difference - is 18.5%! This increase in error rates can by
easily calculated with formula below.</p>
<p><span class="math display">\[\begin{equation}

1 - .95^{n} = error

\label{eq:inflatederrors}

\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}

1 - .95^{4} = 1 - 0.814 = 0.185

\label{eq:inflatederrorsbsp}

\end{equation}\]</span></p>
<p>We will return to this later, but first we will look at different
types of errors.</p>
<p>One differentiates between <span
class="math inline">\(\alpha\)</span>- (or alpha-) and <span
class="math inline">\(\beta\)</span> (or beta-) errors. <span
class="math inline">\(\alpha\)</span> errors represent a situation in
which a test reports a significant effect although there is no effect in
empirical reality. <span class="math inline">\(\beta\)</span> errors
reflect a situation in which a test does not report a significant effect
although there is one in empirical reality (see Table below).</p>
<div class="tabwid"><style>.cl-105792c4{}.cl-104d0a02{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-104d0a16{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-104d0a17{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(255, 0, 0, 1.00);background-color:transparent;}.cl-10513d16{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-10515832{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1051583c{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515846{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515847{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515850{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515851{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1051585a{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1051585b{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515864{width:0.75in;background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1051586e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1051586f{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 0.75pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10515878{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0.75pt solid rgba(102, 102, 102, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-105792c4'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Alpha- and beta-errors.</span></caption><tbody><tr style="overflow-wrap:break-word;"><td  colspan="2" rowspan="2"class="cl-10515832"><p class="cl-10513d16"><span class="cl-104d0a02"></span></p></td><td  colspan="2"class="cl-1051583c"><p class="cl-10513d16"><span class="cl-104d0a16">Reality</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10515850"><p class="cl-10513d16"><span class="cl-104d0a16">Correlation</span></p></td><td class="cl-10515851"><p class="cl-10513d16"><span class="cl-104d0a16">NoCorrelation</span></p></td></tr><tr style="overflow-wrap:break-word;"><td  rowspan="2"class="cl-1051585a"><p class="cl-10513d16"><span class="cl-104d0a16">Data</span></p></td><td class="cl-1051585b"><p class="cl-10513d16"><span class="cl-104d0a16">Correlation</span></p></td><td class="cl-1051585b"><p class="cl-10513d16"><span class="cl-104d0a02">correct</span></p></td><td class="cl-10515864"><p class="cl-10513d16"><span class="cl-104d0a17">alpha-error</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-1051586f"><p class="cl-10513d16"><span class="cl-104d0a16">NoCorrelation</span></p></td><td class="cl-1051586f"><p class="cl-10513d16"><span class="cl-104d0a17">beta-error</span></p></td><td class="cl-10515878"><p class="cl-10513d16"><span class="cl-104d0a02">correct</span></p></td></tr></tbody></table></div>
<p>Regarding the difference between <span
class="math inline">\(\alpha\)</span> and <span
class="math inline">\(\beta\)</span> errors, it can be said that <span
class="math inline">\(\beta\)</span> errors are generally to be
preferred, as they merely state that, based on the data, it can not be
assumed that X or Y is the case, while <span
class="math inline">\(\alpha\)</span> errors do not false statements
become part of recognized knowledge. As a rule of thumb, more
conservative and conservative behavior is less problematic in terms of
science theory, and thus <span class="math inline">\(\alpha\)</span>
rather than <span class="math inline">\(\beta\)</span> errors should be
avoided.</p>
<p>Now that we have clarified what types of errors exist and that errors
accumulate, we will examine a related concept:
<em>Independence</em>.</p>
</div>
<div id="independence" class="section level1" number="10">
<h1><span class="header-section-number">10</span> Independence</h1>
<p>If errors would always add up, then statistics would not be possible,
since every new test would have to take all previous tests into account.
This is obviously absurd and cannot be the case. The question now arises
about what determines, if errors accumulate or not? The answer is called
<em>independence</em> and, in this sense, refers to repeated measures
designs or repeated testing. However, there is also another meaning of
independence: independence of data points or observations (not tests).
But let us look at independence referring to repeated testing first.</p>
<div class="tabwid"><style>.cl-10730a22{table-layout:auto;width:35%;}.cl-1065eafe{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1065eb58{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-106c7022{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-106c702c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-106c8a8a{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8a94{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8a9e{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8a9f{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8aa0{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8aa8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8aa9{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106c8ab2{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-10730a22'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Independent data - each score comes from a different subject.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-106c8a8a"><p class="cl-106c7022"><span class="cl-1065eafe">Subjects</span></p></th><th class="cl-106c8a94"><p class="cl-106c702c"><span class="cl-1065eafe">Scores</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-106c8a9e"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 1</span></p></td><td class="cl-106c8a9f"><p class="cl-106c702c"><span class="cl-1065eb58">21</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8aa0"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 2</span></p></td><td class="cl-106c8aa8"><p class="cl-106c702c"><span class="cl-1065eb58">47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8a9e"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 3</span></p></td><td class="cl-106c8a9f"><p class="cl-106c702c"><span class="cl-1065eb58">46</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8aa0"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 4</span></p></td><td class="cl-106c8aa8"><p class="cl-106c702c"><span class="cl-1065eb58">39</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8a9e"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 5</span></p></td><td class="cl-106c8a9f"><p class="cl-106c702c"><span class="cl-1065eb58">37</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8aa0"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 6</span></p></td><td class="cl-106c8aa8"><p class="cl-106c702c"><span class="cl-1065eb58">30</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8a9e"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 7</span></p></td><td class="cl-106c8a9f"><p class="cl-106c702c"><span class="cl-1065eb58">26</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8aa0"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 8</span></p></td><td class="cl-106c8aa8"><p class="cl-106c702c"><span class="cl-1065eb58">40</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8a9e"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 9</span></p></td><td class="cl-106c8a9f"><p class="cl-106c702c"><span class="cl-1065eb58">38</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-106c8aa9"><p class="cl-106c7022"><span class="cl-1065eb58">Subject 10</span></p></td><td class="cl-106c8ab2"><p class="cl-106c702c"><span class="cl-1065eb58">31</span></p></td></tr></tbody></table></div>
<p><strong>(In-)dependence of tests: repeated measures</strong></p>
<p>If tests are independent of one another, then their errors do not
accumulate. However, if they are related to each other, then the errors
add up. A word of caution is in order here as the concept of
independence in statistics has a different meaning from everyday use: in
statistics, independence means the independence of hypotheses. In the
case of specifications of more general hypotheses, the specified
hypotheses are not independent of the general hypothesis and are not
independent of the other specified hypotheses. In other words, if we
test several specific hypotheses in a more generalized hypothesis, then
the hypotheses are not strictly independent and cannot be treated that
way. If we formulate two hypotheses that are not conceptually linked or
one hypothesis is not derived from the other, then these hypotheses are
independent.</p>
<p>We encounter a related phenomenon when dealing with extensions of
<span class="math inline">\(\chi\)</span><sup>2</sup> test: the reason
why we could not calculate the ordinary Pearson’s <span
class="math inline">\(\chi\)</span><sup>2</sup> test when focusing on
sub-tables derived from larger tables is that the data of represented in
the sub-table is not independent from the other observations summarized
in the larger table.</p>
<div class="tabwid"><style>.cl-1089ac82{table-layout:auto;width:35%;}.cl-107f3c2a{font-family:'Arial';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-107f3c3e{font-family:'Arial';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-108325a6{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-108325ba{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-10833f64{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f6e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f78{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f79{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f82{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f83{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f84{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10833f8c{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1089ac82'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>Dependent data - several scores come from the same subject.</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-10833f64"><p class="cl-108325a6"><span class="cl-107f3c2a">Subjects</span></p></th><th class="cl-10833f6e"><p class="cl-108325ba"><span class="cl-107f3c2a">Scores</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-10833f78"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 1</span></p></td><td class="cl-10833f79"><p class="cl-108325ba"><span class="cl-107f3c3e">45</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f82"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 1</span></p></td><td class="cl-10833f83"><p class="cl-108325ba"><span class="cl-107f3c3e">33</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f78"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 1</span></p></td><td class="cl-10833f79"><p class="cl-108325ba"><span class="cl-107f3c3e">49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f82"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 1</span></p></td><td class="cl-10833f83"><p class="cl-108325ba"><span class="cl-107f3c3e">50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f78"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 1</span></p></td><td class="cl-10833f79"><p class="cl-108325ba"><span class="cl-107f3c3e">38</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f82"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 2</span></p></td><td class="cl-10833f83"><p class="cl-108325ba"><span class="cl-107f3c3e">24</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f78"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 2</span></p></td><td class="cl-10833f79"><p class="cl-108325ba"><span class="cl-107f3c3e">41</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f82"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 2</span></p></td><td class="cl-10833f83"><p class="cl-108325ba"><span class="cl-107f3c3e">26</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f78"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 2</span></p></td><td class="cl-10833f79"><p class="cl-108325ba"><span class="cl-107f3c3e">32</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-10833f84"><p class="cl-108325a6"><span class="cl-107f3c3e">Subject 2</span></p></td><td class="cl-10833f8c"><p class="cl-108325ba"><span class="cl-107f3c3e">47</span></p></td></tr></tbody></table></div>
<p>When we performed the ordinary Pearson’s <span
class="math inline">\(\chi\)</span><sup>2</sup> test we tested whether
emotion metaphors are realized differently across registers. The
subsequent test built on the results of that first test and zoomed in on
a specified hypothesis (namely that two specific types of metaphors
would differ in two specific registers). Therefore, we are dealing with
two hypotheses, the second hypothesis being a specification of the first
hypothesis. This means that the hypotheses were related and not
independent. Consequently, the errors would have added up if we had not
considered that not only the part table was extracted from the data, but
we wanted to test a part table of a larger table.</p>
<p><strong>Independence of observations</strong></p>
<p>A second and perhaps more important meaning of independence refers to
independence of data points or observations (as already mentioned
above). This independence is important because many tests (including
regression) assume that data points are independent in the sense that
data points are unrelated and do not provide information about other
data points. Observations are dependent when data points come from the
same individual or participant or the same item. When data points are
related, then statistical models need to take this into account (which
is achieved, e.g., by including so-called random effects in regression
models).</p>
</div>
<div id="corrections" class="section level1" number="11">
<h1><span class="header-section-number">11</span> Corrections</h1>
<p>Now that we know about error accumulation and issues of independence,
how can we test multiple hypotheses (simultaneously)? One option is to
use multivariate methods, as we will see in the section on “Advanced
Statistics”. Another option is to incorporate corrections to ensure that
the <span class="math inline">\(\alpha\)</span>-level remains at 5% even
with repeated or multiple testing.</p>
<p>The best known and probably the most widely used correction is the
<em>Bonferroni</em> correction, where the <span
class="math inline">\(\alpha\)</span>-level is divided by the number of
tests. For example, if we perform 4 tests, then the <span
class="math inline">\(\alpha\)</span>-level is lowered to .05 / 4 =
.0125 so that the <span class="math inline">\(\alpha\)</span>-level of
the four tests returns to the usual 5% level. The disadvantage of this
correction is that it is more conservative and therefore leads to a
relatively high <span class="math inline">\(\beta\)</span>-error
rate.</p>
<p>Other common corrections are the Holm and the Benjamini-Hochberg
corrections. However, we will not discuss them here. The interested
reader is referred to <span class="citation">Field, Miles, and Field (<a
href="#ref-field2012discovering" role="doc-biblioref">2012</a>)</span>,
pp. 429-430.</p>
</div>
<div id="transformations" class="section level1" number="12">
<h1><span class="header-section-number">12</span> Transformations</h1>
<p>We have now a basic understanding of the normal distribution and its
characteristics. The normal distribution is relevant in statistics
because tests build on assumptions that involve the distributions of
variables or residuals. If the data is not distributed normally but the
test you want to use assumes and therefore requires normality, then
there is a problem. In this section, we will have a look at ways to
<em>normalize</em> data. In this context, normalization refers to
transformations of data that cause the data to exhibit different
distributional characteristics (e.g. being more normal). As such,
transformations can give answers to questions about what can be done if
the distribution of something (errors, data, etc.) is not normal, but it
should be normal?</p>
<p>Let us have a look at an example to clarify what is meant here and
what can be done when dealing with non-normal data. In a first step, we
load some data and test whether it is <em>normal</em> or not. The data
represents the word counts of speakers in a corpus.</p>
<p>The figure below shows a histogram of the wordcounts indicating that
the word counts are extremely left-skewed.</p>
<p><img src="basicquant_files/figure-html/normal1-1.png" width="672" /></p>
<p>Next, we test weather the word counts are distributed normally -
which is unlikely given the histogram. The test we use here is called
the <em>Shapiro-Wilk test</em> and it determines the likelihood with
which a given sample is drawn from normally distributed population. If
the Shapiro-Wilk test reports a significant result, then this means that
the sample is significantly non-normal and unlikely to be drawn from
normally distributed population.</p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  tdat$Words
## W = 0.82322, p-value &lt; 2.2e-16</code></pre>
<p>According to the Shapiro-Wilk test, the distribution of the word
counts is non-normal. It is important to mention here that the
Shapiro-Wilk test is inexact for small samples (N &lt; 60) but to
rigorous for large samples (N &gt; 200).</p>
<p>One issue that we face now that we have confirmed that the word
counts are non-normal relates to the description of the data. If data
are non-normal, then the usual descriptive statistics (mean, median,
standard deviation) are not really appropriate because they either
assume normality (mean and standard deviation) or they are unfit to
report non-normal structure). Therefore, when dealing with non-normal
data, it is common to use alternative descriptive statistics.</p>
<pre class="r"><code>summary(tdat$Words)                   # summary for non-normal data</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   116.0   328.0   523.4   753.0  2482.0</code></pre>
<p>Median absolute deviation (MAD)</p>
<p>MAD is a robust measure of the variability and it represents the
median of the difference of each observed value from the data’s median.
It is thus defined as the median of the absolute deviations from the
data’s median.</p>
<pre class="r"><code>mad(tdat$Words, constant = 1)</code></pre>
<pre><code>## [1] 253</code></pre>
<p>Interquartile range (IQR)</p>
<p>The IQR is a measure of dispersion, that is calculated by subtracting
the first quartile from the third quartile. The first and third
quartiles represent the boundaries of the boxes in boxplots which is why
the box in box plots represents the width of the IQR.</p>
<pre class="r"><code>IQR(tdat$Words)                           </code></pre>
<pre><code>## [1] 637</code></pre>
<p>Before we continue, we generate four plots that show the distribution
of the word counts in more detail to get a more detailed understanding
to what extent the data differ from normality.</p>
<p><img src="basicquant_files/figure-html/plotlog-1.png" width="672" /></p>
<p>The plots show that, in addition to being non-normal, there are
outliers in the data (see points in the boxplot in the lower right
panel).</p>
<p>One way to deal with non-normal data is to transform the data. Here
are selected rules of thumb for data transformations that are
particularly useful when dealing with language data.</p>
<ul>
<li><p>If the data is moderately positively skewed, the best option is
to take the square root of the dependent variable:
<code>sqrt(DepVar)</code>.</p></li>
<li><p>If the data is moderately negatively skewed, the best option is
to square the dependent variable: <code>(DepVar)^2</code>.</p></li>
<li><p>If the data is J shaped, the best option is to transform the
dependent variable in the following way:
<code>1/(DepVar + 1)</code>.</p></li>
</ul>
<p>Before we transform the data, we will center and scale the data which
allows us to extract outliers. Thus, we continue by centering and
scaling the word counts.</p>
<pre class="r"><code># find outliers (z-value based)
tdat &lt;- tdat %&gt;%
  dplyr::mutate(wc = scale(Words, center = TRUE, scale = TRUE))</code></pre>
<p>After centering and scaling, we remove data points that exceed +/-
1.96 standard deviations.</p>
<pre class="r"><code># remove values that exceed 1.96 (95%) sds
mydataWoOutliers &lt;- tdat %&gt;%
  dplyr::filter(wc &gt;= 1.96 | wc &lt;= -1.96)</code></pre>
<p>We can now produce another boxplot to check the distribution of the
word counts has become more normal and if there are still outliers in
the data.</p>
<pre class="r"><code># find outliers (boxplot)
ggplot(mydataWoOutliers, aes(y = Words))+
  # dots in boxplot show outliers
  geom_boxplot(fill = &quot;purple&quot;, alpha = .5) +
  coord_cartesian(x = c(-1, 1)) +
  theme_bw() +
  labs(y = &quot;Density&quot;)</code></pre>
<p><img src="basicquant_files/figure-html/boxplotwords2-1.png" width="672" /></p>
<p>The boxplot looks much better than before, indicating that the data
is substantively more normal. In addition, we can log-transform or take
the square root of word counts to moderate the skewness of the data.</p>
<p>First, we check if log-transforming the word counts makes them more
normal.</p>
<pre class="r"><code>tdat &lt;- tdat %&gt;%
  dplyr::mutate(LoggedWordcount = log1p(Words),
                SquarerootWordcount = sqrt(Words))
p1 &lt;- ggplot(tdat, aes(x = LoggedWordcount)) +
  geom_histogram() +
  theme_bw() +
  labs(y = &quot;Frequency&quot;)
p2 &lt;- ggplot(tdat, aes(x = LoggedWordcount)) +
  geom_density(fill = &quot;purple&quot;, alpha = .5) +
  theme_bw() +
  labs(y = &quot;Density&quot;)
p3 &lt;- ggplot(tdat, aes(sample = LoggedWordcount)) +
  geom_qq() +
  stat_qq_line() +
  theme_bw()
p4 &lt;- ggplot(tdat, aes(y = LoggedWordcount)) +
  geom_boxplot(fill = &quot;purple&quot;, alpha = .5) +
  theme_bw() +
  labs(y = &quot;&quot;) +
  coord_cartesian(xlim = c(-1,1))  +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())
ggpubr::ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2)</code></pre>
<p><img src="basicquant_files/figure-html/plotwc-1.png" width="672" /></p>
<p>The transformed word counts are still very skewed - this can have
several reasons - for once, we may have chosen an inadequate
transformation. Nonetheless, we continue with using a Shapiro-Wilk test
to see if the distribution of the logged word counts is approximately
normal.</p>
<pre class="r"><code># test for normality
shapiro.test(tdat$LoggedWordcount)  # logging not appropriate here</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  tdat$LoggedWordcount
## W = 0.90171, p-value &lt; 2.2e-16</code></pre>
<p>The Shapiro-Wilk test shows that our data is still not non-normal but
the visualizations show that it is much more normal compared to the
original values.</p>
<p>We now check if taking the square root has made the data more
normal.</p>
<pre class="r"><code>p1 &lt;- ggplot(tdat, aes(x = SquarerootWordcount)) +
  geom_histogram() +
  theme_bw() +
  labs(y = &quot;Frequency&quot;)
p2 &lt;-  ggplot(tdat, aes(x = SquarerootWordcount)) +
  geom_density(fill = &quot;purple&quot;, alpha = .5) +
  theme_bw() +
  labs(y = &quot;Density&quot;)
p3 &lt;- ggplot(tdat, aes(sample = SquarerootWordcount)) +
  geom_qq() +
  stat_qq_line() +
  theme_bw() +
  labs(y = &quot;&quot;)
p4 &lt;- ggplot(tdat, aes(y = SquarerootWordcount)) +
  geom_boxplot(fill = &quot;purple&quot;, alpha = .5) +
  theme_bw() +
  labs(y = &quot;&quot;) +
  coord_cartesian(xlim = c(-1,1))  +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank())
ggpubr::ggarrange(p1, p2, p3, p4, ncol = 2, nrow = 2)</code></pre>
<p><img src="basicquant_files/figure-html/plotsqrt-1.png" width="672" /></p>
<p>The visualizations suggest that taking the square root results in a
near normal distribution of the data. Again, we use a Shapiro-Wilk test
to see if the distribution of the values of the square root of the word
counts is approximately normal.</p>
<pre class="r"><code># test for normality
shapiro.test(tdat$SquarerootWordcount)  # square root transforming appropriate here</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  tdat$SquarerootWordcount
## W = 0.96771, p-value = 2.075e-10</code></pre>
<p>Unfortunately, even the square root transformation has not made the
data fully normal as the distribution of the transformed data still
differs significantly from a normal distribution as shown by the
Shapiro-Wilk test.</p>
</div>
<div id="bayes-theorem" class="section level1" number="13">
<h1><span class="header-section-number">13</span> Bayes Theorem</h1>
<p>Bayes’ theorem is a fundamental concept in probability theory and
statistics, named after the Reverend Thomas Bayes. It describes how to
update our beliefs about the probability of an event based on new
evidence or information. The theorem mathematically relates the
conditional probability of an event A given B to the conditional
probability of B given A.</p>
<p>Here’s the formal statement of Bayes’ theorem:</p>
<p><span class="math display">\[\begin{equation}
P(A|B) = \frac{P(B|A) P(A)}{P(B)}
\end{equation}\]</span></p>
<p>In this equation:</p>
<ul>
<li>P(A|B) represents the conditional probability of event A given event
B.<br />
</li>
<li>P(B|A) represents the conditional probability of event B given event
A.</li>
<li>P(A) and P(B) represent the individual probabilities of events A and
B, respectively.</li>
</ul>
<p>To understand Bayes’ theorem better, let’s consider an example:</p>
<p>Suppose we want to investigate the use of a specific linguistic
feature, such as the pronunciation of the “r” sound in certain dialects.
We have two corpora: Corpus A, which represents speakers from a rural
area, and Corpus B, which represents speakers from an urban area. We
want to determine which corpus is more likely to exhibit the non-rhotic
pronunciation (dropping the “r” sound) in words like “car” or
“park.”</p>
<p>Let’s define the events: A: The sentence was produced by Corpus A. B:
The sentence contains non-rhotic pronunciation.</p>
<p>We are interested in calculating P(A|B), the probability that the
sentence was produced by Corpus A given that it contains non-rhotic
pronunciation.</p>
<p>We have the following information: + P(A) = 0.6 (Corpus A represents
a dialect with a higher likelihood of non-rhotic pronunciation) + P(B|A)
= 0.8 (Corpus A has an 80% chance of producing sentences with non-rhotic
pronunciation) + P(B|~A) = 0.3 (Corpus B has a 30% chance of producing
sentences with non-rhotic pronunciation)</p>
<p>Using Bayes’ theorem: <span class="math display">\[\begin{equation}
P(A|B) = \frac{P(B|A) P(A)}{P(B)}
\end{equation}\]</span></p>
<p>Now let’s substitute the given values: <span
class="math display">\[\begin{equation}
P(A|B) = \frac{0.8 * 0.6}{0.8 * 0.6 + 0.3 * (1 - 0.6)}
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
= \frac{0.48}{(0.48 + 0.3 * 0.4)}
≈ 0.48 / 0.6
≈ 0.8
\end{equation}\]</span></p>
<p>Therefore, the probability that a sentence containing non-rhotic
pronunciation was produced by Corpus A (representing the rural dialect)
is approximately 80%.</p>
<p>This example demonstrates how Bayes’ theorem can be applied in
sociolinguistics and corpus linguistics. By considering the prior
probabilities of each corpus (representing different dialects) and their
respective tendencies to exhibit a specific linguistic feature
(non-rhotic pronunciation), we can estimate the likelihood of a sentence
belonging to a particular dialect based on the evidence provided by the
presence of that feature in the sentence.</p>
<p>In the language sciences, Bayes’ theorem has become relevant with the
rise of Bayesian statistics (especially Bayesian mixed-effects models)
in experimental research, such as experimental psycholinguistics, where
Bayesian mixed-effects models are used as an alternative way to
frequentist mixed-models. Both types of models are applied to analyse
what factors correlate with the occurrence of a specific linguistic
feature.</p>
</div>
<div id="citation-session-info" class="section level1 unnumbered">
<h1 class="unnumbered">Citation &amp; Session Info</h1>
<p>Schweinberger, Martin. 2023. <em>Basic Concepts in Quantitative
Research</em>. Brisbane: The University of Queensland. url:
www.ladal.edu.au/basicquant.html (Version 2023.05.31).</p>
<pre><code>@manual{schweinberger2023basicquant,
  author = {Schweinberger, Martin},
  title = {Basic Concepts in Quantitative Research},
  note = {www.ladal.edu.au/basicquant.html},
  year = {2023.05.31},
  organization = &quot;The University of Queensland, Australia. School of Languages and Cultures},
  address = {Brisbane},
  edition = {2023.05.31}
}</code></pre>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.2.2 (2022-10-31 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 22621)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
## [3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
## [5] LC_TIME=English_Australia.utf8    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] ggpubr_0.6.0    e1071_1.7-13    flextable_0.9.1 lubridate_1.9.2
##  [5] forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2     purrr_1.0.1    
##  [9] readr_2.1.4     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.2  
## [13] tidyverse_2.0.0
## 
## loaded via a namespace (and not attached):
##  [1] nlme_3.1-162            fontquiver_0.2.1        backports_1.4.1        
##  [4] tools_4.2.2             bslib_0.4.2             utf8_1.2.3             
##  [7] R6_2.5.1                mgcv_1.8-42             colorspace_2.1-0       
## [10] withr_2.5.0             tidyselect_1.2.0        curl_5.0.0             
## [13] compiler_4.2.2          textshaping_0.3.6       cli_3.6.1              
## [16] xml2_1.3.4              officer_0.6.2           fontBitstreamVera_0.1.1
## [19] labeling_0.4.2          sass_0.4.6              scales_1.2.1           
## [22] proxy_0.4-27            askpass_1.1             systemfonts_1.0.4      
## [25] digest_0.6.31           rmarkdown_2.21          gfonts_0.2.0           
## [28] pkgconfig_2.0.3         htmltools_0.5.5         fastmap_1.1.1          
## [31] highr_0.10              rlang_1.1.1             rstudioapi_0.14        
## [34] httpcode_0.3.0          shiny_1.7.4             jquerylib_0.1.4        
## [37] generics_0.1.3          farver_2.1.1            jsonlite_1.8.4         
## [40] car_3.1-2               zip_2.3.0               magrittr_2.0.3         
## [43] Matrix_1.5-4.1          Rcpp_1.0.10             munsell_0.5.0          
## [46] fansi_1.0.4             abind_1.4-5             gdtools_0.3.3          
## [49] lifecycle_1.0.3         stringi_1.7.12          yaml_2.3.7             
## [52] carData_3.0-5           grid_4.2.2              promises_1.2.0.1       
## [55] crayon_1.5.2            lattice_0.21-8          cowplot_1.1.1          
## [58] splines_4.2.2           hms_1.1.3               knitr_1.43             
## [61] pillar_1.9.0            uuid_1.1-0              ggsignif_0.6.4         
## [64] crul_1.4.0              glue_1.6.2              evaluate_0.21          
## [67] fontLiberation_0.1.0    data.table_1.14.8       vctrs_0.6.2            
## [70] tzdb_0.4.0              httpuv_1.6.11           gtable_0.3.3           
## [73] openssl_2.0.6           cachem_1.0.8            xfun_0.39              
## [76] mime_0.12               broom_1.0.4             xtable_1.8-4           
## [79] rstatix_0.7.2           later_1.3.1             ragg_1.2.5             
## [82] class_7.3-22            timechange_0.2.0        ellipsis_0.3.2</code></pre>
<hr />
<p><a href="#introduction">Back to top</a></p>
<p><a href="https://ladal.edu.au">Back to HOME</a></p>
<hr />
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-field2012discovering" class="csl-entry">
Field, Andy, Jeremy Miles, and Zoe Field. 2012. <em>Discovering
Statistics Using r</em>. Sage.
</div>
<div id="ref-gries2009statistics" class="csl-entry">
Gries, Stefan Th. 2009. <em>Statistics for Linguistics Using r: A
Practical Introduction</em>. Berlin &amp; New York: Mouton de Gruyter.
</div>
<div id="ref-hair2017dist" class="csl-entry">
Hair, J. F., G. T. M. Hult, C. M. Ringle, and M. Sarstedt. 2017.
<span>“A Primer on Partial Least Squares Structural Equation Modeling
(PLS-SEM).”</span>
</div>
<div id="ref-wilson1999natural" class="csl-entry">
Wilson, EO. 1999. <span>“The Natural Sciences.”</span> <em>Consilience:
The Unity of Knowledge</em>, 49–71.
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
