<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.165">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martin Schweinberger">
<meta name="dcterms.date" content="2022-08-31">

<title>Introduction to Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-VSGK4KYDQZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-VSGK4KYDQZ', { 'anonymize_ip': true});
</script>
<link href="site_libs/tabwid-1.0.0/tabwid.css" rel="stylesheet">
<link href="site_libs/tabwid-1.0.0/scrool.css" rel="stylesheet">
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet">
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet">
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./ladal_icon_cas_tran_white_trimed.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Language Technology and Data Analysis Laboratory</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">HOME</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about-ladal" role="button" data-bs-toggle="dropdown" aria-expanded="false">ABOUT LADAL</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about-ladal">    
        <li>
    <a class="dropdown-item" href="./people.html">
 <span class="dropdown-text">People | Collabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./news.html">
 <span class="dropdown-text">News</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-events" role="button" data-bs-toggle="dropdown" aria-expanded="false">EVENTS</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-events">    
        <li>
    <a class="dropdown-item" href="./workshops.html">
 <span class="dropdown-text">Workshops</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./compthinking.html">
 <span class="dropdown-text">Computational Thinking in HASS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./webinars2022.html">
 <span class="dropdown-text">LADAL Webinar Series 2022</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./opening.html">
 <span class="dropdown-text">LADAL Webinar Series 2021</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./atapevents.html">
 <span class="dropdown-text">ATAP Events</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./tutorials.html">TUTORIALS</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="button" data-bs-toggle="dropdown" aria-expanded="false">RESOURCES</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="./links.html">
 <span class="dropdown-text">Links</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./base.html">
 <span class="dropdown-text">Tutorial stylesheet</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./contact.html">CONTACT</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-basic-principle" id="toc-the-basic-principle" class="nav-link" data-scroll-target="#the-basic-principle">The Basic Principle</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#example-1-preposition-use-across-real-time" id="toc-example-1-preposition-use-across-real-time" class="nav-link" data-scroll-target="#example-1-preposition-use-across-real-time">Example 1: Preposition Use across Real-Time</a>
  <ul class="collapse">
  <li><a href="#interpreting-output" id="toc-interpreting-output" class="nav-link" data-scroll-target="#interpreting-output">Interpreting Output</a></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics">Model Diagnostics</a></li>
  <li><a href="#summarizing-results" id="toc-summarizing-results" class="nav-link" data-scroll-target="#summarizing-results">Summarizing Results</a></li>
  </ul></li>
  <li><a href="#example-2-teaching-styles" id="toc-example-2-teaching-styles" class="nav-link" data-scroll-target="#example-2-teaching-styles">Example 2: Teaching Styles</a></li>
  </ul></li>
  <li><a href="#citation-session-info" id="toc-citation-session-info" class="nav-link" data-scroll-target="#citation-session-info">Citation &amp; Session Info</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Regression Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Martin Schweinberger </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 31, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output-display">
<p><img src="https://slcladal.github.io/images/uq1.jpg" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<section id="introduction" class="level1 unnumbered">
<h1 class="unnumbered">Introduction</h1>
<p>This tutorial introduces regression analyses (also called regression modeling) using R.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Regression models are among the most widely used quantitative methods in the language sciences to assess if and how predictors (variables or interactions between variables) correlate with a certain response.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="https://slcladal.github.io/images/yr_chili.jpg" class="img-fluid" style="float:right; padding:10px;width:15.0%"></p>
</div>
</div>
<p>This tutorial is aimed at intermediate and advanced users of R with the aim of showcasing how to perform regression analysis using R. The aim is not to provide a fully-fledged analysis but rather to show and exemplify common regression types, model diagnostics, and model fitting using R.</p>
<br>
<div class="warning" style="padding:0.1em; background-color:#f2f2f2; color:#51247a">
<span>
<p style="margin-top:1em; text-align:center">
The entire R Notebook for the tutorial can be downloaded <a href="https://slcladal.github.io/content/introreg.Rmd"><strong>here</strong></a>. If you want to render the R Notebook on your machine, i.e.&nbsp;knitting the document to html or a pdf, you need to make sure that you have R and RStudio installed and you also need to download the <a href="https://slcladal.github.io/content/bibliography.bib"><strong>bibliography file</strong></a> and store it in the same folder where you store the Rmd or the Rproj file. <br>
</p>
<p style="margin-left:1em;">
</p>
<p></p>
</span></div>
<p><br></p>
<p>Regression models are so popular because they can</p>
<ul>
<li><p>incorporate many predictors in a single model (multivariate: allows to test the impact of one predictor while the impact of (all) other predictors is controlled for)</p></li>
<li><p>extremely flexible and and can be fitted to different types of predictors and dependent variables</p></li>
<li><p>provide output that can be easily interpreted</p></li>
<li><p>conceptually relative simple and not overly complex from a mathematical perspective</p></li>
</ul>
<p>R offers various ready-made functions with which implementing different types of regression models is very easy.</p>
<p>The most widely use regression models are</p>
<ul>
<li><p>linear regression (dependent variable is numeric, no outliers)</p></li>
<li><p>logistic regression (dependent variable is binary)</p></li>
<li><p>ordinal regression (dependent variable represents an ordered factor, e.g.&nbsp;Likert items)</p></li>
<li><p>multinomial regression (dependent variable is categorical)</p></li>
</ul>
<p>The major difference between these types of models is that they take different types of dependent variables: linear regressions take numeric, logistic regressions take nominal variables, ordinal regressions take ordinal variables, and Poisson regressions take dependent variables that reflect counts of (rare) events. Robust regression, in contrast, is a simple multiple linear regression that is able to handle outliers due to a weighing procedure.</p>
<p>If regression models contain a random effect structure which is used to model nestedness or dependence among data points, the regression models are called <em>mixed-effect models</em>. regressions that do not have a random effect component to model nestedness or dependence are referred to as fixed-effect regressions (we will have a closer look at the difference between fixed and random effects below).</p>
<p>There are two basic types of regression models:</p>
<ul>
<li><p>fixed-effects regression models</p></li>
<li><p>mixed-effects regression models (which are fitted using the <code>lme4</code> package <span class="citation" data-cites="lme4">[<a href="#ref-lme4" role="doc-biblioref">1</a>]</span> in this tutorial).</p></li>
</ul>
<p>Fixed-effects regression models are models that assume a non-hierarchical data structure, i.e.&nbsp;data where data points are not nested or grouped in higher order categories (e.g.&nbsp;students within classes). The first part of this tutorial focuses on fixed-effects regression models while the second part focuses on mixed-effects regression models.</p>
<p>There exists a wealth of literature focusing on regression analysis and the concepts it is based on. For instance, there are <span class="citation" data-cites="achen1982interpreting">[<a href="#ref-achen1982interpreting" role="doc-biblioref">2</a>]</span>, <span class="citation" data-cites="bortz2006statistik">[<a href="#ref-bortz2006statistik" role="doc-biblioref">3</a>]</span>, <span class="citation" data-cites="crawley2005statistics">[<a href="#ref-crawley2005statistics" role="doc-biblioref">4</a>]</span>, <span class="citation" data-cites="faraway2002practical">[<a href="#ref-faraway2002practical" role="doc-biblioref">5</a>]</span>, <span class="citation" data-cites="field2012discovering">[<a href="#ref-field2012discovering" role="doc-biblioref">6</a>]</span> (my personal favorite), <span class="citation" data-cites="gries2021statistics">[<a href="#ref-gries2021statistics" role="doc-biblioref">7</a>]</span>, <span class="citation" data-cites="levshina2015linguistics">[<a href="#ref-levshina2015linguistics" role="doc-biblioref">8</a>]</span>, and <span class="citation" data-cites="wilcox2009basic">[<a href="#ref-wilcox2009basic" role="doc-biblioref">9</a>]</span> to name just a few. Introductions to regression modeling in R are <span class="citation" data-cites="baayen2008analyzing">[<a href="#ref-baayen2008analyzing" role="doc-biblioref">10</a>]</span>, <span class="citation" data-cites="crawley2012r">[<a href="#ref-crawley2012r" role="doc-biblioref">11</a>]</span>, <span class="citation" data-cites="gries2021statistics">[<a href="#ref-gries2021statistics" role="doc-biblioref">7</a>]</span>, or <span class="citation" data-cites="levshina2015linguistics">[<a href="#ref-levshina2015linguistics" role="doc-biblioref">8</a>]</span>.</p>
</section>
<section id="the-basic-principle" class="level1 unnumbered">
<h1 class="unnumbered">The Basic Principle</h1>
<p>The idea behind regression analysis is expressed formally in the equation below where <span class="math inline">\(f_{(x)}\)</span> is the <span class="math inline">\(y\)</span>-value we want to predict, <span class="math inline">\(\alpha\)</span> is the intercept (the point where the regression line crosses the <span class="math inline">\(y\)</span>-axis), <span class="math inline">\(\beta\)</span> is the coefficient (the slope of the regression line).</p>
<p><span class="math display">\[\begin{equation}
f_{(x)} = \alpha + \beta_{i}x + \epsilon
\end{equation}\]</span></p>
<p>To understand what this means, let us imagine that we have collected information about the how tall people are and what they weigh. Now we want to predict the weight of people of a certain height - let’s say 180cm.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<div class="tabwid"><style>.cl-9a5b5f68{table-layout:auto;width:75%;}.cl-9a532dca{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9a532dcb{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9a5339c8{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9a5358ae{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358b8{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358c2{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358c3{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358c4{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358c5{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358cc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9a5358cd{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class="cl-9a5b5f68">
<caption class="Table Caption">
<p>Weigth and height of a random sample of people.</p>
</caption>

<thead><tr style="overflow-wrap:break-word;"><td class="cl-9a5358cc"><p class="cl-9a5339c8"><span class="cl-9a532dca">Height</span></p></td><td class="cl-9a5358cd"><p class="cl-9a5339c8"><span class="cl-9a532dca">Weight</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9a5358ae"><p class="cl-9a5339c8"><span class="cl-9a532dcb">173</span></p></td><td class="cl-9a5358b8"><p class="cl-9a5339c8"><span class="cl-9a532dcb">80</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358c4"><p class="cl-9a5339c8"><span class="cl-9a532dcb">169</span></p></td><td class="cl-9a5358c5"><p class="cl-9a5339c8"><span class="cl-9a532dcb">68</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358ae"><p class="cl-9a5339c8"><span class="cl-9a532dcb">176</span></p></td><td class="cl-9a5358b8"><p class="cl-9a5339c8"><span class="cl-9a532dcb">72</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358c4"><p class="cl-9a5339c8"><span class="cl-9a532dcb">166</span></p></td><td class="cl-9a5358c5"><p class="cl-9a5339c8"><span class="cl-9a532dcb">75</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358ae"><p class="cl-9a5339c8"><span class="cl-9a532dcb">161</span></p></td><td class="cl-9a5358b8"><p class="cl-9a5339c8"><span class="cl-9a532dcb">70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358c4"><p class="cl-9a5339c8"><span class="cl-9a532dcb">164</span></p></td><td class="cl-9a5358c5"><p class="cl-9a5339c8"><span class="cl-9a532dcb">65</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358ae"><p class="cl-9a5339c8"><span class="cl-9a532dcb">160</span></p></td><td class="cl-9a5358b8"><p class="cl-9a5339c8"><span class="cl-9a532dcb">62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358c4"><p class="cl-9a5339c8"><span class="cl-9a532dcb">158</span></p></td><td class="cl-9a5358c5"><p class="cl-9a5339c8"><span class="cl-9a532dcb">60</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358ae"><p class="cl-9a5339c8"><span class="cl-9a532dcb">180</span></p></td><td class="cl-9a5358b8"><p class="cl-9a5339c8"><span class="cl-9a532dcb">85</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9a5358c2"><p class="cl-9a5339c8"><span class="cl-9a532dcb">187</span></p></td><td class="cl-9a5358c3"><p class="cl-9a5339c8"><span class="cl-9a532dcb">92</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>We can run a simple linear regression on the data and we get the following output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model for upper panels</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(Weight <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Weight ~ 1, data = df)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-12.90   -7.15   -1.90    5.85   19.10  

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   72.900      3.244   22.48 3.24e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 105.2111)

    Null deviance: 946.9  on 9  degrees of freedom
Residual deviance: 946.9  on 9  degrees of freedom
AIC: 77.885

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>To estimate how much some weights who is 180cm tall, we would multiply the coefficient (slope of the line) with 180 (<span class="math inline">\(x\)</span>) and add the value of the intercept (point where line crosses the <span class="math inline">\(y\)</span>-axis). If we plug in the numbers from the regression model below, we get</p>
<p><span class="math display">\[\begin{equation}
-93.77 + 0.98 ∗ 180 = 83.33 (kg)
\end{equation}\]</span></p>
<p>A person who is 180cm tall is predicted to weigh 83.33kg. Thus, the predictions of the weights are visualized as the red line in the figure below. Such lines are called <em>regression lines</em>. Regression lines are those lines where the sum of the red lines should be minimal. The slope of the regression line is called <em>coefficient</em> and the point where the regression line crosses the y-axis at x = 0 is called the <em>intercept</em>. Other important concepts in regression analysis are <em>variance</em> and <em>residuals</em>. <em>Residuals</em> are the distance between the line and the points (the red lines) and it is also called <em>variance</em>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/intro01-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Some words about the plots in the figure above: the upper left panel shows the raw observed data (black dots). The upper right panel shows the mean weight (blue line) and the residuals (in red). residuals are the distances from the expected or predicted values to the observed values (in this case the mean is the most most basic model which we use to predict values while the observed values simply represent the actual data points). The lower left panel shows observed values and the regression line, i.e, that line which, when drawn through the data points, will have the lowest sum of residuals. The lower right panel shows the regression line and the residuals, i.e.&nbsp;the distances between the expected or predicted values to the actual observed values (in red). Note that the sum of residuals in the lower right panel is much smaller than the sum of residuals in the upper right panel. This suggest that considering Height is a good idea as it explains a substantive amount of residual error and reduces the sum of residuals (or variance).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Now that we are familiar with the basic principle of regression modeling - i.e.&nbsp;finding the line through data that has the smallest sum of residuals, we will apply this to a linguistic example.</p>
<p><strong>Preparation and session set up</strong></p>
<p>This tutorial is based on R. If you have not installed R or are new to it, you will find an introduction to and more information how to use R <a href="https://slcladal.github.io/intror.html">here</a>. For this tutorials, we need to install certain <em>packages</em> from an R <em>library</em> so that the scripts shown below are executed without errors. Before turning to the code below, please install the packages by running the code below this paragraph. If you have already installed the packages mentioned below, then you can skip ahead and ignore this section. To install the necessary packages, simply run the following code - it may take some time (between 1 and 5 minutes to install all of the libraries so you do not need to worry if it takes some time).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("car")</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"flextable"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggpubr"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggfortify"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"see"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"performance"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"report"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># install klippy for copy-to-clipboard button in code chunks</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"remotes"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"rlesur/klippy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have installed the packages, we activate them as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set options</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">stringsAsFactors =</span> F)          <span class="co"># no automatic data transformation</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="st">"scipen"</span> <span class="ot">=</span> <span class="dv">100</span>, <span class="st">"digits"</span> <span class="ot">=</span> <span class="dv">12</span>) <span class="co"># suppress math annotation</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># activate klippy for copy-to-clipboard button</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>klippy<span class="sc">::</span><span class="fu">klippy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
</div>
</div>
<p>Once you have installed R and RStudio and initiated the session by executing the code shown above, you are good to go.</p>
</section>
<section id="simple-linear-regression" class="level1 unnumbered">
<h1 class="unnumbered">Simple Linear Regression</h1>
<p>Simple Linear Regression is the most basic type of regression and it it falls into the class of fixed-effects regression models. Regressions are used when we try to understand how independent variables correlate with a dependent or outcome variable. So, if you want to investigate how a certain factor affects an outcome, then a regression is the way to go. We will have a look at two simple examples to understand what the concepts underlying a regression mean and how a regression works. The R code, that we will use, is adapted from many highly recommendable introductions which also focus on regression (among other types of analyses), for example, <span class="citation" data-cites="gries2021statistics">[<a href="#ref-gries2021statistics" role="doc-biblioref">7</a>]</span>, <span class="citation" data-cites="winter2019statistics">[<a href="#ref-winter2019statistics" role="doc-biblioref">12</a>]</span>, <span class="citation" data-cites="levshina2015linguistics">[<a href="#ref-levshina2015linguistics" role="doc-biblioref">8</a>]</span>, <span class="citation" data-cites="winter2019statistics">[<a href="#ref-winter2019statistics" role="doc-biblioref">12</a>]</span> or <span class="citation" data-cites="wilcox2009basic">[<a href="#ref-wilcox2009basic" role="doc-biblioref">9</a>]</span>. <span class="citation" data-cites="baayen2008analyzing">[<a href="#ref-baayen2008analyzing" role="doc-biblioref">10</a>]</span> is also very good but probably not the first book one should read about statistics but it is highly recommendable for advanced learners.</p>
<p>Although the basic logic underlying regressions is identical to the conceptual underpinnings of <em>analysis of variance</em> (ANOVA), a related method, sociolinguists have traditionally favored regression analysis in their studies while ANOVAs have been the method of choice in psycholinguistics. The preference for either method is grounded in historical happenstances and the culture of these subdisciplines rather than in methodological reasoning. However, ANOVA are more restricted in that they can only take numeric dependent variables and they have stricter model assumptions that are violated more readily. In addition, a minor difference between regressions and ANOVA lies in the fact that regressions are based on the <span class="math inline">\(t\)</span>-distribution while ANOVAs use the F-distribution (however, the F-value is simply the value of t squared or t<sup>2</sup>). Both t- and F-values report on the ratio between explained and unexplained variance.</p>
<p>The idea behind regression analysis is expressed formally in the equation below where<span class="math inline">\(f_{(x)}\)</span> is the y-value we want to predict, <span class="math inline">\(\alpha\)</span> is the intercept (the point where the regression line crosses the y-axis at x = 0), <span class="math inline">\(\beta\)</span> is the coefficient (the slope of the regression line).</p>
<p><span class="math display">\[\begin{equation}
f_{(x)} = \alpha + \beta_{i}x + \epsilon
\end{equation}\]</span></p>
<p>In other words, to estimate how much some weights who is 180cm tall, we would multiply the coefficient (slope of the line) with 180 (x) and add the value of the intercept (point where line crosses the y-axis at x = 0).</p>
<p>However, the idea behind regressions can best be described graphically: imagine a cloud of points (like the points in the scatterplot in the upper left panel below). Regressions aim to find that line which has the minimal summed distance between points and the line (like the line in the lower panels). Technically speaking, the aim of a regression is to find the line with the minimal deviance (or the line with the minimal sum of residuals). Residuals are the distance between the line and the points (the red lines) and it is also called <em>variance</em>.</p>
<p>Thus, regression lines are those lines where the sum of the red lines should be minimal. The slope of the regression line is called <em>coefficient</em> and the point where the regression line crosses the y-axis at x = 0 is called the <em>intercept</em>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A word about standard errors (SE) is in order here because most commonly used statistics programs will provide SE values when reporting regression models. The SE is a measure that tells us how much the coefficients were to vary if the same regression were applied to many samples from the same population. A relatively small SE value therefore indicates that the coefficients will remain very stable if the same regression model is fitted to many different samples with identical parameters. In contrast, a large SE tells you that the model is volatile and not very stable or reliable as the coefficients vary substantially if the model is applied to many samples.</p>
<p>Mathematically, the SE is the standard deviation (SD) divided by the square root of the sample size (N) (see below).The SD is the square root of the deviance (that is, the SD is the square root of the sum of the mean <span class="math inline">\(\bar{x}\)</span> minus each data point (x<sub>i</sub>) squared divided by the sample size (N) minus 1).</p>
<p><span class="math display">\[\begin{equation}
Standard Error (SE) = \frac{\sum (\bar{x}-x_{i})^2/N-1}{\sqrt{N}} = \frac{SD}{\sqrt{N}}
\end{equation}\]</span></p>
<section id="example-1-preposition-use-across-real-time" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="example-1-preposition-use-across-real-time">Example 1: Preposition Use across Real-Time</h2>
<p>We will now turn to our first example. In this example, we will investigate whether the frequency of prepositions has changed from Middle English to Late Modern English. The reasoning behind this example is that Old English was highly synthetic compared with Present-Day English which comparatively analytic. In other words, while Old English speakers used case to indicate syntactic relations, speakers of Present-Day English use word order and prepositions to indicate syntactic relationships. This means that the loss of case had to be compensated by different strategies and maybe these strategies continued to develop and increase in frequency even after the change from synthetic to analytic had been mostly accomplished. And this prolonged change in compensatory strategies is what this example will focus on.</p>
<p>The analysis is based on data extracted from the <em>Penn Corpora of Historical English</em> (see http://www.ling.upenn.edu/hist-corpora/), that consists of 603 texts written between 1125 and 1900. In preparation of this example, all elements that were part-of-speech tagged as prepositions were extracted from the PennCorpora.</p>
<p>Then, the relative frequencies (per 1,000 words) of prepositions per text were calculated. This frequency of prepositions per 1,000 words represents our dependent variable. In a next step, the date when each letter had been written was extracted. The resulting two vectors were combined into a table which thus contained for each text, when it was written (independent variable) and its relative frequency of prepositions (dependent or outcome variable).</p>
<p>A regression analysis will follow the steps described below:</p>
<ol type="1">
<li><p>Extraction and processing of the data</p></li>
<li><p>Data visualization</p></li>
<li><p>Applying the regression analysis to the data</p></li>
<li><p>Diagnosing the regression model and checking whether or not basic model assumptions have been violated.</p></li>
</ol>
<p>In a first step, we load functions that we may need (which in this case is a function that we will use to summarize the results of the analysis).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load functions</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"https://slcladal.github.io/rscripts/slrsummary.r"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After preparing our session, we can now load and inspect the data to get a first impression of its properties.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>slrdata  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">"https://slcladal.github.io/data/sld.rda"</span>, <span class="st">"rb"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<div class="tabwid"><style>.cl-9c88a4d0{table-layout:auto;width:75%;}.cl-9c8339aa{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9c8339be{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9c8349fe{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9c8349ff{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9c838afe{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b08{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b12{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b13{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b1c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b26{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b27{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b30{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b31{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b3a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b44{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b45{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b46{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b4e{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b58{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9c838b59{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class="cl-9c88a4d0">
<caption class="Table Caption">
<p>First 15 rows of slrdata.</p>
</caption>

<thead><tr style="overflow-wrap:break-word;"><td class="cl-9c838b46"><p class="cl-9c8349fe"><span class="cl-9c8339aa">Date</span></p></td><td class="cl-9c838b4e"><p class="cl-9c8349ff"><span class="cl-9c8339aa">Genre</span></p></td><td class="cl-9c838b4e"><p class="cl-9c8349ff"><span class="cl-9c8339aa">Text</span></p></td><td class="cl-9c838b58"><p class="cl-9c8349fe"><span class="cl-9c8339aa">Prepositions</span></p></td><td class="cl-9c838b59"><p class="cl-9c8349ff"><span class="cl-9c8339aa">Region</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,736</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Science</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">albin</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">166.01</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,711</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Education</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">anon</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">139.86</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,808</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">PrivateLetter</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">austen</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">130.78</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,878</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Education</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">bain</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">151.29</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,743</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Education</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">barclay</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">145.72</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,908</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Education</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">benson</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">120.77</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,906</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Diary</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">benson</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">119.17</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,897</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Philosophy</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">boethja</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">132.96</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,785</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Philosophy</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">boethri</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">130.49</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,776</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Diary</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">boswell</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">135.94</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,905</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Travel</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">bradley</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">154.20</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,711</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Education</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">brightland</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">149.14</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b13"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,762</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">Sermon</span></p></td><td class="cl-9c838afe"><p class="cl-9c8349ff"><span class="cl-9c8339be">burton</span></p></td><td class="cl-9c838b08"><p class="cl-9c8349fe"><span class="cl-9c8339be">159.71</span></p></td><td class="cl-9c838b12"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b27"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,726</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">Sermon</span></p></td><td class="cl-9c838b1c"><p class="cl-9c8349ff"><span class="cl-9c8339be">butler</span></p></td><td class="cl-9c838b30"><p class="cl-9c8349fe"><span class="cl-9c8339be">157.49</span></p></td><td class="cl-9c838b26"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9c838b31"><p class="cl-9c8349fe"><span class="cl-9c8339be">1,835</span></p></td><td class="cl-9c838b3a"><p class="cl-9c8349ff"><span class="cl-9c8339be">PrivateLetter</span></p></td><td class="cl-9c838b3a"><p class="cl-9c8349ff"><span class="cl-9c8339be">carlyle</span></p></td><td class="cl-9c838b44"><p class="cl-9c8349fe"><span class="cl-9c8339be">124.16</span></p></td><td class="cl-9c838b45"><p class="cl-9c8349ff"><span class="cl-9c8339be">North</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Inspecting the data is very important because it can happen that a data set may not load completely or that variables which should be numeric have been converted to character variables. If unchecked, then such issues could go unnoticed and cause trouble.</p>
<p>We will now plot the data to get a better understanding of what the data looks like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(slrdata, <span class="fu">aes</span>(Date, Prepositions)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Prepositions per 1,000 words"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(slrdata, <span class="fu">aes</span>(Date, Prepositions)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Prepositions per 1,000 words"</span>) <span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="co"># with linear model smoothing!</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># display plots</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggarrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Before beginning with the regression analysis, we will center the Date variable using the <code>scale</code> function. We center the values of Date by subtracting each value from the mean of Date. This can be useful when dealing with numeric variables because if we did not center Date, we would get estimated values for year 0 (a year when English did not even exist yet). If a variable is centered, the regression provides estimates of the model refer to the mean of that numeric variable. In other words, centering can be very helpful, especially with respect to the interpretation of the results that regression models report.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># center date</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>slrdata <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">scale</span>(Date)) <span class="ot">-&gt;</span> slrdata </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will now begin the regression analysis by generating a first regression model and inspect its results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create initial model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>m1.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prepositions <span class="sc">~</span> Date, <span class="at">data =</span> slrdata)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect results</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Prepositions ~ Date, data = slrdata)

Residuals:
        Min          1Q      Median          3Q         Max 
-69.1012471 -13.8549421   0.5779091  13.3208913  62.8580401 

Coefficients:
                 Estimate    Std. Error   t value             Pr(&gt;|t|)    
(Intercept) 132.190093110   0.838637480 157.62483 &lt; 0.0000000000000002 ***
Date          2.000732730   0.839419427   2.38347             0.017498 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.4339648 on 535 degrees of freedom
Multiple R-squared:  0.010507008,   Adjusted R-squared:  0.00865748837 
F-statistic: 5.68093894 on 1 and 535 DF,  p-value: 0.017498081</code></pre>
</div>
</div>
<section id="interpreting-output" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpreting-output">Interpreting Output</h3>
<p>The summary output starts by repeating the regression equation. Then, the model provides the distribution of the residuals. The residuals should be distributed normally with the absolute values of the Min and Max as well as the 1Q (first quartile) and 3Q (third quartile) being similar or ideally identical. In our case, the values are very similar which suggests that the residuals are distributed evenly and follow a normal distribution. The next part of the report is the coefficients table. The estimate for the intercept is the value of y at x = 0. The estimate for Date represents the slope of the regression line and tells us that with each year, the predicted frequency of prepositions increase by .01732 prepositions. The t-value is the Estimate divided by the standard error (Std. Error). Based on the t-value, the p-value can be calculated manually as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use pt function (which uses t-values and the degrees of freedom)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.383</span>, <span class="fu">nrow</span>(slrdata)<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0175196401501</code></pre>
</div>
</div>
<p>The R<sup>2</sup>-values tell us how much variance is explained by our model. The baseline value represents a model that uses merely the mean. 0.0105 means that our model explains only 1.05 percent of the variance (0.010 x 100) - which is a tiny amount. The problem of the multiple R<sup>2</sup> is that it will increase even if we add variables that explain almost no variance. Hence, multiple R<sup>2</sup> encourages the inclusion of <em>junk</em> variables.</p>
<p><span class="math display">\[\begin{equation}
R^2 = R^2_{multiple} = 1 - \frac{\sum (y_i - \hat{y_i})^2}{\sum (y_i - \bar y)^2}
\end{equation}\]</span></p>
<p>The adjusted R<sup>2</sup>-value takes the number of predictors into account and, thus, the adjusted R<sup>2</sup> will always be lower than the multiple R<sup>2</sup>. This is so because the adjusted R<sup>2</sup> penalizes models for having predictors. The equation for the adjusted R<sup>2</sup> below shows that the amount of variance that is explained by all the variables in the model (the top part of the fraction) must outweigh the inclusion of the number of variables (k) (lower part of the fraction). Thus, the adjusted R<sup>2</sup> will decrease when variables are added that explain little or even no variance while it will increase if variables are added that explain a lot of variance.</p>
<p><span class="math display">\[\begin{equation}
R^2_{adjusted} = 1 - (\frac{(1 - R^2)(n - 1)}{n - k - 1})
\end{equation}\]</span></p>
<p>If there is a big difference between the two R<sup>2</sup>-values, then the model contains (many) predictors that do not explain much variance which is not good. The F-statistic and the associated p-value tell us that the model, despite explaining almost no variance, is still significantly better than an intercept-only base-line model (or using the overall mean to predict the frequency of prepositions per text).</p>
<p>We can test this and also see where the F-values comes from by comparing the fit of the baseline or null model which only used the overall mean as the sole predictor with the fit of our regression model with used Date as a predictor for preposition use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create intercept-only base-line model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>m0.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prepositions <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> slrdata)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the base-line and the more saturated model</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1.lm, m0.lm, <span class="at">test =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Prepositions ~ Date
Model 2: Prepositions ~ 1
  Res.Df         RSS Df   Sum of Sq       F   Pr(&gt;F)  
1    535 202058.2576                                  
2    536 204203.8289 -1 -2145.57126 5.68094 0.017498 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The F- and p-values are exactly those reported by the summary which shows where the F-values comes from and what it means; namely it denote the difference between the base-line and the more saturated model.</p>
<p>The degrees of freedom associated with the residual standard error are the number of cases in the model minus the number of predictors (including the intercept). The residual standard error is square root of the sum of the squared residuals of the model divided by the degrees of freedom. Have a look at he following to clear this up:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DF = N - number of predictors (including intercept)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>DegreesOfFreedom <span class="ot">&lt;-</span> <span class="fu">nrow</span>(slrdata)<span class="sc">-</span><span class="fu">length</span>(<span class="fu">coef</span>(m1.lm))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># sum of the squared residuals</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>SumSquaredResiduals <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(m1.lm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual Standard Error</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(SumSquaredResiduals<span class="sc">/</span>DegreesOfFreedom); DegreesOfFreedom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.4339647585</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 535</code></pre>
</div>
</div>
</section>
<section id="model-diagnostics" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="model-diagnostics">Model Diagnostics</h3>
<p>We will now check if mathematical assumptions have been violated (homogeneity of variance) or whether the data contains outliers. We check this using diagnostic plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(<span class="fu">resid</span>(m1.lm)),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">residuals =</span> <span class="fu">resid</span>(m1.lm),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">standard =</span> <span class="fu">rstandard</span>(m1.lm),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">studend =</span> <span class="fu">rstudent</span>(m1.lm))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># generate plots</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> id, <span class="at">y =</span> residuals)) <span class="sc">+</span> </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Residuals"</span>, <span class="at">x =</span> <span class="st">"Index"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> id, <span class="at">y =</span> standard)) <span class="sc">+</span> </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Standardized Residuals"</span>, <span class="at">x =</span> <span class="st">"Index"</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> id, <span class="at">y =</span> studend)) <span class="sc">+</span> </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Studentized Residuals"</span>, <span class="at">x =</span> <span class="st">"Index"</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="co"># display plots</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggarrange</span>(p1, p2, p3, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The left graph shows the residuals of the model (i.e., the differences between the observed and the values predicted by the regression model). The problem with this plot is that the residuals are not standardized and so they cannot be compared to the residuals of other models. To remedy this deficiency, residuals are normalized by dividing the residuals by their standard deviation. Then, the normalized residuals can be plotted against the observed values (center panel). In this way, not only are standardized residuals obtained, but the values of the residuals are transformed into z-values, and one can use the z-distribution to find problematic data points. There are three rules of thumb regarding finding problematic data points through standardized residuals <span class="citation" data-cites="field2012discovering">[<a href="#ref-field2012discovering" role="doc-biblioref">6</a>]</span>:</p>
<ul>
<li><p>Points with values higher than 3.29 should be removed from the data.</p></li>
<li><p>If more than 1% of the data points have values higher than 2.58, then the error rate of our model is too high.</p></li>
<li><p>If more than 5% of the data points have values greater than 1.96, then the error rate of our model is too high.</p></li>
</ul>
<p>The right panel shows the * studentized residuals* (adjusted predicted values: each data point is divided by the standard error of the residuals). In this way, it is possible to use Student’s t-distribution to diagnose our model.</p>
<p>Adjusted predicted values are residuals of a special kind: the model is calculated without a data point and then used to predict this data point. The difference between the observed data point and its predicted value is then called the adjusted predicted value. In summary, studentized residuals are very useful because they allow us to identify influential data points.</p>
<p>The plots show that there are two potentially problematic data points (the top-most and bottom-most point). These two points are clearly different from the other data points and may therefore be outliers. We will test later if these points need to be removed.</p>
<p>We will now generate more diagnostic plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate plots</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(m1.lm) <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The diagnostic plots are very positive and we will go through why this is so for each panel. The graph in the upper left panel is useful for finding outliers or for determining the correlation between residuals and predicted values: when a trend becomes visible in the line or points (e.g., a rising trend or a zigzag line), then this would indicate that the model would be problematic (in such cases, it can help to remove data points that are too influential (outliers)).</p>
<p>The graphic in the upper right panel indicates whether the residuals are normally distributed (which is desirable) or whether the residuals do not follow a normal distribution. If the points lie on the line, the residuals follow a normal distribution. For example, if the points are not on the line at the top and bottom, it shows that the model does not predict small and large values well and that it therefore does not have a good fit.</p>
<p>The graphic in the lower left panel provides information about <em>homoscedasticity</em>. Homoscedasticity means that the variance of the residuals remains constant and does not correlate with any independent variable. In unproblematic cases, the graphic shows a flat line. If there is a trend in the line, we are dealing with heteroscedasticity, that is, a correlation between independent variables and the residuals, which is very problematic for regressions.</p>
<p>The graph in the lower right panel shows problematic influential data points that disproportionately affect the regression (this would be problematic). If such influential data points are present, they should be either weighted (one could generate a robust rather than a simple linear regression) or they must be removed. The graph displays Cook’s distance, which shows how the regression changes when a model without this data point is calculated. The cook distance thus shows the influence a data point has on the regression as a whole. Data points that have a Cook’s distance value greater than 1 are problematic <span class="citation" data-cites="field2012discovering">[<a href="#ref-field2012discovering" role="doc-biblioref">6</a>]</span>.</p>
<p>The so-called leverage is also a measure that indicates how strongly a data point affects the accuracy of the regression. Leverage values range between 0 (no influence) and 1 (strong influence: suboptimal!). To test whether a specific data point has a high leverage value, we calculate a cut-off point that indicates whether the leverage is too strong or still acceptable. The following two formulas are used for this:</p>
<p><span class="math display">\[\begin{equation}
Leverage = \frac{3(k + 1)}{n} |  \frac{2(k + 1)}{n}
\end{equation}\]</span></p>
<p>We will look more closely at leverage in the context of multiple linear regression. We can thus turn to summarized our regression analysis.</p>
<p><strong>Model Diagnostics Made Easy</strong></p>
<p>A very handy way to inspect the quality of regression models is offered by the <code>performance</code> package as the <code>check_model</code> function in the <code>performance</code> package extracts and provides summaries of model diagnostics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create summary table</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(m1.lm)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr_diag-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Using the <code>performance</code> package to inspect model diagnostics is really easy and neat. However, extracting the diagnostics using the <code>check_model</code> function is not always advisable, for instance, when dealing with only a categorical (instead of a numeric predictor). The decision what diagnostics to inspect and how to interpret them thus depends on the model and what the diagnostics are supposed to check. If you are unsure, I suggest you extract all diagnostics and see if there are apparent issues (indicated by high values or deviations from the expected values).</p>
<p>In addition, we can use the <code>performance</code> package to validate(or inspect) the performance of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create summary table</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">model_performance</span>(m1.lm)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC      |      BIC |    R2 | R2 (adj.) |   RMSE |  Sigma
---------------------------------------------------------
4714.518 | 4727.376 | 0.011 |     0.009 | 19.398 | 19.434</code></pre>
</div>
</div>
</section>
<section id="summarizing-results" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="summarizing-results">Summarizing Results</h3>
<p>Commonly, the results of regression analyses are summarized in tabular format and additionally described in prose. We therefore start the write-up with a tabular summary summarizing the results of the regression analysis in a table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create summary table</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">slrsummary</span>(m1.lm)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<div class="tabwid"><style>.cl-9df4fdf0{table-layout:auto;width:75%;}.cl-9df1e00c{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9df1e016{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9df1e8ea{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9df20686{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df20690{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df2069a{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df2069b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df2069c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df2069d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206a4{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206a5{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206ae{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206af{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206b8{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9df206b9{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class="cl-9df4fdf0">
<caption class="Table Caption">
<p>Results of a simple linear regression analysis.</p>
</caption>

<thead><tr style="overflow-wrap:break-word;"><td class="cl-9df206b9"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">Parameters</span></p></td><td class="cl-9df206af"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">Estimate</span></p></td><td class="cl-9df206af"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">Pearson's r</span></p></td><td class="cl-9df206af"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">Std. Error</span></p></td><td class="cl-9df206af"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">t value</span></p></td><td class="cl-9df206af"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">Pr(&gt;|t|)</span></p></td><td class="cl-9df206b8"><p class="cl-9df1e8ea"><span class="cl-9df1e00c">P-value sig.</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9df2069a"><p class="cl-9df1e8ea"><span class="cl-9df1e016">(Intercept)</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016">132.19</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.84</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016">157.62</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0</span></p></td><td class="cl-9df20690"><p class="cl-9df1e8ea"><span class="cl-9df1e016">p &lt; .001***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069b"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Date</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016">2</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.1</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.84</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016">2.38</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.0175</span></p></td><td class="cl-9df2069d"><p class="cl-9df1e8ea"><span class="cl-9df1e016">p &lt; .05*</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069a"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Model statistics</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20690"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Value</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069b"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Number of cases in model</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069d"><p class="cl-9df1e8ea"><span class="cl-9df1e016">537</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069a"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Residual standard error on 535 DF</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20690"><p class="cl-9df1e8ea"><span class="cl-9df1e016">19.43</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069b"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Multiple R-squared</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069d"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.0105</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069a"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Adjusted R-squared</span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20686"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df20690"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.0087</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df2069b"><p class="cl-9df1e8ea"><span class="cl-9df1e016">F-statistic (1, 535)</span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069c"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df2069d"><p class="cl-9df1e8ea"><span class="cl-9df1e016">5.68</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9df206ae"><p class="cl-9df1e8ea"><span class="cl-9df1e016">Model p-value</span></p></td><td class="cl-9df206a4"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df206a4"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df206a4"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df206a4"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df206a4"><p class="cl-9df1e8ea"><span class="cl-9df1e016"></span></p></td><td class="cl-9df206a5"><p class="cl-9df1e8ea"><span class="cl-9df1e016">0.0175</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>An alternative but less informative summary table of the results of a regression analysis can be generated using the <code>tab_model</code> function from the <code>sjPlot</code> package <span class="citation" data-cites="sjPlot">[<a href="#ref-sjPlot" role="doc-biblioref">13</a>]</span> (as is shown below).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate summary table</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m1.lm) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Prepositions</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">132.19</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">130.54&nbsp;–&nbsp;133.84</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Date</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">2.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.35&nbsp;–&nbsp;3.65</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>0.017</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">537</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.011 / 0.009</td>
</tr>

</tbody></table>

</div>
</div>
<hr>
<p>Typically, the results of regression analyses are presented in such tables as they include all important measures of model quality and significance, as well as the magnitude of the effects.</p>
<p>In addition, the results of simple linear regressions should be summarized in writing.</p>
<p>We can use the <code>reports</code> package <span class="citation" data-cites="report">[<a href="#ref-report" role="doc-biblioref">14</a>]</span> to summarize the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Prepositions with Date (formula: Prepositions ~ Date). The model explains a statistically significant and very weak proportion of variance (R2 = 0.01, F(1, 535) = 5.68, p = 0.017, adj. R2 = 8.66e-03). The model's intercept, corresponding to Date = 0, is at 132.19 (95% CI [130.54, 133.84], t(535) = 157.62, p &lt; .001). Within this model:

  - The effect of Date is statistically significant and positive (beta = 2.00, 95% CI [0.35, 3.65], t(535) = 2.38, p = 0.017; Std. beta = 0.10, 95% CI [0.02, 0.19])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
</div>
</div>
<p>We can use this output to write up a final report:</p>
<p>A simple linear regression has been fitted to the data. A visual assessment of the model diagnostic graphics did not indicate any problematic or disproportionately influential data points (outliers) and performed significantly better compared to an intercept-only base line model but only explained .87 percent of the variance (adjusted R<sup>2</sup>: .0087, F-statistic (1, 535): 5,68, p-value: 0.0175*). The final minimal adequate linear regression model is based on 537 data points and confirms a significant and positive correlation between the year in which the text was written and the relative frequency of prepositions (coefficient estimate: .02 (standardized : 0.10, 95% CI [0.02, 0.19]), SE: 0.01, t-value<sub>535</sub>: 2.38, p-value: .0175*). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</p>
</section>
</section>
<section id="example-2-teaching-styles" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="example-2-teaching-styles">Example 2: Teaching Styles</h2>
<p>In the previous example, we dealt with two numeric variables, while the following example deals with a categorical independent variable and a numeric dependent variable. The ability for regressions to handle very different types of variables makes regressions a widely used and robust method of analysis.</p>
<p>In this example, we are dealing with two groups of students that have been randomly assigned to be exposed to different teaching methods. Both groups undergo a language learning test after the lesson with a maximum score of 20 points.</p>
<p>The question that we will try to answer is whether the students in group A have performed significantly better than those in group B which would indicate that the teaching method to which group A was exposed works better than the teaching method to which group B was exposed.</p>
<p>Let’s move on to implementing the regression in R. In a first step, we load the data set and inspect its structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>slrdata2  <span class="ot">&lt;-</span> base<span class="sc">::</span><span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="st">"https://slcladal.github.io/data/sgd.rda"</span>, <span class="st">"rb"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<div class="tabwid"><style>.cl-9ebf52c6{table-layout:auto;width:75%;}.cl-9eba6392{font-family:'DejaVu Sans';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9eba63a6{font-family:'DejaVu Sans';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9eba756c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9eba7576{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9ebaaaaa{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaabe{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaabf{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaac8{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaac9{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaad2{background-color:rgba(239, 239, 239, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaadc{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 1pt solid rgba(102, 102, 102, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9ebaaadd{background-color:rgba(207, 207, 207, 1.00);vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(102, 102, 102, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class="cl-9ebf52c6">
<caption class="Table Caption">
<p>First 15 rows of the slrdata2 data.</p>
</caption>

<thead><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaadc"><p class="cl-9eba756c"><span class="cl-9eba6392">Group</span></p></td><td class="cl-9ebaaadd"><p class="cl-9eba7576"><span class="cl-9eba6392">Score</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">12</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">11</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">18</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">19</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">14</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">13</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">11</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">12</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaaaa"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaabe"><p class="cl-9eba7576"><span class="cl-9eba63a6">18</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaabf"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaac8"><p class="cl-9eba7576"><span class="cl-9eba63a6">15</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-9ebaaac9"><p class="cl-9eba756c"><span class="cl-9eba63a6">A</span></p></td><td class="cl-9ebaaad2"><p class="cl-9eba7576"><span class="cl-9eba63a6">16</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Now, we graphically display the data. In this case, a boxplot represents a good way to visualize the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract means</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>slrdata2 <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Group) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Score), <span class="dv">1</span>), <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Score), <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Group, Score)) <span class="sc">+</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="fu">c</span>(<span class="st">"orange"</span>, <span class="st">"darkgray"</span>)) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"M = "</span>, Mean, <span class="at">sep =</span> <span class="st">""</span>), <span class="at">y =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"SD = "</span>, SD, <span class="at">sep =</span> <span class="st">""</span>), <span class="at">y =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Group"</span>) <span class="sc">+</span>                      </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Test score (Points)"</span>, <span class="at">cex =</span> .<span class="dv">75</span>) <span class="sc">+</span>   </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>)) <span class="sc">+</span>  </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>)                </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data indicate that group A did significantly better than group B. We will test this impression by generating the regression model and creating the model and extracting the model summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate regression model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>m2.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Score <span class="sc">~</span> Group, <span class="at">data =</span> slrdata2) </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect results</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2.lm)                             </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Score ~ Group, data = slrdata2)

Residuals:
        Min          1Q      Median          3Q         Max 
-6.76666667 -1.93333333  0.15000000  2.06666667  6.23333333 

Coefficients:
                Estimate   Std. Error  t value               Pr(&gt;|t|)    
(Intercept) 14.933333333  0.534571121 27.93517 &lt; 0.000000000000000222 ***
GroupB      -3.166666667  0.755997730 -4.18873            0.000096692 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.92796662 on 58 degrees of freedom
Multiple R-squared:  0.232249929,   Adjusted R-squared:  0.219012859 
F-statistic:  17.545418 on 1 and 58 DF,  p-value: 0.0000966923559</code></pre>
</div>
</div>
<p>The model summary reports that Group A performed significantly better compared with Group B. This is shown by the fact that the p-value (the value in the column with the header (Pr(&gt;|t|)) is smaller than .001 as indicated by the three * after the p-values). Also, the negative Estimate for Group B indicates that Group B has lower scores than Group A. We will now generate the diagnostic graphics.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))        <span class="co"># plot window: 1 plot/row, 3 plots/column</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">resid</span>(m2.lm))     <span class="co"># generate diagnostic plot</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstandard</span>(m2.lm)) <span class="co"># generate diagnostic plot</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstudent</span>(m2.lm)); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))  <span class="co"># restore normal plot window</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graphics do not indicate outliers or other issues, so we can continue with more diagnostic graphics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># generate a plot window with 2x2 panels</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2.lm); <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)) <span class="co"># restore normal plot window</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="introreg_files/figure-html/slr25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>These graphics also show no problems which is why we can now summarize the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tabulate results</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(m2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">Score</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">p</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">14.93</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">13.86&nbsp;–&nbsp;16.00</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Group [B]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-3.17</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-4.68&nbsp;–&nbsp;-1.65</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "><strong>&lt;0.001</strong></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">60</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">0.232 / 0.219</td>
</tr>

</tbody></table>

</div>
</div>
<p>We can use the <code>reports</code> package <span class="citation" data-cites="report">[<a href="#ref-report" role="doc-biblioref">14</a>]</span> to summarize the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>report<span class="sc">::</span><span class="fu">report</span>(m2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Score with Group (formula: Score ~ Group). The model explains a statistically significant and moderate proportion of variance (R2 = 0.23, F(1, 58) = 17.55, p &lt; .001, adj. R2 = 0.22). The model's intercept, corresponding to Group = A, is at 14.93 (95% CI [13.86, 16.00], t(58) = 27.94, p &lt; .001). Within this model:

  - The effect of Group [B] is statistically significant and negative (beta = -3.17, 95% CI [-4.68, -1.65], t(58) = -4.19, p &lt; .001; Std. beta = -0.96, 95% CI [-1.41, -0.50])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</code></pre>
</div>
</div>
<p>We can use this output to write up a final report:</p>
<p>A simple linear regression was fitted to the data. A visual assessment of the model diagnostics did not indicate any problematic or disproportionately influential data points (outliers). The final linear regression model is based on 60 data points, performed significantly better than an intercept-only base line model (F (1, 58): 17.55, p-value &lt;. 001<sup><span class="math inline">\(***\)</span></sup>), and reported that the model explained 21.9 percent of variance which confirmed a good model fit. According to this final model, group A scored significantly better on the language learning test than group B (coefficient: -3.17, 95% CI [-4.68, -1.65], Std. : -0.96, 95% CI [-1.41, -0.50], SE: 0.48, t-value<sub>58</sub>: -4.19, p-value &lt;. 001<sup><span class="math inline">\(***\)</span></sup>). Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using the Wald approximation.</p>
<p>That’s it for this tutorial. We hope that you have enjoyed this tutorial and learned how to perform regression analysis including model fitting and model diagnostics as well as reporting regression results.</p>
</section>
</section>
<section id="citation-session-info" class="level1 unnumbered">
<h1 class="unnumbered">Citation &amp; Session Info</h1>
<p>Schweinberger, Martin. 2022. <em>Introduction to Regression Analysis</em>. Brisbane: The University of Queensland. url: https://slcladal.github.io/introreg.html (Version 2022.08.31).</p>
<pre><code>@manual{schweinberger2022introreg,
  author = {Schweinberger, Martin},
  title = {Introduction to Regression Analysis},
  note = {https://slcladal.github.io/regression.html},
  year = {2022},
  organization = "The University of Queensland, Australia. School of Languages and Cultures},
  address = {Brisbane},
  edition = {2022.08.31}
}</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] report_0.5.1      see_0.7.1         performance_0.9.1 sjPlot_2.8.10    
 [5] ggfortify_0.4.14  vip_0.3.2         ggpubr_0.4.0      ggplot2_3.3.6    
 [9] flextable_0.7.3   dplyr_1.0.9      

loaded via a namespace (and not attached):
 [1] nlme_3.1-158      insight_0.18.0    tools_4.2.1       backports_1.4.1  
 [5] utf8_1.2.2        R6_2.5.1          sjlabelled_1.2.0  DBI_1.1.3        
 [9] mgcv_1.8-40       colorspace_2.0-3  withr_2.5.0       tidyselect_1.1.2 
[13] gridExtra_2.3     emmeans_1.7.5     compiler_4.2.1    cli_3.3.0        
[17] xml2_1.3.3        officer_0.4.3     sandwich_3.0-2    labeling_0.4.2   
[21] bayestestR_0.12.1 scales_1.2.0      mvtnorm_1.1-3     systemfonts_1.0.4
[25] stringr_1.4.0     digest_0.6.29     minqa_1.2.4       rmarkdown_2.14   
[29] base64enc_0.1-3   pkgconfig_2.0.3   htmltools_0.5.2   lme4_1.1-30      
[33] fastmap_1.1.0     htmlwidgets_1.5.4 rlang_1.0.4       rstudioapi_0.13  
[37] farver_2.1.1      generics_0.1.3    zoo_1.8-10        jsonlite_1.8.0   
[41] zip_2.2.0         car_3.1-0         magrittr_2.0.3    patchwork_1.1.1  
[45] parameters_0.18.1 Matrix_1.4-1      Rcpp_1.0.8.3      munsell_0.5.0    
[49] fansi_1.0.3       abind_1.4-5       gdtools_0.2.4     lifecycle_1.0.1  
[53] stringi_1.7.8     multcomp_1.4-19   yaml_2.3.5        carData_3.0-5    
[57] MASS_7.3-58.1     grid_4.2.1        sjmisc_2.8.9      crayon_1.5.1     
[61] lattice_0.20-45   ggeffects_1.1.2   cowplot_1.1.1     splines_4.2.1    
[65] sjstats_0.18.1    klippy_0.0.0.9500 knitr_1.39        pillar_1.7.0     
[69] uuid_1.1-0        boot_1.3-28       estimability_1.4  ggsignif_0.6.3   
[73] effectsize_0.7.0  codetools_0.2-18  glue_1.6.2        evaluate_0.15    
[77] modelr_0.1.8      data.table_1.14.2 nloptr_2.0.3      vctrs_0.4.1      
[81] gtable_0.3.0      purrr_0.3.4       tidyr_1.2.0       assertthat_0.2.1 
[85] datawizard_0.4.1  xfun_0.31         xtable_1.8-4      broom_1.0.0      
[89] coda_0.19-4       rstatix_0.7.0     survival_3.4-0    tibble_3.1.7     
[93] TH.data_1.1-1     ellipsis_0.3.2   </code></pre>
</div>
</div>
<hr>
<p><a href="#introduction">Back to top</a></p>
<p><a href="https://slcladal.github.io/index.html">Back to HOME</a></p>
<hr>
</section>
<section id="references" class="level1 unnumbered">




</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-lme4" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Bates, D., Mächler, M., Bolker, B., Walker, S.: <a href="https://doi.org/10.18637/jss.v067.i01">Fitting linear mixed-effects models using <span class="nocase">lme4</span></a>. Journal of Statistical Software. 67, 1–48 (2015).</div>
</div>
<div id="ref-achen1982interpreting" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Achen, C.H.: Interpreting and using regression. Sage (1982).</div>
</div>
<div id="ref-bortz2006statistik" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Bortz, J.: Statistik: F<span>ü</span>r human-und sozialwissenschaftler. Springer-Verlag (2006).</div>
</div>
<div id="ref-crawley2005statistics" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Crawley, M.J.: Statistics: An introduction using r. 2005. John Wiley &amp; Sons, Chichester, West Sussex (2005).</div>
</div>
<div id="ref-faraway2002practical" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Faraway, J.J.: Practical regression and ANOVA using r. University of Bath (2002).</div>
</div>
<div id="ref-field2012discovering" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Field, A., Miles, J., Field, Z.: Discovering statistics using r. Sage (2012).</div>
</div>
<div id="ref-gries2021statistics" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Gries, S.T.: Statistics for linguistics using r: A practical introduction. Mouton de Gruyter, Berlin &amp; New York (2021).</div>
</div>
<div id="ref-levshina2015linguistics" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Levshina, N.: How to do linguistics with r: Data exploration and statistical analysis. John Benjamins Publishing Company, Amsterdam (2015).</div>
</div>
<div id="ref-wilcox2009basic" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Wilcox, R.R.: Basic statistics: Understanding conventional methods and modern insights. Oxford University Press (2009).</div>
</div>
<div id="ref-baayen2008analyzing" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Baayen, R.H.: Analyzing linguistic data. A practical introduction to statistics using r. Cambridge University press, Cambridge (2008).</div>
</div>
<div id="ref-crawley2012r" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Crawley, M.J.: The r book. John Wiley &amp; Sons (2012).</div>
</div>
<div id="ref-winter2019statistics" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Winter, B.: Statistics for linguists: An introduction using r. Routledge (2019).</div>
</div>
<div id="ref-sjPlot" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Lüdecke, D.: <a href="https://CRAN.R-project.org/package=sjPlot">sjPlot: Data visualization for statistics in social science</a>. (2021).</div>
</div>
<div id="ref-report" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Makowski, D., Ben-Shachar, M.S., Patil, I., Lüdecke, D.: <a href="https://github.com/easystats/report">Automated results reporting as a practical tool to improve reproducibility and methodological best practices adoption</a>. CRAN. (2021).</div>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>I’m extremely grateful to Stefan Thomas Gries who provided very helpful feedback and pointed out many errors in previous versions of this tutorial. All remaining errors are, of course, my own.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>I’m very grateful to Antonio Dello Iacono who pointed out that the plots require additional discussion.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>I’m very grateful to Antonio Dello Iacono who pointed out that a previous version of this tutorial misinterpreted the results as I erroneously reversed the group results.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>